### ISSUE TITLE
希望能做到自定义字体

### ISSUE THREAD

**Issue by Lightczx** [KimigaiiWuyi/GenshinUID#1]
排版也可以优化一下，现在这个字体的大小看着不是很舒服

**Comment by KimigaiiWuyi** [comment]
> 排版也可以优化一下，现在这个字体的大小看着不是很舒服

字体可以直接替换mys里的yuanshen.ttf文件即可，无需重启bot，不过我不建议替换，因为不同字体排版不一样233还是用默认的好，字体大小的话 现在差不多能做到看得清，再大感觉就有点影响美观了

**Comment by Lightczx** [comment]
那能不能做下自定义各处的字体大小呢

**Comment by KimigaiiWuyi** [comment]
> 那能不能做下自定义各处的字体大小呢

你想怎么自定义呢 如果要回复的时候传参，那就有可能会有uidxxxxxxx23,26,32太长的触发词，如果只想统一修改，那么直接修改get img内的ysfont里的数字即可

**Comment by Lightczx** [comment]
了解了
