### ISSUE TITLE
im = Message(f'[CQ:image,file=file://{img_path}]')

### ISSUE THREAD

**Issue by noobem** [KimigaiiWuyi/GenshinUID#100]
这里报错了，去了个斜杠好了

**Comment by KimigaiiWuyi** [comment]
哪个功能报错了呢

**Comment by lgc2333** [comment]
> 这里报错了，去了个斜杠好了

linux系统吗

**Comment by noobem** [comment]
> 哪个功能报错了呢

windows系统，查看活动的功能，现在我看指令里好像没了

**Comment by KimigaiiWuyi** [comment]
> > 哪个功能报错了呢
> 
> windows系统，查看活动的功能，现在我看指令里好像没了

噢 ，指令列表忘加了，不过还是可用的，只不过日期的bug还没修
这应该是windows特有的报错

**Comment by KimigaiiWuyi** [comment]
> 我的windows要加三个斜杠，不然报错 建议仓库主用MessageSegment.image()发图片，兼容性更好

现在好像直接用Message套一层就好了吧，内容物自动处理
