### ISSUE TITLE
请问这个适配nonebotv2.0.0b1了吗

### ISSUE THREAD

**Issue by zhadsa** [KimigaiiWuyi/GenshinUID#101]

**Comment by KimigaiiWuyi** [comment]
没有 稍后修改requirements

**Comment by KimigaiiWuyi** [comment]
requirements已修改。
考虑到多数插件还未跟进，本插件为避免使用者感到困扰，所以短期内本插件**不会**跟进到Beta1
如果你想在Nonebot2 2.0.0-beta1上使用本插件，可以根据[将 nonebot2 升级到 2.0.0-beta.1 的准备工作
](https://github.com/nonebot/discussions/discussions/74)进行修改

**Comment by zhadsa** [comment]
好，谢谢

**Comment by KimigaiiWuyi** [comment]
可以测试一下新分支[nonebot2-beta1](https://github.com/KimigaiiWuyi/GenshinUID/tree/nonebot2-beta1)
