### ISSUE TITLE
And More……

### ISSUE THREAD

**Issue by KimigaiiWuyi** [KimigaiiWuyi/GenshinUID#102]
- [x] 角色面板 #195 

+ 进度 90%（等待2.7版本更新之后）

-----

- [ ] Wiki内容的图片模式（最近发现容易风控，图片版提上日程）

<details>
<summary>进度 90%</summary>

![s](https://s2.loli.net/2022/05/24/TIR4emQZG9nOtX1.jpg)

</details>

-----

- [x] 全角色别名（适配wiki角色/天赋等等……） 

+ json文件已由[@珊瑚宫千花](https://space.bilibili.com/398528056)提供

-----

- [ ] nonebot2-beta1 分支的单元测试（使用[nonebug](https://github.com/nonebot/nonebug)校验机器人发送内容）

+ 进度35%

-----

- [ ] 天赋的图片生成（适配不同角色的长宽以及列表格数的不同） 

+ 进度0%

-----

- [x] 优化 log #227

+ 进度0%

-----

- [x] uid查询界面添加天赋信息 并进一步做到自定义背景的颜色协调
<details>
<summary>进度 70%</summary>

![1](https://user-images.githubusercontent.com/55526518/159635338-68a0a1a2-246b-44ea-bc89-a5fa00a64797.PNG)

</details>

-----

- [x] 当前状态的图片模式（最近发现容易风控，图片版提上日程）#79
<details>
<summary>进度 99% 等待push</summary>

![d](https://user-images.githubusercontent.com/55526518/152277138-81b06008-2b37-44c7-af5c-5a5d69dc8331.png)

</details>

-----

- [x] Wiki中天赋的过长处理

+ 采取合并转发方式

-----

- [x] 米游币Auto的移植

+ [AutoMihoyoBBS](https://github.com/Womsxd/AutoMihoyoBBS/issues/27)

-----

- [x] 米游币Auto的每日自动化开关

+ 原来`开始获取米游币`命令的每日自动执行
+ `开启自动米游币`
+ 已完成99%，等待push

-----

- [x] 深渊图片的风格和角色信息风格匹配

+ 利用查询已有的texture2d去重绘深渊信息图片

-----

- [x] 活动列表的正确日期获取 & UI美化 #107 

+ ~~还没去关注咋弄到~~
+ 已修复
+ UI过长需要补宽度

-----

- [x] NoneBot2 Beta1的支持 #101 

+ ~~短期不会跟进，跟进将会以新分支形式支持~~
+ 由[@MingxuanGame](https://github.com/MingxuanGame)移植至新分支[nonebot2-beta1](https://github.com/KimigaiiWuyi/GenshinUID/tree/nonebot2-beta1)
+ [将 nonebot2 升级到 2.0.0-beta.1 的准备工作](https://github.com/nonebot/discussions/discussions/74)

**Comment by MingxuanGame** [comment]
#109 nonebot2 b1 更新完成

**Comment by MingxuanGame** [comment]
[![472f2a6ac0626724.png](https://i.postimg.cc/kXXzBVtj/472f2a6ac0626724.png)](https://postimg.cc/0rFc4ynm)

机器人互刷尽早解决（doge

**Comment by GuiltyKirito** [comment]
> * [ ]  当前状态的图片模式（最近发现容易风控，图片版提上日程）[什么时候当前状态（实时便笺）可以生成图片 #79](https://github.com/KimigaiiWuyi/GenshinUID/issues/79)
> 
> 进度 60% 缺少icon
> * [ ]  Wiki内容的图片模式（最近发现容易风控，图片版提上日程）
> 
> 进度 20%
> * [x]  Wiki中天赋的过长处理
> 
> * 采取合并转发方式
> 
> * [ ]  米游币Auto的移植
> 
> * [AutoMihoyoBBS](https://github.com/Womsxd/AutoMihoyoBBS/issues/27)
> 
> * [x]  深渊图片的风格和角色信息风格匹配
> 
> * 利用查询已有的texture2d去重绘深渊信息图片
> 
> * [x]  活动列表的正确日期获取 & UI美化 [活动列表部分活动开始日期错误 #107](https://github.com/KimigaiiWuyi/GenshinUID/issues/107)
> 
> * ~还没去关注咋弄到~
> * 已修复
> * UI过长需要补宽度
> 
> * [x]  NoneBot2 Beta1的支持 [请问这个适配nonebotv2.0.0b1了吗 #101](https://github.com/KimigaiiWuyi/GenshinUID/issues/101)
> 
> * ~短期不会跟进，跟进将会以新分支形式支持~
> * 由[@MingxuanGame](https://github.com/MingxuanGame)移植至新分支[nonebot2-beta1](https://github.com/KimigaiiWuyi/GenshinUID/tree/nonebot2-beta1)
> * [将 nonebot2 升级到 2.0.0-beta.1 的准备工作](https://github.com/nonebot/discussions/discussions/74)

努力做到一天一催，提醒大佬

**Comment by shirokurakana** [comment]
> [![472f2a6ac0626724.png](https://camo.githubusercontent.com/5bebdc3464c1a5dcf8b0f2dfc592ef6e4a93af5d7df1a1ff34ced16e71f775f8/68747470733a2f2f692e706f7374696d672e63632f6b58587a4256746a2f343732663261366163303632363732342e706e67)](https://postimg.cc/0rFc4ynm)
> 
> 机器人互刷尽早解决（doge

可以同关键词做个cache，短时间内不重复响应
当然最简单粗暴的就是把另一个bot加入排除名单（
