### ISSUE TITLE
西风剑wiki数据错误

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#103]
![Screenshot_2022-02-03-17-39-07-652_com tencent mobileqq](https://user-images.githubusercontent.com/59048777/152317649-f8353047-eef3-4cbb-9c75-6eaa4b40576a.jpg)

**Comment by lgc2333** [comment]
基础攻击力应为401

**Comment by KimigaiiWuyi** [comment]
> 基础攻击力应为401

我代码好像全部舍掉了，floor（）
应该改成全部进一位

**Comment by KimigaiiWuyi** [comment]
Hoshino版本已同步
