### ISSUE TITLE
活动列表部分活动开始日期错误

### ISSUE THREAD

**Issue by RemKeeper** [KimigaiiWuyi/GenshinUID#107]
![腾讯云_event](https://user-images.githubusercontent.com/78486275/152737055-7ce3569d-0340-4b95-8234-142fe59b5d48.jpg)
活动列表某些活动的开始日期是12月33号
hoshinobot
最新版本GenshinUID插件
![image](https://user-images.githubusercontent.com/78486275/152737467-93bc49d9-3671-461c-8681-e7e9dbfde998.png)
服务器时间准确
centos
![image](https://user-images.githubusercontent.com/78486275/152737577-8d50781a-1c26-49d6-8d46-92fadfe1b26c.png)

**Comment by KimigaiiWuyi** [comment]
#102 老问题了，因为这个命令使用频率不高，所以一直没管，接下来优化一下UI和时间问题

**Comment by KimigaiiWuyi** [comment]
已修复
