### ISSUE TITLE
ValueError: Unknown parameter Bot for function <function rule_all_recheck at 0x0000024EDD535040> with type <class 'inspect._empty'>

### ISSUE THREAD

**Issue by YanHuanD** [KimigaiiWuyi/GenshinUID#108]
![image](https://user-images.githubusercontent.com/99136573/152740776-6fe6e3ba-495c-4d67-ae35-bbe0e05936db.png)

**Comment by lgc2333** [comment]
你使用的nonebot版本是多少呢

**Comment by lgc2333** [comment]
这个插件需要的nonebor版本为a16而不是beta1哦
