### ISSUE TITLE
绑定cookies mys uid 后绑定指令提示未绑定

### ISSUE THREAD

**Issue by RemKeeper** [KimigaiiWuyi/GenshinUID#111]
![)LLA`IU64ALEX4QZ4(9B~NN](https://user-images.githubusercontent.com/78486275/153134869-4cb8b8e7-551b-47a0-88ff-167d3c9d7ebd.png)

运行于docker环境的hoshino， errlog.log如下
[error.log](https://github.com/KimigaiiWuyi/GenshinUID/files/8030092/error.log)

docker logs hoshino 错误开始部分输出如下
[docker logs hoshino.txt](https://github.com/KimigaiiWuyi/GenshinUID/files/8030253/docker.logs.hoshino.txt)

docker logs gocqhttp错误开始部分如下
[docker logs gocqhttp.txt](https://github.com/KimigaiiWuyi/GenshinUID/files/8030260/docker.logs.gocqhttp.txt)

**Comment by KimigaiiWuyi** [comment]
手误 你绑定可以签到 他绑定是不行的 好奇怪的问题
回去看一眼log

**Comment by MingxuanGame** [comment]
> 手误 你绑定可以签到 他绑定是不行的 好奇怪的问题 回去看一眼log

log我看了，没traceback
docker的log时间不符

**Comment by MingxuanGame** [comment]
使用最新的提交试试
若不行请再发log

**Comment by RemKeeper** [comment]
> 使用最新的提交试试
> 若不行请再发log

那个群友初三上学去了，剩下的，测了几天，无法复现bug
应该是修复了
