### ISSUE TITLE
nonebot2 似乎不再支持 go-cqhttp 协议

### ISSUE THREAD

**Issue by ZhouYingSASA** [KimigaiiWuyi/GenshinUID#113]
如题，现在的 nonebot2 支持列表里只找到了 onebot v11 作为替代，已经不再支持 cqhttp，手动添加 nonebot-adapter-cqhttp 也已经导致报错。。

**Comment by KimigaiiWuyi** [comment]
a16版本都不能添加cqhttp适配器？

**Comment by ZhouYingSASA** [comment]
现在的 nb 脚手架已经无法安装 a16 版本了

**Comment by KimigaiiWuyi** [comment]
> 现在的 nb 脚手架已经无法安装 a16 版本了

pip 还可以装

**Comment by lgc2333** [comment]
pip install nb-cli==0.5.3

**Comment by ZhouYingSASA** [comment]
> pip install nb-cli==0.5.3

感谢，我昨天尝试过，没有成功，但是今天成功了。能跑就行哈哈哈哈
