### ISSUE TITLE
wuyi佬，修出新bug了，活动列表 命令报错

### ISSUE THREAD

**Issue by RemKeeper** [KimigaiiWuyi/GenshinUID#114]
![image](https://user-images.githubusercontent.com/78486275/153650352-15c33e5d-a58e-42aa-a0f3-fd4c1fe79943.png)

hoshino err.log
![image](https://user-images.githubusercontent.com/78486275/153650590-e4fa3845-bd30-4490-a45f-67c1c17a5a1f.png)
docker logs gocqhttp
![image](https://user-images.githubusercontent.com/78486275/153651230-8b2dd83b-24cf-4f58-8682-3bccb7732a9b.png)

docker logs hoshino
![image](https://user-images.githubusercontent.com/78486275/153651399-d3031448-e453-4607-afd3-f37b37c936c6.png)

**Comment by KimigaiiWuyi** [comment]
尴尬了，又忘加依赖了，已补
