### ISSUE TITLE
御神签好像出问题了

### ISSUE THREAD

**Issue by 8wsd** [KimigaiiWuyi/GenshinUID#119]
好像不刷新了

**Comment by 8wsd** [comment]
后台没报错

**Comment by KimigaiiWuyi** [comment]
不刷新的意思是？今天抽的御神签依旧会调用昨天的数据吗？

**Comment by 8wsd** [comment]
![image](https://user-images.githubusercontent.com/42790798/154398294-c741849e-3b53-4107-9c62-06afaee98f56.png)

**Comment by 8wsd** [comment]
对

**Comment by KimigaiiWuyi** [comment]
> 对

检查一下`ID_DATA.db`的`UserDict`这个表，是否每天会清空？
或者可以关注一下零点的时候，后台有无报错，刷新数据库是在零点

**Comment by 8wsd** [comment]
好的谢谢

**Comment by KimigaiiWuyi** [comment]
> > 对
> 
> 检查一下`ID_DATA.db`的`UserDict`这个表，是否每天会清空？ 或者可以关注一下零点的时候，后台有无报错，刷新数据库是在零点

或者可以对比一下`ID_DATA.db`和`ID_DATA_bak.db`两个数据库中`userdict`的表的差异，bak是昨天的数据库自动备份文件

**Comment by 8wsd** [comment]
我好像没有ID_DATA_bak.db

**Comment by KimigaiiWuyi** [comment]
> 我好像没有ID_DATA_bak.db

那就说明自动任务确实出问题了，是Hoshino版本吗

**Comment by 8wsd** [comment]
对

**Comment by KimigaiiWuyi** [comment]
> 对

你git pull更新过了吗

**Comment by 8wsd** [comment]
没

**Comment by KimigaiiWuyi** [comment]
> 没

你用的是早期版本，`git pull`更新过之后应该不会有这个问题 [8cf1dd6](https://github.com/KimigaiiWuyi/GenshinUID/commit/8cf1dd6b378762f8e50ff85f4dc7a0322bb84677)

**Comment by 8wsd** [comment]
好我去试试
