### ISSUE TITLE
当米哈游通行证账号绑有其他米哈游游戏角色时，该账号主人无法通过绑定mysid方式查询

### ISSUE THREAD

**Issue by Nuevo009** [KimigaiiWuyi/GenshinUID#12]
如题，有个群友除了原神还玩崩坏三，他同时绑定了mysid和uid，`查询`返回

```
Api报错，返回内容为：
{'data': None, 'message': '用户信息不匹配', 'retcode': 1008}
出现这种情况可能的UID输入错误 or 不存在
```
查询数据库的cache显示该mysid绑定的uid是他蹦蹦蹦的uid

让他获取cookies后添加，数据库中他所绑定的那条cookies显示的uid还是他bbb的uid，也无法用`当前状态`，尝试直接修改数据库把uid换成他原神的也没用。。。

校验cookies显示正常，在数据库中查看cache记录，显示该cookies可以被其他人用来查询信息。。。

看了看是优先用mysid查询，所以让他只绑定uid。可以通过uid查询

但是这个号可以通过绑定cookies来实现`当前状态`吗？

**Comment by KimigaiiWuyi** [comment]
> 如题，有个群友除了原神还玩崩坏三，他同时绑定了mysid和uid，`查询`返回
> 
> ```
> Api报错，返回内容为：
> {'data': None, 'message': '用户信息不匹配', 'retcode': 1008}
> 出现这种情况可能的UID输入错误 or 不存在
> ```
> 
> 查询数据库的cache显示该mysid绑定的uid是他蹦蹦蹦的uid
> 
> 让他获取cookies后添加，数据库中他所绑定的那条cookies显示的uid还是他bbb的uid，也无法用`当前状态`，尝试直接修改数据库把uid换成他原神的也没用。。。
> 
> 校验cookies显示正常，在数据库中查看cache记录，显示该cookies可以被其他人用来查询信息。。。
> 
> 看了看是优先用mysid查询，所以让他只绑定uid。可以通过uid查询
> 
> 但是这个号可以通过绑定cookies来实现`当前状态`吗？

我们群里不少人是都玩的，理论上是不会有影响的，我自己也是有bbb的号；cookies上的acountid是米游社的通行证，当前状态只会调用cookies和绑定的uid，而不会调用绑定的mysid。

如果方便的话，能手动抓一下他跑getDB.py里面GetMysInfo()这个方法返回的data提供给我吗？

**Comment by KimigaiiWuyi** [comment]
> 如题，有个群友除了原神还玩崩坏三，他同时绑定了mysid和uid，`查询`返回
> 
> ```
> Api报错，返回内容为：
> {'data': None, 'message': '用户信息不匹配', 'retcode': 1008}
> 出现这种情况可能的UID输入错误 or 不存在
> ```
> 
> 查询数据库的cache显示该mysid绑定的uid是他蹦蹦蹦的uid
> 
> 让他获取cookies后添加，数据库中他所绑定的那条cookies显示的uid还是他bbb的uid，也无法用`当前状态`，尝试直接修改数据库把uid换成他原神的也没用。。。
> 
> 校验cookies显示正常，在数据库中查看cache记录，显示该cookies可以被其他人用来查询信息。。。
> 
> 看了看是优先用mysid查询，所以让他只绑定uid。可以通过uid查询
> 
> 但是这个号可以通过绑定cookies来实现`当前状态`吗？

或者直接告诉我他的米游社通行证，我自己做一下测试

**Comment by Nuevo009** [comment]
> > 如题，有个群友除了原神还玩崩坏三，他同时绑定了mysid和uid，`查询`返回
> > ```
> > Api报错，返回内容为：
> > {'data': None, 'message': '用户信息不匹配', 'retcode': 1008}
> > 出现这种情况可能的UID输入错误 or 不存在
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 查询数据库的cache显示该mysid绑定的uid是他蹦蹦蹦的uid
> > 让他获取cookies后添加，数据库中他所绑定的那条cookies显示的uid还是他bbb的uid，也无法用`当前状态`，尝试直接修改数据库把uid换成他原神的也没用。。。
> > 校验cookies显示正常，在数据库中查看cache记录，显示该cookies可以被其他人用来查询信息。。。
> > 看了看是优先用mysid查询，所以让他只绑定uid。可以通过uid查询
> > 但是这个号可以通过绑定cookies来实现`当前状态`吗？
> 
> 或者直接告诉我他的米游社通行证，我自己做一下测试
非常感谢您的回复。
我暂时没有时间(其实是py刚入门有点看不懂)做更多测试，他的mysid是72118447
感谢大佬

**Comment by Nuevo009** [comment]
> 我们群里不少人是都玩的，理论上是不会有影响的，我自己也是有bbb的号；cookies上的acountid是米游社的通行证，当前状态只会调用cookies和绑定的uid，而不会调用绑定的mysid。

我知道cookies上的acountid是米哈游通行证id

我指的是，database里面NewCookiesTable表中，他的cookies那一行UID显示的是他蹦蹦蹦的uid
通过绑定mysid获取的uid也是他蹦蹦蹦的uid
![116.png](https://www.z4a.net/images/2021/10/30/116.png)

**Comment by KimigaiiWuyi** [comment]
> > 我们群里不少人是都玩的，理论上是不会有影响的，我自己也是有bbb的号；cookies上的acountid是米游社的通行证，当前状态只会调用cookies和绑定的uid，而不会调用绑定的mysid。
> 
> 我知道cookies上的acountid是米哈游通行证id
> 
> 我指的是，database里面NewCookiesTable表中，他的cookies那一行UID显示的是他蹦蹦蹦的uid 通过绑定mysid获取的uid也是他蹦蹦蹦的uid ![116.png](https://camo.githubusercontent.com/37b214656c82e7678d5114cea778cfcf2707b3b467f6e09ac77f175356e3df67/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032312f31302f33302f3131362e706e67)

修好了，git pull下来更新看看。
因为添加ck操作我没有办法帮忙待测试，所以pull完成之后，请先去NewCookiesTable这个表，删除他的Cookies记录，再去UIDDATA这个表，删除他的绑定记录，然后再去CookiesCache这个表，删除他的使用记录，然后重新测试。

测试通过后请回复~

**Comment by Nuevo009** [comment]
> > > 我们群里不少人是都玩的，理论上是不会有影响的，我自己也是有bbb的号；cookies上的acountid是米游社的通行证，当前状态只会调用cookies和绑定的uid，而不会调用绑定的mysid。
> > 
> > 
> > 我知道cookies上的acountid是米哈游通行证id
> > 我指的是，database里面NewCookiesTable表中，他的cookies那一行UID显示的是他蹦蹦蹦的uid 通过绑定mysid获取的uid也是他蹦蹦蹦的uid ![116.png](https://camo.githubusercontent.com/37b214656c82e7678d5114cea778cfcf2707b3b467f6e09ac77f175356e3df67/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032312f31302f33302f3131362e706e67)
> 
> 修好了，git pull下来更新看看。 因为添加ck操作我没有办法帮忙待测试，所以pull完成之后，请先去NewCookiesTable这个表，删除他的Cookies记录，再去UIDDATA这个表，删除他的绑定记录，然后再去CookiesCache这个表，删除他的使用记录，然后重新测试。
> 
> 测试通过后请回复~

让他绑定了cookies之后，现在数据库里面是正常了，但是他绑定了uid之后，`当前状态`还是`没有找到绑定信息`，接着绑定mysid依然不行，但是直接`查询`可以了

**Comment by KimigaiiWuyi** [comment]
> > > > 我们群里不少人是都玩的，理论上是不会有影响的，我自己也是有bbb的号；cookies上的acountid是米游社的通行证，当前状态只会调用cookies和绑定的uid，而不会调用绑定的mysid。
> > > 
> > > 
> > > 我知道cookies上的acountid是米哈游通行证id
> > > 我指的是，database里面NewCookiesTable表中，他的cookies那一行UID显示的是他蹦蹦蹦的uid 通过绑定mysid获取的uid也是他蹦蹦蹦的uid ![116.png](https://camo.githubusercontent.com/37b214656c82e7678d5114cea778cfcf2707b3b467f6e09ac77f175356e3df67/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032312f31302f33302f3131362e706e67)
> > 
> > 
> > 修好了，git pull下来更新看看。 因为添加ck操作我没有办法帮忙待测试，所以pull完成之后，请先去NewCookiesTable这个表，删除他的Cookies记录，再去UIDDATA这个表，删除他的绑定记录，然后再去CookiesCache这个表，删除他的使用记录，然后重新测试。
> > 测试通过后请回复~
> 
> 让他绑定了cookies之后，现在数据库里面是正常了，但是他绑定了uid之后，`当前状态`还是`没有找到绑定信息`，接着绑定mysid依然不行，但是直接`查询`可以了
 确认数据库内 NewCookiesTable里的UID无误，并且UIDDATA里uid无误的话，当前状态不能用 应该是没有去米游社开启这个功能，这个功能是手动开的

**Comment by KimigaiiWuyi** [comment]
> > > > 我们群里不少人是都玩的，理论上是不会有影响的，我自己也是有bbb的号；cookies上的acountid是米游社的通行证，当前状态只会调用cookies和绑定的uid，而不会调用绑定的mysid。
> > > 
> > > 
> > > 我知道cookies上的acountid是米哈游通行证id
> > > 我指的是，database里面NewCookiesTable表中，他的cookies那一行UID显示的是他蹦蹦蹦的uid 通过绑定mysid获取的uid也是他蹦蹦蹦的uid ![116.png](https://camo.githubusercontent.com/37b214656c82e7678d5114cea778cfcf2707b3b467f6e09ac77f175356e3df67/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032312f31302f33302f3131362e706e67)
> > 
> > 
> > 修好了，git pull下来更新看看。 因为添加ck操作我没有办法帮忙待测试，所以pull完成之后，请先去NewCookiesTable这个表，删除他的Cookies记录，再去UIDDATA这个表，删除他的绑定记录，然后再去CookiesCache这个表，删除他的使用记录，然后重新测试。
> > 测试通过后请回复~
> 
> 让他绑定了cookies之后，现在数据库里面是正常了，但是他绑定了uid之后，`当前状态`还是`没有找到绑定信息`，接着绑定mysid依然不行，但是直接`查询`可以了

确认数据库内 NewCookiesTable里的UID无误，并且UIDDATA里uid无误的话，当前状态不能用 应该是没有去米游社开启这个功能，这个功能是手动开的

**Comment by Nuevo009** [comment]
> > > > 我们群里不少人是都玩的，理论上是不会有影响的，我自己也是有bbb的号；cookies上的acountid是米游社的通行证，当前状态只会调用cookies和绑定的uid，而不会调用绑定的mysid。
> > > 
> > > 
> > > 我知道cookies上的acountid是米哈游通行证id
> > > 我指的是，database里面NewCookiesTable表中，他的cookies那一行UID显示的是他蹦蹦蹦的uid 通过绑定mysid获取的uid也是他蹦蹦蹦的uid ![116.png](https://camo.githubusercontent.com/37b214656c82e7678d5114cea778cfcf2707b3b467f6e09ac77f175356e3df67/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032312f31302f33302f3131362e706e67)
> > 
> > 
> > 修好了，git pull下来更新看看。 因为添加ck操作我没有办法帮忙待测试，所以pull完成之后，请先去NewCookiesTable这个表，删除他的Cookies记录，再去UIDDATA这个表，删除他的绑定记录，然后再去CookiesCache这个表，删除他的使用记录，然后重新测试。
> > 测试通过后请回复~
> 
> 让他绑定了cookies之后，现在数据库里面是正常了，但是他绑定了uid之后，`当前状态`还是`没有找到绑定信息`，接着绑定mysid依然不行，但是直接`查询`可以了

在cookiescache表中他mysid对应的uid是none，使用的cookies也是他的[![117.png](https://www.z4a.net/images/2021/10/30/117.png)](https://www.z4a.net/image/gR4qiI)

**Comment by Nuevo009** [comment]
> > > > > 我们群里不少人是都玩的，理论上是不会有影响的，我自己也是有bbb的号；cookies上的acountid是米游社的通行证，当前状态只会调用cookies和绑定的uid，而不会调用绑定的mysid。
> > > > 
> > > > 
> > > > 我知道cookies上的acountid是米哈游通行证id
> > > > 我指的是，database里面NewCookiesTable表中，他的cookies那一行UID显示的是他蹦蹦蹦的uid 通过绑定mysid获取的uid也是他蹦蹦蹦的uid ![116.png](https://camo.githubusercontent.com/37b214656c82e7678d5114cea778cfcf2707b3b467f6e09ac77f175356e3df67/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032312f31302f33302f3131362e706e67)
> > > 
> > > 
> > > 修好了，git pull下来更新看看。 因为添加ck操作我没有办法帮忙待测试，所以pull完成之后，请先去NewCookiesTable这个表，删除他的Cookies记录，再去UIDDATA这个表，删除他的绑定记录，然后再去CookiesCache这个表，删除他的使用记录，然后重新测试。
> > > 测试通过后请回复~
> > 
> > 
> > 让他绑定了cookies之后，现在数据库里面是正常了，但是他绑定了uid之后，`当前状态`还是`没有找到绑定信息`，接着绑定mysid依然不行，但是直接`查询`可以了
> 
> 确认数据库内 NewCookiesTable里的UID无误，并且UIDDATA里uid无误的话，当前状态不能用 应该是没有去米游社开启这个功能，这个功能是手动开的

我先替他给您道个歉。。。他根本不知道米游社有这功能。。。现在让他手动打开之后可以了。非常感谢。

**Comment by KimigaiiWuyi** [comment]
> > > > > > 我们群里不少人是都玩的，理论上是不会有影响的，我自己也是有bbb的号；cookies上的acountid是米游社的通行证，当前状态只会调用cookies和绑定的uid，而不会调用绑定的mysid。
> > > > > 
> > > > > 
> > > > > 我知道cookies上的acountid是米哈游通行证id
> > > > > 我指的是，database里面NewCookiesTable表中，他的cookies那一行UID显示的是他蹦蹦蹦的uid 通过绑定mysid获取的uid也是他蹦蹦蹦的uid ![116.png](https://camo.githubusercontent.com/37b214656c82e7678d5114cea778cfcf2707b3b467f6e09ac77f175356e3df67/68747470733a2f2f7777772e7a34612e6e65742f696d616765732f323032312f31302f33302f3131362e706e67)
> > > > 
> > > > 
> > > > 修好了，git pull下来更新看看。 因为添加ck操作我没有办法帮忙待测试，所以pull完成之后，请先去NewCookiesTable这个表，删除他的Cookies记录，再去UIDDATA这个表，删除他的绑定记录，然后再去CookiesCache这个表，删除他的使用记录，然后重新测试。
> > > > 测试通过后请回复~
> > > 
> > > 
> > > 让他绑定了cookies之后，现在数据库里面是正常了，但是他绑定了uid之后，`当前状态`还是`没有找到绑定信息`，接着绑定mysid依然不行，但是直接`查询`可以了
> > 
> > 
> > 确认数据库内 NewCookiesTable里的UID无误，并且UIDDATA里uid无误的话，当前状态不能用 应该是没有去米游社开启这个功能，这个功能是手动开的
> 
> 我先替他给您道个歉。。。他根本不知道米游社有这功能。。。现在让他手动打开之后可以了。非常感谢。

没事，下次更新我做一个提示好了，给没开这个功能的提示一下（

**Comment by Nuevo009** [comment]
嗯。。。返回角色信息的顺序也是他手动设置，他之前设置的第一条是崩坏三，所以原先取的是第一条，现在加个判断就能正常获取uid了。如果自己设置原神在第一个应该就没这问题。作者回复速度太快了，给您点个赞
