### ISSUE TITLE
部署插件ERROR

### ISSUE THREAD

**Issue by tendapc** [KimigaiiWuyi/GenshinUID#120]
PS C:\Users\Administrator\Desktop\aibot\aibot\plugins\GenshinUID> pip3 install -r requirements.txt
Collecting requests==2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting httpx==0.18.1
  Using cached httpx-0.18.1-py3-none-any.whl (75 kB)
Collecting Pillow>=8.3.1
  Using cached Pillow-9.0.1-cp39-cp39-win_amd64.whl (3.2 MB)
Collecting nonebot-plugin-apscheduler>=0.1.2
  Using cached nonebot_plugin_apscheduler-0.1.2-py3-none-any.whl (2.8 kB)
Collecting wordcloud>=1.8.1
  Using cached wordcloud-1.8.1.tar.gz (220 kB)
  Preparing metadata (setup.py) ... done
ERROR: No .egg-info directory found in C:\Users\Administrator\AppData\Local\Temp\2\pip-pip-egg-info-orvcmm6o

**Comment by MingxuanGame** [comment]
更新pip和setuptools
```shell
pipe install pip setuptools -U
```
