### ISSUE TITLE
添加Cookie相关问题

### ISSUE THREAD

**Issue by ghost** [KimigaiiWuyi/GenshinUID#124]
开了无痕模式，并且获取到了Cookie，并且添加了，机器人也显示添加成功，为什么过一会校验Cookie的时候显示Cookie是异常的，删除了，请问要怎样才不会删除？

**Comment by KimigaiiWuyi** [comment]
米游社现在 Cookies失效规则 我也不是完全清楚，但是至少获取到Cookies之后，请不要在任何米游社接口登出账号/修改密码，包括但不限于网页端/APP端等，如果确定自己没有登出过账号，可以在非无痕模式下尝试获取

**Comment by SPLUS-VABLE** [comment]
还有个问题，请问一下群友私聊机器人添加Cookies没有回应，而我却可以，是怎么回事？

**Comment by KimigaiiWuyi** [comment]
> 还有个问题，请问一下群友私聊机器人添加Cookies没有回应，而我却可以，是怎么回事？

仅限bot好友，临时私聊对话太容易风控了，bot信息敢发出去，tx马上就把你号封了，请先让他们添加bot为好友

**Comment by SPLUS-VABLE** [comment]
好的，谢谢无疑大佬的解答

**Comment by KimigaiiWuyi** [comment]
> 好的，谢谢无疑大佬的解答

要问问题请**新开issuse**，不要在别人的问题下询问，这样别人会有邮件提醒的，很扰民，而且会歪楼

**Comment by SPLUS-VABLE** [comment]
抱歉

**Comment by shirokurakana** [comment]
> > 还有个问题，请问一下群友私聊机器人添加Cookies没有回应，而我却可以，是怎么回事？
> 
> 仅限bot好友，临时私聊对话太容易风控了，bot信息敢发出去，tx马上就把你号封了，请先让他们添加bot为好友

其实接受私聊对话也容易吃风控，建议直接上号把bot改成不允许任何私聊
