### ISSUE TITLE
wiki模块指令问题

### ISSUE THREAD

**Issue by AinoAty** [KimigaiiWuyi/GenshinUID#125]
在群聊里打出武器还有角色就会触发at武器、角色不存在，有办法去除嘛？

**Comment by KimigaiiWuyi** [comment]
这个属于触发词问题，武器/角色属于触发词前缀，做的时候考虑到方便性，没有加必须AT才能用指令的方式，如果加上AT机器人才能用的话，会麻烦很多

**Comment by 3273576540** [comment]
更新了，hoshino好像无法载入服务了

**Comment by 3273576540** [comment]
就是genshinuid.py改了就行了，谢谢无疑佬

**Comment by SPLUS-VABLE** [comment]
想问问，就是当前状态的指令只有添加了cookies本人的才能使用吗，为什么群里其他人使用不了，其他的查询指令都能使用？谢谢无疑佬的解答。

**Comment by KimigaiiWuyi** [comment]
> 想问问，就是当前状态的指令只有添加了cookies本人的才能使用吗，为什么群里其他人使用不了，其他的查询指令都能使用？谢谢无疑佬的解答。

只有同时添加cookies和绑定uid才能使用`当前状态`命令，命令表里有写

**Comment by SPLUS-VABLE** [comment]
好的，谢谢无疑大佬！！
