### ISSUE TITLE
大佬，更新最新包后出现了error

### ISSUE THREAD

**Issue by a970703218** [KimigaiiWuyi/GenshinUID#126]
![Screenshot_20220306_152618](https://user-images.githubusercontent.com/48351858/156913407-12d5e791-4cdc-4e9f-a1d3-8b62983d8339.jpg)

**Comment by KimigaiiWuyi** [comment]
看上去上面一个报错是因为服务名重复了？不是很了解hoshino，建议去hoshino群里问问，我感觉修改`__init___.py`下`sv=Service('genshinuid')`应该就可以，可能和另一个插件冲突。
下面的报错和该插件无关系，是一个`anti_asoul`的插件

**Comment by a970703218** [comment]
> 看上去上面一个报错是因为服务名重复了？不是很了解hoshino，建议去hoshino群里问问，我感觉修改`__init___.py`下`sv=Service('genshinuid')`应该就可以，可能和另一个插件冲突。 下面的报错和该插件无关系，是一个`anti_asoul`的插件

![Screenshot_20220306_153521](https://user-images.githubusercontent.com/48351858/156913728-d6a77147-60d3-4301-aafc-3be1ef0b7308.jpg)
大佬，主要是新功能的报错了好像，没更新前服务名是没重复的

**Comment by KimigaiiWuyi** [comment]
> > 看上去上面一个报错是因为服务名重复了？不是很了解hoshino，建议去hoshino群里问问，我感觉修改`__init___.py`下`sv=Service('genshinuid')`应该就可以，可能和另一个插件冲突。 下面的报错和该插件无关系，是一个`anti_asoul`的插件
> 
> ![Screenshot_20220306_153521](https://user-images.githubusercontent.com/48351858/156913728-d6a77147-60d3-4301-aafc-3be1ef0b7308.jpg) 大佬，主要是新功能的报错了好像，没更新前服务名是没重复的

欸 hoshino没有on_regex吗？我研究一下文档

**Comment by KimigaiiWuyi** [comment]
> > 看上去上面一个报错是因为服务名重复了？不是很了解hoshino，建议去hoshino群里问问，我感觉修改`__init___.py`下`sv=Service('genshinuid')`应该就可以，可能和另一个插件冲突。 下面的报错和该插件无关系，是一个`anti_asoul`的插件
> 
> ![Screenshot_20220306_153521](https://user-images.githubusercontent.com/48351858/156913728-d6a77147-60d3-4301-aafc-3be1ef0b7308.jpg) 大佬，主要是新功能的报错了好像，没更新前服务名是没重复的

尝试一下重新更新是否成功，我修改`on_regex`为`on_rex`了

**Comment by a970703218** [comment]
> > > 看上去上面一个报错是因为服务名重复了？不是很了解hoshino，建议去hoshino群里问问，我感觉修改`__init___.py`下`sv=Service('genshinuid')`应该就可以，可能和另一个插件冲突。 下面的报错和该插件无关系，是一个`anti_asoul`的插件
> > 
> > 
> > ![Screenshot_20220306_153521](https://user-images.githubusercontent.com/48351858/156913728-d6a77147-60d3-4301-aafc-3be1ef0b7308.jpg) 大佬，主要是新功能的报错了好像，没更新前服务名是没重复的
> 
> 尝试一下重新更新是否成功，我修改`on_regex`为`on_rex`了

好的，我更新下

**Comment by a970703218** [comment]
> > > 看上去上面一个报错是因为服务名重复了？不是很了解hoshino，建议去hoshino群里问问，我感觉修改`__init___.py`下`sv=Service('genshinuid')`应该就可以，可能和另一个插件冲突。 下面的报错和该插件无关系，是一个`anti_asoul`的插件
> > 
> > 
> > ![Screenshot_20220306_153521](https://user-images.githubusercontent.com/48351858/156913728-d6a77147-60d3-4301-aafc-3be1ef0b7308.jpg) 大佬，主要是新功能的报错了好像，没更新前服务名是没重复的
> 
> 尝试一下重新更新是否成功，我修改`on_regex`为`on_rex`了

已成功 ！谢谢大佬
