### ISSUE TITLE
关于查询角色uid

### ISSUE THREAD

**Issue by 836672549** [KimigaiiWuyi/GenshinUID#128]
大佬您好，我的群聊机器人再绑定uid后输入uid，机器人回复“发生错误 list index out of range,请检查后台输出”。这个问题怎么解决呢

**Comment by KimigaiiWuyi** [comment]
带上后台报错截图

**Comment by 836672549** [comment]
![3a83e47c-c886-4726-a384-b691d0844edf](https://user-images.githubusercontent.com/71533394/157398901-aecae752-5209-472c-a534-b533d909c805.png)

**Comment by KimigaiiWuyi** [comment]
> ![3a83e47c-c886-4726-a384-b691d0844edf](https://user-images.githubusercontent.com/71533394/157398901-aecae752-5209-472c-a534-b533d909c805.png)

你命令错了，uid后应该跟数字

**Comment by KimigaiiWuyi** [comment]
> ![3a83e47c-c886-4726-a384-b691d0844edf](https://user-images.githubusercontent.com/71533394/157398901-aecae752-5209-472c-a534-b533d909c805.png)

例如 `绑定uid123456`，`uid123456`等等，请详细查看wiki里有关命令表的部分

**Comment by 836672549** [comment]
发送绑定uidxxx成功，发送uid123456没有回复

**Comment by KimigaiiWuyi** [comment]
> 发送绑定uidxxx成功，发送uid123456没有回复

带上后台报错

**Comment by 836672549** [comment]
<img width="718" alt="截图" src="https://user-images.githubusercontent.com/71533394/157401078-e9292b4c-b0f8-4664-aec8-530146bfef7c.PNG">

**Comment by KimigaiiWuyi** [comment]
> <img alt="截图" width="718" src="https://user-images.githubusercontent.com/71533394/157401078-e9292b4c-b0f8-4664-aec8-530146bfef7c.PNG">

关键是后面的部分，triggered之后的部分

**Comment by 836672549** [comment]
后面啥也没有，只有别的群消息

**Comment by KimigaiiWuyi** [comment]
> 后面啥也没有，只有别的群消息

尝试`校验全部Cookies`看看ck是否正常

**Comment by 836672549** [comment]
有两个正常的

**Comment by KimigaiiWuyi** [comment]
> 有两个正常的

有失效的吗，校验完成之后再尝试uid命令呢？

**Comment by 836672549** [comment]
我之前好像一直是发送失效的cookies，我更新一下就好了，谢谢了

**Comment by KimigaiiWuyi** [comment]
> 我之前好像一直是发送失效的cookies，我更新一下就好了，谢谢了

确实也是个bug，之前其实一直有注意到如果失效ck的话没有报错，一直忘了改，回头再看看问题在哪

**Comment by 836672549** [comment]
如果我朋友没有绑定cookies我是不能查询他的角色详情嘛

**Comment by KimigaiiWuyi** [comment]
> 如果我朋友没有绑定cookies我是不能查询他的角色详情嘛

对的，米哈游限制，没有ck只能查8个 而且不能查询 深渊的详细配队

**Comment by 836672549** [comment]
万恶的MHY

**Comment by KimigaiiWuyi** [comment]
nb2版本应该已修复，其他版本等周末改
