### ISSUE TITLE
Cookies校验失败

### ISSUE THREAD

**Issue by AmamiHaruka** [KimigaiiWuyi/GenshinUID#13]
插件已经在正常使用中，
于2021.11.01 18:00后功能失效，
校验全部Cookies 发现全部失效，
重新添加也全部返回失败。
疑似是MHY修改了什么？

**Comment by KimigaiiWuyi** [comment]
> 插件已经在正常使用中， 于2021.11.01 18:00后功能失效， 校验全部Cookies 发现全部失效， 重新添加也全部返回失败。 疑似是MHY修改了什么？

晚六点的时候，米游社服务器炸了，所以都不行。
（如果这时候你去米游社看自己角色的话，就会发现）
现在应该是一切正常了，我无需做什么修改
只是你这个删除掉的Cookies……恐怕得自己添加回来了

**Comment by AmamiHaruka** [comment]
我发现了，不过我备份了数据库，再校验之前。

**Comment by KimigaiiWuyi** [comment]
> 我发现了，不过我备份了数据库，再校验之前。

机智！
