### ISSUE TITLE
活动列表

### ISSUE THREAD

**Issue by Zoe-Wh1t3zZ** [KimigaiiWuyi/GenshinUID#130]
![$T){BN%6M O%(V}@2$PFA`2](https://user-images.githubusercontent.com/94744908/157722312-b87805f0-f5cd-4438-a75f-316f50d016aa.PNG)

**Comment by MingxuanGame** [comment]
淦
每次出新活动就炸
今天改

**Comment by MingxuanGame** [comment]
由于活动更新
无法复现问题
此issue标记为`ToDo`
待能复现时修复

**Comment by MingxuanGame** [comment]
已复现此bug
将于近期修复

**Comment by MingxuanGame** [comment]
fix in [e07183b](https://github.com/KimigaiiWuyi/GenshinUID/commit/e07183beaec5bd6a1ffa4461f53d5d97f431908d) and [d98d95e](https://github.com/KimigaiiWuyi/GenshinUID/commit/d98d95e53a6e403d5b430c2ebbe2d9577171b0db)
