### ISSUE TITLE
关于新版本没有__init__.py以及部署失败

### ISSUE THREAD

**Issue by VoplsX** [KimigaiiWuyi/GenshinUID#131]
在将genshinuid放入plugins后，在使用最新的nonebot-b1时又或者A16，好像由于没有__init__.py直接无法读取，在bot.py添加也不行，必须有__init__.py，搞不太明白，当我更改了genshinuid.py的文件名__init__.py后，b1版本提醒
![image](https://user-images.githubusercontent.com/23568231/157730898-dce1ead1-b7c9-4739-9ff3-5eebb2f660d9.png)
。用A16版本
![image](https://user-images.githubusercontent.com/23568231/157731034-aa371baf-52af-4e2c-bda3-f40b4ea05677.png)
。捣鼓了半天实在是没办法了，求大佬解答

**Comment by KimigaiiWuyi** [comment]
在Hoshino版本上`__init__.py`又不能被正确识别，奇怪的是，我自己本地的Nonebot2，无论哪种情况都可以正确导包
你可以在`Nonebot2-Beta1`版本下的`get_mihoyo_bbs_coin`的开头加入`import sys`,并在导包前面一行加入`sys.path.append(os.path.dirname(os.path.realpath(__file__)))`然后重新尝试

**Comment by KimigaiiWuyi** [comment]
你也可以进QQ群`929275476`找到我 再多次测试一下

**Comment by VoplsX** [comment]
感谢大佬，并进行版本更新！亦可以正常使用！十分感谢！
