### ISSUE TITLE
大佬，角色wiki这边返回的问题

### ISSUE THREAD

**Issue by a970703218** [KimigaiiWuyi/GenshinUID#132]
角色草系会返回宵宫(
![Screenshot_20220311_103448_com tencent mobileqq](https://user-images.githubusercontent.com/48351858/157791394-bb461747-5fb3-4ed4-b46e-5bdea11c79f3.jpg)

**Comment by KimigaiiWuyi** [comment]
那是因为，宵宫的突破材料，有 一个 有带草的

**Comment by KimigaiiWuyi** [comment]
`角色`命令后面可以接受 模糊的材料名字，所以`鸣草`被纳入列表里

**Comment by a970703218** [comment]
> `角色`命令后面可以接受 模糊的材料名字，所以`鸣草`被纳入列表里

哦哦，好的(谢谢大佬
