### ISSUE TITLE
wiki指令列表需要更新

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#136]
如题
获取米游币和啥啥能给谁用和谁能用啥啥啥

**Comment by MingxuanGame** [comment]
你去更新一下吧
表格能用markdown的就尽量用

**Comment by lgc2333** [comment]
我寻思着我没法编辑wiki啊

**Comment by MingxuanGame** [comment]
?
协作者不是有wiki权限吗
要不你改好了把md文件发我

**Comment by lgc2333** [comment]
[Home.md](https://github.com/KimigaiiWuyi/GenshinUID/files/8237159/Home.md)

**Comment by lgc2333** [comment]
然而我并不是协作者

**Comment by lgc2333** [comment]
[Home.md](https://github.com/KimigaiiWuyi/GenshinUID/files/8237161/Home.md)

**Comment by lgc2333** [comment]
[Home.md](https://github.com/KimigaiiWuyi/GenshinUID/files/8237171/Home.md)

**Comment by MingxuanGame** [comment]
已更新
