### ISSUE TITLE
插件目录应该填什么，试了好多次都没成功

### ISSUE THREAD

**Issue by chongdong12** [KimigaiiWuyi/GenshinUID#137]
文件加路径为src/plugins/GenshinUID，我再bot.py里边配置的是 nonebot.load_plugins("src/plugins/GenshinUID") ，提示报错为AttributeError: 'Config' object has no attribute 'genshinuid_priority'。不知道如何解决，请问有人知道吗

**Comment by MingxuanGame** [comment]
更新一下
这个引用不会关闭
若还有问题再发

**Comment by chongdong12** [comment]
> 

更新是指哪个呢？

**Comment by MingxuanGame** [comment]
`git pull`就行
提交是35dcd29

**Comment by chongdong12** [comment]
> `git pull`就行 提交是35dcd29
根据您的指示，我成功pull后，再次nb run 后提示了新的报错提示 ： RuntimeError: Cannot load plugin "nonebot_plugin_apscheduler"!  请问是什么原因呢？

**Comment by MingxuanGame** [comment]
> > `git pull`就行 提交是35dcd29
> > 根据您的指示，我成功pull后，再次nb run 后提示了新的报错提示 ： RuntimeError: Cannot load plugin "nonebot_plugin_apscheduler"!  请问是什么原因呢？

发一下完整日志

**Comment by chongdong12** [comment]
> > > `git pull`就行 提交是35dcd29
> > > 根据您的指示，我成功pull后，再次nb run 后提示了新的报错提示 ： RuntimeError: Cannot load plugin "nonebot_plugin_apscheduler"!  请问是什么原因呢？
> 
> 发一下完整日志

[nohup.txt](https://github.com/KimigaiiWuyi/GenshinUID/files/8239530/nohup.txt)
你看这个可以吗

**Comment by MingxuanGame** [comment]
确定了是计时器的问题
依照下面的顺序修改
1.执行`vim /etc/localtime`
如果不是`Asia/Shanghai`就改为这个（需要会vim操作）
2.执行`rm -f /etc/localtime`
3.执行`cp /usr/share/zoneinfo/Asia/Shanghai/etc/localtime`

**Comment by chongdong12** [comment]
> cp /usr/share/zoneinfo/Asia/Shanghai/etc/localtime

成功了 谢谢你
