### ISSUE TITLE
关于指令的一些问题

### ISSUE THREAD

**Issue by chongdong12** [KimigaiiWuyi/GenshinUID#138]
1、模块指令列表里边有一些指令有的需要 / 才能查询，有的不需要。
比如指令 “当前状态” 要加上/，而指令 “开启推送” 不需要加上，这个是什么问题呢？
2、绑定cookie和uid后，指令 “uidxxxx” 、 “uidxxxx深渊” 和 “mysxxx” 都没反应，这种情况是正常的吗
![2ESCOX%D)%XTESST$PA_0FD](https://user-images.githubusercontent.com/95455587/158062953-7009217b-d784-4014-ae15-e1efed09b6ed.png)
3、调出 指令菜单 的触发词是啥咧

**Comment by MingxuanGame** [comment]
1.这个是没有设置命令前缀
在`.env.dev`修改这个设置命令前缀
```
COMMAND_START=["/", ""]
```
2.都没返回是不正常的，可以看看后台（当然如果是因为没有设置命令前缀大概率没事）
3.没有指令菜单，可以看[wiki](https://github.com/KimigaiiWuyi/GenshinUID/wiki#%E4%B8%A8%E6%8C%87%E4%BB%A4%E5%88%97%E8%A1%A8)

**Comment by chongdong12** [comment]
在修改命令前缀后，第一个问题解决了 ，但是第二个问题在修改后还是存在，在后台也没有反应

**Comment by MingxuanGame** [comment]
可以看一下go-cqhttp的后台
我感觉是吃风控了

**Comment by chongdong12** [comment]
在群里发送其他消息都没问题，就只有前几个指令出错，比如uidxxx 、 mysxxx 之类的

**Comment by MingxuanGame** [comment]
把go-cqhttp的log和nonebot的log发一下

**Comment by chongdong12** [comment]
不好意思 有点久
[nb2.txt](https://github.com/KimigaiiWuyi/GenshinUID/files/8239909/nb2.txt)
[cqhttp.txt](https://github.com/KimigaiiWuyi/GenshinUID/files/8239910/cqhttp.txt)

**Comment by KimigaiiWuyi** [comment]
> 不好意思 有点久 [nb2.txt](https://github.com/KimigaiiWuyi/GenshinUID/files/8239909/nb2.txt) [cqhttp.txt](https://github.com/KimigaiiWuyi/GenshinUID/files/8239910/cqhttp.txt)

你这两个log都是收到uid之后就没剩下的了？
如果没有的话考虑是CK失效的问题 最近有个bug ck失效无报错 #128

**Comment by chongdong12** [comment]
测试过了 ck是有效的

**Comment by KimigaiiWuyi** [comment]
> 测试过了 ck是有效的

那你后面的log呢？cqhttp的那个甚至只能看得到指令的那一行，看不到响应的结果

**Comment by chongdong12** [comment]
emm不是很懂哎 我是正常启动cqhttp之后就这样了

**Comment by KimigaiiWuyi** [comment]
> emm不是很懂哎 我是正常启动cqhttp之后就这样了

我看到nb2的log里，你是私聊bot调用命令`uid`，`uid``mys`等查询命令，均只支持群聊

**Comment by chongdong12** [comment]
> > emm不是很懂哎 我是正常启动cqhttp之后就这样了
> 
> 我看到nb2的log里，你是私聊bot调用命令`uid`，而`uid` `mys`等查询命令，均只支持群聊

原来不支持私聊呀，刚才在群里可以成功查询了，非常感谢！

**Comment by KimigaiiWuyi** [comment]
>
