### ISSUE TITLE
使用on_prefix触发器的“开启/关闭 推送”的相关命令会覆盖HoshinoBot的功能开关

### ISSUE THREAD

**Issue by DaiShengSheng** [KimigaiiWuyi/GenshinUID#140]
当GenshinUID做为HoshinoBot插件使用时，会将HoshinoBot自带的功能“开启/关闭 功能”的命令覆盖，导致原生HoshinoBot的插件开关功能失效

**Comment by KimigaiiWuyi** [comment]
已修改为`gs开启`、`gs关闭`
