### ISSUE TITLE
添加cookies返回检验失败。

### ISSUE THREAD

**Issue by AmamiHaruka** [KimigaiiWuyi/GenshinUID#146]
使用获取米游社 Cookies方法，获取到的cookies串中并不包含account_id = xxxxxx和cookie_token = xxxxxx 这两项参数。导致校验失败。

**Comment by Wansn-w** [comment]
尝试访问米游社的其它页面，比如每日签到等

**Comment by AmamiHaruka** [comment]
> 

PC上也有签到吗，还是只能从APP上

**Comment by Wansn-w** [comment]
唔 刚下意识认为是国际服了qwq
不过[国服电脑版主页](https://bbs.mihoyo.com/ys) 直接运行就能获取这两个参数

当然，只要cookie含有如下三项中的一项其实就有效
- `ltoken` & `ltuid`
- `cookie_token` & `account_id`
- `login_ticket`

**Comment by AmamiHaruka** [comment]
这个确实没有这俩参数，我查询了下办法，使用浏览器的无痕模式，再进行如上操作，返回的cookies中是带有cookie_token&account_id。这样就能通过bot的添加cookies的操作了。
