### ISSUE TITLE
qq群内查询UID返回输入错误

### ISSUE THREAD

**Issue by AmamiHaruka** [KimigaiiWuyi/GenshinUID#147]
cookies已经添加成功，在群内查询uid还是不能成功。
hoshino cmd窗口显示
![image](https://user-images.githubusercontent.com/10334215/159114775-d80e17e2-74d5-4fb8-8338-173f1219d93d.png)

实际使用截图
![image](https://user-images.githubusercontent.com/10334215/159114939-c1d8a570-fe7d-4490-95d3-4521d852e09e.png)

**Comment by KimigaiiWuyi** [comment]
这是多久以前的版本，建议先`git pull` 更新一下

**Comment by AmamiHaruka** [comment]
我确信是删除了原文件，按照安装说明重新git clone的代码呀。git log --stat 如下
![image](https://user-images.githubusercontent.com/10334215/159115538-50f75c1f-0389-4931-bae2-f573ce67b56f.png)
以前也出现过类似的问题，版本对不上，最后还是使用的下载zip包。

**Comment by KimigaiiWuyi** [comment]
你找一下`__init.py__`或者新版本叫`genshinuid.py`有没有 冲突的代码 ，或者可以在里面ctrl F搜索一下`输入错误`这个字，截图看看具体代码段

**Comment by AmamiHaruka** [comment]
破案了，是hoshinobot 下载的时候在modules/genshin/下也有个老版的GenshinUID，我把冲突的删了就好了。

**Comment by AmamiHaruka** [comment]
破案了，是hoshinobot 下载的时候在modules/genshin/下也有个老版的GenshinUID，我把冲突的删了就好了。
