### ISSUE TITLE
语音指令无法使用

### ISSUE THREAD

**Issue by tuanzi66** [KimigaiiWuyi/GenshinUID#149]
![`C18QQ6ZS)SY7A_{OLH}(Y5](https://user-images.githubusercontent.com/101592087/159149186-e417293e-c809-4fef-99d1-08bd2f7e8d7a.png)

![QQ截图20220320131513](https://user-images.githubusercontent.com/101592087/159149260-244f098f-b945-4f3d-9422-9797d9a21e56.png)

**Comment by KimigaiiWuyi** [comment]
看上去获取的是没有问题，发送出了问题；考虑是账号被一定程度的风控，可以查看`go-cqhttp`的报错提示
