### ISSUE TITLE
安装时显示：输入错误

### ISSUE THREAD

**Issue by olcxian** [KimigaiiWuyi/GenshinUID#15]
我安装后使用的跟图片有关的任何指令都会提示输入错误，但是其他功能正常使用，如签到

**Comment by KimigaiiWuyi** [comment]
能否描述清楚问题发生的场景，以及复现情况，如是否添加cookies，是否绑定uid/mys，输入什么命令后提示输入错误

**Comment by olcxian** [comment]
> 能否描述清楚问题发生的场景，以及复现情况，如是否添加cookies，是否绑定uid/mys，输入什么命令后提示输入错误

![Screenshot_2021-11-07-02-34-52-292_com tencent mobileqq](https://user-images.githubusercontent.com/45726680/140620309-9880e814-1bdf-4c90-b00f-0ee43b64a55d.jpg)

我添加cookies成功了，也可以使用米游社签到功能，但是一旦我查询玩家信息或者玩家深渊就会显示输入错误

**Comment by KimigaiiWuyi** [comment]
> > 能否描述清楚问题发生的场景，以及复现情况，如是否添加cookies，是否绑定uid/mys，输入什么命令后提示输入错误
> 
> ![Screenshot_2021-11-07-02-34-52-292_com tencent mobileqq](https://user-images.githubusercontent.com/45726680/140620309-9880e814-1bdf-4c90-b00f-0ee43b64a55d.jpg)
> 
> 我添加cookies成功了，也可以使用米游社签到功能，但是一旦我查询玩家信息或者玩家深渊就会显示输入错误

我尝试了一下，没有找到这个米游社id，或者你是想使用uidxxxxx？
