### ISSUE TITLE
Cookie无法添加问题

### ISSUE THREAD

**Issue by RemKeeper** [KimigaiiWuyi/GenshinUID#150]
当事人处于登录状态，且可点赞，收藏，常用登录平台IOS/MAC        游戏区服ios
米游社页面下获取的cookies

`_MHYUUID=******; _ga=******; UM_distinctid=******; mi18nLang=zh-cn; _gid=******; login_uid=******; login_ticket=******; CNZZDATA1275023096=******; ltoken=******; ltuid=******`

通行证页面下获取cookies

`_MHYUUID=******; _ga=******; UM_distinctid=******; mi18nLang=zh-cn; _gid=GA1.2.1817279510.1647782470; login_uid=******; login_ticket=******; ltoken=******; ltuid=******; CNZZDATA1274689524=******`

均无法添加
![image](https://user-images.githubusercontent.com/68982190/159169858-bbbef599-5b10-464f-a263-ec78ddf3d481.png)

尝试添加stoken
![image](https://user-images.githubusercontent.com/68982190/159169810-25cf28ba-2d55-46b0-835f-803547a31849.png)

（脱敏 by MingxuanGame）

**Comment by RemKeeper** [comment]
![image](https://user-images.githubusercontent.com/78486275/159167510-3d9dd5c1-3635-45a2-a5e4-00309d7fceb2.png)
另一个添加成功的，获取米游币指令报错

**Comment by MingxuanGame** [comment]
Cookie中不含`account_id`，导致正则匹配错误
![image](https://user-images.githubusercontent.com/68982190/159168096-f0a41805-2afc-4716-9e53-ed200370c364.png)
[相关代码](https://github.com/KimigaiiWuyi/GenshinUID/blob/main/mihoyo_libs/get_mihoyo_bbs_data.py#L255)

**Comment by RemKeeper** [comment]
> Cookie中代码`account_id`，导致正匹配[相关错误](https://github.com/KimigaiiWuyi/GenshinUID/blob/main/mihoyo_libs/get_mihoyo_bbs_data.py#L255) ![图片](https://user-images.githubusercontent.com/68982190/159168096-f0a41805-2afc-4716-9e53-ed200370c364.png) [](https://github.com/KimigaiiWuyi/GenshinUID/blob/main/mihoyo_libs/get_mihoyo_bbs_data.py#L255)

我这边用document.cookie 或者是网络抓包都无法找到这个字段,是我的获取方式或操作环境有问题吗(Chrome无痕浏览模式)

**Comment by MingxuanGame** [comment]
> > Cookie中代码`account_id`，导致正匹配[相关错误](https://github.com/KimigaiiWuyi/GenshinUID/blob/main/mihoyo_libs/get_mihoyo_bbs_data.py#L255) ![图片](https://user-images.githubusercontent.com/68982190/159168096-f0a41805-2afc-4716-9e53-ed200370c364.png)
> 
> 我这边用document.cookie 或者是网络抓包都无法找到这个字段,是我的获取方式或操作环境有问题吗(Chrome无痕浏览模式)

并没有问题，是程序的问题
`ltuid`和`login_uid`均可以作为米游社通行证id，但是并未使用

**Comment by RemKeeper** [comment]
> > > Cookie中代码`account_id`，导致正匹配[相关错误](https://github.com/KimigaiiWuyi/GenshinUID/blob/main/mihoyo_libs/get_mihoyo_bbs_data.py#L255) ![图片](https://user-images.githubusercontent.com/68982190/159168096-f0a41805-2afc-4716-9e53-ed200370c364.png)
> > 
> > 
> > 我这边用document.cookie 或者是网络抓包都无法找到这个字段,是我的获取方式或操作环境有问题吗(Chrome无痕浏览模式)
> 
> 并没有问题，是程序的问题 `ltuid`和`login_uid`均可以作为米游社通行证id，但是并未使用

好吧，我不懂python，唯一能做的只有等待作者大大修改了()

**Comment by MingxuanGame** [comment]
> ![image](https://user-images.githubusercontent.com/78486275/159167510-3d9dd5c1-3635-45a2-a5e4-00309d7fceb2.png) 另一个添加成功的，获取米游币指令报错

离谱了，要是绑定stoken就会查询uid，如果报错就无法添加
这个添加后使用报错
请在Hoshino运行文件夹运行下面的python文件（将文件中的`userid`改成那位群友的qq号）
然后发送结果
```python
import sqlite3


conn = sqlite3.connect('ID_DATA.db')
c = conn.cursor()
cursor = c.execute("SELECT *  FROM UIDDATA WHERE USERID = ?", (userid,))
for row in cursor:
	print(row[1])
```

**Comment by KimigaiiWuyi** [comment]
> > > Cookie中代码`account_id`，导致正匹配[相关错误](https://github.com/KimigaiiWuyi/GenshinUID/blob/main/mihoyo_libs/get_mihoyo_bbs_data.py#L255) ![图片](https://user-images.githubusercontent.com/68982190/159168096-f0a41805-2afc-4716-9e53-ed200370c364.png)
> > 
> > 
> > 我这边用document.cookie 或者是网络抓包都无法找到这个字段,是我的获取方式或操作环境有问题吗(Chrome无痕浏览模式)
> 
> 并没有问题，是程序的问题 `ltuid`和`login_uid`均可以作为米游社通行证id，但是并未使用

ltuid查不到树脂信息，所以必须获取account_id

**Comment by RemKeeper** [comment]
> > ![image](https://user-images.githubusercontent.com/78486275/159167510-3d9dd5c1-3635-45a2-a5e4-00309d7fceb2.png) 另一个添加成功的，获取米游币指令报错
> 
> 离谱了，要是绑定stoken就会查询uid，如果报错就无法添加 这个添加后使用报错 请在Hoshino运行文件夹运行下面的python文件（将文件中的`userid`改成那位群友的qq号） 然后发送结果
> 
> ```python
> import sqlite3
> 
> 
> conn = sqlite3.connect('ID_DATA.db')
> c = conn.cursor()
> cursor = c.execute("SELECT *  FROM UIDDATA WHERE USERID = ?", (userid,))
> for row in cursor:
> 	print(row[1])
> ```

在非无痕浏览条件下重新抓取添加了一遍，正常了

**Comment by RemKeeper** [comment]
> > > > Cookie中代码`account_id`，导致正匹配[相关错误](https://github.com/KimigaiiWuyi/GenshinUID/blob/main/mihoyo_libs/get_mihoyo_bbs_data.py#L255) ![图片](https://user-images.githubusercontent.com/68982190/159168096-f0a41805-2afc-4716-9e53-ed200370c364.png)
> > > 
> > > 
> > > 我这边用document.cookie 或者是网络抓包都无法找到这个字段,是我的获取方式或操作环境有问题吗(Chrome无痕浏览模式)
> > 
> > 
> > 并没有问题，是程序的问题 `ltuid`和`login_uid`均可以作为米游社通行证id，但是并未使用
> 
> ltuid查不到树脂信息，所以必须获取account_id

这个是要开启了实时便签才会有吗？一直抓不到，重新登录也是一样，每天等群友上线了我试试从安卓APP上抓网络包()

**Comment by KimigaiiWuyi** [comment]
> > > > > Cookie中代码`account_id`，导致正匹配[相关错误](https://github.com/KimigaiiWuyi/GenshinUID/blob/main/mihoyo_libs/get_mihoyo_bbs_data.py#L255) ![图片](https://user-images.githubusercontent.com/68982190/159168096-f0a41805-2afc-4716-9e53-ed200370c364.png)
> > > > 
> > > > 
> > > > 我这边用document.cookie 或者是网络抓包都无法找到这个字段,是我的获取方式或操作环境有问题吗(Chrome无痕浏览模式)
> > > 
> > > 
> > > 并没有问题，是程序的问题 `ltuid`和`login_uid`均可以作为米游社通行证id，但是并未使用
> > 
> > 
> > ltuid查不到树脂信息，所以必须获取account_id
> 
> 这个是要开启了实时便签才会有吗？一直抓不到，重新登录也是一样，每天等群友上线了我试试从安卓APP上抓网络包()

不用开启实时便签也会有
