### ISSUE TITLE
想知道为什么会产生这种情况

### ISSUE THREAD

**Issue by jinxx52** [KimigaiiWuyi/GenshinUID#151]
用的是python3.8.2 nonebot2 beta2
是版本问题吗
![VTJ PZE4K~5}1FX(V6{1BLT](https://user-images.githubusercontent.com/86406052/160279680-7815364e-1079-4b53-861b-f79bd66775c4.png)

**Comment by MingxuanGame** [comment]
尝试使用Python3.9及以上
内置类型直接类型标注是在3.9添加的
详情参考[这个](https://docs.python.org/zh-cn/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections)

**Comment by RemKeeper** [comment]
> 尝试使用Python3.9及以上 内置类型直接类型标注是在3.9添加的 详情参考[这个](https://docs.python.org/zh-cn/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections)

想问一下docker里应该怎么更新python版本啊()

**Comment by jinxx52** [comment]
> 尝试使用Python3.9及以上
> 内置类型直接类型标注是在3.9添加的
> 详情参考[这个](https://docs.python.org/zh-cn/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections)

是这样的 解决了
