### ISSUE TITLE
HoshinoBot更新插件问题

### ISSUE THREAD

**Issue by 741807012** [KimigaiiWuyi/GenshinUID#152]
![`82$~2(LE85PB_D2JG`8OGG](https://user-images.githubusercontent.com/90551536/160281307-a52b0c8c-ff00-4450-aad7-4ef1e395cf5e.png)
这个什么问题

**Comment by KimigaiiWuyi** [comment]
emmm初步推测可能是异步任务部分执行失败？每次都这样吗？

**Comment by 741807012** [comment]
> 

是的啊

**Comment by KimigaiiWuyi** [comment]
> > 
> 
> 是的啊

看看控制台报错

**Comment by 741807012** [comment]
> 

![image](https://user-images.githubusercontent.com/90551536/160282358-ef731962-c88b-4a33-8308-021353247a98.png)

**Comment by 741807012** [comment]
不知道那里的问题

**Comment by KimigaiiWuyi** [comment]
从log上倒是看不出什么问题，现在还有这个问题吗？
你的服务器是哪个服务商的？配置如何？

**Comment by 741807012** [comment]
> 从log上倒是看不出什么问题，现在还有这个问题吗？ 你的服务器是哪个服务商的？配置如何？

还有这个问题，你是什么系统装的，Python版本，NoneBot2版本，我直接安装一样的版本和开发环境吧

**Comment by KimigaiiWuyi** [comment]
> > 从log上倒是看不出什么问题，现在还有这个问题吗？ 你的服务器是哪个服务商的？配置如何？
> 
> 还有这个问题，你是什么系统装的，Python版本，NoneBot2版本，我直接安装一样的版本和开发环境吧

我是阿里云centos7.9，py3.9.5，nb2A16，不过我感觉倒不是这些问题引起的
很奇怪，目前就一例，虽然知道是异步造成的，但不清楚具体是什么bug，你有试过重新安装插件尝试吗？

**Comment by 741807012** [comment]
> > > 从log上倒是看不出什么问题，现在还有这个问题吗？ 你的服务器是哪个服务商的？配置如何？
> > 
> > 
> > 还有这个问题，你是什么系统装的，Python版本，NoneBot2版本，我直接安装一样的版本和开发环境吧
> 
> 我是阿里云centos7.9，py3.9.5，nb2A16，不过我感觉倒不是这些问题引起的 很奇怪，目前就一例，虽然知道是异步造成的，但不清楚具体是什么bug，你有试过重新安装插件尝试吗？

重新安装了，还是不行，我是老版本更新上去的是mys崩溃后一段时间的版本

**Comment by 741807012** [comment]
NoneBot2不会安装，所以一直没切换

**Comment by MingxuanGame** [comment]
目前确定是网络IO的问题，造成数据丢失（也就是图片生成函数跑完了数据也没有获取到）
准备近期修复
已添加`ToDo`标签

**Comment by MingxuanGame** [comment]
fix in [4e32636](https://github.com/KimigaiiWuyi/GenshinUID/commit/4e326368a255f2b967ef62078c701d35b09c34d2)
