### ISSUE TITLE
更新最新包后hoshino报错(覆盖更新)

### ISSUE THREAD

**Issue by Juenia** [KimigaiiWuyi/GenshinUID#154]
报错内容
![Screenshot_20220329_133731](https://user-images.githubusercontent.com/48351858/160540869-4024a993-0e0c-4baf-84bb-45508ec2ec79.jpg)

**Comment by MingxuanGame** [comment]
重复的
#151

**Comment by Juenia** [comment]
> 重复的 #151

大佬，hoshino的话好像py3.9会无法运行

**Comment by MingxuanGame** [comment]
> > 重复的 #151
> 
> 大佬，hoshino的话好像py3.9会无法运行

并不会，正常用即可，已经测试过了

**Comment by Juenia** [comment]
> > > 重复的 #151
> > 
> > 
> > 大佬，hoshino的话好像py3.9会无法运行
> 
> 并不会，正常用即可，已经测试过了

![Screenshot_20220329_143323](https://user-images.githubusercontent.com/48351858/160548186-3d5d2788-4d1e-4a4b-96b3-aebb070caa9b.jpg)
大佬，升级3.9后的报错

**Comment by MingxuanGame** [comment]
> > > > 重复的 #151
> > > 
> > > 
> > > 大佬，hoshino的话好像py3.9会无法运行
> > 
> > 并不会，正常用即可，已经测试过了
> 
> ![Screenshot_20220329_143323](https://user-images.githubusercontent.com/48351858/160548186-3d5d2788-4d1e-4a4b-96b3-aebb070caa9b.jpg)
> 大佬，升级3.9后的报错

发log

**Comment by MingxuanGame** [comment]
> > > > 重复的 #151
> > > 
> > > 
> > > 大佬，hoshino的话好像py3.9会无法运行
> > 
> > 并不会，正常用即可，已经测试过了
> 
> ![Screenshot_20220329_143323](https://user-images.githubusercontent.com/48351858/160548186-3d5d2788-4d1e-4a4b-96b3-aebb070caa9b.jpg)
> 大佬，升级3.9后的报错

重新安装一遍依赖（hoshino和genshinuid的）

**Comment by KimigaiiWuyi** [comment]
> > > > 重复的 #151
> > > 
> > > 
> > > 大佬，hoshino的话好像py3.9会无法运行
> > 
> > 
> > 并不会，正常用即可，已经测试过了
> 
> ![Screenshot_20220329_143323](https://user-images.githubusercontent.com/48351858/160548186-3d5d2788-4d1e-4a4b-96b3-aebb070caa9b.jpg) 大佬，升级3.9后的报错

这是另外一个插件`Mahoo`的问题，应该安装opencc 依赖即可

**Comment by Juenia** [comment]
> > > > > 重复的 #151
> > > > 
> > > > 
> > > > 大佬，hoshino的话好像py3.9会无法运行
> > > 
> > > 
> > > 并不会，正常用即可，已经测试过了
> > 
> > 
> > ![Screenshot_20220329_143323](https://user-images.githubusercontent.com/48351858/160548186-3d5d2788-4d1e-4a4b-96b3-aebb070caa9b.jpg)
> > 大佬，升级3.9后的报错
> 
> 重新安装一遍依赖（hoshino和genshinuid的）

都重装了，依旧只有word cloud库报错，安装依赖的时候没有error

**Comment by MingxuanGame** [comment]
你怎么开启hoshino和安装模块的
命令发一下

**Comment by KimigaiiWuyi** [comment]
> > > > > > 重复的 #151
> > > > > 
> > > > > 
> > > > > 大佬，hoshino的话好像py3.9会无法运行
> > > > 
> > > > 
> > > > 并不会，正常用即可，已经测试过了
> > > 
> > > 
> > > ![Screenshot_20220329_143323](https://user-images.githubusercontent.com/48351858/160548186-3d5d2788-4d1e-4a4b-96b3-aebb070caa9b.jpg)
> > > 大佬，升级3.9后的报错
> > 
> > 
> > 重新安装一遍依赖（hoshino和genshinuid的）
> 
> 都重装了，依旧只有word cloud库报错，安装依赖的时候没有error

`pip install wordcloud`试试？或者用`pip list`看一眼有没有wordcloud

**Comment by Juenia** [comment]
> > > > > 重复的 #151
> > > > 
> > > > 
> > > > 大佬，hoshino的话好像py3.9会无法运行
> > > 
> > > 
> > > 并不会，正常用即可，已经测试过了
> > 
> > 
> > ![Screenshot_20220329_143323](https://user-images.githubusercontent.com/48351858/160548186-3d5d2788-4d1e-4a4b-96b3-aebb070caa9b.jpg) 大佬，升级3.9后的报错
> 
> 这是另外一个插件`Mahoo`的问题，应该安装opencc 依赖即可

大佬，那个插件并未启用

**Comment by Juenia** [comment]
> > > > > > > 重复的 #151
> > > > > > 
> > > > > > 
> > > > > > 大佬，hoshino的话好像py3.9会无法运行
> > > > > 
> > > > > 
> > > > > 并不会，正常用即可，已经测试过了
> > > > 
> > > > 
> > > > ![Screenshot_20220329_143323](https://user-images.githubusercontent.com/48351858/160548186-3d5d2788-4d1e-4a4b-96b3-aebb070caa9b.jpg)
> > > > 大佬，升级3.9后的报错
> > > 
> > > 
> > > 重新安装一遍依赖（hoshino和genshinuid的）
> > 
> > 
> > 都重装了，依旧只有word cloud库报错，安装依赖的时候没有error
> 
> `pip install wordcloud`试试？或者用`pip list`看一眼有没有wordcloud

![Screenshot_20220329_144617_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/160550243-5fc2c724-31b5-44ec-8e9b-d9483e65bdd9.jpg)
大佬，感谢排雷，是wordcloud库安装报错了，目前正在百度(

**Comment by MingxuanGame** [comment]
安装[vs生成工具](https://download.visualstudio.microsoft.com/download/pr/d06b357b-3d84-49ac-acc4-68ed90dc799f/ca1d6619a5414c67c290daf248dafbd402e5bf33cd92ecf0e3d94252fad4da20/vs_BuildTools.exe)
![-768dd6dc8331f10b.png](https://user-images.githubusercontent.com/68982190/160551161-78c2b95d-093f-479b-8065-99fb93956f12.png)

**Comment by Juenia** [comment]
> 安装[vs生成工具](https://download.visualstudio.microsoft.com/download/pr/d06b357b-3d84-49ac-acc4-68ed90dc799f/ca1d6619a5414c67c290daf248dafbd402e5bf33cd92ecf0e3d94252fad4da20/vs_BuildTools.exe) ![-768dd6dc8331f10b.png](https://user-images.githubusercontent.com/68982190/160551161-78c2b95d-093f-479b-8065-99fb93956f12.png)

谢谢大佬，正在安装(
