### ISSUE TITLE
开启自动签到，推送等命令无反应

### ISSUE THREAD

**Issue by forchannot** [KimigaiiWuyi/GenshinUID#155]
其他命令都正常，开启自动签到，树脂自动推送这种开启和关闭没有任何回应，发送的qq号已经加入了hoshinobot的超级管理员里面，没有任何报错，也没有任何回应

**Comment by KimigaiiWuyi** [comment]
为避免和lssv插件引起冲突，已修改成`gs开启`，`gs关闭`

**Comment by forchannot** [comment]
> 为避免和lssv插件引起冲突，已修改成`gs开启`，`gs关闭`

![image](https://user-images.githubusercontent.com/100580891/160573994-4901d29f-af03-4417-a6c5-8c14e1daa5ec.png)
fa'son发送gs开启关闭会这样

**Comment by KimigaiiWuyi** [comment]
> > 为避免和lssv插件引起冲突，已修改成`gs开启`，`gs关闭`
> 
> ![image](https://user-images.githubusercontent.com/100580891/160573994-4901d29f-af03-4417-a6c5-8c14e1daa5ec.png) fa'son发送gs开启关闭会这样

你需要在后面加要开启的东西，比如`gs开启推送`，`gs开启自动签到`等等

**Comment by forchannot** [comment]
> 

哦，好的，感谢大佬
