### ISSUE TITLE
米游社自动签到一分钟有限制访问次数

### ISSUE THREAD

**Issue by chenliweixie** [KimigaiiWuyi/GenshinUID#16]
目测一分钟最多访问10次，自动签到可能要分批次进行

**Comment by li704644993** [comment]
我也发现有的人老自动签到失败。
校验了一下cookie，那个人老是倒数第一个，然后倒数第二个校验失败他就签到失败了。
不知道是你说的这个原因还是一分钟最多10次的原因

**Comment by KimigaiiWuyi** [comment]
> 我也发现有的人老自动签到失败。 校验了一下cookie，那个人老是倒数第一个，然后倒数第二个校验失败他就签到失败了。 不知道是你说的这个原因还是一分钟最多10次的原因

这个问题刚刚（也许）解决了，未经过充分测试，请git pull 看一下

主楼的问题还没解决，我过几天再写一下，最近略忙

**Comment by li704644993** [comment]
> > 我也发现有的人老自动签到失败。 校验了一下cookie，那个人老是倒数第一个，然后倒数第二个校验失败他就签到失败了。 不知道是你说的这个原因还是一分钟最多10次的原因
> 
> 这个问题刚刚（也许）解决了，未经过充分测试，请git pull 看一下
> 
> 主楼的问题还没解决，我过几天再写一下，最近略忙

大佬，你getDB文件里面新增了一个GetAward方法，但是你没有上传。。。

**Comment by KimigaiiWuyi** [comment]
> > > 我也发现有的人老自动签到失败。 校验了一下cookie，那个人老是倒数第一个，然后倒数第二个校验失败他就签到失败了。 不知道是你说的这个原因还是一分钟最多10次的原因
> > 
> > 
> > 这个问题刚刚（也许）解决了，未经过充分测试，请git pull 看一下
> > 主楼的问题还没解决，我过几天再写一下，最近略忙
> 
> 大佬，你getDB文件里面新增了一个GetAward方法，但是你没有上传。。。

尴尬了……昨晚忘了
我刚刚直接用github edit修改了，试试git pull
我第一次直接edit，不知道行不行

**Comment by chenliweixie** [comment]
> > 我也发现有的人老自动签到失败。 校验了一下cookie，那个人老是倒数第一个，然后倒数第二个校验失败他就签到失败了。 不知道是你说的这个原因还是一分钟最多10次的原因
> 
> 这个问题刚刚（也许）解决了，未经过充分测试，请git pull 看一下
> 
> 主楼的问题还没解决，我过几天再写一下，最近略忙

自己稍微调整了下代码逻辑 调用10次后睡眠1分钟好像签到就没问题了，总结一下：米忽悠罪大恶极

**Comment by KimigaiiWuyi** [comment]
> > > 我也发现有的人老自动签到失败。 校验了一下cookie，那个人老是倒数第一个，然后倒数第二个校验失败他就签到失败了。 不知道是你说的这个原因还是一分钟最多10次的原因
> > 
> > 
> > 这个问题刚刚（也许）解决了，未经过充分测试，请git pull 看一下
> > 主楼的问题还没解决，我过几天再写一下，最近略忙
> 
> 自己稍微调整了下代码逻辑 调用10次后睡眠1分钟好像签到就没问题了，总结一下：米忽悠罪大恶极

这样主要会造成一直卡在那，导致其他机器人功能用不了；
又不想天天从零点检测到二十四点有没有人没签到；
我想想有没有更好的方式

**Comment by lgc2333** [comment]
主楼试一下我的fork

**Comment by KimigaiiWuyi** [comment]
#26
