### ISSUE TITLE
米游社新增了参量质变仪时间查询

### ISSUE THREAD

**Issue by forchannot** [KimigaiiWuyi/GenshinUID#160]
机器人能加入这个功能吗，如果代码有更新，应该怎么升级呢，直接把新的clone过去替换还是删掉原来的重新clone呢

**Comment by KimigaiiWuyi** [comment]
插件目录下执行`git pull`即可更新
今晚加入参量质变仪

**Comment by forchannot** [comment]
> 插件目录下执行`git pull`即可更新 今晚加入参量质变仪

是直接git pull GenshinUID就可以了吗，还没怎么接触过git命令

**Comment by KimigaiiWuyi** [comment]
> > 插件目录下执行`git pull`即可更新 今晚加入参量质变仪
> 
> 是直接git pull GenshinUID就可以了吗，还没怎么接触过git命令

`git pull`就好，不需要加入genshinuid，但是要在目录下

**Comment by KimigaiiWuyi** [comment]
已新增

**Comment by forchannot** [comment]
> 已新增

大佬牛逼，这么晚还在肝代码

**Comment by forchannot** [comment]
> > 已新增
> 
> 大佬牛逼，这么晚还在肝代码

**Comment by forchannot** [comment]
> 已新增

大佬牛，能否给质变仪单独设置个提醒呢？比如还有两小时或者一小时就在群里提醒下。如果很麻烦的话就算了

**Comment by KimigaiiWuyi** [comment]
> > 已新增
> 
> 大佬牛，能否给质变仪单独设置个提醒呢？比如还有两小时或者一小时就在群里提醒下。如果很麻烦的话就算了

提醒会做的，但可能要连着之前的重做，之前的提醒太烦了，打算独立出一个表来

**Comment by KimigaiiWuyi** [comment]
已增加
