### ISSUE TITLE
当前信息图片生成的原石统计标签有误

### ISSUE THREAD

**Issue by vesugier** [KimigaiiWuyi/GenshinUID#161]
![image](https://user-images.githubusercontent.com/66554786/160982061-1b4fe771-bee5-4779-a467-6dea23faf9ed.png)

出错标签已加粗标明↓

原石收入组成：
**冒险奖励**：8182（48%）
活动奖励：2420（14%）
**任务奖励**：2350（14%）
**每日活跃**：1800（11%）
**邮件奖励**：1300（7%）
**深境螺旋**：650（3%）
其他：662（3%）

**Comment by vesugier** [comment]
出错图片定位
https://github.com/KimigaiiWuyi/GenshinUID/blob/main/mihoyo_libs/mihoyo_bbs/texture2d/info_2.png

看了下代码，应该就是图片本体错了

**Comment by KimigaiiWuyi** [comment]
> 出错图片定位 https://github.com/KimigaiiWuyi/GenshinUID/blob/main/mihoyo_libs/mihoyo_bbs/texture2d/info_2.png
> 
> 看了下代码，应该就是图片本体错了

没有考虑到json返回的是带排序的，今晚修改

**Comment by KimigaiiWuyi** [comment]
应该已经修改完成

**Comment by vesugier** [comment]
> 应该已经修改完成

已正常显示
