### ISSUE TITLE
git pull问题

### ISSUE THREAD

**Issue by tuanzi66** [KimigaiiWuyi/GenshinUID#162]
![6$HZID(C@1DN4F}13{IP7T9](https://user-images.githubusercontent.com/101592087/161025791-2f557920-9cb3-4b6a-84e1-f7069b24e655.png)
或者就是出现这个
![I0KJG8Z5@_V2![6$HZID(C@1DN4F}13{IP7T9](https://user-images.githubusercontent.com/101592087/161025791-2f557920-9cb3-4b6a-84e1-f7069b24e655.png)
或者就是出现这个
V1F4IRLZR](https://user-images.githubusercontent.com/101592087/161026256-e22c78b3-a992-4ecf-bd70-22a6105c0b3d.png)

**Comment by MingxuanGame** [comment]
对于第一种情况
```shell
git pull origin main
```
对于第二种情况是当前文件夹不是git存储库，不能对其使用`git pull`

**Comment by tuanzi66** [comment]
> 
![6%Z}V@SL)F%P1M7F0 @JOHH](https://user-images.githubusercontent.com/101592087/161030146-b6bbb14b-abfc-4a4c-93be-4682de2ae6bc.png)



>

**Comment by MingxuanGame** [comment]
```shell
git remote add origin https://github.com/KimigaiiWuyi/GenshinUID.git
git pull origin main
```
