### ISSUE TITLE
某某角色能用啥，某某武器怎么用似乎失效了？

### ISSUE THREAD

**Issue by forchannot** [KimigaiiWuyi/GenshinUID#163]
![IMG_20220401_025219](https://user-images.githubusercontent.com/100580891/161128570-30940de7-6750-4a0f-afe4-cb62a6b3212b.jpg)

其他功能没问题，这个控制台提示获取建议失败

**Comment by MingxuanGame** [comment]
发一下log

**Comment by MiniGrayGay** [comment]
![0MSCQVUG4T`KSRAB(NHFHS2](https://user-images.githubusercontent.com/64829926/161177149-b5504129-4cf9-49fd-a36c-39d5affa5a62.jpg)

**Comment by forchannot** [comment]
> 发一下log

![Screenshot_2022-04-01-11-18-56-945_com microsoft rdc androidx](https://user-images.githubusercontent.com/100580891/161188773-602acb52-031b-46ab-833d-5926eea182d0.png)

**Comment by forchannot** [comment]
> ![0MSCQVUG4T`KSRAB(NHFHS2](https://user-images.githubusercontent.com/64829926/161177149-b5504129-4cf9-49fd-a36c-39d5affa5a62.jpg)

![Screenshot_2022-04-01-11-18-56-945_com microsoft rdc androidx](https://user-images.githubusercontent.com/100580891/161188808-2545b2aa-cdd2-4c6e-8fa6-d6feea0ca342.png)

**Comment by KimigaiiWuyi** [comment]
> > ![0MSCQVUG4T`KSRAB(NHFHS2](https://user-images.githubusercontent.com/64829926/161177149-b5504129-4cf9-49fd-a36c-39d5affa5a62.jpg)
> 
> ![Screenshot_2022-04-01-11-18-56-945_com microsoft rdc androidx](https://user-images.githubusercontent.com/100580891/161188808-2545b2aa-cdd2-4c6e-8fa6-d6feea0ca342.png)

我昨晚傻逼了 路径写错了，你现在`git pull`一下看看是否正常

**Comment by forchannot** [comment]
> > > ![0MSCQVUG4T`KSRAB(NHFHS2](https://user-images.githubusercontent.com/64829926/161177149-b5504129-4cf9-49fd-a36c-39d5affa5a62.jpg)
> > 
> > 
> > ![Screenshot_2022-04-01-11-18-56-945_com microsoft rdc androidx](https://user-images.githubusercontent.com/100580891/161188808-2545b2aa-cdd2-4c6e-8fa6-d6feea0ca342.png)
> 
> 我昨晚傻逼了 路径写错了，你现在`git pull`一下看看是否正常

已经解决了
