### ISSUE TITLE
添加cookies总是检测不通过，后面具体格式是什么

### ISSUE THREAD

**Issue by AdminVivy** [KimigaiiWuyi/GenshinUID#17]

**Comment by KimigaiiWuyi** [comment]
按照readme里的教程来，大概会得到一串以分号隔断，一堆字符串，关键信息是account_id=xxxxxxx；Cookie_token=xxxxxxxx这样的东西，非常长的字符串

**Comment by AdminVivy** [comment]
添加 UM_distinctid=xxxxxxxxxxxx; _ga=xxxxxxxxxxxx; _gid=xxxxxxxxxxxx; CNZZDATA1275023096=xxxxxxxxxxxx; _MHYUUID=xxxxxxxxxxxx; ltoken=xxxxxxxxxxxx; ltuid=xxxxxxxxxxxx; cookie_token=xxxxxxxxxxxx; account_id=xxxxxxxx;

我是这样发送的，但是还是说检测不通过

**Comment by KimigaiiWuyi** [comment]
> 添加 UM_distinctid=xxxxxxxxxxxx; _ga=xxxxxxxxxxxx; _gid=xxxxxxxxxxxx; CNZZDATA1275023096=xxxxxxxxxxxx; _MHYUUID=xxxxxxxxxxxx; ltoken=xxxxxxxxxxxx; ltuid=xxxxxxxxxxxx; cookie_token=xxxxxxxxxxxx; account_id=xxxxxxxx;
> 
> 我是这样发送的，但是还是说检测不通过

按照教程开无痕隐私模式抓一下看看。

**Comment by AdminVivy** [comment]
一样的，依旧是说 校验失败！请输入正确的Cookies！
所以不太明白后面要什么。。

**Comment by KimigaiiWuyi** [comment]
> 一样的，依旧是说 校验失败！请输入正确的Cookies！ 所以不太明白后面要什么。。

无痕模式抓出来的不应该会有UM_distinctid这一项

**Comment by KimigaiiWuyi** [comment]
> 一样的，依旧是说 校验失败！请输入正确的Cookies！ 所以不太明白后面要什么。。

主要cookies属于隐私信息，这方面我确实没办法帮你 验证了；我自己刚刚尝试了一下是完全正常的

**Comment by AdminVivy** [comment]
> > 一样的，依旧是说 校验失败！请输入正确的Cookies！ 所以不太明白后面要什么。。
> 
> 无痕模式抓出来的不应该会有UM_distinctid这一项

啊这。。。试了好几个浏览器都是有这项

**Comment by AdminVivy** [comment]
> > 一样的，依旧是说 校验失败！请输入正确的Cookies！ 所以不太明白后面要什么。。
> 
> 主要cookies属于隐私信息，这方面我确实没办法帮你 验证了；我自己刚刚尝试了一下是完全正常的

你可以像我那样一个正则替换把值全部换成xxx，参数保留（

**Comment by KimigaiiWuyi** [comment]
> > > 一样的，依旧是说 校验失败！请输入正确的Cookies！ 所以不太明白后面要什么。。
> > 
> > 
> > 主要cookies属于隐私信息，这方面我确实没办法帮你 验证了；我自己刚刚尝试了一下是完全正常的
> 
> 你可以像我那样一个正则替换把值全部换成xxx，参数保留（

参数其实无所谓，我里面写了正则，最后只会保留account_id和cookie_token；我刚想到一种可能性，就是你这个号没有登陆过手机米游社，所以在校验的时候失败了

**Comment by AdminVivy** [comment]
> > > > 一样的，依旧是说 校验失败！请输入正确的Cookies！ 所以不太明白后面要什么。。
> > > 
> > > 
> > > 主要cookies属于隐私信息，这方面我确实没办法帮你 验证了；我自己刚刚尝试了一下是完全正常的
> > 
> > 
> > 你可以像我那样一个正则替换把值全部换成xxx，参数保留（
> 
> 参数其实无所谓，我里面写了正则，最后只会保留account_id和cookie_token；我刚想到一种可能性，就是你这个号没有登陆过手机米游社，所以在校验的时候失败了

那可能是这个号没有创建过原神账号的原因么

**Comment by KimigaiiWuyi** [comment]
> > > > > 一样的，依旧是说 校验失败！请输入正确的Cookies！ 所以不太明白后面要什么。。
> > > > 
> > > > 
> > > > 主要cookies属于隐私信息，这方面我确实没办法帮你 验证了；我自己刚刚尝试了一下是完全正常的
> > > 
> > > 
> > > 你可以像我那样一个正则替换把值全部换成xxx，参数保留（
> > 
> > 
> > 参数其实无所谓，我里面写了正则，最后只会保留account_id和cookie_token；我刚想到一种可能性，就是你这个号没有登陆过手机米游社，所以在校验的时候失败了
> 
> 那可能是这个号没有创建过原神账号的原因么

没创建原神账号也过不了校验

**Comment by AdminVivy** [comment]
> > > > > > 一样的，依旧是说 校验失败！请输入正确的Cookies！ 所以不太明白后面要什么。。
> > > > > 
> > > > > 
> > > > > 主要cookies属于隐私信息，这方面我确实没办法帮你 验证了；我自己刚刚尝试了一下是完全正常的
> > > > 
> > > > 
> > > > 你可以像我那样一个正则替换把值全部换成xxx，参数保留（
> > > 
> > > 
> > > 参数其实无所谓，我里面写了正则，最后只会保留account_id和cookie_token；我刚想到一种可能性，就是你这个号没有登陆过手机米游社，所以在校验的时候失败了
> > 
> > 
> > 那可能是这个号没有创建过原神账号的原因么
> 
> 没创建原神账号也过不了校验

原来如此 那就是这个问题了，感谢dalao

**Comment by KimigaiiWuyi** [comment]
> > > > > > > 一样的，依旧是说 校验失败！请输入正确的Cookies！ 所以不太明白后面要什么。。
> > > > > > 
> > > > > > 
> > > > > > 主要cookies属于隐私信息，这方面我确实没办法帮你 验证了；我自己刚刚尝试了一下是完全正常的
> > > > > 
> > > > > 
> > > > > 你可以像我那样一个正则替换把值全部换成xxx，参数保留（
> > > > 
> > > > 
> > > > 参数其实无所谓，我里面写了正则，最后只会保留account_id和cookie_token；我刚想到一种可能性，就是你这个号没有登陆过手机米游社，所以在校验的时候失败了
> > > 
> > > 
> > > 那可能是这个号没有创建过原神账号的原因么
> > 
> > 
> > 没创建原神账号也过不了校验
> 
> 原来如此 那就是这个问题了，感谢dalao

因为不知道没登陆过原神账号的Cookies能不能查询别人的信息，所以校验多做了一步
