### ISSUE TITLE
添加stoken报错

### ISSUE THREAD

**Issue by lalakam** [KimigaiiWuyi/GenshinUID#171]
校验失败！请输入正确的Cookies！
错误信息为'NoneType' object has no attribute 'group'

**Comment by KimigaiiWuyi** [comment]
添加stoken 需要获取到的值有`login_ticket`的参数，如果确实有，发一下log，关键信息打码

**Comment by lalakam** [comment]
用文档的脚本获取的时候里面没有login_ticket参数，不知道是不是我的问题

**Comment by KimigaiiWuyi** [comment]
> 用文档的脚本获取的时候里面没有login_ticket参数，不知道是不是我的问题

尝试退出登录重新使用方法、或者使用无痕模式

**Comment by lalakam** [comment]
刚开始就是用的无痕模式不行，现在退出重登了，加Cookie正常，stoken就报错
![QQ截图20220401234906](https://user-images.githubusercontent.com/77124366/161298400-685b3213-9820-4e3f-b42c-9690a99b1380.png)
![1](https://user-images.githubusercontent.com/77124366/161298632-9614683c-14ba-4162-9942-3e601c965d0b.png)
没有login_ticket参数

**Comment by KimigaiiWuyi** [comment]
> 刚开始就是用的无痕模式不行，现在退出重登了，加Cookie正常，stoken就报错 ![QQ截图20220401234906](https://user-images.githubusercontent.com/77124366/161298400-685b3213-9820-4e3f-b42c-9690a99b1380.png) ![1](https://user-images.githubusercontent.com/77124366/161298632-9614683c-14ba-4162-9942-3e601c965d0b.png) 没有login_ticket参数

你确定是按文档操作的吗，cookies和stoken的获取的链接是不一样的，在获取stoken那个链接才能获取到，如果确定是正确的，那明天再试试吧，我刚刚自己尝试几次，没有失败的

**Comment by lalakam** [comment]
> > 刚开始就是用的无痕模式不行，现在退出重登了，加Cookie正常，stoken就报错 ![QQ截图20220401234906](https://user-images.githubusercontent.com/77124366/161298400-685b3213-9820-4e3f-b42c-9690a99b1380.png) ![1](https://user-images.githubusercontent.com/77124366/161298632-9614683c-14ba-4162-9942-3e601c965d0b.png) 没有login_ticket参数
> 
> 你确定是按文档操作的吗，cookies和stoken的获取的链接是不一样的，在获取stoken那个链接才能获取到，如果确定是正确的，那明天再试试吧，我刚刚自己尝试几次，没有失败的

也可能是我的问题，白天我再试试看，早点休息吧，晚安～

**Comment by forchannot** [comment]
> 添加stoken 需要获取到的值有`login_ticket`的参数，如果确实有，发一下log，关键信息打码

![image](https://user-images.githubusercontent.com/100580891/161368579-42034e3a-9cff-4b45-a95a-077608ef0391.png)
发给机器人后没有任何回应，其他的功能正常

**Comment by lalakam** [comment]
确实用的文档的脚本，一样的，很怪，不知道其他人有出现过没

**Comment by KimigaiiWuyi** [comment]
> 确实用的文档的脚本，一样的，很怪，不知道其他人有出现过没

还是不行吗，没有获取到包含login ticket的字段？

**Comment by lalakam** [comment]
> > 确实用的文档的脚本，一样的，很怪，不知道其他人有出现过没
> 
> 还是不行吗，没有获取到包含login ticket的字段？

是的，不知道是不是我的问题

**Comment by KimigaiiWuyi** [comment]
> > > 确实用的文档的脚本，一样的，很怪，不知道其他人有出现过没
> > 
> > 
> > 还是不行吗，没有获取到包含login ticket的字段？
> 
> 是的，不知道是不是我的问题

那个页面要必须要登陆，不可能获取不到login ticket字段啊
如果这里拿不到，你可能只能手机抓包了

**Comment by lalakam** [comment]
我换了浏览器就好了，可能是我的问题，我叫朋友弄也是可以的，那应该是我的问题。解决了，辛苦作者了~这个问题我就关闭了，辛苦作者了~
