### ISSUE TITLE
临时会话私聊不回复

### ISSUE THREAD

**Issue by Putarku** [KimigaiiWuyi/GenshinUID#172]
只有加了好友的才会回复，log上确实是接受到消息了，但是没加好友的临时会话就不会回复

**Comment by KimigaiiWuyi** [comment]
特地设置的，临时会话bot私聊风控概率极高，不想让bot转瞬就寄的话还是老老实实加好友吧

**Comment by Putarku** [comment]
这个之前一段时间只有私聊就马上冻结，我最高一天冻了3次，最近貌似没啥问题了。那行我还是让bot加好友吧
