### ISSUE TITLE
语音发送失败

### ISSUE THREAD

**Issue by AquamarineCyan** [KimigaiiWuyi/GenshinUID#174]
- nonebot-b2
- python3.9
- 最新版，4月2日覆盖源码

报错中间部分以省略
ffmpeg已加Path环境（有可能配置问题？）

![ffmpeg00](https://user-images.githubusercontent.com/64363680/161374841-0eda5e6a-30c8-441a-8602-3599db7b29f4.png)
![ffmpeg01](https://user-images.githubusercontent.com/64363680/161374855-a78ced80-048e-4299-b039-422ebb9be438.png)
![ffmpeg02](https://user-images.githubusercontent.com/64363680/161374859-25d90e08-0b62-47c8-9679-c0b99293957b.png)
![ffmpeg03](https://user-images.githubusercontent.com/64363680/161374863-20433b45-d6ad-479e-ac10-9ba6a9be3b9f.png)
![ffmpeg04](https://user-images.githubusercontent.com/64363680/161374865-c48b4b1d-4310-46f3-8f61-7deb1805b14d.png)

**Comment by MingxuanGame** [comment]
根据go-cqhttp返回的消息是没有配置path
试试把系统变量和用户变量的path都设置一下，并且在终端尝试输入`ffmpeg`
若无报错，重启go-cqhttp

**Comment by AquamarineCyan** [comment]
> 根据go-cqhttp返回的消息是没有配置path 试试把系统变量和用户变量的path都设置一下，并且在终端尝试输入`ffmpeg` 若无报错，重启go-cqhttp

都试了，可以使用，应该是加环境之后需要重启
