### ISSUE TITLE
怀疑matcher手滑用错了

### ISSUE THREAD

**Issue by RafuiiChan** [KimigaiiWuyi/GenshinUID#183]
https://github.com/KimigaiiWuyi/GenshinUID/blob/7440ef280583e51a2ef774cd3d3b9903f7ab056c/genshin_uid/main.py#L391

这个在 `get_polar`（获取命座信息）的处理函数里面，但是却用了 `get_weapon` ，应该是用 `get_polar` 吧（

**Comment by KimigaiiWuyi** [comment]
`Nonebot2` & `NoneBot2-beta1` 分支已修改~~
