### ISSUE TITLE
获取帮助和建议失败

### ISSUE THREAD

**Issue by forchannot** [KimigaiiWuyi/GenshinUID#184]
![Screenshot_2022-04-06-09-23-33-608_com microsoft rdc androidx](https://user-images.githubusercontent.com/100580891/161876962-c1c43fb3-1a07-41b0-97a9-395bbe936bab.png)
并且获取建议也失败
![Screenshot_2022-04-06-09-25-51-634_com microsoft rdc androidx](https://user-images.githubusercontent.com/100580891/161877162-9977da14-7f6a-45dc-b322-6be684ef3000.png)

**Comment by KimigaiiWuyi** [comment]
尝试更新一下看看，好久没写hoshino，忘了send还要加ev

**Comment by forchannot** [comment]
> 尝试更新一下看看，好久没写hoshino，忘了send还要加ev

随便试了几个，应该没问题了
