### ISSUE TITLE
gs帮助指令里琉璃袋打错了（

### ISSUE THREAD

**Issue by ChiefNUO** [KimigaiiWuyi/GenshinUID#186]
![_(KF@IM$5@U2I~_%5N %QK9](https://user-images.githubusercontent.com/101488726/161879264-eeb98967-74de-4669-9218-b777c658a64e.PNG)

**Comment by KimigaiiWuyi** [comment]
az，回去改

**Comment by ChiefNUO** [comment]
还有这个便笺打成便筏了

**Comment by KimigaiiWuyi** [comment]
都修了
