### ISSUE TITLE
[建议]新增代抢米游币兑换功能

### ISSUE THREAD

**Issue by RemKeeper** [KimigaiiWuyi/GenshinUID#187]
https://github.com/CMHopeSunshine/LittlePaimon/tree/master/hoshino/modules/myb_exchange

类似项目，不知道能不能整合上连接数据库，就不用重复添加ck了()

**Comment by KimigaiiWuyi** [comment]
本来就有类似计划去做这个，不过不知道要咕到啥时候去了
`自动米游币`是群友去年七月份提的需求（（

**Comment by KimigaiiWuyi** [comment]
涉及到地址，放弃
