### ISSUE TITLE
米游币的签到能否每日自动进行呢

### ISSUE THREAD

**Issue by Putarku** [KimigaiiWuyi/GenshinUID#189]
如题。另外貌似每日第一次获取米游币均会失败，第二次才能成功

**Comment by KimigaiiWuyi** [comment]
`gs开启自动米游币`
失败的log有吗，我目前没有遇到过第一次会失败的

**Comment by Putarku** [comment]
这个我明天提交一下，今天的log被顶下去了

**Comment by Putarku** [comment]
![image](https://user-images.githubusercontent.com/66679443/161966389-8b2504f1-d3f9-4460-9907-3580d3129779.png)

**Comment by lgc2333** [comment]
访问超时，检查一下网络环境看看？
