### ISSUE TITLE
wiki功能建议新增查询突破材料和天赋材料的功能。

### ISSUE THREAD

**Issue by li704644993** [KimigaiiWuyi/GenshinUID#19]
RT。求大佬酌情考虑。。。。

**Comment by li704644993** [comment]
角色查询出来的内容实际上都比较基础，希望加在角色信息里。辛苦大佬。。。

**Comment by KimigaiiWuyi** [comment]
没有合适的Api，想加的话方法有点笨……考虑加，但也是之后的事了；目前有更好的其他插件实现[Genshin_Impact_Bot](https://github.com/H-K-Y/Genshin_Impact_bot)

**Comment by li704644993** [comment]
> 没有合适的Api，想加的话方法有点笨……考虑加，但也是之后的事了；目前有更好的其他插件实现[Genshin_Impact_Bot](https://github.com/H-K-Y/Genshin_Impact_bot)

好嘞，感谢大佬。

**Comment by wudifeixue** [comment]
说到这个，你这个插件和Genshin_Impact_Bot名字冲突导致默认两个插件无法同时使用，需要手动修改代码改变插件名称

**Comment by KimigaiiWuyi** [comment]
> 说到这个，你这个插件和Genshin_Impact_Bot名字冲突导致默认两个插件无法同时使用，需要手动修改代码改变插件名称

不会啊 我hoshino nb2都是两个都用的，没有冲突过

**Comment by KimigaiiWuyi** [comment]
现可通过`材料xx`命令（eg.`材料可莉`）来获取材料列表
