### ISSUE TITLE
gs开启自动米游币是只有私聊才有的命令吗，然后开启之后发现没有自动获取成功，日志也没有报错，手动获取能够成功。

### ISSUE THREAD

**Issue by SPLUS-VABLE** [KimigaiiWuyi/GenshinUID#190]

**Comment by KimigaiiWuyi** [comment]
无论你群聊还是私聊都可以，最后报告都会以`好友私聊`形式发送

**Comment by SPLUS-VABLE** [comment]
看了一下代码群聊好像不支持这个命令

**Comment by KimigaiiWuyi** [comment]
> 看了一下代码群聊好像不支持这个命令

Hoshino的 开启/关闭 类命令都不支持群聊

**Comment by SPLUS-VABLE** [comment]
然后米游币报告也没有私聊发送，签到的报告倒是有

**Comment by KimigaiiWuyi** [comment]
> > 看了一下代码群聊好像不支持这个命令
> 
> Hoshino的 开启/关闭 类命令都不支持群聊

大部分把，因为hoshino的私聊得单独写

**Comment by KimigaiiWuyi** [comment]
> 然后米游币报告也没有私聊发送，签到的报告倒是有

你私聊开启bot有反馈，但是并没有签到成功么？`stoken`绑定了吗

**Comment by SPLUS-VABLE** [comment]
stoken绑定了，而且也能开始获取米游币

**Comment by SPLUS-VABLE** [comment]
就是那个自动开启的没有成功

**Comment by KimigaiiWuyi** [comment]
> 就是那个自动开启的没有成功

bot有反馈说 成功开启么

**Comment by SPLUS-VABLE** [comment]
有

**Comment by KimigaiiWuyi** [comment]
> > 就是那个自动开启的没有成功
> 
> bot有反馈说 成功开启么

Hoshino的应该是只能私聊开启

**Comment by SPLUS-VABLE** [comment]
发送了成功

**Comment by KimigaiiWuyi** [comment]
> 发送了成功

没有错误log么？我研究一下

**Comment by SPLUS-VABLE** [comment]
看一下明天0：50分日志有没有吧，今天的没有看到

**Comment by SPLUS-VABLE** [comment]
谢谢大佬解答。

**Comment by KimigaiiWuyi** [comment]
更新之后，尝试重新开启自动米游币（私聊`gs开启自动米游币`）
然后使用命令`全部重获取`看看能否正常

**Comment by SPLUS-VABLE** [comment]
机器人反馈已开始执行，这个应该是正常吧

**Comment by SPLUS-VABLE** [comment]
![image](https://user-images.githubusercontent.com/42440354/162355390-6f0a88ae-98a9-4f89-b476-3986a5efb047.png)
完成了但是有报错

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/42440354/162355390-6f0a88ae-98a9-4f89-b476-3986a5efb047.png) 完成了但是有报错

看看go-cq端的log？

**Comment by SPLUS-VABLE** [comment]
![image](https://user-images.githubusercontent.com/42440354/162356469-ca9c271d-7893-4eef-b836-721b92e8f820.png)

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/42440354/162356469-ca9c271d-7893-4eef-b836-721b92e8f820.png)

每日自动获取米游币没有问题了；
只是私聊推送的问题，是因为你go-cq和bot的链接有问题

**Comment by SPLUS-VABLE** [comment]
好的，谢谢大佬解答！

**Comment by KimigaiiWuyi** [comment]
> > ![image](https://user-images.githubusercontent.com/42440354/162356469-ca9c271d-7893-4eef-b836-721b92e8f820.png)
> 
> 每日自动获取米游币没有问题了； 只是私聊推送的问题，是因为你go-cq和bot的链接有问题

你看一下你11:07之后的go-cq端log，那时候应该已经连上了才对，才能接收指令，看看报错

**Comment by SPLUS-VABLE** [comment]
好的

**Comment by KimigaiiWuyi** [comment]
> 好的

更新后再次尝试使用`全部重获取`，看看报告是否能正常发送

**Comment by SPLUS-VABLE** [comment]
好的，刚刚也在看这里的代码
