### ISSUE TITLE
大佬这个错误是为啥，发生错误 list index out of range,请检查后台输出。

### ISSUE THREAD

**Issue by 1340723643** [KimigaiiWuyi/GenshinUID#193]
![QQ图片20220409225107](https://user-images.githubusercontent.com/87091572/162579536-6a3c7e36-3cf2-42d2-b5d5-6c4417fdb9b0.jpg)
![Snipaste_2022-04-09_22-56-55](https://user-images.githubusercontent.com/87091572/162579538-2f07e8ba-bb40-4d43-bb1a-889f8eb5d974.png)

**Comment by lgc2333** [comment]
你查询时没有带uid，当然报错了2022年4月9日 22:58，果果 ***@***.***>写道：

**Comment by lgc2333** [comment]
请使用【查询】指令查看自己的信息2022年4月9日 23:22，student_2333 ***@***.***>写道：你查询时没有带uid，当然报错了2022年4月9日 22:58，果果 ***@***.***>写道：

**Comment by 1340723643** [comment]
按照你说操作的，现已解决，是我粗心没注意看文档，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KimigaiiWuyi/GenshinUID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 晚上11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 大佬这个错误是为啥，发生错误 list index out of range,请检查后台输出。 (Issue #193)





 请使用【查询】指令查看自己的信息2022年4月9日 23:22，student_2333 ***@***.***&gt;写道：你查询时没有带uid，当然报错了2022年4月9日 22:58，果果 ***@***.***&gt;写道：
