### ISSUE TITLE
[建议]查询失败返回语句优化

### ISSUE THREAD

**Issue by Putarku** [KimigaiiWuyi/GenshinUID#194]
例如
没有绑定cookies，使用“当前状态”“每月统计”等命令
当前情况：返回“未找到绑定信息”，这样信息不够明确，会有人一直绑定uid或者是mys
建议：更改为“未绑定cookies信息，使用【xx】命令获取绑定教程”，stoken同理

然后关于cookies获取这块，因为现在不是所有人手头都有电脑可以方便的用代码获取cookies。
所以我找了一下，有一个“alook浏览器”可以直接显示并且拷贝cookies出来，stoken也是一样可以获取的。建议加到教程或者提示中

**Comment by Putarku** [comment]
![image](https://user-images.githubusercontent.com/66679443/162616490-84531381-9a01-49e7-b90d-ba68c46dd0f4.png)

**Comment by MingxuanGame** [comment]
查询语句失败返回优化这个可以

但是alook浏览器在App Store是收费的，并不建议

**Comment by lgc2333** [comment]
Android可以试试via，具体方法我不赘述，用脚本功能就可以，或者kiwi browser，可以打开开发者控制台

**Comment by 741807012** [comment]
> 查询语句失败返回优化这个可以
> 
> 但是alook浏览器在App Store是收费的，并不建议

iOS快捷指令就可以获取Cookie，我自己写了一个[快捷指令](https://www.icloud.com/shortcuts/52de4af065504d3ba781354b9d81a135)还有安卓手机都可以完美运行这个插件了，不需要root不需要买服务器，iOS版安装插件还在研究，现在还是只能运行go-cqhttp远程访问插件

**Comment by 741807012** [comment]
> > 查询语句失败返回优化这个可以
> > 但是alook浏览器在App Store是收费的，并不建议
> 
> iOS快捷指令就可以获取Cookie，我自己写了一个[快捷指令](https://www.icloud.com/shortcuts/52de4af065504d3ba781354b9d81a135)还有安卓手机都可以完美运行这个插件了，不需要root不需要买服务器，iOS版安装插件还在研究，现在还是只能运行go-cqhttp远程访问插件

有什么问题可以加我QQ，名字就是我QQ号，备注那里看到添加的

**Comment by MingxuanGame** [comment]
获取cookie教程：#92 #201 #203
过段时间我会把教程指向这里
错误信息优化近期更新

**Comment by KimigaiiWuyi** [comment]
已优化~
