### ISSUE TITLE
Illegal header value b '*** 后面是COOKIE

### ISSUE THREAD

**Issue by NepPure** [KimigaiiWuyi/GenshinUID#2]
![image](https://user-images.githubusercontent.com/12379907/128140167-1e39ef9a-0842-4984-aa68-f061cfabdc80.png)

查询失败，尝试把日志打印出来是这样，大佬有无什么头绪

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/12379907/128140167-1e39ef9a-0842-4984-aa68-f061cfabdc80.png)
> 
> 查询失败，尝试把日志打印出来是这样，大佬有无什么头绪

cookies格式错误 检查一下三个地方的cookies输入是否正确，有无单引号引住等格式问题，（我猜最大可能是你把cookies复制直接覆盖了原本的单引号，cookies要放在单引号内部

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/128141266-acbebc64-3aef-4b54-bed2-8d9f9ccf6de5.png)

谢谢大佬 我这样一下就好了

**Comment by NepPure** [comment]
期待继续完善，

![image](https://user-images.githubusercontent.com/12379907/128141869-6a456bd6-e52e-49a3-ba94-fd8513062f0c.png)

所有角色这里都是F是指的啥

**Comment by KimigaiiWuyi** [comment]
> 期待继续完善，
> 
> ![image](https://user-images.githubusercontent.com/12379907/128141869-6a456bd6-e52e-49a3-ba94-fd8513062f0c.png)
> 
> 所有角色这里都是F是指的啥

full，满好感

**Comment by NepPure** [comment]
![image](https://user-images.githubusercontent.com/12379907/128142386-ee48ac4e-119f-451f-8688-04d97152e969.png)

这个位置显示的是QQ昵称有点怪啊，是不是应该显示旅行者的昵称

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/12379907/128142386-ee48ac4e-119f-451f-8688-04d97152e969.png)
> 
> 这个位置显示的是QQ昵称有点怪啊，是不是应该显示旅行者的昵称

api获取不到这个信息，我也想加2333

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/12379907/128142386-ee48ac4e-119f-451f-8688-04d97152e969.png)
> 
> 这个位置显示的是QQ昵称有点怪啊，是不是应该显示旅行者的昵称

有问题可以群里艾特我  我github回复怪累的

**Comment by NepPure** [comment]
```
>> 本文件内容为 https://api-takumi.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=160476586 的请求抓包详情，供您分析和定位问题。

1. 请求内容 Request:

GET /game_record/card/wapi/getGameRecordCard?uid=160476586 HTTP/1.1
Host: api-takumi.mihoyo.com
x-rpc-client_type: 5
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-cn
Accept: application/json, text/plain, */*
Origin: https://webstatic.mihoyo.com
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) miHoYoBBS/2.10.0
Connection: keep-alive
x-rpc-app_version: 2.10.0
Referer: https://webstatic.mihoyo.com/app/community-game-records/?bbs_auth_required=true&v=100&game_id=2&bbs_presentation_style=fullscreen&gid=2&user_id=160476586&uid=160476586
Cookie: *
DS: *



2. 响应内容 Response:

HTTP/1.1 200 OK
Date: Wed, 04 Aug 2021 07:49:57 GMT
Content-Type: application/json
Content-Length: 854
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin,X-Requested-With,Content-Type,Accept,gameName,Channel,DS
Access-Control-Allow-Methods: GET,POST,OPTIONS
Access-Control-Allow-Origin: https://webstatic.mihoyo.com
Set-Cookie: *
Set-Cookie: *
Vary: Accept-Encoding
X-Powered-By: takumi
X-Trace-Id: 7528e54cfcb5b27b:7528e54cfcb5b27b:0:1

{"retcode":0,"message":"OK","data":{"list":[{"has_role":true,"game_id":2,"game_role_id":"101407402","nickname":"皮纳特","region":"cn_gf01","level":56,"background_image":"https://upload-bbs.mihoyo.com/upload/2020/09/22/0762ab7cc42ac5a760bb4d1ea87b2c42_1236712390449986860.png","is_public":true,"data":[{"name":"活跃天数","type":1,"value":"312"},{"name":"获得角色数","type":1,"value":"29"},{"name":"成就达成数","type":1,"value":"269"},{"name":"深境螺旋","type":1,"value":"12-3"}],"region_name":"天空岛","url":"https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen\u0026bbs_auth_required=true\u0026v=100\u0026gid=2\u0026user_id=160476586","data_switches":[{"switch_id":1,"is_public":true,"switch_name":"个人主页卡片"},{"switch_id":2,"is_public":true,"switch_name":"角色详情数据"}]}]}}

```

这个信息在gamecard接口里面

**Comment by NepPure** [comment]
剩下的就交给作者大大啦 ✿✿ヽ(°▽°)ノ✿

F有点丑 要不要考虑整个❤之类

**Comment by KimigaiiWuyi** [comment]
> ```
> >> 本文件内容为 https://api-takumi.mihoyo.com/game_record/card/wapi/getGameRecordCard?uid=160476586 的请求抓包详情，供您分析和定位问题。
> 
> 1. 请求内容 Request:
> 
> GET /game_record/card/wapi/getGameRecordCard?uid=160476586 HTTP/1.1
> Host: api-takumi.mihoyo.com
> x-rpc-client_type: 5
> Accept-Encoding: gzip, deflate, br
> Accept-Language: zh-cn
> Accept: application/json, text/plain, */*
> Origin: https://webstatic.mihoyo.com
> User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) miHoYoBBS/2.10.0
> Connection: keep-alive
> x-rpc-app_version: 2.10.0
> Referer: https://webstatic.mihoyo.com/app/community-game-records/?bbs_auth_required=true&v=100&game_id=2&bbs_presentation_style=fullscreen&gid=2&user_id=160476586&uid=160476586
> Cookie: *
> DS: *
> 
> 
> 
> 2. 响应内容 Response:
> 
> HTTP/1.1 200 OK
> Date: Wed, 04 Aug 2021 07:49:57 GMT
> Content-Type: application/json
> Content-Length: 854
> Connection: keep-alive
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Headers: Origin,X-Requested-With,Content-Type,Accept,gameName,Channel,DS
> Access-Control-Allow-Methods: GET,POST,OPTIONS
> Access-Control-Allow-Origin: https://webstatic.mihoyo.com
> Set-Cookie: *
> Set-Cookie: *
> Vary: Accept-Encoding
> X-Powered-By: takumi
> X-Trace-Id: 7528e54cfcb5b27b:7528e54cfcb5b27b:0:1
> 
> {"retcode":0,"message":"OK","data":{"list":[{"has_role":true,"game_id":2,"game_role_id":"101407402","nickname":"皮纳特","region":"cn_gf01","level":56,"background_image":"https://upload-bbs.mihoyo.com/upload/2020/09/22/0762ab7cc42ac5a760bb4d1ea87b2c42_1236712390449986860.png","is_public":true,"data":[{"name":"活跃天数","type":1,"value":"312"},{"name":"获得角色数","type":1,"value":"29"},{"name":"成就达成数","type":1,"value":"269"},{"name":"深境螺旋","type":1,"value":"12-3"}],"region_name":"天空岛","url":"https://webstatic.mihoyo.com/app/community-game-records/?bbs_presentation_style=fullscreen\u0026bbs_auth_required=true\u0026v=100\u0026gid=2\u0026user_id=160476586","data_switches":[{"switch_id":1,"is_public":true,"switch_name":"个人主页卡片"},{"switch_id":2,"is_public":true,"switch_name":"角色详情数据"}]}]}}
> ```
> 
> 这个信息在gamecard接口里面

这个需要mys的id，实际查询起来感觉倒是比较麻烦 好多人不会去记米游社的id吧2333如果需求很高的话 倒也是可以做

**Comment by KimigaiiWuyi** [comment]
> 剩下的就交给作者大大啦 ✿✿ヽ(°▽°)ノ✿
> 
> F有点丑 要不要考虑整个❤之类
爱心加上去蛮奇怪的 我后续再优化一下

**Comment by NepPure** [comment]
原来这是mysid，淦 是有点蛋疼 不实用 我琢磨下

**Comment by NepPure** [comment]
实在不行的话 建议角色卡设计就不要显示昵称了，突出UID就行

**Comment by vaqua** [comment]
> ![image](https://user-images.githubusercontent.com/12379907/128140167-1e39ef9a-0842-4984-aa68-f061cfabdc80.png)
> 
> 查询失败，尝试把日志打印出来是这样，大佬有无什么头绪

楼主你好,我想问问这些错误日志在哪里找的?我出错了也想找出错日志
