### ISSUE TITLE
校验失败！请输入正确的Cookies！

### ISSUE THREAD

**Issue by gameovertse** [KimigaiiWuyi/GenshinUID#20]
我按照正确的方式获取到了米游社的cookies，但是在私聊机器人“添加 （我获取的cookies）”后，总是出现校验失败的问题。请问这个应该怎么解决
![QQ图片20211117111456](https://user-images.githubusercontent.com/86156447/142128167-6853b1d5-7eee-46a7-91d9-bf30859e686f.png)

**Comment by KimigaiiWuyi** [comment]
优先检查这个Cookies 对应的米游社账号 有没有登陆过手机端米游社/有没有原神账号；其次检查这个Cookies有没有account_id = xxxxxx ; Cookie_token = xxxxxx这两条参数

**Comment by gameovertse** [comment]
> 优先检查这个Cookies 对应的米游社账号 有没有登陆过手机端米游社/有没有原神账号；其次检查这个Cookies有没有account_id = xxxxxx ; Cookie_token = xxxxxx这两条参数

谢谢解答，刚刚检查了一下，确实没有你说的这两条参数，又严格按照教程的方法获取了一下，已解决。
