### ISSUE TITLE
添加cookies报错

### ISSUE THREAD

**Issue by yuyueamatsuki** [KimigaiiWuyi/GenshinUID#200]
之前的版本都没问题的，换最新版后就这样了
![image](https://user-images.githubusercontent.com/86163024/163658328-40206a9b-dc3d-4075-9793-b4f9da453ae5.png)

**Comment by yuyueamatsuki** [comment]
![image](https://user-images.githubusercontent.com/86163024/163658444-ed5de73c-e0ba-4acf-ae1e-c7325be42e42.png)

**Comment by Putarku** [comment]
你这cookies好像缺少那两个关键字段，cookies_token和account_id

**Comment by yuyueamatsuki** [comment]
> 你这cookies好像缺少那两个关键字段，cookies_token和account_id

有的
![QJ{PHZ$LSC(AR6H$ZQU7) M](https://user-images.githubusercontent.com/86163024/163659121-f367d5fc-4df9-4d44-8018-f149d67bbd0b.png)

**Comment by yuyueamatsuki** [comment]
顺便提一下nonebot2版本是alpha16

**Comment by MingxuanGame** [comment]
感觉像是ck失效了
重新获取看看

**Comment by KimigaiiWuyi** [comment]
就是CK失效了，应该重新获取

**Comment by yuyueamatsuki** [comment]
> 就是CK失效了，应该重新获取

重新获取仍然是这样![IMG_20220417_185517.jpg](https://user-images.githubusercontent.com/86163024/163711481-7663b1bd-3555-462a-a45a-fbc53cc89468.jpg)
