### ISSUE TITLE
安卓端获取Cookie工具

### ISSUE THREAD

**Issue by shirokurakana** [KimigaiiWuyi/GenshinUID#203]
https://thdog.lanzout.com/idQNG03cajbg

其实就是在webview中登录米游社，然后取cookie
可惜源码搞丢了，不然还能再优化一下体验

**Comment by Juenia** [comment]
可以用via运行huoquCookies的代码，或者某工具(应急食品)中也可以长按获取Cookies

**Comment by Z735803792** [comment]
有没有办法安卓端获取Stoken
