### ISSUE TITLE
【反馈问题】nb版无法使用部分功能，查询uid和mys

### ISSUE THREAD

**Issue by Z735803792** [KimigaiiWuyi/GenshinUID#205]
【问题】:使用uid或mys指令时list index out of range

python3.8.10，nonebot2.0.0-beta2
安装方法：在lib\site-backages目录下get clone，并单独拿出文件夹“genshin_uid”
在bot.py文件中加入
nonebot.load_plugin("genshin_uid")

问题：在以成功绑定cookie和stoken的情况下，查询uid时终端
![QQ截图20220418170602](https://user-images.githubusercontent.com/70925546/163785529-c8bca299-1860-4a75-b4fc-1f461fac1bc9.png)
对话信息：
![QQ截图20220418170739](https://user-images.githubusercontent.com/70925546/163785637-e39ecccc-34d8-4b20-9332-2b0a2abbbb9e.png)

已尝试清除无效cookie也没有解决问题。加载插件时终端无任何报错。

p.s.能正常使用的功能：当前状态、当前信息、每月统计、活动列表、签到、获取米游币并无问题
无法正常使用的功能：uid和mys，查询深渊，wiki板块全部

**Comment by KimigaiiWuyi** [comment]
查询已绑定的自己的号用命令`查询`
查询别人的用`uid123456`这样的形式，单独输入uid无效果
尽量在群聊中使用，另外wiki异常的log有吗

**Comment by Z735803792** [comment]
**uid:使用uid查询没问题，但是无法通过绑定快速查询（已经绑定了cookie)**
![QQ截图20220418172555](https://user-images.githubusercontent.com/70925546/163808683-e597878e-4614-4bff-bcb8-ee4fff7cf6d2.png)


**wiki:推荐/攻略、用什么/怎么养、给谁用/谁能用功能无法使用，终端无回应**
![QQ截图20220418202104](https://user-images.githubusercontent.com/70925546/163809116-ac874aed-746a-450a-9e37-d4ba437a764d.png)
![QQ截图20220418203925](https://user-images.githubusercontent.com/70925546/163809674-00e668af-7abb-439b-9fc0-1bec0ca8358f.png)


次要：天赋查询，只能查除了普攻技能以外的数据，终端回应下2图（并无大碍，因为实际上没什么人查这个）
![QQ截图20220418202441](https://user-images.githubusercontent.com/70925546/163809224-cd423a83-4d44-4807-a953-e71e01c800c5.png)
![QQ截图20220418173113](https://user-images.githubusercontent.com/70925546/163809407-7155f033-ef59-4d3c-bdbb-461df9a8cc74.png)

**Comment by Juenia** [comment]
> **uid:使用uid查询没问题，但是无法通过绑定快速查询（已经绑定了cookie)**
> ![QQ截图20220418172555](https://user-images.githubusercontent.com/70925546/163808683-e597878e-4614-4bff-bcb8-ee4fff7cf6d2.png)
> 
> 
> **wiki:推荐/攻略、用什么/怎么养、给谁用/谁能用功能无法使用，终端无回应**
> ![QQ截图20220418202104](https://user-images.githubusercontent.com/70925546/163809116-ac874aed-746a-450a-9e37-d4ba437a764d.png)
> ![QQ截图20220418203925](https://user-images.githubusercontent.com/70925546/163809674-00e668af-7abb-439b-9fc0-1bec0ca8358f.png)
> 
> 
> 次要：天赋查询，只能查除了普攻技能以外的数据，终端回应下2图（并无大碍，因为实际上没什么人查这个）
> ![QQ截图20220418202441](https://user-images.githubusercontent.com/70925546/163809224-cd423a83-4d44-4807-a953-e71e01c800c5.png)
> ![QQ截图20220418173113](https://user-images.githubusercontent.com/70925546/163809407-7155f033-ef59-4d3c-bdbb-461df9a8cc74.png)
> 
> 

绑定uid后使用的指令为《查询》

**Comment by KimigaiiWuyi** [comment]
`git pull`更新应该可以解决

**Comment by Z735803792** [comment]
> 

并不行
![image](https://user-images.githubusercontent.com/70925546/163818615-f7b9f01c-60c5-4862-bb31-412462073212.png)

**Comment by KimigaiiWuyi** [comment]
> > 
> 
> 并不行 ![image](https://user-images.githubusercontent.com/70925546/163818615-f7b9f01c-60c5-4862-bb31-412462073212.png)

log还是一样吗？

**Comment by Z735803792** [comment]
> > > 
> > 
> > 
> > 并不行 ![image](https://user-images.githubusercontent.com/70925546/163818615-f7b9f01c-60c5-4862-bb31-412462073212.png)
> 
> log还是一样吗？

不一样了，这次没有报错了
![image](https://user-images.githubusercontent.com/70925546/163818876-62960708-bfdc-4690-8b99-83426a35bcc3.png)

**Comment by KimigaiiWuyi** [comment]
> > > > 
> > > 
> > > 
> > > 并不行 ![image](https://user-images.githubusercontent.com/70925546/163818615-f7b9f01c-60c5-4862-bb31-412462073212.png)
> > 
> > 
> > log还是一样吗？
> 
> 不一样了，这次没有报错了 ![image](https://user-images.githubusercontent.com/70925546/163818876-62960708-bfdc-4690-8b99-83426a35bcc3.png)

考虑到没有报错，应该是你Nonebot2设置有误，`COMMAND_START`可以设置成`['']`空白，默认应该是只识别/前缀，所以你可以使用`/查询`等以此类推，具体设置可以参阅Nonebot2的文档

**Comment by Z735803792** [comment]
出现新问题了，git pull后出现的，前缀我一直设置是空白的。
1、指令：gs帮助
![image](https://user-images.githubusercontent.com/70925546/163820649-8ab6ca78-e5e3-452c-b021-a7675da1af26.png)

2、下面这个终端并没有报错
![image](https://user-images.githubusercontent.com/70925546/163820960-21768ea9-dc80-4c49-83ed-09debc73096c.png)

3、wiki的查询依旧那几个没反应

**Comment by MingxuanGame** [comment]
攻略由于那个参数的问题进不了事件响应
等我更新一下

**Comment by MingxuanGame** [comment]
更新试试

**Comment by Z735803792** [comment]
已更新，除了上述绑定仍然不能快速查询（uid是快捷指令吗？）且终端没有报错
![image](https://user-images.githubusercontent.com/70925546/163827428-d38410e6-d8f4-4b0c-bd50-e1d20ceaddea.png)

只剩下面两个wiki不能查询的：天赋和角色（xx推荐好像也是查角色功能，这个能用）且终端无提示
![image](https://user-images.githubusercontent.com/70925546/163826918-7f4e859a-f677-4818-a65d-aa4cfe70eb18.png)
剩下的功能全部都正常运行，感谢大佬的更新ozr，个人而言此插件已经可以正常使用了。

**Comment by MingxuanGame** [comment]
> 已更新，除了上述绑定仍然不能快速查询（uid是快捷指令吗？）且终端没有报错
> ![image](https://user-images.githubusercontent.com/70925546/163827428-d38410e6-d8f4-4b0c-bd50-e1d20ceaddea.png)
> 
> 只剩下面两个wiki不能查询的：天赋和角色（xx推荐好像也是查角色功能，这个能用）且终端无提示
> ![image](https://user-images.githubusercontent.com/70925546/163826918-7f4e859a-f677-4818-a65d-aa4cfe70eb18.png)
> 剩下的功能全部都正常运行，感谢大佬的更新ozr，个人而言此插件已经可以正常使用了。

离谱，天赋和角色推送前我已经单元测试没问题了，等下我再看看哪里的问题

**Comment by MiniGrayGay** [comment]
前三个天赋有具体数值是合并转发来的，会不会是风控发不出，这玩意很迷，在我的群里面，七七Wiki是发不出的，一斗也是

**Comment by KimigaiiWuyi** [comment]
有空仔细看一下issuse了，我感觉应该是你在私聊情况下使用导致
群聊下应该是正常的
