### ISSUE TITLE
【问题反馈】关于群内推送

### ISSUE THREAD

**Issue by 741807012** [KimigaiiWuyi/GenshinUID#206]
群内群员绑定好后群里开启了推送，然后退群了，群内一直推送，无法关闭

**Comment by KimigaiiWuyi** [comment]
倒是没有想过这个问题，先临时进入数据库关闭开关？用一个能打开`ID_DATA.DB`的软件，如`DB Browser for SQLite`或`sqlite studio`，在`NewCookiesTable`这个表里，找到他的uid，对应的`StatusA`改为`off`即可
