### ISSUE TITLE
自动签到和推送提示未绑定UID的BUG

### ISSUE THREAD

**Issue by snhun** [KimigaiiWuyi/GenshinUID#207]
![BUG](https://user-images.githubusercontent.com/5186603/164890748-0f4a5051-6ee3-46cc-856e-49f890579672.png)

**Comment by KimigaiiWuyi** [comment]
发一下log & 哪一个版本的插件

**Comment by snhun** [comment]
> 发一下log & 哪一个版本的插件
![log](https://user-images.githubusercontent.com/5186603/164893589-707a643f-d3a9-4012-a74f-4ba3f5cbe267.png)

nonebot2-beta1

**Comment by snhun** [comment]
查询@群友，获取的还是自己的信息

**Comment by KimigaiiWuyi** [comment]
> 查询@群友，获取的还是自己的信息

现在是正常的吗

**Comment by snhun** [comment]
> > 查询@群友，获取的还是自己的信息
> 
> 现在是正常的吗

测试已正常
