### ISSUE TITLE
获取失败

### ISSUE THREAD

**Issue by 136585816** [KimigaiiWuyi/GenshinUID#209]
![image](https://user-images.githubusercontent.com/60592078/165095036-7dfc2adc-3afd-404e-9c05-a0f8234d7214.png)
![image](https://user-images.githubusercontent.com/60592078/165094923-d094f865-12aa-4abd-9176-de6c1c6d43d8.png)
是SSL的问题？请问这个要怎么解决……

**Comment by KimigaiiWuyi** [comment]
有开代理之类的么

**Comment by 136585816** [comment]
没有，这台服务器本身就是在外网的

**Comment by 136585816** [comment]
> 有开代理之类的么

没有，这台服务器本身就是在外网的

**Comment by KimigaiiWuyi** [comment]
> > 有开代理之类的么
> 
> 没有，这台服务器本身就是在外网的

检查一下环境变量中是否有openssl的相关配置，可以先注释掉么

**Comment by 136585816** [comment]
> > > 有开代理之类的么
> > 
> > 
> > 没有，这台服务器本身就是在外网的
> 
> 检查一下环境变量中是否有openssl的相关配置，可以先注释掉么
服务器环境变量没openssl的配置，系统是debian9，python3.9.12、3.10.4，OpenSSL1.1.1，libressl3.0.2都尝试过了，都是这个问题。不过我这台服务器上还搭载了ws+tls的V2ray，不知道是不是这个的影响

我在本地又建了一个centos7.9的虚拟机，Python3.9.12,openssl1.02k,【UID，mys】命令可以用，但只能查询到自己绑定的玩家信息，其他人的UID没法查询，【查询深渊，UID深渊】查别人的直接没有反应，查自己的报获取失败……
![image](https://user-images.githubusercontent.com/60592078/165266456-72b33456-5f4e-4fee-a164-6ced2ec08ac4.png)

![image](https://user-images.githubusercontent.com/60592078/165265163-9c6b3a45-7a4c-4b33-808d-0f9401e73047.png)
![image](https://user-images.githubusercontent.com/60592078/165266257-6cbd35cc-a105-4fe5-93cb-a7df6cf2a18f.png)

**Comment by KimigaiiWuyi** [comment]
> > > > 有开代理之类的么
> > > 
> > > 
> > > 没有，这台服务器本身就是在外网的
> > 
> > 
> > 检查一下环境变量中是否有openssl的相关配置，可以先注释掉么
> > 服务器环境变量没openssl的配置，系统是debian9，python3.9.12、3.10.4，OpenSSL1.1.1，libressl3.0.2都尝试过了，都是这个问题。不过我这台服务器上还搭载了ws+tls的V2ray，不知道是不是这个的影响
> 
> 我在本地又建了一个centos7.9的虚拟机，Python3.9.12,openssl1.02k,【UID，mys】命令可以用，但只能查询到自己绑定的玩家信息，其他人的UID没法查询，【查询深渊，UID深渊】查别人的直接没有反应，查自己的报获取失败…… ![image](https://user-images.githubusercontent.com/60592078/165266456-72b33456-5f4e-4fee-a164-6ced2ec08ac4.png)
> 
> ![image](https://user-images.githubusercontent.com/60592078/165265163-9c6b3a45-7a4c-4b33-808d-0f9401e73047.png) ![image](https://user-images.githubusercontent.com/60592078/165266257-6cbd35cc-a105-4fe5-93cb-a7df6cf2a18f.png)

所有uid，mys均为小写，大写不识别

**Comment by KimigaiiWuyi** [comment]
改为小写之后是否能正常识别？（

**Comment by 136585816** [comment]
> 改为小写之后是否能正常识别？（

本地部署的正常了，所有的都能用，云上的还是那个ssl问题，不知道怎么解决

**Comment by KimigaiiWuyi** [comment]
> > 改为小写之后是否能正常识别？（
> 
> 本地部署的正常了，所有的都能用，云上的还是那个ssl问题，不知道怎么解决

有检查过环境变量内有无openssl相关参数？

**Comment by 136585816** [comment]
> > > 改为小写之后是否能正常识别？（
> > 
> > 
> > 本地部署的正常了，所有的都能用，云上的还是那个ssl问题，不知道怎么解决
> 
> 有检查过环境变量内有无openssl相关参数？

服务器环境变量没openssl的配置，系统是debian9，python3.9.12、3.10.4，OpenSSL1.1.1，libressl3.0.2都尝试过了，都是这个问题。不过我这台服务器上还搭载了ws+tls的V2ray，不知道是不是这个的影响

**Comment by KimigaiiWuyi** [comment]
> > > > 改为小写之后是否能正常识别？（
> > > 
> > > 
> > > 本地部署的正常了，所有的都能用，云上的还是那个ssl问题，不知道怎么解决
> > 
> > 
> > 有检查过环境变量内有无openssl相关参数？
> 
> 服务器环境变量没openssl的配置，系统是debian9，python3.9.12、3.10.4，OpenSSL1.1.1，libressl3.0.2都尝试过了，都是这个问题。不过我这台服务器上还搭载了ws+tls的V2ray，不知道是不是这个的影响

停止v2ray服务是否会正常？看起来很值得怀疑

**Comment by KimigaiiWuyi** [comment]
> > > > > > 改为小写之后是否能正常识别？（
> > > > > 
> > > > > 
> > > > > 本地部署的正常了，所有的都能用，云上的还是那个ssl问题，不知道怎么解决
> > > > 
> > > > 
> > > > 有检查过环境变量内有无openssl相关参数？
> > > 
> > > 
> > > 服务器环境变量没openssl的配置，系统是debian9，python3.9.12、3.10.4，OpenSSL1.1.1，libressl3.0.2都尝试过了，都是这个问题。不过我这台服务器上还搭载了ws+tls的V2ray，不知道是不是这个的影响
> > 
> > 
> > 停止v2ray服务是否会正常？看起来很值得怀疑
> 
> 尝试了一下，还是不行

那不懂了，先留着issuse，看看有没有大佬路过解决一下（

**Comment by half-ghost** [comment]
我今天新装的插件也遇到此问题，和你一样的报错，后边解决了，希望可以帮到你。参考的文章:[https://www.cnblogs.com/anjingshen/p/15591858.html](https://www.cnblogs.com/anjingshen/p/15591858.html)，第4.2.4节。如果觉得文章说的不够详细，可以参考我的补充，不过我用的是windows服务器，可能和你不太一样。文章中提到的cacert.pem文件似乎是位于 **你安装python的根目录\Lib\site-packages\certifi**下（对我而言是在这里），然后去添加环境变量** SSL_CERT_FILE，他的值为这个路径，具体到cacert.pem，然后再去python中运行
`import ssl
ssl.get_default_verify_paths()`
这两句代码，如果看到cafile=刚刚设置的路径的话，说明已经成功了，这时候再去试试看这个指令，没报错的话就大功告成，还有报错那我就不知道了
