### ISSUE TITLE
【建议】验证Cookie后发送消息问题

### ISSUE THREAD

**Issue by 741807012** [KimigaiiWuyi/GenshinUID#210]
建议分段发送或者直接表明正常的Cookie有多少，失效的有多少被删除了，我机器人Cookie过多，QQ都发不出消息了

**Comment by KimigaiiWuyi** [comment]
已调整，尝试`git pull`更新后，是否输出精简信息（仅当ck数量大于9生效）

**Comment by 741807012** [comment]
> 已调整，尝试更新后，是否输出精简信息（仅当ck数量大于9生效）`git pull`

![image](https://user-images.githubusercontent.com/90551536/165322588-fc7a77a6-f874-44e9-b6ad-363e5bf047f0.png)
正常了，就是为什么Cookie后面要加个s呢

**Comment by KimigaiiWuyi** [comment]
> > 已调整，尝试更新后，是否输出精简信息（仅当ck数量大于9生效）`git pull`
> 
> ![image](https://user-images.githubusercontent.com/90551536/165322588-fc7a77a6-f874-44e9-b6ad-363e5bf047f0.png) 正常了，就是为什么Cookie后面要加个s呢

复数形式，个人习惯233（
