### ISSUE TITLE
频道机器人代码存在语法错误无法运行

### ISSUE THREAD

**Issue by yen-qian** [KimigaiiWuyi/GenshinUID#211]
![截图](https://user-images.githubusercontent.com/23378957/165503577-3fc3f612-9ab8-4e34-9f97-7fc64e814a0c.png)

**Comment by KimigaiiWuyi** [comment]
`git pull`后试一试，好像上次规范引号的时候把东西弄乱了，不过频道Bot这边确实很少去管了
