### ISSUE TITLE
[建议]米游社签到和获取米游币改成随机时间

### ISSUE THREAD

**Issue by G41mywaifu** [KimigaiiWuyi/GenshinUID#212]
用一个变量来控制进行时间  然后用零点的定时任务来控制这个变量  
我简单测试了一下应该是可以的 ， 一直同一个时间签到会不会增加被封号的可能。。

**Comment by KimigaiiWuyi** [comment]
sleep有随机函数，每天都不完全是一个时间

**Comment by G41mywaifu** [comment]
emm ，好吧，但我觉得间隔稍大一点比较好
