### ISSUE TITLE
有没有办法优化一下wiki 查询

### ISSUE THREAD

**Issue by jinxx52** [KimigaiiWuyi/GenshinUID#215]
比如可选的@触发，在env里添加指令前缀似乎无效

**Comment by KimigaiiWuyi** [comment]
wiki类的指令 好像没有@的可选触发吧

**Comment by jinxx52** [comment]
> wiki类的指令 好像没有@的可选触发吧

就是有没有机会加上这样的可选@触发，正常聊天也会触发就有点搞，![Screenshot_2022-04-28-16-39-37-10_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/86406052/165713206-84956ecf-549f-408b-ab15-e6ced09c1be2.jpg) 
这个是我已经在env里改过command_start只有/触发了，但是正常聊天还会有，还是说只是我的个例吗

**Comment by KimigaiiWuyi** [comment]
如果你是最新的`nonebot2-beta1`分支下的，就可以只响应COMMAND_START中的内容

**Comment by jinxx52** [comment]
> 如果你是最新的`nonebot2-beta1`分支下的，就可以只响应COMMAND_START中的内容

谢谢
