### ISSUE TITLE
qq频道 Bot代码无法正常使用功能

### ISSUE THREAD

**Issue by yen-qian** [KimigaiiWuyi/GenshinUID#217]
![image](https://user-images.githubusercontent.com/23378957/165799167-afb6cf9c-087b-43f3-93bc-41a6c4e816f1.png)

**Comment by KimigaiiWuyi** [comment]
好像是因为频道的api变动，at可以自己提取出来了？
很久没看了，晚上回去检查一下

**Comment by yen-qian** [comment]
感谢

**Comment by KimigaiiWuyi** [comment]
> 感谢

晚了一天，现在应该可以使用大部分功能了~
