### ISSUE TITLE
wiki需要更新

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#218]
如题

**Comment by KimigaiiWuyi** [comment]
[Wiki页面](https://github.com/KimigaiiWuyi/GenshinUID/wiki)吗，还是指wiki模块的api

**Comment by lgc2333** [comment]
Wiki页面

从 Windows 版邮件发送

发件人: Wuyi无疑
发送时间: 2022年4月30日 20:28
收件人: KimigaiiWuyi/GenshinUID
抄送: student_2333; Author
主题: Re: [KimigaiiWuyi/GenshinUID] wiki需要更新 (Issue #218)

Wiki页面吗，还是指wiki模块的api

**Comment by KimigaiiWuyi** [comment]
已更新`gs帮助`和wiki页面
