### ISSUE TITLE
【BUG反馈】NoneBot2

### ISSUE THREAD

**Issue by 741807012** [KimigaiiWuyi/GenshinUID#219]
机器人好友查询功能不能用，应该是没加判断绑定
![IMG_3619](https://user-images.githubusercontent.com/90551536/166100638-a5895a49-8b30-4e66-853a-d21917b82455.PNG)
群内查询@群友，查询到的是我自己信息
![image](https://user-images.githubusercontent.com/90551536/166100742-6e43d6bc-a417-4874-aa9d-02f83bcd383f.png)

**Comment by 741807012** [comment]
Nonebot2-beta2，忘记打后面beta2了

**Comment by MingxuanGame** [comment]
和 #207 一样的问题

应该是这里的 `extract_plain_text` 将 @ 过滤掉了

https://github.com/KimigaiiWuyi/GenshinUID/blob/728ea9abc241c74aa4bb9bba232e0dfea8c4686e/genshin_uid/main.py#L952-L954

等下去看看

**Comment by KimigaiiWuyi** [comment]
现在是正常的吗？

**Comment by 741807012** [comment]
> 现在是正常的吗？

没时间更新，现在更新了正常了
