### ISSUE TITLE
添加Cookies失败

### ISSUE THREAD

**Issue by MrLinda** [KimigaiiWuyi/GenshinUID#221]
'NoneType' object is not subscriptable
![image](https://user-images.githubusercontent.com/22100216/166178534-2a595f3f-82eb-46c6-8523-ad285cb2e591.png)
![24RV8A (9@Z7{QPMQPGHO$3](https://user-images.githubusercontent.com/22100216/166178553-32dbc726-ede8-411f-9e8c-53b97a8e2f99.png)

**Comment by KimigaiiWuyi** [comment]
`cookie`内需要包含`acount_id`和`cookie_token`两个参数，如果没有的话，建议退出米游社然后，然后重新登陆获取；或者可以考虑使用`无痕模式`登录获取

**Comment by MrLinda** [comment]
![L MA3PA ) 0W5%RXBCBDY33](https://user-images.githubusercontent.com/22100216/166184870-5e7fb5a5-04d5-499e-ab64-68cf53f04533.png)
这两个参数都有

**Comment by KimigaiiWuyi** [comment]
> ![L MA3PA ) 0W5%RXBCBDY33](https://user-images.githubusercontent.com/22100216/166184870-5e7fb5a5-04d5-499e-ab64-68cf53f04533.png) 这两个参数都有

可能是ck刚获取就失效了，建议按照上面方法重新获取
> 退出米游社然后，然后重新登陆获取；或者可以考虑使用无痕模式登录获取

**Comment by MrLinda** [comment]
两种方法都试了，
还是不行

**Comment by KimigaiiWuyi** [comment]
> 两种方法都试了， 还是不行

奇怪欸，这个米游社账号是你玩原神的号么

**Comment by MrLinda** [comment]
是的，我也很奇怪。昨天晚上都能用的，今天早上就不行了

**Comment by 741807012** [comment]
> 是的，我也很奇怪。昨天晚上都能用的，今天早上就不行了

无痕模式重新获取，不行就用苹果快捷指令，记得无痕模式

**Comment by MrLinda** [comment]
我把服务器重装了一遍就好了
