### ISSUE TITLE
好多无意义的换行

### ISSUE THREAD

**Issue by xiaofeicn** [KimigaiiWuyi/GenshinUID#223]
最近的更新比以往多了很多无意义的换行，这个以后会修复一下吗

**Comment by MingxuanGame** [comment]
希望能提供一下具体的分支和文件，有时间会看看

**Comment by xiaofeicn** [comment]
分支:noebot2

**Comment by xiaofeicn** [comment]
文件 main

**Comment by MingxuanGame** [comment]
空行并不是无意义
这个是 PEP8 样式规范
相关参考：https://peps.python.org/pep-0008/#blank-lines
