### ISSUE TITLE
无法使用查询uid等功能

### ISSUE THREAD

**Issue by chuanchuan744** [KimigaiiWuyi/GenshinUID#224]
如题
![2](https://user-images.githubusercontent.com/66564610/166664475-85e2d07d-2122-435f-be5d-3f73e63dede5.png)
![1](https://user-images.githubusercontent.com/66564610/166664482-658316d6-0c61-4ba4-9893-8308aa9a9cfa.png)

**Comment by MingxuanGame** [comment]
输入`/校验全部Cookies`试试

**Comment by chuanchuan744** [comment]
都没法绑定
![3](https://user-images.githubusercontent.com/66564610/166666606-9a32f487-d971-4232-a663-20d3a221853b.png)

![4](https://user-images.githubusercontent.com/66564610/166666597-08325e87-2ebc-408c-867e-96a41cdc2dab.png)

**Comment by MingxuanGame** [comment]
你的 Cookie 缺一些东西
参考#221

**Comment by chuanchuan744** [comment]
已解决 感谢！
