### ISSUE TITLE
米游币签到失败

### ISSUE THREAD

**Issue by XiaoFuOS** [KimigaiiWuyi/GenshinUID#230]
cookie明明有了的
![image](https://user-images.githubusercontent.com/103229747/167975717-157ccc9c-8d7f-472f-bb63-f2d3f6bc4708.png)
![image](https://user-images.githubusercontent.com/103229747/167975817-efbd5859-d864-4e86-a327-00f72f801c7c.png)
![image](https://user-images.githubusercontent.com/103229747/167975840-1b43c1cb-446a-4a32-b15d-3797fc235ddb.png)
![image](https://user-images.githubusercontent.com/103229747/167975889-b07e5b9c-4425-461f-a088-ea4ffef26fcb.png)

看着cookie也没失效

**Comment by KimigaiiWuyi** [comment]
虽然米游币的提示是Cookies，但实际用的是Stoken，说明stoken失效了，如果检查米游社任务确实没做的话，重新试一下添加stoken

**Comment by XiaoFuOS** [comment]
> 虽然米游币的提示是Cookies，但实际用的是Stoken，说明stoken失效了，如果检查米游社任务确实没做的话，重新试一下添加stoken

![image](https://user-images.githubusercontent.com/103229747/167984641-d79a949e-136b-4d03-b85b-0b89d0e817a6.png)
![image](https://user-images.githubusercontent.com/103229747/167984674-f39baca1-fe6f-4aa6-be41-cb2fd473eae0.png)
刚加也一样，就很怪

**Comment by lgc2333** [comment]
建议提供后台日志，以便更好定位问题原因

**Comment by XiaoFuOS** [comment]
> 建议提供后台日志，以便更好定位问题原因

![image](https://user-images.githubusercontent.com/103229747/168274008-8537ecf2-b157-4f52-b31a-f50d2e10a5f3.png)
就这两段

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/168311705-ae0c4674-8207-44f2-b8ce-74604b6da387.png)
看起来是这里的问题…… @KimigaiiWuyi

**Comment by KimigaiiWuyi** [comment]
> 有没有一种可能，讨论区已经手动签到过了，返回了已经签到过的err
> 
> > ![image](https://user-images.githubusercontent.com/59048777/168311705-ae0c4674-8207-44f2-b8ce-74604b6da387.png) 看起来是这里的问题…… @KimigaiiWuyi
> 
> 有没有一种可能，签到已经手动进行过了，返回的是已经签到过的err

emmmm，我已经忘记API返回值是什么样了
@XiaoFuOS 米游社会显示任务已完成嘛？
