### ISSUE TITLE
请问这个情况改如何解决呢？

### ISSUE THREAD

**Issue by GuiltyKirito** [KimigaiiWuyi/GenshinUID#231]
执行uid命令时候 返回以下错误，请问如何解决呢？
```
获取失败，有可能是数据状态有问题,
[Errno 2] No such file or directory: '/home/nb2/GShin/./src/plugins/GenshinUID/mihoyo_bbs/bg'
请检查后台输出。
```

我检查了路径，确实没有这个路径，我是需要改成什么吗？
最新分支

![image](https://user-images.githubusercontent.com/13746290/168422855-fcb25b96-86cf-4344-a0e9-74676c4f53a9.png)

**Comment by KimigaiiWuyi** [comment]
看了一眼仓库中是有这个路径的啊
https://github.com/KimigaiiWuyi/GenshinUID/tree/nonebot2-beta1/genshin_uid/mihoyo_libs/mihoyo_bbs/bg

**Comment by GuiltyKirito** [comment]
> 看了一眼仓库中是有这个路径的啊 https://github.com/KimigaiiWuyi/GenshinUID/tree/nonebot2-beta1/genshin_uid/mihoyo_libs/mihoyo_bbs/bg

不知道为啥~那我拷贝下这几个文件

**Comment by GuiltyKirito** [comment]
![image](https://user-images.githubusercontent.com/13746290/169451108-d842085b-34f1-41aa-9636-d2b207c2d05d.png)
添加cookies失败

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/13746290/169451108-d842085b-34f1-41aa-9636-d2b207c2d05d.png) 添加cookies失败

是否是最新版本？
应该是前天下午，米游社API变动，会造成校验失败

**Comment by GuiltyKirito** [comment]
> > ![image](https://user-images.githubusercontent.com/13746290/169451108-d842085b-34f1-41aa-9636-d2b207c2d05d.png) 添加cookies失败
> 
> 是否是最新版本？ 应该是前天下午，米游社API变动，会造成校验失败

坑爹的米忽悠，我这就重新装一下~

**Comment by GuiltyKirito** [comment]
> > ![image](https://user-images.githubusercontent.com/13746290/169451108-d842085b-34f1-41aa-9636-d2b207c2d05d.png) 添加cookies失败
> 
> 是否是最新版本？ 应该是前天下午，米游社API变动，会造成校验失败

试了下，还是不行，代码已经是最新提交 
![image](https://user-images.githubusercontent.com/13746290/169632806-bcbc03b4-8b2c-4773-8115-b77d4a9ff631.png)
是我少执行了什么咩？

**Comment by KimigaiiWuyi** [comment]
> > > ![image](https://user-images.githubusercontent.com/13746290/169451108-d842085b-34f1-41aa-9636-d2b207c2d05d.png) 添加cookies失败
> > 
> > 
> > 是否是最新版本？ 应该是前天下午，米游社API变动，会造成校验失败
> 
> 试了下，还是不行，代码已经是最新提交 ![image](https://user-images.githubusercontent.com/13746290/169632806-bcbc03b4-8b2c-4773-8115-b77d4a9ff631.png) 是我少执行了什么咩？

这个版本应该是OK的，请重新登陆米游社获取ck添加试试，还不行的话，截图log我看看

**Comment by GuiltyKirito** [comment]
> > > > ![image](https://user-images.githubusercontent.com/13746290/169451108-d842085b-34f1-41aa-9636-d2b207c2d05d.png) 添加cookies失败
> > > 
> > > 
> > > 是否是最新版本？ 应该是前天下午，米游社API变动，会造成校验失败
> > 
> > 
> > 试了下，还是不行，代码已经是最新提交 ![image](https://user-images.githubusercontent.com/13746290/169632806-bcbc03b4-8b2c-4773-8115-b77d4a9ff631.png) 是我少执行了什么咩？
> 
> 这个版本应该是OK的，请重新登陆米游社获取ck添加试试，还不行的话，截图log我看看

![image](https://user-images.githubusercontent.com/13746290/169633323-8c41bf61-5e4c-4728-967f-db3a797a9b91.png)


大佬666，大佬帮忙过目~

**Comment by KimigaiiWuyi** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/13746290/169451108-d842085b-34f1-41aa-9636-d2b207c2d05d.png) 添加cookies失败
> > > > 
> > > > 
> > > > 是否是最新版本？ 应该是前天下午，米游社API变动，会造成校验失败
> > > 
> > > 
> > > 试了下，还是不行，代码已经是最新提交 ![image](https://user-images.githubusercontent.com/13746290/169632806-bcbc03b4-8b2c-4773-8115-b77d4a9ff631.png) 是我少执行了什么咩？
> > 
> > 
> > 这个版本应该是OK的，请重新登陆米游社获取ck添加试试，还不行的话，截图log我看看
> 
> ![image](https://user-images.githubusercontent.com/13746290/169633323-8c41bf61-5e4c-4728-967f-db3a797a9b91.png)
> 
> 大佬666，大佬帮忙过目~

要的 你添加时候的log，启动的错误是由于重复插件引起的
不过看到重复插件，有另外一种可能性，也许你只更新了一个插件，另一个实际载入的插件并没有更新

**Comment by GuiltyKirito** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/13746290/169451108-d842085b-34f1-41aa-9636-d2b207c2d05d.png) 添加cookies失败
> > > > > 
> > > > > 
> > > > > 是否是最新版本？ 应该是前天下午，米游社API变动，会造成校验失败
> > > > 
> > > > 
> > > > 试了下，还是不行，代码已经是最新提交 ![image](https://user-images.githubusercontent.com/13746290/169632806-bcbc03b4-8b2c-4773-8115-b77d4a9ff631.png) 是我少执行了什么咩？
> > > 
> > > 
> > > 这个版本应该是OK的，请重新登陆米游社获取ck添加试试，还不行的话，截图log我看看
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/13746290/169633323-8c41bf61-5e4c-4728-967f-db3a797a9b91.png)
> > 大佬666，大佬帮忙过目~
> 
> 要的 你添加时候的log，启动的错误是由于重复插件引起的 不过看到重复插件，有另外一种可能性，也许你只更新了一个插件，另一个实际载入的插件并没有更新

实在抱歉，如果可以且方便的能否请大佬把大佬的bot.py 借我参考下，我可能配置得不对~

**Comment by KimigaiiWuyi** [comment]
emmm，应该不需要配置bot.py就可以正常载入插件才对，只要再插件目录下

**Comment by GuiltyKirito** [comment]
> emmm，应该不需要配置bot.py就可以正常载入插件才对，只要再插件目录下

咱也不知道哪里出了问题，

我的顺序是 
```
//拉取最新代码
git pull 

// 装一下包
pip3 install -r requirements.txt

//执行nb 
nohup nb run &

```

就这样就结束了

**Comment by KimigaiiWuyi** [comment]
> > emmm，应该不需要配置bot.py就可以正常载入插件才对，只要再插件目录下
> 
> 咱也不知道哪里出了问题，
> 
> 我的顺序是
> 
> ```
> //拉取最新代码
> git pull 
> 
> // 装一下包
> pip3 install -r requirements.txt
> 
> //执行nb 
> nohup nb run &
> ```
> 
> 就这样就结束了

发一下添加ck时的错误log

**Comment by GuiltyKirito** [comment]
> > > emmm，应该不需要配置bot.py就可以正常载入插件才对，只要再插件目录下
> > 
> > 
> > 咱也不知道哪里出了问题，
> > 我的顺序是
> > ```
> > //拉取最新代码
> > git pull 
> > 
> > // 装一下包
> > pip3 install -r requirements.txt
> > 
> > //执行nb 
> > nohup nb run &
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 就这样就结束了
> 
> 发一下添加ck时的错误log

无疑大佬np提醒了我，我是国崩，我重新kill掉nohup nb 的进程 重新搞一个就好了。。。
