### ISSUE TITLE
stoken添加失败

### ISSUE THREAD

**Issue by tsukang** [KimigaiiWuyi/GenshinUID#232]
添加米游社cookie时正常 但添加stoken时一直失败:
"校验失败！请输入正确的Cookies！错误信息为expected string or bytes-like object"
换无痕浏览模式重新登陆米游社在进入用户中心也还是失败,想问一下可能是什么原因

**Comment by KimigaiiWuyi** [comment]
截图一下后台log
确保获得的字段内包含`login_ticket=xxx`

**Comment by tsukang** [comment]
![image](https://user-images.githubusercontent.com/87464755/169181806-42e170b4-e65f-485c-8e39-923b18f2709d.png)

**Comment by tsukang** [comment]
已解决 之前绑定的时候把mysuid填到原神uid里了

**Comment by tsukang** [comment]
![36P95QW1_GX_{EWFPQK(W}1](https://user-images.githubusercontent.com/87464755/169185482-da1a168b-d5a9-4ecb-bcc0-19523435fd94.png)
之前看到这个以为是绑mysuid
