### ISSUE TITLE
Cookie添加失败，有account_id和cookie_token字段

### ISSUE THREAD

**Issue by SPLUS-VABLE** [KimigaiiWuyi/GenshinUID#233]
![image](https://user-images.githubusercontent.com/42440354/169180383-d2dab57c-6bec-47c1-9872-74bab858271d.png)

**Comment by KimigaiiWuyi** [comment]
最新版本吗？昨天米友社换api了

**Comment by SPLUS-VABLE** [comment]
对的，刚刚拉了代码

**Comment by SPLUS-VABLE** [comment]
然后发现还是有报错

**Comment by KimigaiiWuyi** [comment]
> 然后发现还是有报错

再`git pull`一下，截图我看看

**Comment by SPLUS-VABLE** [comment]
可以了，感谢无疑大佬解答！
