### ISSUE TITLE
米有社 stoken 绑定失败

### ISSUE THREAD

**Issue by GuiltyKirito** [KimigaiiWuyi/GenshinUID#235]
![E7V23H5~DH9@49WUW{S@A(M](https://user-images.githubusercontent.com/13746290/169643789-c684e061-7cca-4cb7-ba2c-c4668f9d1a08.png)

![H1~YZG@IEDD2}VIS _T@2{Y](https://user-images.githubusercontent.com/13746290/169643792-fd8012c0-c298-4484-9c78-e1d375eb65c4.jpg)

多谢大佬帮忙解答 大佬YYDS

**Comment by KimigaiiWuyi** [comment]
可以尝试在添加stoken之后加个空格 
添加过ck 并绑定过uid之后，才能绑定stoken
获取login_ticket之后请在五分钟之内完成添加

**Comment by GuiltyKirito** [comment]
> 

大佬666 果然我重新操作了添加ck 重新绑定uid 再重新绑定新的stoken 成功了 大佬YYDS
