### ISSUE TITLE
获取uid个人信息/活动列表出错的问题

### ISSUE THREAD

**Issue by ljsgtcsos** [KimigaiiWuyi/GenshinUID#236]
![image](https://user-images.githubusercontent.com/105969015/169644145-10a5c3c5-1793-4d40-9ef5-a4a2b19bf02d.png)
看了下好像没有类似的报错问题..
不太清楚怎么解决

**Comment by GuiltyKirito** [comment]
是最新分支吗？

**Comment by MingxuanGame** [comment]
b3 更新了依赖注入的 Event 判断方式，等下我看看

**Comment by ljsgtcsos** [comment]
> 是最新的分支吗？

是.. 昨天刚拉的

**Comment by GuiltyKirito** [comment]
> > 是最新的分支吗？
> 
> 是.. 昨天刚拉的

尝试重新kill掉进程 重新install 库 重新run项目 kill掉老进程可能比较重要哦~

**Comment by MingxuanGame** [comment]
> b3 更新了依赖注入的 Event 判断方式，等下我看看

测试了，3.9－存在 bug，正在进行进一步测试

**Comment by MingxuanGame** [comment]
等待 nonebot2 修复

**Comment by ZhouYingSASA** [comment]
nonebot2 分支，校验 cookie 找的正则是 r\account_id=(\d*)\ (get_mihoyo_bbs_data.py:259,25)，现在 cookie 里好像已经没有这个字段了 麻烦更新一下谢谢

**Comment by MingxuanGame** [comment]
你需要退出，重新登录在抓，登录时间久了 cookie 就会缺东西
