### ISSUE TITLE
获取活动列表失败

### ISSUE THREAD

**Issue by SPLUS-VABLE** [KimigaiiWuyi/GenshinUID#237]
![image](https://user-images.githubusercontent.com/42440354/169675825-6f4d4210-166e-4895-8bfa-387ecbdb6143.png)
![image](https://user-images.githubusercontent.com/42440354/169675834-26a1842c-d68e-4549-9d0f-29689d994fce.png)

**Comment by KimigaiiWuyi** [comment]
趁着地脉活动又来了，赶紧修一修，之后如果还有问题，再开issuse吧
