### ISSUE TITLE
nonebot2-beta1分支里main.py里的unreachable code太多了

### ISSUE THREAD

**Issue by RafuiiChan** [KimigaiiWuyi/GenshinUID#238]
如题，该分支的 genshin_uid 里的 main.py 里有着大量
```
await matcher.finish('机器人发送消息失败：{}'.format(e.info['wording']))
logger.exception('发送当前xx信息失败')
```
这种代码，但是`matcher.finish`是会抛异常的，其后面同一代码块的代码不会生效，比如这个 logger.exception 正常情况下永远也不会执行。
这种情况在以前版本好像没发现过，不知道是不是这次更新大意了。（虽然不影响使用就是了）

## 修改建议：
根据原来的代码的意图，部分 `matcher.finish` 可改为 `matcher.send`  或者先打印日志再 matcher.finish ，以及 finish 后的 无用的 return 语句可以删掉。

**Comment by KimigaiiWuyi** [comment]
等待mix改罢，~~我还没用过Beta版本的NoneBot（跑~~

**Comment by MingxuanGame** [comment]
Related #227

**Comment by MingxuanGame** [comment]
fixed in 3.0
