### ISSUE TITLE
添加cookie失败

### ISSUE THREAD

**Issue by RafuiiChan** [KimigaiiWuyi/GenshinUID#239]
添加cookies的时候失败，发现是获取到的cookie里的 uid 和 token 的键名改了（改成了`ltuid` 和 `ltoken`），修改了下源代码后确实可以用了
但是获取 **角色信息** 和 **每月统计** 还是会出问题（获取`当前状态`功能是正常的，签到功能我不用，没试），获取角色信息时天赋信息获取失败（错误信息：`get_image` 第1040行 'NoneType' object is not subscriptable，char_talent_data 是 None，把画天赋的代码），打印了 char_talent_data 后是这样的
![image](https://user-images.githubusercontent.com/66518048/169929981-1cf4dcbc-0119-4ab1-8967-c40e1b20a663.png)

每月统计也是报 NoneType 错误，`get_mihoyo_bbs_data` 第 274行 `data = await get_award(uid)` 这个data是 None

蹲一波解决 （虽然这点错误对我来说无伤大雅

乆乆乆乆乆乆乆乆乆乆乆

**Comment by KimigaiiWuyi** [comment]
ltuid 和 ltoken就是拿不到札记的啊，建议还是用account_id & cookie_token

**Comment by RafuiiChan** [comment]
> ltuid 和 ltoken就是拿不到札记的啊，建议还是用account_id & cookie_token

用那两个直接就..cookie添加失败了

**Comment by KimigaiiWuyi** [comment]
> > ltuid 和 ltoken就是拿不到札记的啊，建议还是用account_id & cookie_token
> 
> 用那两个直接就..cookie添加失败了

你获取到的完整ck，应该包含account_id & cookie_token，如果没有建议重新登陆米游社 or 使用无痕模式获取
ltuid & ltoken是不完整的ck

**Comment by RafuiiChan** [comment]
> > > ltuid 和 ltoken就是拿不到札记的啊，建议还是用account_id & cookie_token
> > 
> > 
> > 用那两个直接就..cookie添加失败了
> 
> 你获取到的完整ck，应该包含account_id & cookie_token，如果没有建议重新登陆米游社 or 使用无痕模式获取 ltuid & ltoken是不完整的ck

原来如此，OK了
