### ISSUE TITLE
自动米游币私聊提示易导致封号

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#241]
tx给的封号原因是涉嫌诈骗
![Screenshot_20220527-040323](https://user-images.githubusercontent.com/59048777/170570884-60a16179-d03b-4141-82b0-471aaf6eda27.png)
![Screenshot_20220527-040341](https://user-images.githubusercontent.com/59048777/170570920-459c8213-3ed0-49fa-a067-4d89ff9fd709.png)

**Comment by lgc2333** [comment]
之前两次貌似是这个的锅 这次是因为涩图…

**Comment by qianxu2001** [comment]
同被封号，也是说涉诈，刚人脸解冻，建议加个推送开关

**Comment by KimigaiiWuyi** [comment]
已添加全局推送开关`gs开启米游币推送`和`gs关闭米游币推送`

**Comment by HA-JD** [comment]
![image](https://user-images.githubusercontent.com/47666701/171098650-250c2be5-7dca-4726-9307-a26b3268e4f2.png)
离谱

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/47666701/171098650-250c2be5-7dca-4726-9307-a26b3268e4f2.png) 离谱

使用`gs开启自动米游币` & `gs关闭米游币推送`达到每晚自动做米游币任务而不推送

**Comment by HA-JD** [comment]
gs关闭米游币推送发送后不提示成功是正常的吗？

**Comment by HA-JD** [comment]
![image](https://user-images.githubusercontent.com/47666701/171100390-eac2a298-a59c-4af8-8bde-641c8735ac04.png)

**Comment by KimigaiiWuyi** [comment]
> gs关闭米游币推送发送后不提示成功是正常的吗？

不正常，可以去群聊试试，因为是全局关闭的，或者你没有更新最新版本

**Comment by HA-JD** [comment]
忘了更新了
![image](https://user-images.githubusercontent.com/47666701/171100846-3fc97127-2234-43ec-85e2-705e8440c591.png)
感谢
