### ISSUE TITLE
查询收集华丽宝箱怎么还超了

### ISSUE THREAD

**Issue by SPLUS-VABLE** [KimigaiiWuyi/GenshinUID#244]
![image](https://user-images.githubusercontent.com/42440354/171353373-01c92650-e51c-473d-8078-aad476cc12bf.png)

**Comment by KimigaiiWuyi** [comment]
> > 数据是2.6的，~我并不知道2.7版本宝箱各有多少个~
> 
> 明白了，话说大佬查询单个角色的信息什么时候推，期待中！

如无意外，今晚
~~有意外的话就不知道什么时候了~~

**Comment by SPLUS-VABLE** [comment]
> > > 数据是2.6的，~我并不知道2.7版本宝箱各有多少个~
> > 
> > 
> > 明白了，话说大佬查询单个角色的信息什么时候推，期待中！
> 
> 如无意外，今晚 ~有意外的话就不知道什么时候了~

ok，谢谢无疑大佬解答！

**Comment by KimigaiiWuyi** [comment]
已更新数据来源
`{'成就':646,'华丽的宝箱':131,'珍贵的宝箱':347,'精致的宝箱':1221,'普通的宝箱':1658}`
华丽的宝箱确实只有131，132可能是bug超的
