### ISSUE TITLE
修改未匹配攻略时的提示

### ISSUE THREAD

**Issue by AquamarineCyan** [KimigaiiWuyi/GenshinUID#245]
似乎是正则匹配“攻略”，导致发不关于原神的带“攻略”二字，都会提示`发送消息失败请参考 go-cqhttp 端输出`
能否直接忽略不提示

**Comment by AquamarineCyan** [comment]
> 哪一个分支的
> ~~`nonebot2`分支应该无此问题~~

就是nb2的😂 还在beta2

**Comment by KimigaiiWuyi** [comment]
> > 哪一个分支的
> > ~`nonebot2`分支应该无此问题~
> 
> 就是nb2的😂 还在beta2

我是指a16应该没问题
`nonebot2-beta`分支的话我检查一下

**Comment by KimigaiiWuyi** [comment]
> > > 哪一个分支的
> > > ~`nonebot2`分支应该无此问题~
> > 
> > 
> > 就是nb2的😂 还在beta2
> 
> 我是指a16应该没问题 `nonebot2-beta`分支的话我检查一下

已修改

**Comment by AquamarineCyan** [comment]
> > > > 哪一个分支的
> > > > ~`nonebot2`分支应该无此问题~
> > > 
> > > 
> > > 就是nb2的😂 还在beta2
> > 
> > 
> > 我是指a16应该没问题 `nonebot2-beta`分支的话我检查一下
> 
> 已修改

已`git pull` 测试无报错提示
