### ISSUE TITLE
有关 查询展柜角色 命令的使用说明

### ISSUE THREAD

**Issue by KimigaiiWuyi** [KimigaiiWuyi/GenshinUID#246]
1. 每天凌晨4点，会自动刷新数据库内已绑定uid的展柜角色（刷新速度为一个uid需要20秒左右），可以使用命令`强制刷新全部数据`来马上执行全部刷新，时间非常久请注意！（**仅限超级管理员**）
2. `强制刷新`命令马上刷新你绑定的uid的展柜角色，后可跟uid来刷新其他账号的展柜角色。例如：`强制刷新100740568`
3. `查询展柜角色`可以查询到你当前绑定uid所有已缓存的展柜角色**列表**，如果**游戏内**更换展柜角色，旧的角色数据仍将保留
4. `查询`后接查询的人物，可以查询到已缓存的展柜角色面板，支持部分别名。例如：`查询公子`
5. 上一条命令可后接任意图片，实现定制图片的自定义功能；同时可后接@xxx ，查询其他已绑定uid的群友的信息面板

2022/6/5 更新
1. 支持通过uid方式查询其他玩家展柜信息
2. 例如：`强制刷新100740568`完之后，使用`uid100740568公子`或者`uid100740568展柜角色`

2022/6/10 更新
**支持2开头的UID，5开头仍不受支持**

2022/7/31 更新
**支持5开头的UID**

**Comment by 1055169799** [comment]
若水不显示
![Screenshot_2022-06-05-15-57-07-06_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/172041888-41ec2c18-bf7b-449f-9d7d-e5a1ff61b671.jpg)

**Comment by KimigaiiWuyi** [comment]
> 若水不显示 ![Screenshot_2022-06-05-15-57-07-06_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/172041888-41ec2c18-bf7b-449f-9d7d-e5a1ff61b671.jpg)

`git pull` 更新即可，已修
