### ISSUE TITLE
强制刷新报错。

### ISSUE THREAD

**Issue by SPLUS-VABLE** [KimigaiiWuyi/GenshinUID#251]
![image](https://user-images.githubusercontent.com/42440354/171526741-febdf196-3b00-493c-bb7f-47e93826533a.png)

**Comment by KimigaiiWuyi** [comment]
> 游戏里面的角色详情已经开启

看log，无报错的话   游戏展柜延迟五分钟，五分钟后再试

**Comment by SPLUS-VABLE** [comment]
![image](https://user-images.githubusercontent.com/42440354/171527130-5fe29e74-5df0-45d6-820a-5d552b467274.png)
查询角色时报这个错

**Comment by SPLUS-VABLE** [comment]
> 升级你的pillow版本 `pip install pillow --upgrade`

已解决，感谢无疑大佬解答
