### ISSUE TITLE
关于夜兰

### ISSUE THREAD

**Issue by SonderXiaoming** [KimigaiiWuyi/GenshinUID#252]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/98363578/171528498-37292f3c-a090-4ff2-b502-c9ebb595c9b4.png">
材质没跟上啊
<img width="812" alt="image" src="https://user-images.githubusercontent.com/98363578/171528550-de969add-1fe2-49f5-bcdb-613721831d64.png">
独树一帜的英文

**Comment by KimigaiiWuyi** [comment]
已改
~~大概~~
