### ISSUE TITLE
强制刷新部分失效

### ISSUE THREAD

**Issue by AquamarineCyan** [KimigaiiWuyi/GenshinUID#254]
- nonebot-beta2
- GenshinUID nonebot-beta1分支（2022.6.5）

强制刷新展柜信息，游戏内已显示
部分返回空列表 `{}`
![issues_pic](https://user-images.githubusercontent.com/64363680/172096901-10530780-2d61-4945-aa0b-50f102bc4829.png)

查询成功时log显示如下
`06-06 12:47:31 [INFO] nonebot | Matcher <Matcher from awesome_bot.plugins.GenshinUID.genshin_uid.main, type=message, priority=1, temp=False> running complete`
查询失败`返回为空列表`时log未显示，似乎是nb未匹配到该插件（只有**1开头的uid命令**才会被nb匹配插件）

**Comment by KimigaiiWuyi** [comment]
#246 看粗体标注

**Comment by AquamarineCyan** [comment]
> #246 看粗体标注

啊这
