### ISSUE TITLE
查询报错

### ISSUE THREAD

**Issue by SonderXiaoming** [KimigaiiWuyi/GenshinUID#259]
![image](https://user-images.githubusercontent.com/98363578/173254587-b7956568-6057-4f49-83ed-c86a7d7c6521.png)

**Comment by SonderXiaoming** [comment]
刷新无效

**Comment by KimigaiiWuyi** [comment]
hoshino似乎不支持直接发送bytes
我修改一下

**Comment by KimigaiiWuyi** [comment]
尝试git pull是否解决

**Comment by SonderXiaoming** [comment]
解决（希望增加对hoshino版测试）

**Comment by KimigaiiWuyi** [comment]
> 解决（希望增加对hoshino版测试）

每次都是盲写的（
切环境有点麻烦

**Comment by SonderXiaoming** [comment]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/98363578/173260175-933cadfe-09b9-4a38-82cc-5e54284ab5e3.png">
希望这个打印的也能在查询图片里面，更直观

**Comment by KimigaiiWuyi** [comment]
> <img alt="image" width="1091" src="https://user-images.githubusercontent.com/98363578/173260175-933cadfe-09b9-4a38-82cc-5e54284ab5e3.png">
> 
> 希望这个打印的也能在查询图片里面，更直观

后续会单独做一页，（有空的话

**Comment by SonderXiaoming** [comment]
![QQ图片20220612193251](https://user-images.githubusercontent.com/98363578/173260282-3b52637d-9607-46eb-8911-4886e752adac.jpg)
这算不算胡桃图片位置错误

**Comment by KimigaiiWuyi** [comment]
> ![QQ图片20220612193251](https://user-images.githubusercontent.com/98363578/173260282-3b52637d-9607-46eb-8911-4886e752adac.jpg) 这算不算胡桃图片位置错误

倒也不算，只不过有必要修改默认立绘的偏移值，你新开一个issuse吧，我这周解决

**Comment by KimigaiiWuyi** [comment]
> ![QQ图片20220612193251](https://user-images.githubusercontent.com/98363578/173260282-3b52637d-9607-46eb-8911-4886e752adac.jpg) 这算不算胡桃图片位置错误

优拉的更离谱一点
