### ISSUE TITLE
[建议]修改获取米游币回复对话

### ISSUE THREAD

**Issue by Z735803792** [KimigaiiWuyi/GenshinUID#260]
最近几个号被封了4-5次，检查发现最大原因应该是这个米游币获取回复对话。猜测是因为回复里带点赞两个字，被重点检测了，建议修改下说法，拼音谐音什么代替下。

**Comment by KimigaiiWuyi** [comment]
今天晚上修改一下，简化一下
不过推荐使用`gs开启自动米游币` 然后`gs关闭米游币推送`达到每晚自动获取米游币+无推送

**Comment by Z735803792** [comment]
okk感谢

**Comment by KimigaiiWuyi** [comment]
先这样改了看看情况，有问题再开issuse
