### ISSUE TITLE
查询功能部分角色图片位置错误

### ISSUE THREAD

**Issue by SonderXiaoming** [KimigaiiWuyi/GenshinUID#261]
![QQ图片20220612193251](https://user-images.githubusercontent.com/98363578/173260282-3b52637d-9607-46eb-8911-4886e752adac.jpg)
这算不算胡桃图片位置错误

_Originally posted by @SonderXiaoming in https://github.com/KimigaiiWuyi/GenshinUID/issues/259#issuecomment-1153335986_

**Comment by KimigaiiWuyi** [comment]
已完善
