### ISSUE TITLE
天赋查询倍率有误

### ISSUE THREAD

**Issue by A-JiuA** [KimigaiiWuyi/GenshinUID#266]
目前看到个别几个比较离谱，见图
![image](https://user-images.githubusercontent.com/34974508/175519802-62e4bb01-fd71-4877-8438-f8a327845be2.png)
![image](https://user-images.githubusercontent.com/34974508/175519875-b64a2f06-e753-4331-b840-ac584cb03091.png)
似乎是小数点加错位置了？

**Comment by KimigaiiWuyi** [comment]
已修复~
`git pull`后查看是否还有问题，
无问题自行关闭issuse
