### ISSUE TITLE
enka的这个服务，有自己搭建的可能性吗？

### ISSUE THREAD

**Issue by 1055169799** [KimigaiiWuyi/GenshinUID#267]
太不稳定了，据说服务器是俄罗斯那边的人搞的？这几天大概是用这个的机器人变多了，然后又赶上放假，这服务器一下子就被挤爆了。

**Comment by KimigaiiWuyi** [comment]
服务器被挤爆是什么表现

**Comment by A-JiuA** [comment]
> 服务器被挤爆是什么表现

![Screenshot_2022-06-25-23-02-36-013-edit_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/34974508/175779384-8f8c7566-bae4-4a2a-a2d3-11570f284c1a.jpg)![Screenshot_2022-06-25-23-02-53-137-edit_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/34974508/175779387-90722769-1546-4557-bc0e-8f5963b65e6f.jpg)

**Comment by 1055169799** [comment]
> 服务器被挤爆是什么表现

目前使用 强制刷新 命令获取角色的数据就是 “获取角色数据失败！”

其他作者的机器人也是 ”请求失败:请求错误，请稍后重试 “

**Comment by KimigaiiWuyi** [comment]
> > 服务器被挤爆是什么表现
> 
> 目前使用 强制刷新 命令获取角色的数据就是 “获取角色数据失败！”
> 
> 其他作者的机器人也是 ”请求失败:请求错误，请稍后重试 “

你那边目前所有uid都刷不了是吧，还是会过一段时间之后就可以了

**Comment by A-JiuA** [comment]
> > > 服务器被挤爆是什么表现
> > 
> > 目前使用 强制刷新 命令获取角色的数据就是 “获取角色数据失败！”
> > 
> > 其他作者的机器人也是 ”请求失败:请求错误，请稍后重试 “
> 
> 你那边目前所有uid都刷不了是吧，还是会过一段时间之后就可以了

我这边已经寄了一个多小时还没恢复，访问enka提示500error

**Comment by KimigaiiWuyi** [comment]
> > > > 服务器被挤爆是什么表现
> > > 
> > > 
> > > 目前使用 强制刷新 命令获取角色的数据就是 “获取角色数据失败！”
> > > 其他作者的机器人也是 ”请求失败:请求错误，请稍后重试 “
> > 
> > 
> > 你那边目前所有uid都刷不了是吧，还是会过一段时间之后就可以了
> 
> 我这边已经寄了一个多小时还没恢复，访问enka提示500error

嗯……现在是这样，因为在大约四天前，有个人通过这个网站进行遍历uid数据
所以作者加大了限制力度，
作者和我说，限制之后，大约一天每个ip的访问量是有限制的，约莫在小百的样子

**Comment by 1055169799** [comment]
> > > 服务器被挤爆是什么表现
> > 
> > 
> > 目前使用 强制刷新 命令获取角色的数据就是 “获取角色数据失败！”
> > 其他作者的机器人也是 ”请求失败:请求错误，请稍后重试 “
> 
> 你那边目前所有uid都刷不了是吧，还是会过一段时间之后就可以了

最近几天出现的比较频繁，但基本都是等三五分钟就好了，今天时间长了，从群内机器人发的消息记录来看，从晚上十点左右到现在，一个小时了还是获取不到数据。

**Comment by KimigaiiWuyi** [comment]
目前api需要增加一个key的parameters，但是key的话，目前作者没有发放的打算，我手里有一个不限制次数的key，暂时是无法公开

**Comment by A-JiuA** [comment]
> > > > > 服务器被挤爆是什么表现
> > > > 
> > > > 
> > > > 目前使用 强制刷新 命令获取角色的数据就是 “获取角色数据失败！”
> > > > 其他作者的机器人也是 ”请求失败:请求错误，请稍后重试 “
> > > 
> > > 
> > > 你那边目前所有uid都刷不了是吧，还是会过一段时间之后就可以了
> > 
> > 我这边已经寄了一个多小时还没恢复，访问enka提示500error
> 
> 嗯……现在是这样，因为在大约四天前，有个人通过这个网站进行遍历uid数据
> 所以作者加大了限制力度，
> 作者和我说，限制之后，大约一天每个ip的访问量是有限制的，约莫在小百的样子

其实我们群里才五个人在用，今天也没刷几次

**Comment by 1055169799** [comment]
> 目前api需要增加一个key的parameters，但是key的话，目前作者没有发放的打算，我手里有一个不限制次数的key，暂时是无法公开

作者的网页我去看了，在网页上输入uid，也是获取不到数据的。如果可以，我们想自己尝试搭建，据说需要的资源配置比较高，但是我这边是用的是公司的机房，配置不成问题，显卡带原神最高画质都是足够的。如果你能联系的上，可否帮忙传达一下？

**Comment by A-JiuA** [comment]
我这边也是十点左右就用不了了，也许是作者在维护网站

**Comment by KimigaiiWuyi** [comment]
> 我这边也是十点左右就用不了了，也许是作者在维护网站

emmm，也许是作者又缺少中国原神帐号了，我和他交流一下

**Comment by KimigaiiWuyi** [comment]
> 我这边也是十点左右就用不了了，也许是作者在维护网站

和作者反馈完了，应该已修复

**Comment by 1055169799** [comment]
> > 我这边也是十点左右就用不了了，也许是作者在维护网站
> 
> 和作者反馈完了，应该已修复

好的，感谢
