### ISSUE TITLE
【公告】Q群交流

### ISSUE THREAD

**Issue by KimigaiiWuyi** [KimigaiiWuyi/GenshinUID#268]
原本是GI BOT的群，索性也同时讨论GSUID好了
**群号：929275476**

建立有一段时间了，发个公告吧（
入群请请说明来自GSUID

**Comment by lgc2333** [comment]
搜群号找不到群，建议放加群链接

**Comment by KimigaiiWuyi** [comment]
[加群链接](点击链接加入群聊【GI Bot Group】：https://jq.qq.com/?_wv=1027&k=92NCvHPB)

**Comment by Ghost-chu** [comment]
入群问题似乎已经更新？
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/30802565/db9c57d0-4b31-4812-a14c-c2565c3ef79e)

Update: 是 go-cqhttp

**Comment by XiaoJunWu01** [comment]
进群答案是多少啊？
