### ISSUE TITLE
关于每日自动获取米游币

### ISSUE THREAD

**Issue by C-Jun-GIT** [KimigaiiWuyi/GenshinUID#269]
这个功能是没有完成吗？似乎存在部分相关代码，但是调用部分未发现

**Comment by KimigaiiWuyi** [comment]
`gs开启自动米游币`
`gs关闭米游币推送`
`gs帮助`
以上三个指令应该有用

**Comment by C-Jun-GIT** [comment]
> `gs开启自动米游币` `gs关闭米游币推送` `gs帮助` 以上三个指令应该有用

sorry，我再查看了一下，确实有相关指令。但是似乎只是私聊限定，而并没有在群聊中开放。

感谢回答！

**Comment by KimigaiiWuyi** [comment]
> > `gs开启自动米游币` `gs关闭米游币推送` `gs帮助` 以上三个指令应该有用
> 
> sorry，我再查看了一下，确实有相关指令。但是似乎只是私聊限定，而并没有在群聊中开放。
> 
> 感谢回答！

Hoshino版本是私聊限定
