### ISSUE TITLE
希望能加入国际服的UID查询

### ISSUE THREAD

**Issue by KazuhaKun** [KimigaiiWuyi/GenshinUID#27]
如题，因为有一部分人确实是在qq里讨论国际服的，有国际服也更加方便。十分感谢

**Comment by KimigaiiWuyi** [comment]
有计划，但是根据需求来看，优先度较低；第二点就是，我没有国际服的uid可供测试

**Comment by KazuhaKun** [comment]
测试uid确实是一个问题，国际服都绑定了邮箱，除非是初始号。

**Comment by lgc2333** [comment]
国际服我貌似看到有库可以直接调用
https://github.com/thesadru/genshinstats

**Comment by KimigaiiWuyi** [comment]
> 测试uid确实是一个问题，国际服都绑定了邮箱，除非是初始号。

刚刚了解到 ，国际服的api必须挂代理才能访问，所以这个功能实际用途不大
真的要写，优先级也非常靠后
还请理解

**Comment by Wansn-w** [comment]
> 国际服我貌似看到有库可以直接调用 https://github.com/thesadru/genshinstats

事实上这也包含国服的API，但含有一些冗余的功能而这对bot来说没有必要...同作者的`Genshin.py`也是如此

**Comment by wudifeixue** [comment]
由于。。这几天立绘事件，我跑外服了，我想试试把这部分加进去了

**Comment by KimigaiiWuyi** [comment]
> 由于。。这几天立绘事件，我跑外服了，我想试试把这部分加进去了

我暂时没有这方面需求，你可以先自己试试，外服的API和DS算法在github上都能找到，能整合到一个func里最好

**Comment by wudifeixue** [comment]
好的我去试试，能成功好用了再整合进来
