### ISSUE TITLE
关于米游币的获取

### ISSUE THREAD

**Issue by 1055169799** [KimigaiiWuyi/GenshinUID#270]
米游币的获取似乎没有看到输出结果，不像签到那样会显示“今日自动签到已完成！本群共签到成功108人，共签到失败0人。”（如果签到成功后去执行 校验全部Cookies 会发现这里的人数虚标，机器人会返回uidxxxcookie失效的数据，但这些人cookie失效了，却还是计入签到成功）

而且米游币的获取似乎是单个线程进行的，一旦有人发送获取米游币的命令来插队，就会导致获取失败

stoken的失效与否也没有检验信息，就像“校验全部Cookies”这种命令。

不知下个更新是否可以考虑把这个补充一下呢。

对了，关于获取cookie和stoken我这边找人做了安卓APP，可以一键获取，但由于我对genshinuid的部分代码有做修改，所以获取的数据可能不那么完美适配genshinuid的原代码，如果有需要我可以提供APP。
![-3e678025c39a7a00.png](https://user-images.githubusercontent.com/41286675/176495070-ce7c2675-c788-4338-8198-76f3587d5379.png)
![5919e51c892afdc4.png](https://user-images.githubusercontent.com/41286675/176495095-db9487bf-26d0-464a-913a-eeefc18be2a2.png)

**Comment by KimigaiiWuyi** [comment]
1. 如果CK失效应该返回失败人数并且@失败的人才对，这点我们群已经几次见过失败并@人的情况了，如果确实没签上，但显示成功了，有可能是bug
2. stoken的校验周末应该会去加
3. 你应该是使用了`gs关闭米游币推送`，所以单人不会收到米游币成功的消息？是否有必要加入 如果使用了`gs关闭米游币推送`，那么当天的米游币获取信息 会私发给`SUPERUSER`，这一条也许有用
4. 至于APP，因为似乎涉及到用户隐私是否存在恶意上传的可能性，如果可以公开源码的话是最好的，你可以新开一个repo存放这个，应该很多人都会需要

**Comment by KimigaiiWuyi** [comment]
`git pull`后
新增`校验全部Stoken`，同时后台可以看到info信息
新增每日自动米游币任务结束后向SUPERUSER发送报告

**Comment by 1055169799** [comment]
> `git pull`后
> 新增`校验全部Stoken`，同时后台可以看到info信息
> 新增每日自动米游币任务结束后向SUPERUSER发送报告

好的，我明天测试一下

**Comment by KimigaiiWuyi** [comment]
> > > `git pull`后
> > > 新增`校验全部Stoken`，同时后台可以看到info信息
> > > 新增每日自动米游币任务结束后向SUPERUSER发送报告
> > 
> > 
> > 好的，我明天测试一下
> 
> 刚试了一下，结果是机器人群聊内发送了： 发生错误 name 'bot' is not defined,请检查后台输出。 这个应该是米游币获取结束后的反馈命令吧

哪一个分支 and 后台报错截图？
`校验全部Stoken`会调用私聊api私聊stoken已失效成员，所以会使用到bot

**Comment by 1055169799** [comment]
> > > > `git pull`后
> > > > 新增`校验全部Stoken`，同时后台可以看到info信息
> > > > 新增每日自动米游币任务结束后向SUPERUSER发送报告
> > > 
> > > 
> > > 好的，我明天测试一下
> > 
> > 
> > 刚试了一下，结果是机器人群聊内发送了： 发生错误 name 'bot' is not defined,请检查后台输出。 这个应该是米游币获取结束后的反馈命令吧
> 
> 哪一个分支 and 后台报错截图？ `校验全部Stoken`会调用私聊api私聊stoken已失效成员，所以会使用到bot

分支？是指github的文件分支吗？我就是从 https://github.com/KimigaiiWuyi/GenshinUID 这里面直接下载压缩包，然后覆盖掉更新的。
后台的话
![image](https://user-images.githubusercontent.com/41286675/177193826-147782d2-2c9c-4106-a320-515e7d39f0bc.png)

![image](https://user-images.githubusercontent.com/41286675/177193909-c2fcdb16-2137-4312-a06f-f0c023b1b1ea.png)
![image](https://user-images.githubusercontent.com/41286675/177193845-e1bc9ee5-f15c-4ee7-a56b-b83d1ad32ff1.png)
看聊天记录的时间，应该是这里
私聊的话，我是关闭的

**Comment by 1055169799** [comment]
上面显示的417和537行，我对比文件看了一下都没有问题的，没修改过什么

![image](https://user-images.githubusercontent.com/41286675/177194663-65eed7a8-f578-405b-b5a3-c0156b781060.png)
![image](https://user-images.githubusercontent.com/41286675/177194705-096c5bd2-4458-45b4-a631-cfea823c5b6e.png)

**Comment by KimigaiiWuyi** [comment]
> 上面显示的417和537行，我对比文件看了一下都没有问题的，没修改过什么
> 
> ![image](https://user-images.githubusercontent.com/41286675/177194663-65eed7a8-f578-405b-b5a3-c0156b781060.png) ![image](https://user-images.githubusercontent.com/41286675/177194705-096c5bd2-4458-45b4-a631-cfea823c5b6e.png)

git pull 试一下？
另外`校验全部Stoken`这个命令能用吗

**Comment by KimigaiiWuyi** [comment]
> > > 上面显示的417和537行，我对比文件看了一下都没有问题的，没修改过什么
> > > ![image](https://user-images.githubusercontent.com/41286675/177194663-65eed7a8-f578-405b-b5a3-c0156b781060.png) ![image](https://user-images.githubusercontent.com/41286675/177194705-096c5bd2-4458-45b4-a631-cfea823c5b6e.png)
> > 
> > 
> > git pull 试一下？ 另外`校验全部Stoken`这个命令能用吗
> 
> 直接git的话会把我修改的一下私聊转群聊的代码给覆盖掉吧
> 
> 另外命令可以用 ![image](https://user-images.githubusercontent.com/41286675/177195810-0177c992-e1bf-4206-bab3-73a8b2e34ebb.png)

可以尝试把516行的`for qid in bot.config.SUPERUSERS`中的`bot`修改为`hoshino_bot`看看

**Comment by 1055169799** [comment]
> 
> 可以尝试把516行的`for qid in bot.config.SUPERUSERS`中的`bot`修改为`hoshino_bot`看看

改了，命令正常
![image](https://user-images.githubusercontent.com/41286675/177196811-bea34ed9-d122-4b82-804d-7aa827972358.png)

群聊里是没有收到任何和米游币有关的消息了，私聊有消息，应该是正常了
![image](https://user-images.githubusercontent.com/41286675/177201870-f7521d38-f41f-4400-ba8d-43a646382cff.png)
