### ISSUE TITLE
关于查询展柜单个角色报错 name 'char_info_mask' is not defined

### ISSUE THREAD

**Issue by AdminVivy** [KimigaiiWuyi/GenshinUID#271]
当强制刷新且刷新成功后，使用指令列如 查询雷神，报错如下

Traceback (most recent call last):
  File "GenshinUID/genshinuid.py", line 1198, in get_info
    im = await draw_char_card(raw_data, image)
  File "GenshinUID/enkaToData/drawCharCard.py", line 432, in draw_char_card
    img_temp.paste(char_img,(0,0),char_info_mask)
NameError: name 'char_info_mask' is not defined

**Comment by KimigaiiWuyi** [comment]
抱歉，漏了点东西，已修改
`git pull`之后看是否能解决

**Comment by AdminVivy** [comment]
> 抱歉，漏了点东西，已修改 `git pull`之后看是否能解决

解决了，不过又有新的报错
GenshinUID/enkaToData/drawCharCard.py", line 460, in draw_char_card
    skill_add = avatarName2SkillAdd[char_name]
NameError: name 'avatarName2SkillAdd' is not defined

**Comment by KimigaiiWuyi** [comment]
更新（

**Comment by AdminVivy** [comment]
> 更新（

可以了 感谢
