### ISSUE TITLE
毕业度统计报错

### ISSUE THREAD

**Issue by SonderXiaoming** [KimigaiiWuyi/GenshinUID#274]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/98363578/178116038-1a759c28-b546-47cd-8cd1-c96c81a1b906.png">

**Comment by SonderXiaoming** [comment]
经典，hoshino不熟

**Comment by KimigaiiWuyi** [comment]
啊这……
顺便问一句 查询面板的时候，伤害计算区域有正确显示吗
没有的话我一起修了（

**Comment by SonderXiaoming** [comment]
> 啊这…… 顺便问一句 查询面板的时候，伤害计算区域有正确显示吗 没有的话我一起修了（

没问题

**Comment by KimigaiiWuyi** [comment]
> > 啊这…… 顺便问一句 查询面板的时候，伤害计算区域有正确显示吗 没有的话我一起修了（
> 
> 没问题

试试看更新（

**Comment by SonderXiaoming** [comment]
能不能把参考伤害也附上去

**Comment by KimigaiiWuyi** [comment]
> 能不能把参考伤害也附上去

blue的伤害参考 只有某一个动作的，没有全部的

**Comment by SonderXiaoming** [comment]
至少把毕业度计算依据附上去吧（群友老是问我怎么超过100之类的问题）

**Comment by KimigaiiWuyi** [comment]
> 至少把毕业度计算依据附上去吧（群友老是问我怎么超过100之类的问题）

伤害比参考伤害高了自然就超过100了（
关于这个，会做一个新的页面，展示计算公式的每一项值和预设条件
或者先简单的直接把参考数值附在毕业度下面？

**Comment by SonderXiaoming** [comment]
我觉得都行
