### ISSUE TITLE
角色查询的一些问题

### ISSUE THREAD

**Issue by 836672549** [KimigaiiWuyi/GenshinUID#276]
![image](https://user-images.githubusercontent.com/71533394/178647002-fc6577c8-1c09-438c-8603-06d67ed5828d.png)
我绑定了177的uid，然后强制刷新，机器人会报错：获取角色数据失败！

**Comment by KimigaiiWuyi** [comment]
emmm早上停服维护，enka那边估计在修

**Comment by 836672549** [comment]
OK了

**Comment by 836672549** [comment]
请问一下输入命令：角色鹿野院平藏，为什么返回是查无此角色呢

**Comment by AquamarineCyan** [comment]
> 请问一下输入命令：角色鹿野院平藏，为什么返回是查无此角色呢

新角色要等几天👀
