### ISSUE TITLE
语音发送失败

### ISSUE THREAD

**Issue by dfmjndm** [KimigaiiWuyi/GenshinUID#277]
ffmpeg已经添加到了path里面，执行source etc/profile,重启gocq和hoshino，依然gocq显示检测没有ffmpeg

5ZZzUqdLvI4fM52TWZuqn4IBAcGLoNy6cwwDzvMRU7\/ZvZ3M5m5C5IsFMshVg9nSzhuC7UOz\/ZAuOaFXNaa+rcziyU2fXAiJuR90YpuMUyO2MVZbLKvaK\/IoUHNsuu5tzkebQnbXtjdSADWH09nZ1MABICzAAAAAAAAEEYAAAQAAABbZPUqAqyUnrUkzO3KDzJ+eXbUeWrcjIEek2nuwc+MVMFQAgNT0Y9\/JuHtW5qcvwWvj6vh\/MeHdDDDh7SfFKjzTa8bTNdQqwdnAeSqXrVvtIYyvgWqLbFKNdm\/1aICL2Jo3dwKdg2YK5cVS3WnjWQVp3xuscBMX9VLcU7TLqUM33IS7JijZjraWEcpS8JypnR8jGEp34FmGCXMgI0BpLSSj5AutEIlYSRzfC9o8Bzj+HOfFf61\/Dobd0sPiGXb+tWKJmNmhGIGJRg0cNYSXjTKVv5SC\/sqfJP4ki1ozVbPFQ3YORTqXJcLW7H\/nV0ueD6Wlh+dVaC6r5a4HNVUPidU50BnJampLCxU99WK\/cyiAVsZPfvj9mW1mSztjzn5BwM3Zxl2wrLuj9oywAwJzArvbfk9YQlum+7U9GM2AaeD1Y9a8rsA0AE="}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exec: "ffmpeg": executable file not found in $PATH 将忽略本段CQ码. 
[2022-07-16 20:32:15] [WARNING]: 群消息发送失败: 消息为空.

**Comment by dfmjndm** [comment]
![image](https://user-images.githubusercontent.com/57401901/179355145-9ba0a8d3-4b8a-4f26-8b03-da1f7a2621e1.png)

**Comment by KimigaiiWuyi** [comment]
这好像不是本插件的问题（
似乎是mirai的问题？
可以去它们群问一下

**Comment by dfmjndm** [comment]
需要完全重启机器。
source不知道为什么不行

**Comment by KimigaiiWuyi** [comment]
> 需要完全重启机器。 source不知道为什么不行

啊这，Q&A又能多写一条了（
