### ISSUE TITLE
查询词云报错

### ISSUE THREAD

**Issue by iven13465** [KimigaiiWuyi/GenshinUID#278]
![TH`W9YARN%U%%7P4CUFQGF3](https://user-images.githubusercontent.com/95957360/179386401-71a41140-1941-4938-aabb-5eaf49c9c7a9.png)

后台输出
![@HPKNI73{WEGTEA@RB 2 8](https://user-images.githubusercontent.com/95957360/179386421-41197fad-5d15-4184-a7cb-6d45ac0c5e70.png)

**Comment by KimigaiiWuyi** [comment]
这个功能可能会被废弃（？
等待`3.0dev`重构
