### ISSUE TITLE
【建议】资源自动更新

### ISSUE THREAD

**Issue by SonderXiaoming** [KimigaiiWuyi/GenshinUID#280]
我觉得例如参考面板，给谁用，角色信息这些随卡池更新的或者可能经常要变化的数据应该自动更新（比如做个api，或者每天定时爬一下github）每次git pull有点麻烦，而且经常会无法支持最新的角色/武器

**Comment by KimigaiiWuyi** [comment]
等待`3.0-dev`添加这个功能
资源文件独立出来，同时避免首次`git clone`时长过久

**Comment by SonderXiaoming** [comment]
？居然有版本号，现在是几点几啊，3.0又是啥时候

**Comment by KimigaiiWuyi** [comment]
（刚加的）
已归档的算`1.0`
现在算`2.0`
`3.0`在`dev`分支，有全新的UI & 拆分功能 & 更优命令覆盖，当然暂时还不能用，别去用这个分支
顺利的话 应该就在这两周
![image](https://user-images.githubusercontent.com/55526518/179889556-fcac1623-c8e4-4e11-b54a-5ede213a1755.png)

**Comment by SonderXiaoming** [comment]
好家伙，期待，希望ui做的好看一些(yunzai的部分界面好看多了)

**Comment by KimigaiiWuyi** [comment]
> 好家伙，期待，希望ui做的好看一些(yunzai的部分界面好看多了)

所以在优化了（
主要是为了定制化做了一部分妥协，比如现在 查询展柜角色类命令 后跟图可以替换默认图片之类的
但我发现查询&查询深渊很少有人后面跟图 定制不同样式，所以这次尝试利用程序内部判断 完成每张图有略微差别
比如深渊的抬头就 直接使用 最强一击的角色 立绘，可以在不跟图的情况完成每个玩家的 单独浅定制

**Comment by KimigaiiWuyi** [comment]
图片资源会自动更新, 部分json表还是手动维护由git版本控制
