### ISSUE TITLE
提供一下网上获取的收集进度数据

### ISSUE THREAD

**Issue by 1055169799** [KimigaiiWuyi/GenshinUID#281]
# 记录数据
    raw_data = raw_data['data']
    max_data = {'成就':649,'华丽的宝箱':139,'珍贵的宝箱':368,'精致的宝箱':1306,'普通的宝箱':1776}

因为看到群里有人都百分之一百多了，然后我去搜了一下目前的数据，大概就是上面这个数据吧

![image](https://user-images.githubusercontent.com/41286675/179926933-072cc8f8-798d-4a40-8929-8513f912f12e.png)
👇
![image](https://user-images.githubusercontent.com/41286675/179927022-f072485d-df07-43b5-8829-2cffffc55648.png)

**Comment by KimigaiiWuyi** [comment]
已更新
不过部分数据似乎和这里对不上
http://114.132.218.87:12583/api/genshin/ts

**Comment by 1055169799** [comment]
> 已更新
> 不过部分数据似乎和这里对不上
> http://114.132.218.87:12583/api/genshin/ts

我也是看网上收集的数据，可能海岛的没加吧

**Comment by KimigaiiWuyi** [comment]
我上次的`max_data`应该是2.7版本的全宝箱了，只需要到时候看看2.8新增统计 应该就是准确的数据

> 2.7_max_data = {'成就':646,'华丽的宝箱':131,'珍贵的宝箱':347,'精致的宝箱':1221,'普通的宝箱':1658}

**Comment by 1055169799** [comment]
> 已更新 不过部分数据似乎和这里对不上 http://114.132.218.87:12583/api/genshin/ts

我的数据来源是这里
https://www.fastmock.site/mock/ac7a6c4155d5cd739f1c070c77f52613/api/miaomiao



let gorgeous = 0;//华丽宝箱数
let precious = 0;//珍贵宝箱数
let delicate = 0;//精致宝箱数
let ordinary = 0;//普通宝箱数
let strangeFeed = 0;//奇馈宝箱数
let achievement = 0;//成就数
let teleporter = 0;//传送点数
let alwaysTreasureChest = 0;//总宝箱数
axios.get("https://www.fastmock.site/mock/ac7a6c4155d5cd739f1c070c77f52613/api/miaomiao").then(({data:res})=>{  
    gorgeous = res.data.gorgeous;
    precious = res.data.precious;
    delicate = res.data.delicate;
    ordinary = res.data.ordinary;
    strangeFeed = res.data.strangeFeed;
    achievement = res.data.achievement;
    teleporter = res.data.teleporter;
    alwaysTreasureChest = Number(gorgeous) + Number(precious) + Number(delicate) + Number(ordinary) + Number(strangeFeed);
});

**Comment by KimigaiiWuyi** [comment]
![image](https://user-images.githubusercontent.com/55526518/181135898-349009ea-0805-4af7-bc41-b3dbb9167bb4.png)

**Comment by KimigaiiWuyi** [comment]
2.7_max_data = {'成就':646,'华丽的宝箱':131,'珍贵的宝箱':347,'精致的宝箱':1221,'普通的宝箱':1658}

**Comment by KimigaiiWuyi** [comment]
3.0_max_data = {'成就':748,'华丽的宝箱':142,'珍贵的宝箱':410,'精致的宝箱':1440,'普通的宝箱':2157}
