### ISSUE TITLE
关于角色展示查询

### ISSUE THREAD

**Issue by 836672549** [KimigaiiWuyi/GenshinUID#283]
大佬你好，我弄了好久角色展柜刷新不出来
![image](https://user-images.githubusercontent.com/71533394/180396079-75f2ce12-a045-4a0e-a546-db0b036fca9f.png)
![D0}T_VB9KC}$(@$C 1`T8 A](https://user-images.githubusercontent.com/71533394/180395828-1befe76a-04b7-4592-8269-40a0f5020f34.png)
我强制刷新也失败
![image](https://user-images.githubusercontent.com/71533394/180396434-2b39be42-ffd2-429f-b558-2c947cbedcec.png)
![image](https://user-images.githubusercontent.com/71533394/180395683-4da4bbda-09fc-4243-8c96-c54954508099.png)
还有超级管理权限怎么添加

**Comment by KimigaiiWuyi** [comment]
更新插件
至插件目录下`git pull`

**Comment by 836672549** [comment]
OK，那个超级管理权限怎么添加

**Comment by KimigaiiWuyi** [comment]
> OK，那个超级管理权限怎么添加

Hoshino的SuperUser

**Comment by 836672549** [comment]
![image](https://user-images.githubusercontent.com/71533394/180403757-699c6322-37b9-4acb-a13a-6825c85c4119.png)
我这里添加了好像没有用
![image](https://user-images.githubusercontent.com/71533394/180404574-0865c625-54fa-4501-aa9d-172889fda017.png)

**Comment by 836672549** [comment]
OK了，谢谢大佬
