### ISSUE TITLE
二命雷神无法查询

### ISSUE THREAD

**Issue by keqingyyds** [KimigaiiWuyi/GenshinUID#285]
如题

**Comment by KimigaiiWuyi** [comment]
这个应该是属于 腾讯QQ 方面的风控
与bot无关,之后会改为图片发送

**Comment by keqingyyds** [comment]
> 这个应该是属于 腾讯QQ 方面的风控 与bot无关,之后会改为图片发送

只有雷神这样，其他正常，零命的就查得出来

**Comment by KimigaiiWuyi** [comment]
> > 这个应该是属于 腾讯QQ 方面的风控 与bot无关,之后会改为图片发送
> 
> 只有雷神这样，其他正常，零命的就查得出来

噢 你说的 查询展柜角色里面的 
哪一个分支的,应该已经修复了才对
