### ISSUE TITLE
[建议]增加关闭超级用户每日推送coin

### ISSUE THREAD

**Issue by Z735803792** [KimigaiiWuyi/GenshinUID#286]
我的bot似乎一遇到私聊就容易封号，能加个关闭推送，或者默认关闭可以手动开启就再好不过了(･∀･)

**Comment by KimigaiiWuyi** [comment]
一步一步套娃
全员发送 -> 只发给超级用户 -> 都不发
23333
可以加上,不过需要等一段时间,如果你是Nonebot2-beta1分支的,这周末换上新版 就加入

**Comment by Z735803792** [comment]
现在用的Nonebot2-beta1分支，有关闭推送指令了嘛，

**Comment by KimigaiiWuyi** [comment]
`gs关闭私聊报告`
