### ISSUE TITLE
GenshinUID 3.0 Beta

### ISSUE THREAD

**Issue by KimigaiiWuyi** [KimigaiiWuyi/GenshinUID#289]
`GenshinUI 3.0 beta`将于本周末推送至`Nonebot2-beta1`分支,以下是在升级`3.0 beta`之前你需要知道的.
**做好数据备份!!!**

## 全新UI

重新调整了大部分图片的UI, 具体可以看后附~

## 更广命令

命令在*大多数*兼容原有指令的同时, 做了更广的判定(同时也有带来误触发的可能, 总体是更好了)

新版命令大多遵照【前缀】【UID】【关键词】的方式，其中前缀和UID均可省略

【前缀】：`查询`、`uid`、`mys`

【UID】：特指九位UID，如`100740568`

【关键词】：命令关键词，如`深渊`，`收集`，`每日`等等

以下举几个例子

- 原先的`查询深渊`可以触发的前提下,`深渊`、`sy`同样可以查询
- 原先的`uid100740568深渊`可以触发的前提下,`100740568深渊`、`100740568sy`同样可以查询
- 新增的`每日`，也同时拥有`mr`、`便签`等多种关键词
- 原先的`查询`可以触发的前提下,`uid`、`mys`同样可以触发
- 原先的`uid100740568`可以触发的前提下,`100740568`，`查询100740568`同样可以查询

## 多UID支持

*不仅是uid、大写的UID现在也接受识别*

`删除uid`：直接使用**删除当前绑定的uid**，后也可跟uid来删除特定uid，例如`删除uid100740568`

`绑定uid`：和以前一样的用法，`绑定uid100740568`

`切换uid`：直接使用**顺序切换下一个绑定的uid**，后也可跟uid来切换特定uid，例如`切换uid100740568`

在某些特殊命令，例如`每日`下，绑定的多个uid将同时输出结果，并呈现于一张图上

## 重做的推送模式

原先的`gs开启推送`将自动开启`宝钱提醒`、`体力提醒`、`派遣提醒`、`质变仪提醒`

重做的`gs开启推送`将为所有推送的主开关

提供`gs开启宝钱推送`,`gs开启体力推送`,`gs开启派遣推送`，`gs开启质变仪推送`四个分开关

使用`gs开启推送`的用户将**只会**打开体力推送，其他需要手动开启

**新命令**：`推送状态`可以查看当前开启的推送开关

**新命令**：`设置体力阈值`可以设置开始推送的阈值、达到阈值后将推送**1**次，然后禁用推送直到*下次低于阈值*（#284）

例如：`设置体力阈值150`，`设置宝钱阈值2100`，`设置派遣阈值70`，质变仪无需设置，只会推送一次然后禁用

（派遣阈值的意思是，距离某一个派遣角色完成时间不足多少分钟的意思，例如阈值70为不足70分钟时推送）

#286 ：`gs关闭私聊报告`可阻止所有除了上述四种推送以外的私聊推送(例如超级管理员的米游币任务推送)

## 更好的扩展

代码注释、*静态类型检查*、资源的复用、常用工具的封装、完善的控制台log等等修改

这些都帮助快速开发一个*子插件包*，也方便进行已有子插件的debug调试

同时，不依赖资源包的子插件，可以独立成单独插件，方便移植等等

## 其他修改

`下载全部资源`仓库的体积减少至20M左右，资源包可通过该命令自动爬取`mihoyo`和`fandom`的资源

`gs开启自动米游币`的自动获取时间移动至凌晨一点十六分

`绑定状态`、`绑定信息`输出全开关和绑定状态列表

`参考面板`后可以跟角色,支持别名,例如`参考面板小鹿`,除此外`参考面板火`也同样支持!

`添加` 优化添加Cookie指引，如果需要添加Stoken，只需添加一次含有`login_ticket`的ck，即可完成stoken+cookie的添加！

bug修复：#287

## 删除的功能

一些使用频率较少的功能、或者是不好维护的功能将被移除

`查询词云`（#278）

`御神签`（没人用且不好维护）

`当前信息`（没那么好用，`每月统计`将更换UI替代掉）

## 预览

<details> <summary>UID绑定</summary>  
    <img src="https://s2.loli.net/2022/08/09/kwGnp3i6rOh9usV.jpg" >
</details>

<details> <summary>每日</summary>  
    <img src="https://s2.loli.net/2022/08/01/EPiI98UHlW7ectT.jpg" >
</details>

<details> <summary>多绑定下每日的情况</summary>  
    <img src="https://s2.loli.net/2022/08/08/OStNI1GwWg68Mcz.png" >
</details>

<details> <summary>UID查询</summary>  
    <img src="https://s2.loli.net/2022/08/01/JOyPhj65mMuQ2ps.jpg"/> 
</details>

<details> <summary>UID测试</summary>  
    <img src="https://s2.loli.net/2022/08/08/WIL1StYZABkMR6J.jpg"/> 
</details>

<details> <summary>深渊</summary>  
    <img src="https://s2.loli.net/2022/08/01/HZBgEWIwpeVnUfP.jpg" >
</details>

<details> <summary>收集</summary>  
    <img src="https://s2.loli.net/2022/08/01/rJDMqQU7Fz4Og83.jpg" >
</details>

**Comment by KimigaiiWuyi** [comment]
除此之外，如果有什么特别的 想法 & 功能建议 也可以跟进
（另外，找一个会改Hoshino触发器的帮我该代码QAQ）

**Comment by SonderXiaoming** [comment]
> 除此之外，如果有什么特别的 想法 & 功能建议 也可以跟进 （另外，找一个会改Hoshino触发器的帮我该代码QAQ）

我觉得你只要抓个人查ev就行（不是）

**Comment by KimigaiiWuyi** [comment]
> > 除此之外，如果有什么特别的 想法 & 功能建议 也可以跟进 （另外，找一个会改Hoshino触发器的帮我该代码QAQ）
> 
> 我觉得你只要抓个人查ev就行（不是）

nonebot2-beta分支的全变了，目前还没写hoshino的触发器（
所以需要一个人再搬回来，要不然我就只能慢慢自己写了（
