### ISSUE TITLE
手机端米游社cookie获取软件问题

### ISSUE THREAD

**Issue by madein233** [KimigaiiWuyi/GenshinUID#290]
手机端米游社cookie获取软件获取的cookie与插件需要的格式不一样
希望无疑佬优化一下

**Comment by KimigaiiWuyi** [comment]
手机端获取是什么格式？关键信息脱敏一下我看看~
后续3.0会优化添加ck的流程

**Comment by madein233** [comment]
这样的
UM_distinctid=
_ga=
_MHYUUID=
CNZZDATA12750230=
_gid=
 smidV2=
_gat=
.thumbcache_a5f2da72=
ltoken=
cookie_token=
 account_id=

**Comment by KimigaiiWuyi** [comment]
已修复，目前可以直接通过添加sk方式一并添加两个，也可以直接添加ck
