### ISSUE TITLE
加个每日天赋素材查询

### ISSUE THREAD

**Issue by SonderXiaoming** [KimigaiiWuyi/GenshinUID#292]
https://github.com/H-K-Y/Genshin_Impact_bot
他可以查资源位置，查今日天赋素材，而且好像是自动更新的
（但好像没怎么维护了）

**Comment by lgc2333** [comment]
https://github.com/H-K-Y/Genshin_Impact_bot/issues/18
233333

**Comment by SonderXiaoming** [comment]
艹，我觉得装两个比较麻烦（我说怎么功能几乎不重复）

**Comment by KimigaiiWuyi** [comment]
> 艹，我觉得装两个比较麻烦（我说怎么功能几乎不重复）

因为我也装了两个，所以刻意避开了那边的功能啊……（

**Comment by KimigaiiWuyi** [comment]
说回这个资源点功能，还是得问 @MingxuanGame ，他已经写了很大一部分了

**Comment by MingxuanGame** [comment]
> 说回这个资源点功能，还是得问 @MingxuanGame ，他已经写了很大一部分了

照着原来的基本做好了，但是有一点偏差，我还没修（没时间）

![image](https://user-images.githubusercontent.com/68982190/183581238-c5587829-ad9d-4066-b359-61e2ecf41813.png)

之前如果资源的位置跨度太大的会导致生成的地图很大，以及 oom 问题

现为1000*1000地图，尽量截取更多资源

**Comment by KimigaiiWuyi** [comment]
查今日天赋素材 我之后3.0版本后加上，弄个子插件包还是容易的
