### ISSUE TITLE
米游社签到失败

### ISSUE THREAD

**Issue by madein233** [KimigaiiWuyi/GenshinUID#293]
米游社现在多了个签到验证功能，群里发送“签到”机器人正常发送签到成功，但是在米游社并没有签到成功

**Comment by qianxu2001** [comment]
如果提示是签到成功，那就是成功了，如果提示是 OK，那就是没成功

**Comment by C-Jun-GIT** [comment]
我也是经常出现签到失败的情况，这种情况下再使用指令补签也会失败

**Comment by KimigaiiWuyi** [comment]
在最新版本的`nonebot2-beta1`分支尽力修复了这个问题，大幅度的重试+延长时间，50个UID约莫需要近两小时，成功率大概在80%+，每天没签上的都是随机的，所以应该不太会影响到全勤，在意的可以自己上米游社补签
`hoshino`的话需要等一段时间

**Comment by C-Jun-GIT** [comment]
> 在最新版本的`nonebot2-beta1`分支尽力修复了这个问题，大幅度的重试+延长时间，50个UID约莫需要近两小时，成功率大概在80%+，每天没签上的都是随机的，所以应该不太会影响到原石，在意全勤的可以自己上米游社补签
> `nonebot2-beta1`分支中，可以尝试每天中午、晚上手动发送`全部重签`命令，配合凌晨自动任务，应该可以做到95%+
> `hoshino`的话需要等一段时间（

感谢，可惜我用的是hoshino(

**Comment by Z735803792** [comment]
早上中文晚上试了都是验证码。。感觉签不上的概率提高好多惹，用的beta分支的
![image](https://user-images.githubusercontent.com/70925546/188459167-03edf0b5-6730-42f6-888d-03f364d142b8.png)
