### ISSUE TITLE
查询报错

### ISSUE THREAD

**Issue by iven13465** [KimigaiiWuyi/GenshinUID#294]
![I15W2LA4{PGM6O(YB7TA$2A](https://user-images.githubusercontent.com/95957360/184560933-1b36c319-49e4-46d8-8ce3-12288e939133.png)

![XNB@ZIWTII4 4DAFL{NMPGI](https://user-images.githubusercontent.com/95957360/184560982-1df35a00-ca09-485b-94bc-3be90dbfbdcd.png)

似乎是缺少文件

**Comment by KimigaiiWuyi** [comment]
使用`下载全部资源`命令先下载全部资源
慢的话可以使用群内的资源包,下载完覆盖
或者使用群友提供的 https://down.2654.us/api/public/dl/iKl2gQCP

**Comment by H12120** [comment]
Update----资源包3.0地址 https://down.2654.us/api/public/dl/wCWUePJB
