### ISSUE TITLE
导入时报错 RuntimeError: asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by XiDeng** [KimigaiiWuyi/GenshinUID#295]
开发者您好，我在使用您的插件时部分模块导入报错RuntimeError: asyncio.run() cannot be called from a running event loop
系统: CentOS7
Python版本: 3.10.6
错误信息如下：
[error.log](https://github.com/KimigaiiWuyi/GenshinUID/files/9334617/error.log)

不知道是哪里出了问题呢？请您帮忙看一下。

--------------------------------------------

后续：按照Wuyi大佬的方法，将.env里面的
`ENVIRONMENT=dev`修改为`#ENVIRONMENT=dev`后，插件成功加载。

_注意：应只保留`.env`文件，其余`.env.*`不要保留。_

**Comment by KimigaiiWuyi** [comment]
把 Nonebot 设置中的 `.env`文件中的`DEV`那一行注释掉，
这个文件在Bot主目录，并且是隐藏的

**Comment by scxdhr1998** [comment]
我的也是这个错误
`.env`中配置`ENVIRONMENT=dev`
`.env.dev`和`.env.prod`中配置
`HOST=127.0.0.1
PORT=8080
COMMAND_START=[""] 
LOG_LEVEL=DEBUG
FASTAPI_RELOAD=true 
`
.env中环境无论改成dev还是prod或者删掉都不行

**Comment by KimigaiiWuyi** [comment]
> 我的也是这个错误 `.env`中配置`ENVIRONMENT=dev` `.env.dev`和`.env.prod`中配置 `HOST=127.0.0.1 PORT=8080 COMMAND_START=[""] LOG_LEVEL=DEBUG FASTAPI_RELOAD=true ` .env中环境无论改成dev还是prod或者删掉都不行
`ENVIRONMENT=dev`
这一行注释掉`#ENVIRONMENT=dev`

**Comment by scxdhr1998** [comment]
还是不行
[nb.log](https://github.com/KimigaiiWuyi/GenshinUID/files/9335649/nb.log)

**Comment by KimigaiiWuyi** [comment]
> 还是不行 [nb.log](https://github.com/KimigaiiWuyi/GenshinUID/files/9335649/nb.log)

观察你的log，出现了两次`NoneBot is initializing`
也就是加载了两次，意味着 Nonebot2 debug模式被打开，任何改动都会重载你的Bot

**Comment by XiDeng** [comment]
> 还是不行 [nb.log](https://github.com/KimigaiiWuyi/GenshinUID/files/9335649/nb.log)

我只留了一个.env文件，其余的.env.*都被我删了😂

**Comment by KimigaiiWuyi** [comment]
> > 还是不行 [nb.log](https://github.com/KimigaiiWuyi/GenshinUID/files/9335649/nb.log)
> 
> 我只留了一个.env文件，其余的.env.*都被我删了😂

你成功加载了吗？

**Comment by KimigaiiWuyi** [comment]
> > 还是不行 [nb.log](https://github.com/KimigaiiWuyi/GenshinUID/files/9335649/nb.log)
> 
> 观察你的log，出现了两次`NoneBot is initializing` 也就是加载了两次，意味着 Nonebot2 debug模式被打开，任何改动都会重载你的Bot

可以依次查看读取环境变量优先级，这个模式正常用户不应该开启
> bot.py 文件( nonebot.init ) > 系统环境变量 > .env .env.* 文件

**Comment by XiDeng** [comment]
> > > 还是不行 [nb.log](https://github.com/KimigaiiWuyi/GenshinUID/files/9335649/nb.log)
> > 
> > 
> > 我只留了一个.env文件，其余的.env.*都被我删了😂
> 
> 你成功加载了吗？

我成功了

**Comment by KimigaiiWuyi** [comment]
> > > 还是不行 [nb.log](https://github.com/KimigaiiWuyi/GenshinUID/files/9335649/nb.log)
> > 
> > 
> > 观察你的log，出现了两次`NoneBot is initializing` 也就是加载了两次，意味着 Nonebot2 debug模式被打开，任何改动都会重载你的Bot
> 
> 可以依次查看读取环境变量优先级，这个模式正常用户不应该开启
> 
> > bot.py 文件( nonebot.init ) > 系统环境变量 > .env .env.* 文件

08-15 15:11:58 [INFO] nonebot | Current Env: prod
寻找`.env.prod`文件，关闭它
>> 可以注意到每个log前缀都有`[DEBUG]`，这就是DEBUG模式被开启的意思

**Comment by scxdhr1998** [comment]
删除了.env.dev和.env.prod之后导入成功了

**Comment by KimigaiiWuyi** [comment]
> 删除了.env.dev和.env.prod之后导入成功了 但是genshinuid_map导入报错 `08-15 15:32:54 [ERROR] nonebot | Failed to import "genshinuid_map" Traceback (most recent call last): File "/usr/local/bin/nb", line 8, in sys.exit(main()) File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in **call** return self.main(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run run_bot(file, app) File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 20, in run_bot module = importlib.import_module(module_name) File "/usr/lib/python3.8/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1014, in _gcd_import File "", line 991, in _find_and_load File "", line 975, in _find_and_load_unlocked File "", line 671, in _load_unlocked File "", line 848, in exec_module File "", line 219, in _call_with_frames_removed File "/root/genshiBot/./bot.py", line 29, in nonebot.load_from_toml("pyproject.toml") File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins return manager.load_all_plugins() File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins return set( File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 173, in filter(None, (self.load_plugin(name) for name in self.available_plugins)) File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 148, in load_plugin module = importlib.import_module( File "/usr/lib/python3.8/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1014, in _gcd_import File "", line 991, in _find_and_load File "", line 975, in _find_and_load_unlocked File "", line 671, in _load_unlocked File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module super().exec_module(module) File "", line 848, in exec_module File "", line 219, in _call_with_frames_removed File "/root/genshiBot/./genshibot/plugins/GenshinUID/**init**.py", line 5, in load_plugins(os.path.dirname(**file**)) File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 39, in load_plugins return manager.load_all_plugins() File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins return set( File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 173, in filter(None, (self.load_plugin(name) for name in self.available_plugins))
> 
> > File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 148, in load_plugin
> > module = importlib.import_module(
> > File "/usr/lib/python3.8/importlib/**init**.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1014, in _gcd_import
> > File "", line 991, in _find_and_load
> > File "", line 975, in _find_and_load_unlocked
> > File "", line 671, in _load_unlocked
> > File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module
> > super().exec_module(module)
> > File "", line 848, in exec_module
> > File "", line 219, in _call_with_frames_removed
> > File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshinuid_map/**init**.py", line 4, in 
> > from .genshinmap.models import MapID
> > File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshinuid_map/genshinmap/**init**.py", line 1, in 
> > from .models import Maps as Maps  # noqa: F401
> > File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshinuid_map/genshinmap/models.py", line 22, in 
> > class Label(BaseModel):
> > File "pydantic/main.py", line 188, in pydantic.main.ModelMetaclass.**new**
> > annotations = resolve_annotations(namespace.get('**annotations**', {}), namespace.get('**module**', None))
> > File "pydantic/typing.py", line 419, in pydantic.typing.resolve_annotations
> > value = _eval_type(value, base_globals, None)
> > File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
> > return t._evaluate(globalns, localns)
> > File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
> > eval(self.**forward_code**, globalns, localns),
> > File "", line 1, in 
> > TypeError: 'type' object is not subscriptable`

这个需要问 @MingxuanGame 
等她来吧（

**Comment by scxdhr1998** [comment]
> > 删除了.env.dev和.env.prod之后导入成功了 但是genshinuid_map导入报错 `08-15 15:32:54 [ERROR] nonebot | Failed to import "genshinuid_map" Traceback (most recent call last): File "/usr/local/bin/nb", line 8, in sys.exit(main()) File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in **call** return self.main(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/usr/local/lib/python3.8/dist-packages/nb_cli/commands/main.py", line 30, in run run_bot(file, app) File "/usr/local/lib/python3.8/dist-packages/nb_cli/handlers/deploy.py", line 20, in run_bot module = importlib.import_module(module_name) File "/usr/lib/python3.8/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1014, in _gcd_import File "", line 991, in _find_and_load File "", line 975, in _find_and_load_unlocked File "", line 671, in _load_unlocked File "", line 848, in exec_module File "", line 219, in _call_with_frames_removed File "/root/genshiBot/./bot.py", line 29, in nonebot.load_from_toml("pyproject.toml") File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml return load_all_plugins(plugins, plugin_dirs) File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins return manager.load_all_plugins() File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins return set( File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 173, in filter(None, (self.load_plugin(name) for name in self.available_plugins)) File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 148, in load_plugin module = importlib.import_module( File "/usr/lib/python3.8/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1014, in _gcd_import File "", line 991, in _find_and_load File "", line 975, in _find_and_load_unlocked File "", line 671, in _load_unlocked File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module super().exec_module(module) File "", line 848, in exec_module File "", line 219, in _call_with_frames_removed File "/root/genshiBot/./genshibot/plugins/GenshinUID/**init**.py", line 5, in load_plugins(os.path.dirname(**file**)) File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 39, in load_plugins return manager.load_all_plugins() File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins return set( File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 173, in filter(None, (self.load_plugin(name) for name in self.available_plugins))
> > > File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 148, in load_plugin
> > > module = importlib.import_module(
> > > File "/usr/lib/python3.8/importlib/**init**.py", line 127, in import_module
> > > return _bootstrap._gcd_import(name[level:], package, level)
> > > File "", line 1014, in _gcd_import
> > > File "", line 991, in _find_and_load
> > > File "", line 975, in _find_and_load_unlocked
> > > File "", line 671, in _load_unlocked
> > > File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module
> > > super().exec_module(module)
> > > File "", line 848, in exec_module
> > > File "", line 219, in _call_with_frames_removed
> > > File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshinuid_map/**init**.py", line 4, in
> > > from .genshinmap.models import MapID
> > > File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshinuid_map/genshinmap/**init**.py", line 1, in
> > > from .models import Maps as Maps  # noqa: F401
> > > File "/root/genshiBot/./genshibot/plugins/GenshinUID/genshinuid_map/genshinmap/models.py", line 22, in
> > > class Label(BaseModel):
> > > File "pydantic/main.py", line 188, in pydantic.main.ModelMetaclass.**new**
> > > annotations = resolve_annotations(namespace.get('**annotations**', {}), namespace.get('**module**', None))
> > > File "pydantic/typing.py", line 419, in pydantic.typing.resolve_annotations
> > > value = _eval_type(value, base_globals, None)
> > > File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
> > > return t._evaluate(globalns, localns)
> > > File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
> > > eval(self.**forward_code**, globalns, localns),
> > > File "", line 1, in
> > > TypeError: 'type' object is not subscriptable`
> 
> 这个需要问 @MingxuanGame 等她来吧（

好的,感谢大佬耐心解答

**Comment by lgc2333** [comment]
其实debug mode只需要吧fastapi reload配置关掉就行了2022年8月15日 下午4:05，MingxuanGame ***@***.***>写道：
fixed in ***@***.***

**Comment by XiDeng** [comment]
> 其实debug mode只需要吧fastapi reload配置关掉就行了2022年8月15日 下午4:05，MingxuanGame ***@***.***>写道： fixed in ***@***.*** —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

有道理，今天发现了，但是author已经把这个fixed了
