### ISSUE TITLE
新版安装依赖后报错无法运行

### ISSUE THREAD

**Issue by Aslan0613** [KimigaiiWuyi/GenshinUID#298]
近几天一直无法签到成功，所以就更新了一下，结果一堆报错。重新部署也是一样，
大佬帮忙看看。

[ne.txt](https://github.com/KimigaiiWuyi/GenshinUID/files/9355204/ne.txt)

**Comment by KimigaiiWuyi** [comment]
可能是已经在bot.py中写入加载代码了？
本插件不需要在bot.py中写入加载代码

**Comment by Aslan0613** [comment]
> 可能是已经在bot.py中写入加载代码了？ 本插件不需要在bot.py中写入加载代码

我尝试删除，但是删了就不会加载这个插件了.

**Comment by KimigaiiWuyi** [comment]
> > 可能是已经在bot.py中写入加载代码了？ 本插件不需要在bot.py中写入加载代码
> 
> 我尝试删除，但是删了就不会加载这个插件了.

nonebot2版本是最新的`nonebot2 beta5`么，应该不会吧，看一眼bot目录结构

**Comment by Aslan0613** [comment]
![image](https://user-images.githubusercontent.com/48046438/185021033-11a4fb3b-702b-42b8-b2ca-2fdfd17c2dce.png)


> > > 可能是已经在bot.py中写入加载代码了？ 本插件不需要在bot.py中写入加载代码
> > 
> > 
> > 我尝试删除，但是删了就不会加载这个插件了.
> 
> nonebot2版本是最新的`nonebot2 beta5`么，应该不会吧，看一眼bot目录结构

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/48046438/185021033-11a4fb3b-702b-42b8-b2ca-2fdfd17c2dce.png)
> 
> > > > 可能是已经在bot.py中写入加载代码了？ 本插件不需要在bot.py中写入加载代码
> > > 
> > > 
> > > 我尝试删除，但是删了就不会加载这个插件了.
> > 
> > 
> > nonebot2版本是最新的`nonebot2 beta5`么，应该不会吧，看一眼bot目录结构

GenshinUID应该在插件目录内，比如类似`src/plugin`的地方

**Comment by Aslan0613** [comment]
> 
把genshinuid 文件夹挪到plugins里面就正常了。
万分感谢大佬解答!
