### ISSUE TITLE
久歧忍派遣没修好，名字打错了

### ISSUE THREAD

**Issue by 1055169799** [KimigaiiWuyi/GenshinUID#299]
今天发现之前修复的问题，因为拼写疏忽，还是没修复
![image](https://user-images.githubusercontent.com/41286675/185288618-4f438056-6d67-4055-8243-6ed67f51fd4a.png)
![image](https://user-images.githubusercontent.com/41286675/185288507-881d544e-f5f1-4e4c-96ec-b56a354c47bc.png)
![image](https://user-images.githubusercontent.com/41286675/185288535-e6edcc19-22cf-459b-8c6d-40bdf5f152c7.png)

**Comment by KimigaiiWuyi** [comment]
草 拼写错了
这是`hoshino`分支吧
暂时应该不影响，留到3.0修吧

**Comment by KimigaiiWuyi** [comment]
已更新
