### ISSUE TITLE
请问这是缺了什么

### ISSUE THREAD

**Issue by Astesai** [KimigaiiWuyi/GenshinUID#3]
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable

**Comment by KimigaiiWuyi** [comment]
> ujson module not found, using json
> msgpack not installed, MsgPackSerializer unavailable

你是不是python的环境变量没有配置

**Comment by Astesai** [comment]
> > ujson module not found, using json
> > msgpack not installed, MsgPackSerializer unavailable
> 
> 你是不是python的环境变量没有配置

要怎么配置

**Comment by KimigaiiWuyi** [comment]
> > > ujson module not found, using json
> > > msgpack not installed, MsgPackSerializer unavailable
> > 
> > 
> > 你是不是python的环境变量没有配置
> 
> 要怎么配置

可以谷歌 你用的系统 + python环境变量配置 
例如 centos 7.9 python环境变量配置

**Comment by Astesai** [comment]
> > > > ujson module not found, using json
> > > > msgpack not installed, MsgPackSerializer unavailable
> > > 
> > > 
> > > 你是不是python的环境变量没有配置
> > 
> > 
> > 要怎么配置
> 
> 可以谷歌 你用的系统 + python环境变量配置
> 例如 centos 7.9 python环境变量配置

那么WARNING: Not found config of "GenshinUID"呢 好像没有见配置文件

**Comment by KimigaiiWuyi** [comment]
> > > > > ujson module not found, using json
> > > > > msgpack not installed, MsgPackSerializer unavailable
> > > > 
> > > > 
> > > > 你是不是python的环境变量没有配置
> > > 
> > > 
> > > 要怎么配置
> > 
> > 
> > 可以谷歌 你用的系统 + python环境变量配置
> > 例如 centos 7.9 python环境变量配置
> 
> 那么WARNING: Not found config of "GenshinUID"呢 好像没有见配置文件

hoshinobot里配置文件启用了就没有关系 
可以检查一下能否正常使用

**Comment by Astesai** [comment]
> > > > > > ujson module not found, using json
> > > > > > msgpack not installed, MsgPackSerializer unavailable
> > > > > 
> > > > > 
> > > > > 你是不是python的环境变量没有配置
> > > > 
> > > > 
> > > > 要怎么配置
> > > 
> > > 
> > > 可以谷歌 你用的系统 + python环境变量配置
> > > 例如 centos 7.9 python环境变量配置
> > 
> > 
> > 那么WARNING: Not found config of "GenshinUID"呢 好像没有见配置文件
> 
> hoshinobot里配置文件启用了就没有关系
> 可以检查一下能否正常使用

PS C:\Users\xxx\Desktop\HoshinoBot> python .\run.py
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\HoshinoBot\run.py", line 1, in <module>
    import hoshino
  File "C:\Users\xxx\Desktop\HoshinoBot\hoshino\__init__.py", line 9, in <module>
    from . import config
  File "C:\Users\xxx\Desktop\HoshinoBot\hoshino\config\__init__.py", line 15, in <module>
    importlib.import_module('hoshino.config.' + module)
  File "F:\Software\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\xxx\Desktop\HoshinoBot\hoshino\config\flac.py", line 2, in <module>
    from hoshino import Service, priv, logger, aiorequests
  File "C:\Users\xxx\Desktop\HoshinoBot\hoshino\priv.py", line 17, in <module>
    from hoshino.typing import CQEvent
  File "C:\Users\xxx\Desktop\HoshinoBot\hoshino\typing.py", line 8, in <module>
    from . import HoshinoBot
ImportError: cannot import name 'HoshinoBot' from partially initialized module 'hoshino' (most likely due to a circular import) (C:\Users\xxx\Desktop\HoshinoBot\hoshino\__init__.py)
还是不行

**Comment by KimigaiiWuyi** [comment]
> > > > > > > ujson module not found, using json
> > > > > > > msgpack not installed, MsgPackSerializer unavailable
> > > > > > 
> > > > > > 
> > > > > > 你是不是python的环境变量没有配置
> > > > > 
> > > > > 
> > > > > 要怎么配置
> > > > 
> > > > 
> > > > 可以谷歌 你用的系统 + python环境变量配置
> > > > 例如 centos 7.9 python环境变量配置
> > > 
> > > 
> > > 那么WARNING: Not found config of "GenshinUID"呢 好像没有见配置文件
> > 
> > 
> > hoshinobot里配置文件启用了就没有关系
> > 可以检查一下能否正常使用
> 
> PS C:\Users\xxx\Desktop\HoshinoBot> python .\run.py
> ujson module not found, using json
> msgpack not installed, MsgPackSerializer unavailable
> Traceback (most recent call last):
> File "C:\Users\xxx\Desktop\HoshinoBot\run.py", line 1, in
> import hoshino
> File "C:\Users\xxx\Desktop\HoshinoBot\hoshino__init__.py", line 9, in
> from . import config
> File "C:\Users\xxx\Desktop\HoshinoBot\hoshino\config__init__.py", line 15, in
> importlib.import_module('hoshino.config.' + module)
> File "F:\Software\python\lib\importlib__init__.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level) File "C:\Users\xxx\Desktop\HoshinoBot\hoshino\config\flac.py", line 2, in from hoshino import Service, priv, logger, aiorequests File "C:\Users\xxx\Desktop\HoshinoBot\hoshino\priv.py", line 17, in from hoshino.typing import CQEvent File "C:\Users\xxx\Desktop\HoshinoBot\hoshino\typing.py", line 8, in from . import HoshinoBot ImportError: cannot import name 'HoshinoBot' from partially initialized module 'hoshino' (most likely due to a circular import) (C:\Users\xxx\Desktop\HoshinoBot\hoshino__init__.py)
> 还是不行

可能是端口冲突了，你看看cqhttp和hoshino的端口有没有被占用，你换一个端口试一下
还有建议就是用云服务器运行 不要用windows（（

**Comment by Astesai** [comment]
> 可能是端口冲突了，你看看cqhttp和hoshino的端口有没有被占用，你换一个端口试一下
> 还有建议就是用云服务器运行 不要用windows（（

好的 我去看看
就是想试一下而已

**Comment by Astesai** [comment]
> 可能是端口冲突了，你看看cqhttp和hoshino的端口有没有被占用，你换一个端口试一下
> 还有建议就是用云服务器运行 不要用windows（（

把端口都改成了8888还是不行（
方便加个qq聊吗

**Comment by KimigaiiWuyi** [comment]
> > 可能是端口冲突了，你看看cqhttp和hoshino的端口有没有被占用，你换一个端口试一下
> > 还有建议就是用云服务器运行 不要用windows（（
> 
> 把端口都改成了8888还是不行（
> 方便加个qq聊吗

你可以加444835641
