### ISSUE TITLE
添加 stoken 时提示“该CK字段出错, 缺少login_uid或stuid或ltuid字段!”

### ISSUE THREAD

**Issue by qianxu2001** [KimigaiiWuyi/GenshinUID#300]
实际上包含了其中的任意一个字段，但是仍然提示缺少，经过测试发现，任意使用这三个中的两个进行组合就不报错了，甚至组合两个相同的字段都行，比如```添加 stoken stuid=xxx; stuid=xxx; stoken=xxx; login_ticket=xxx```都行，是正则出 bug 了？

**Comment by qianxu2001** [comment]
又测试了一下，直接添加 + stoken 就不会有问题，在中间插入 stoken 就会有问题
![image](https://user-images.githubusercontent.com/62287903/185730558-1d884390-34e1-4cbd-9372-f81b6b529049.png)

**Comment by KimigaiiWuyi** [comment]
应该是多了空格的缘故

**Comment by qianxu2001** [comment]
> 应该是多了空格的缘故

有没有空格都会不行（
![image](https://user-images.githubusercontent.com/62287903/185741609-1df217bb-c978-4985-a830-cf691b51c6b5.png)

**Comment by KimigaiiWuyi** [comment]
现在应该不需要stoken，直接添加 login_ticket=xxxx;xxx=xxx就可以了吧

**Comment by qianxu2001** [comment]
> 现在应该不需要stoken，直接添加 login_ticket=xxxx;xxx=xxx就可以了吧

ok
