### ISSUE TITLE
签到提示成功，但米游社没有签到成功

### ISSUE THREAD

**Issue by SPLUS-VABLE** [KimigaiiWuyi/GenshinUID#301]
![image](https://user-images.githubusercontent.com/42440354/185773702-d71719fd-4495-4dd7-af35-b34438c78060.png)

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/42440354/185773702-d71719fd-4495-4dd7-af35-b34438c78060.png)

`hoshino`分支的么?暂时的话 OK 就是没有成功

**Comment by SPLUS-VABLE** [comment]
> > ![image](https://user-images.githubusercontent.com/42440354/185773702-d71719fd-4495-4dd7-af35-b34438c78060.png)
> 
> `hoshino`分支的么?暂时的话 OK 就是没有成功
对的，是什么原因造成的，Cookie应该添加成功了

**Comment by KimigaiiWuyi** [comment]
> > > ![image](https://user-images.githubusercontent.com/42440354/185773702-d71719fd-4495-4dd7-af35-b34438c78060.png)
> > 
> > 
> > `hoshino`分支的么?暂时的话 OK 就是没有成功
> > 对的，是什么原因造成的，Cookie应该添加成功了

可以看看https://github.com/Womsxd/AutoMihoyoBBS/issues/179
和本项目下的https://github.com/KimigaiiWuyi/GenshinUID/issues/293

**Comment by SPLUS-VABLE** [comment]
> > > > ![image](https://user-images.githubusercontent.com/42440354/185773702-d71719fd-4495-4dd7-af35-b34438c78060.png)
> > > 
> > > 
> > > `hoshino`分支的么?暂时的话 OK 就是没有成功
> > > 对的，是什么原因造成的，Cookie应该添加成功了
> 
> 可以看看[Womsxd/AutoMihoyoBBS#179](https://github.com/Womsxd/AutoMihoyoBBS/issues/179) 和本项目下的#293

好的，谢谢大佬！

**Comment by Taokyla** [comment]
+1 
`{"retcode":0,"message":"OK","data":{"code":"","risk_code":375,"gt":"f1342eaf43e356aa680d18f55fa1f1ca","challenge":"2bca5ecc97602765e9d0b65537b435e0","success":1}}`

**Comment by KimigaiiWuyi** [comment]
转移至 #293
