### ISSUE TITLE
资源下载出错

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#303]
![Screenshot_20220825-015352](https://user-images.githubusercontent.com/59048777/186489275-3c40053a-404e-4ae1-94b1-38d6e7dee53c.png)
![Screenshot_20220824-234518](https://user-images.githubusercontent.com/59048777/186489318-6957e856-cef8-468e-8b15-a5425f31bc54.png)

**Comment by KimigaiiWuyi** [comment]
已修复
