### ISSUE TITLE
`刷新抽卡记录`指令不可用

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#306]
![-4a0b9c9ef8b4a34a](https://user-images.githubusercontent.com/59048777/186995413-f3e9655b-e5bd-47be-a61b-31b3d0338148.jpg)

**Comment by KimigaiiWuyi** [comment]
更新试试

**Comment by lgc2333** [comment]
依然无效
如果需要更多信息直接qq联系我

**Comment by qianxu2001** [comment]
> 依然无效 如果需要更多信息直接qq联系我

我今天拉最新代码已经可以用了，你试试

**Comment by lgc2333** [comment]
> > 依然无效 如果需要更多信息直接qq联系我
> 
> 我今天拉最新代码已经可以用了，你试试

已经可以了，我close掉
