### ISSUE TITLE
“状态”指令和报刀插件指令冲突。

### ISSUE THREAD

**Issue by SonderXiaoming** [KimigaiiWuyi/GenshinUID#312]
建议修改

**Comment by KimigaiiWuyi** [comment]
好像没有`状态`这个指令,是`当前状态`么

**Comment by SonderXiaoming** [comment]
![image](https://user-images.githubusercontent.com/98363578/187324408-b29b4a43-a339-4be1-bd6e-aa8600de593d.png)

**Comment by SonderXiaoming** [comment]
你是想用正则？

**Comment by KimigaiiWuyi** [comment]
> 你是想用正则？

原来是这里 稍后去掉，是想用aliases一样的效果，这几个都可以触发
