### ISSUE TITLE
HXD看看能不能把这个插件的查询地图资源功能给移过来

### ISSUE THREAD

**Issue by 1055169799** [KimigaiiWuyi/GenshinUID#314]
项目地址 https://github.com/H-K-Y/Genshin_Impact_bot/tree/main/query_resource_points

原作者似乎不更新了，和艾琳的egenshin一样，一到新版，插件都基本废了

这个是查询地图资源用的，对接的是米游社大地图的资源，蒙德和璃月的本来可以用，这次一更新，增加了须弥地图，直接用不了了
![image](https://user-images.githubusercontent.com/41286675/187478608-e26e0cbf-b4d7-4181-83a3-e27be0ad2894.png)
![image](https://user-images.githubusercontent.com/41286675/187478653-2d671528-ecfd-4eac-a4f5-c05eac52b2c0.png)

![image](https://user-images.githubusercontent.com/41286675/187478338-3a05430b-39b0-43e1-b068-dd3d99cd17ac.png)
![image](https://user-images.githubusercontent.com/41286675/187478705-a4b91fc0-88d7-4e25-bba5-900bc02ed81d.png)
![image](https://user-images.githubusercontent.com/41286675/187478772-eaa5f9e9-ec50-4aaa-8b6d-f2881c9364c4.png)

我这边改了一下，直接错位了
![image](https://user-images.githubusercontent.com/41286675/187479829-aa6a3818-6d2f-42ec-a8fa-8d13faa73d2d.png)
![image](https://user-images.githubusercontent.com/41286675/187479581-ed04a5c4-1933-45c7-93fd-d4e3c472ea23.png)

看看能否移过来吧，毕竟这功能很好用，使用频率还是很高的

**Comment by KimigaiiWuyi** [comment]
现在也有这个功能哦,你用hoshino应该是指令冲突了,你把这个插件关掉就能用本项目的`xx在哪里`了

**Comment by 1055169799** [comment]
> 现在也有这个功能哦,你用hoshino应该是指令冲突了,你把这个插件关掉就能用本项目的`xx在哪里`了

这样吗！我试试

**Comment by SonderXiaoming** [comment]
![image](https://user-images.githubusercontent.com/98363578/187515236-7ae0d9ef-c485-4784-937e-f104affd96ef.png)
是不是有点问题

**Comment by 1055169799** [comment]
额，似乎没有那么理想
![image](https://user-images.githubusercontent.com/41286675/187684483-b7aac70d-6834-4af9-b913-15161dbd6863.png)
![image](https://user-images.githubusercontent.com/41286675/187684510-41210800-181f-4d9f-96e7-f48a53ccc960.png)
![image](https://user-images.githubusercontent.com/41286675/187684582-98e3a725-e1c2-4721-b892-2f4a456f13c3.png)

**Comment by Z735803792** [comment]
地图显示小了捏，大佬加油~

**Comment by KimigaiiWuyi** [comment]
转移至新项目[fastapi_genshin_map](https://github.com/KimigaiiWuyi/fastapi_genshin_map)
目前插件已经使用上web服务,
包括yunzaibot的cvs插件和Nonebot2的本插件,都会使用这个fastAPI服务
有命令调用的问题可以来这边开issuse
有地图问题可以去那边开Issuse
