### ISSUE TITLE
一直查询角色信息

### ISSUE THREAD

**Issue by madein233** [KimigaiiWuyi/GenshinUID#316]
![BV`0QT5QZ5(JHEQB5~`XQYT](https://user-images.githubusercontent.com/98536559/188254133-b3cdbd32-f52d-4205-9f66-b2417a228308.png)
一直在查询角色信息，结果为空，这是bug吗？

**Comment by KimigaiiWuyi** [comment]
不是bug, Nonebot2本来每条消息都有处理的,立马return了所以对性能没有影响
觉得看着不舒服的话,之后我改变一下逻辑,为空直接不出log好了
