### ISSUE TITLE
更新以后有部分模块报错

### ISSUE THREAD

**Issue by Putarku** [KimigaiiWuyi/GenshinUID#317]
![image](https://user-images.githubusercontent.com/66679443/188269298-1a8b8b44-afd0-411a-bc58-ff28886aa750.png)
![image](https://user-images.githubusercontent.com/66679443/188269339-44eb27db-4ef1-4323-b244-9977c22aa113.png)

用的是beta1的分支，基本上都是这一条报错

**Comment by KimigaiiWuyi** [comment]
升级Nonebot2版本至Beta4

**Comment by Putarku** [comment]
好的了解
