### ISSUE TITLE
须弥更新后查询收集华丽的宝箱数值爆表

### ISSUE THREAD

**Issue by Putarku** [KimigaiiWuyi/GenshinUID#318]
![image](https://user-images.githubusercontent.com/66679443/188320682-4a49556d-c1bd-4c48-b8d2-31ef2906039b.png)

**Comment by KimigaiiWuyi** [comment]
不是很清楚准确的数字是多少
之后找一下

**Comment by KimigaiiWuyi** [comment]
已更新
