### ISSUE TITLE
希望hoshino版本解决一下多人签到失败问题。

### ISSUE THREAD

**Issue by li704644993** [KimigaiiWuyi/GenshinUID#32]
就是后几个人老失败，是米哈呦签到频率限制的问题。
麻烦大佬解决一下hoshino版本的问题。。

**Comment by KimigaiiWuyi** [comment]
今晚合并一下nb2的feat

**Comment by KimigaiiWuyi** [comment]
git pull测试一下？
直接用群里用命令`全部重签`
这个命令必须是机器人管理员才行
这个如果报错，再联系我，因为我现在没用Hoshino，不太好测试，可以加我Q444835641

**Comment by li704644993** [comment]
> 
可以了，感谢大佬

**Comment by KimigaiiWuyi** [comment]
> > 
> 
> 可以了，感谢大佬

ok,后续有问题可以联系我q~
