### ISSUE TITLE
无法使用部分指令 无法正常使用

### ISSUE THREAD

**Issue by chuanchuan744** [KimigaiiWuyi/GenshinUID#324]
![%B(YZ0YWY RKN4XH$J (UTU](https://user-images.githubusercontent.com/66564610/189395733-8bbe1b7f-4061-4e58-a5aa-355b2b354d56.png)
![AZM3LP4YU)72VMG)(0X5E0S](https://user-images.githubusercontent.com/66564610/189395743-3e18f422-5770-4e16-ba4d-bd667d1ec585.png)
![Q3 {`TGR~%@7379TKS1ARKC](https://user-images.githubusercontent.com/66564610/189395962-177c94c0-bfdb-4fd5-9e11-40cb7fe0ca38.png)
问题如题
cq版本v1.0.0-rc3
系统windows server
使用的是插件最新版本

**Comment by chuanchuan744** [comment]
不行捏 也是这样

**Comment by KimigaiiWuyi** [comment]
终于搞好其他的了...
绑定uid功能不是`on_command`,所以不需要加指令头`/`;
绑定Cookies可以退出登陆重新获取看看是否正常

**Comment by chuanchuan744** [comment]
已解决 非常感谢
