### ISSUE TITLE
诺艾尔名称报错

### ISSUE THREAD

**Issue by Mateoust** [KimigaiiWuyi/GenshinUID#33]
https://github.com/KimigaiiWuyi/GenshinUID/blob/fb555a9595f051cbe257acc0967324b1a2022d7c/__init__.py#L48

api的原始数据
`{'avatar_side_icon': 'https://upload-bbs.mihoyo.com/game_record/genshin/character_side_icon/UI_AvatarIcon_Side_Noel.png', 'status': 'Finished', 'remained_time': '0'}`

在`UI_AvatarIcon_Side_Noel.png`中
Noelle少了le变成了Noel无法和中文名称匹配。从而导致报错

其他的暂时未知

**Comment by KimigaiiWuyi** [comment]
已修复
