### ISSUE TITLE
刷新抽卡记录指令报错

### ISSUE THREAD

**Issue by Kudou-Chitose** [KimigaiiWuyi/GenshinUID#330]
![image](https://user-images.githubusercontent.com/41569230/189525621-a35b424f-fa9e-46f6-b279-4e211473710f.png)

第一次刷新抽卡记录后可正常使用，第二天抽卡后刷新报错，删除UID重新绑定CK/SK仍报错。

**Comment by KimigaiiWuyi** [comment]
还是SK失效的问题吧,导致获取数据为空

**Comment by Kudou-Chitose** [comment]
已解决，感谢指点。
