### ISSUE TITLE
生成地图信息错误

### ISSUE THREAD

**Issue by xh22805** [KimigaiiWuyi/GenshinUID#333]
![image](https://user-images.githubusercontent.com/104178374/190599399-e5111226-5090-4c74-963d-f32840ae5d10.png)

**Comment by KimigaiiWuyi** [comment]
地图太大了，生成报内存不足了

**Comment by KimigaiiWuyi** [comment]
链接：https://pan.baidu.com/s/1216LgswEwy1EH8WrzsAchA?pwd=Wuyi 
提取码：Wuyi
解压至`genshinuid_map/map_data`目录下
![image](https://user-images.githubusercontent.com/55526518/190849493-0a6512fc-0378-4d58-976e-3ab78128e5f7.png)

**Comment by xh22805** [comment]
好了，谢谢大佬
