### ISSUE TITLE
发生错误 'playerInfo'，请检查后台输出。

### ISSUE THREAD

**Issue by RUSSELL987** [KimigaiiWuyi/GenshinUID#342]
![QQ图片20220928070131](https://user-images.githubusercontent.com/59349123/192652610-60a86650-6093-4d96-acdf-6143bf233f00.png)
![QQ图片20220928070135](https://user-images.githubusercontent.com/59349123/192652615-bcd467bb-4c63-40d3-9831-dd2b939e526a.png)
![QQ图片20220928070139](https://user-images.githubusercontent.com/59349123/192652622-a04481f7-8b0d-4e19-8dee-c376c4e8ca8a.png)

**Comment by KimigaiiWuyi** [comment]
主要是由于版本更新，enka那边暂时关服了
我也没有判断是否为空，等一会enka状态恢复了就好了，晚上回去修改判断值
很急的话也可以使用文字版的`当前状态`命令

**Comment by RUSSELL987** [comment]
好的，谢谢wuyi佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KimigaiiWuyi/GenshinUID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 上午9:16
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342)





 
主要是由于版本更新，enka那边暂时关服了
 我也没有判断是否为空，等一会enka状态恢复了就好了，晚上回去修改判断值
 很急的话也可以使用文字版的当前状态命令

**Comment by KimigaiiWuyi** [comment]
现在应该正常

**Comment by RUSSELL987** [comment]
啊试了一下还是同样的报错







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KimigaiiWuyi/GenshinUID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 晚上9:17
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342)





 
现在应该正常

**Comment by KimigaiiWuyi** [comment]
> 啊试了一下还是同样的报错
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" ***@***.***&gt;; 发送时间:&nbsp;2022年9月28日(星期三) 晚上9:17 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342) 现在应该正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

你刚更新的么

**Comment by RUSSELL987** [comment]
刚更完，大概是早上不到六点，发现只要绑定了cookies每日就会报错，其他功能正常。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KimigaiiWuyi/GenshinUID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 晚上9:24
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342)





  
啊试了一下还是同样的报错
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间:&nbsp;2022年9月28日(星期三) 晚上9:17 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342) 现在应该正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
你刚更新的么

**Comment by KimigaiiWuyi** [comment]
> 刚更完，大概是早上不到六点，发现只要绑定了cookies每日就会报错，其他功能正常。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" ***@***.***&gt;; 发送时间:&nbsp;2022年9月28日(星期三) 晚上9:24 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342) 啊试了一下还是同样的报错 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间:&nbsp;2022年9月28日(星期三) 晚上9:17 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342) 现在应该正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt; 你刚更新的么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

新的报错截图我看看

**Comment by RUSSELL987** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KimigaiiWuyi/GenshinUID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 晚上9:29
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342)





  
刚更完，大概是早上不到六点，发现只要绑定了cookies每日就会报错，其他功能正常。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间:&nbsp;2022年9月28日(星期三) 晚上9:24 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342) 啊试了一下还是同样的报错 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间:&nbsp;2022年9月28日(星期三) 晚上9:17 @.&gt;; @.&gt;;"State @.&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342) 现在应该正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt; 你刚更新的么 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.&gt;
  
新的报错截图我看看

**Comment by KimigaiiWuyi** [comment]
> 

报错截图呢

**Comment by RUSSELL987** [comment]
日志在哪看啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KimigaiiWuyi/GenshinUID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月28日(星期三) 晚上10:00
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342)





   
报错截图呢

**Comment by KimigaiiWuyi** [comment]
> 日志在哪看啊
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" ***@***.***&gt;; 发送时间:&nbsp;2022年9月28日(星期三) 晚上10:00 ***@***.***&gt;; ***@***.***&gt;;"State ***@***.***&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 发生错误 'playerInfo'，请检查后台输出。 (Issue #342) 报错截图呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

你发一遍命令后台就有报错吧
