### ISSUE TITLE
添加cookies/stoken出错

### ISSUE THREAD

**Issue by C-Jun-GIT** [KimigaiiWuyi/GenshinUID#343]
![图片](https://user-images.githubusercontent.com/84917972/193000738-a5937f96-b104-4a85-bfba-09de1b37b943.png)
后台输出如上

**Comment by KimigaiiWuyi** [comment]
CK过期吧

**Comment by C-Jun-GIT** [comment]
试了一下，如果按照旧教程在https://bbs.mihoyo.com/ys/页面获取cookie，该cookie无法被绑定，后台输出如上
之后尝试了一下在http://user.mihoyo.com/页面获取cookie，成功

**Comment by KimigaiiWuyi** [comment]
> https://bbs.mihoyo.com/ys/

上面获取的是CK，下面获取的SK
上面获取的方法我下午试过 应该是可以的，可以开无痕试一下
不过SK能拿到的权限确实更多，而且会一起绑定CK，也可做为替代方法
