### ISSUE TITLE
Hoshino无法进行自动签到和自动米游币，但是手动执行可以成功。

### ISSUE THREAD

**Issue by SPLUS-VABLE** [KimigaiiWuyi/GenshinUID#348]

**Comment by KimigaiiWuyi** [comment]
可以提供一下日志么

**Comment by SPLUS-VABLE** [comment]
没有报错日志，感觉好像是这个定时任务没执行。
![image](https://user-images.githubusercontent.com/42440354/193826914-c8565187-b50e-4c1a-b5a2-6a3d4ae558aa.png)

**Comment by KimigaiiWuyi** [comment]
> 没有报错日志，感觉好像是这个定时任务没执行。 ![image](https://user-images.githubusercontent.com/42440354/193826914-c8565187-b50e-4c1a-b5a2-6a3d4ae558aa.png)

有没有可能没有打开`gs开启定时签到`?用`gs配置`看一下

**Comment by SPLUS-VABLE** [comment]
这个gs配置怎么开启
