### ISSUE TITLE
当前信息功能报错。

### ISSUE THREAD

**Issue by SPLUS-VABLE** [KimigaiiWuyi/GenshinUID#350]
![image](https://user-images.githubusercontent.com/42440354/193818307-c71d6650-5959-4fa0-8514-380f7d19ffb2.png)

**Comment by KimigaiiWuyi** [comment]
这是CK过期了吧

**Comment by SPLUS-VABLE** [comment]
这个重新绑定ck也是报这个错误。

**Comment by KimigaiiWuyi** [comment]
尝试无痕模式获取CK呢,这个应该确实是CK过期了,获取了空数据

**Comment by SPLUS-VABLE** [comment]
用无痕模式获取CK也不行

> 尝试无痕模式获取CK呢,这个应该确实是CK过期了,获取了空数据

**Comment by SPLUS-VABLE** [comment]
当前状态能使用，zj用不了

**Comment by KimigaiiWuyi** [comment]
更新后查看是否能用

**Comment by SPLUS-VABLE** [comment]
可以了，谢谢无疑大佬
