### ISSUE TITLE
改密码后用自己cookie查询自己会死循环

### ISSUE THREAD

**Issue by Ninsplay** [KimigaiiWuyi/GenshinUID#354]
用的hoshino
使用查询指令一直没响应然后翻了下代码
GenshinUID\GenshinUID\utils\get_cookies\get_cookies.py里

    async def get_useable_cookies(self, uid: str):
        self.uid = uid
        while True:
            self.useable_cookies = str(await cache_db(uid))
            if self.useable_cookies == '':
                return '绑定记录不存在。'
            elif self.useable_cookies == '没有可以使用的Cookies！':
                return '没有可以使用的Cookies！'
            await self.get_uid_data()
            msg = await self.check_cookies_useable()
            if isinstance(msg, str):
                return msg
            else:
                if msg:
                    return None

这块在死循环
在await self.get_uid_data()后面加了行print(self.raw_data)后的输出
![XVTZ9TZ`@N P1@BLKV4_)}R](https://user-images.githubusercontent.com/75929887/196145306-f19c2f7a-5503-4f02-b7fa-a6ab61850787.png)

**Comment by KimigaiiWuyi** [comment]
CK失效，这块确实需要优化一下，这两天处理

**Comment by KimigaiiWuyi** [comment]
> CK失效，这块确实需要优化一下，这两天处理

可以先用`校验所有Cookies`命令先删除

**Comment by Ninsplay** [comment]
ok

**Comment by KimigaiiWuyi** [comment]
应该没有问题了

**Comment by Ninsplay** [comment]
试了下应该是没问题了
