### ISSUE TITLE
能否新增查看原图功能？

### ISSUE THREAD

**Issue by keqing114514** [KimigaiiWuyi/GenshinUID#355]
发出来的随机图的原图获取，看其他的有这个功能

**Comment by KimigaiiWuyi** [comment]
已添加

**Comment by keqing114514** [comment]
您好…重新拉取以后回复消息并没有任何反应，使用的是hoshinobot

**Comment by KimigaiiWuyi** [comment]
> 您好…重新拉取以后回复消息并没有任何反应，使用的是hoshinobot

在hoshino上有些问题,现在应该可以用了
