### ISSUE TITLE
N50pqm7FSy2AkFz2B3TqtuZMJ5TOl3Ep 这个盐怎么抓的

### ISSUE THREAD

**Issue by icetech233** [KimigaiiWuyi/GenshinUID#357]
N50pqm7FSy2AkFz2B3TqtuZMJ5TOl3Ep 这个盐怎么抓的

**Comment by KimigaiiWuyi** [comment]
[这个项目](https://github.com/Womsxd/AutoMihoyoBBS)拿的,
web的话网页能看到,
app端的要逆向
