### ISSUE TITLE
可以做如果库中存在对应uid的cookie就用这个cookie查询其资料吗

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#36]
如题
自己是技术渣 不会写qwq

**Comment by KimigaiiWuyi** [comment]
可以，而且很简单；
由于我的代码都没写注释，所以看起来很麻烦，
从库中读取CK的函数在`getDB.py`中的`cacheDB`，这个函数返回的值`use`就是读取的ck，这个函数传入第一个参数`uid`可以传入mysid/uid，通过第二个参数`mode`判断，`mode == 2`的情况，`uid`被视为mysid；
当`cacheDB`函数从数据库缓存中获取到了这个uid查询的记录（也就是说今天查过了），则会直接调用`CookiesCache`这个表里面对应的ck，已确保不会重复使用CK。
当`cacheDB`函数从数据库缓存中获取不到这个uid查询的记录（也就是说今天没查过），则会从`NewCookiesTable`这个表中随机抽调一条ck，返回出去。
也就是说 可以在`if len(c_data)==0:`这个判断语句内的第一条`cookiesrow = c.execute("SELECT * FROM NewCookiesTable ORDER BY RANDOM() limit 1")`，这条是`SQL语句`，意思就是随机抽一条，你可以在这个地方加入优先级判断，让函数优先寻找`NewCookiesTable`这个表存不存在当前`uid`对应的ck，如果存在就返回，不存在就随机抽一条

**Comment by KimigaiiWuyi** [comment]
我大概要等到周天再写这一块了，如果感兴趣可以先写了提pr（其实应该也就加几行的事）

**Comment by lgc2333** [comment]
> 可以，而且很简单； 由于我的代码都没写注释，所以看起来很麻烦， 从库中读取CK的函数在`getDB.py`中的`cacheDB`，这个函数返回的值`use`就是读取的ck，这个函数传入第一个参数`uid`可以传入mysid/uid，通过第二个参数`mode`判断，`mode == 2`的情况，`uid`被视为mysid； 当`cacheDB`函数从数据库缓存中获取到了这个uid查询的记录（也就是说今天查过了），则会直接调用`CookiesCache`这个表里面对应的ck，已确保不会重复使用CK。 当`cacheDB`函数从数据库缓存中获取不到这个uid查询的记录（也就是说今天没查过），则会从`NewCookiesTable`这个表中随机抽调一条ck，返回出去。 也就是说 可以在`if len(c_data)==0:`这个判断语句内的第一条`cookiesrow = c.execute("SELECT * FROM NewCookiesTable ORDER BY RANDOM() limit 1")`，这条是`SQL语句`，意思就是随机抽一条，你可以在这个地方加入优先级判断，让函数优先寻找`NewCookiesTable`这个表存不存在当前`uid`对应的ck，如果存在就返回，不存在就随机抽一条

不会SQL QAQ

**Comment by KimigaiiWuyi** [comment]
> > 可以，而且很简单； 由于我的代码都没写注释，所以看起来很麻烦， 从库中读取CK的函数在`getDB.py`中的`cacheDB`，这个函数返回的值`use`就是读取的ck，这个函数传入第一个参数`uid`可以传入mysid/uid，通过第二个参数`mode`判断，`mode == 2`的情况，`uid`被视为mysid； 当`cacheDB`函数从数据库缓存中获取到了这个uid查询的记录（也就是说今天查过了），则会直接调用`CookiesCache`这个表里面对应的ck，已确保不会重复使用CK。 当`cacheDB`函数从数据库缓存中获取不到这个uid查询的记录（也就是说今天没查过），则会从`NewCookiesTable`这个表中随机抽调一条ck，返回出去。 也就是说 可以在`if len(c_data)==0:`这个判断语句内的第一条`cookiesrow = c.execute("SELECT * FROM NewCookiesTable ORDER BY RANDOM() limit 1")`，这条是`SQL语句`，意思就是随机抽一条，你可以在这个地方加入优先级判断，让函数优先寻找`NewCookiesTable`这个表存不存在当前`uid`对应的ck，如果存在就返回，不存在就随机抽一条
> 
> 不会SQL QAQ

抓个教程半小时就看懂了2333 
sqlite3的增删改查还是比较容易的，不行我周日再写吧，如果那时候没提pr的话（

**Comment by KimigaiiWuyi** [comment]
`git pull`更新测试一下
