### ISSUE TITLE
三个下载在powershell都报错了...

### ISSUE THREAD

**Issue by glzat** [KimigaiiWuyi/GenshinUID#362]

**Comment by lgc2333** [comment]
![-fc49bdbf1e136aa](https://user-images.githubusercontent.com/59048777/198928483-a2c7e4bf-b4dc-4fb2-bed7-a945b7bfb84c.jpg)
![5d6c4cecbc13a26b](https://user-images.githubusercontent.com/59048777/198928494-5b5d7e8c-ec78-497c-9881-caf5240f23a5.jpg)
**请提供报错信息** 谢谢
