### ISSUE TITLE
【报错】刷新抽卡寄录

### ISSUE THREAD

**Issue by Umamusume-Agnes-Digital** [KimigaiiWuyi/GenshinUID#363]
![image](https://user-images.githubusercontent.com/70925546/199010457-a2c9ae73-aa28-43a4-a122-02cfa63b4daa.png)

**Comment by Z735803792** [comment]
qq:发生错误 argument of type 'NoneType' is not iterable，请检查后台输出。

**Comment by lgc2333** [comment]
这个账号最近6个月没有任何抽卡记录吗

**Comment by Z735803792** [comment]
操作是这样的，
1、先查抽卡记录，有上个月刷新抽过的300抽左右记录，**可以显示**
2、私聊导入了抽卡记录，获取了全部的1300抽记录，**可以显示**
3、确认了他的CK和token都是正常的
4、`刷新抽卡记录`，报错如上

**Comment by lgc2333** [comment]
看起来应该是抽卡记录Authkey获取失败了 重绑stoken看看

**Comment by Z735803792** [comment]
如何解绑token和ck，只能删除uid重绑吗
