### ISSUE TITLE
私聊发送抽卡记录 json 文件无反应

### ISSUE THREAD

**Issue by qianxu2001** [KimigaiiWuyi/GenshinUID#372]
![image](https://user-images.githubusercontent.com/62287903/199490494-baae8bea-9324-4ca7-85c6-1aaa7dad1cf7.png)

**Comment by KimigaiiWuyi** [comment]
怪了,,使用`抽卡记录`也没有新增数据么?

**Comment by qianxu2001** [comment]
> 怪了,,使用`抽卡记录`也没有新增数据么?

没，只有机器人刷新出来的（

**Comment by Z735803792** [comment]
+1，前天更新草神版本后就用不了了

**Comment by Z735803792** [comment]
私聊直接发这个没有任何响应
[UIGF_105517604_20221122216.zip](https://github.com/KimigaiiWuyi/GenshinUID/files/9934307/UIGF_105517604_20221122216.zip)

**Comment by qianxu2001** [comment]
> 方便把json分享出来看看吗

[104700795.zip](https://github.com/KimigaiiWuyi/GenshinUID/files/9936663/104700795.zip)

**Comment by KimigaiiWuyi** [comment]
怪事,两个json都不能复现
bot没有返回`该抽卡记录UID105517604与你绑定UID100740568不符合！`这样的信息么
我看到matcher已经返回了消息
![image](https://user-images.githubusercontent.com/55526518/200032779-7aa7aa69-a8c4-418b-a781-5e7e56ba660a.png)

**Comment by qianxu2001** [comment]
> 怪事,两个json都不能复现 bot没有返回`该抽卡记录UID105517604与你绑定UID100740568不符合！`这样的信息么 我看到matcher已经返回了消息 ![image](https://user-images.githubusercontent.com/55526518/200032779-7aa7aa69-a8c4-418b-a781-5e7e56ba660a.png)

没有回复任何东西（

**Comment by Z735803792** [comment]
没有任何回复，而且我这测试的时候，绑定信息是一致的，要不然切换绑定再导入罢

**Comment by KimigaiiWuyi** [comment]
> 没有任何回复，而且我这测试的时候，绑定信息是一致的，要不然切换绑定再导入罢

你有用频道的patch么
