### ISSUE TITLE
尝试nonebot2安装方式3出现error报错

### ISSUE THREAD

**Issue by Juenia** [KimigaiiWuyi/GenshinUID#378]
求助。
尝试使用`pip3 install --editable ./GenshinUID-nonebot2`安装后出现以下错误，搜索不出具体原因，求助。![Screenshot_20221110_180340.jpg](https://user-images.githubusercontent.com/48351858/201061786-77fb29e8-3897-4f27-8d6f-4abd42c70c0f.jpg)

**Comment by Juenia** [comment]
> 建议直接移动到插件目录里

能否问下python3.10能使用插件吗

**Comment by KimigaiiWuyi** [comment]
> > 建议直接移动到插件目录里
> 
> 能否问下python3.10能使用插件吗

可以，3.11可能会有兼容性问题，3.10没问题

**Comment by KimigaiiWuyi** [comment]
> > 建议直接移动到插件目录里
> 
> 直接clone仓库到插件目录吗？

对

**Comment by Juenia** [comment]
> > > 建议直接移动到插件目录里
> > 
> > 能否问下python3.10能使用插件吗
> 
> 可以，3.11可能会有兼容性问题，3.10没问题

好的，谢谢

**Comment by Juenia** [comment]
> > > 建议直接移动到插件目录里
> > 
> > 直接clone仓库到插件目录吗？
> 
> 对

好的，我试试，谢谢
