### ISSUE TITLE
个人输入每日查询会报错，米游社的其它功能没有影响

### ISSUE THREAD

**Issue by yayayayayayz** [KimigaiiWuyi/GenshinUID#379]
![image](https://user-images.githubusercontent.com/103040983/201154704-c7fa4fab-93f1-4a57-bd79-b5bcb4cc787a.png)
输入每日查询会报错，米游社的其它功能没有影响，其他用户也没有问题，只有个人会有报错，如图
![image](https://user-images.githubusercontent.com/103040983/201155494-80470ebc-640c-4935-89b4-6f81153a7aa4.png)
是否有清除个人全部ck的办法，想尝试重新绑定ck，希望大佬能看到并给与指导

**Comment by yayayayayayz** [comment]
![image](https://user-images.githubusercontent.com/103040983/201156621-9ae15832-4479-4efe-90fc-291bc4f659d3.png)
已尝试校验ck也没有查找到过期ck

**Comment by KimigaiiWuyi** [comment]
遇到验证码了, 让他进米游社,我的角色,会看到验证码,没看到多逛两圈米游社

**Comment by yayayayayayz** [comment]
> 遇到验证码了, 让他进米游社,我的角色,会看到验证码,没看到多逛两圈米游社

感谢大佬指导，问题已解决
