### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by kyokusanaki** [KimigaiiWuyi/GenshinUID#38]
我在米游社获取的cookie，在私聊bot的时候发现一直校验失败，然后我更换了米游社通行证的cookie，但是还是校验失败，请问这是怎么回事，我输入指令添加之后有一格空格的，不输入空格无反应

**Comment by lgc2333** [comment]
本地有没有挂vpn

**Comment by KimigaiiWuyi** [comment]
优先检查这个Cookies 对应的米游社账号 有没有登陆过手机端米游社/有没有原神账号；其次检查这个Cookies有没有account_id = xxxxxx ; Cookie_token = xxxxxx这两条参数

**Comment by KimigaiiWuyi** [comment]
无更多信息。
