### ISSUE TITLE
微信端gs帮助指令出错

### ISSUE THREAD

**Issue by Baoer1** [KimigaiiWuyi/GenshinUID#380]
11-11 13:25:17 [SUCCESS] nonebot | ntchat wxid_*** | [MT_RECV_TEXT_MSG]: Message 677188729589962341 from wxid_***: gs帮助
11-11 13:25:17 [DEBUG] nonebot | Checking for matchers in priority 1...
11-11 13:25:17 [INFO] nonebot | Event will be handled by Matcher(type='message',module=GenshinUID.genshinuid_help)
11-11 13:25:17 [DEBUG] nonebot | Running Matcher(type='message', module=GenshinUID.genshinuid_help)
11-11 13:25:17 [DEBUG] nonebot | Running handler Dependent(call=send_guide_pic)
11-11 13:25:17 [INFO] genshinuid_help | 获得gs帮助图片成功！
11-11 13:25:17 [DEBUG] nonebot | ntchat | Calling API send_image
11-11 13:25:27 [WARNING] nonebot | ntchat | WebSocket for Bot wxid_*** closed by peer
11-11 13:25:27 [INFO] websockets | connection closed
11-11 13:25:37 [INFO] uvicorn | ('127.0.0.1', 50180) - "WebSocket /ntchat/ws" [accepted]
11-11 13:25:37 [INFO] nonebot | ntchat | Bot wxid_*** connected
11-11 13:25:37 [INFO] websockets | connection open
11-11 13:25:37 [INFO] genshinuid_update | 检查遗留信息...
11-11 13:25:47 [DEBUG] nonebot | ntchat | Calling API send_text
11-11 13:25:47 [ERROR] GenshinUID | 获取建议信息错误
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)

下面是ntchat报错的内容：
11-11 13:25:17 [SUCCESS] ntchat_client | wechat - 收到wechat消息：{'data': {'at_user_list': [], 'from_wxid': 'wxid_***', 'is_pc': 0, 'msg': 'gs帮助',
 'msgid': '677188729589962341', 'room_wxid': '', 'timestamp': 1668144316, 'to_wxid': 'wxid_***', 'wx_type': 1}, 'type': 11046}
11-11 13:25:17 [DEBUG] ntchat_client | websocket - 向ws发送消息：{"data": {"at_user_list": [], "from_wxid": "wxid_***", "is_pc": 0, "msg": "gs帮助",
"msgid": "677188729589962341", "room_wxid": "", "timestamp": 1668144316, "to_wxid": "wxid_***", "wx_type": 1}, "type": 11046}
11-11 13:25:37 [ERROR] ntchat_client | websocket - ws链接异常关闭：
11-11 13:25:37 [INFO] ntchat_client | websocket - 正在连接到：ws://127.0.0.1:12345/ntchat/ws
11-11 13:25:37 [SUCCESS] ntchat_client | websocket - ws已成功连接！
11-11 13:25:47 [SUCCESS] ntchat_client | websocket - 收到ws消息：{"action": "send_text", "params": {"content": "发生错误<NetWorkError message=WebSocket API call timeout
11-11 13:25:47 [DEBUG] ntchat_client | wechat - 调用接口：send_text，参数：{'content': '发生错误 <NetWorkError 
![04d04099dde8e59a40d29328bd3979a](https://user-images.githubusercontent.com/101307731/201272175-53560de1-e60a-4f6e-909c-f9ef8f8b93d8.jpg)
message=WebSocket API call timeout>，请检查后台输出。', 'to_wxid': 'wxid_***'}
11-11 13:25:47 [DEBUG] ntchat_client | websocket - 向ws发送消息：{"status": 200, "msg": "调用成功", "data": true, "echo": "6"}

**Comment by KimigaiiWuyi** [comment]
重新下载NTchat，最新版已经修复该问题
