### ISSUE TITLE
抽卡记录报错

### ISSUE THREAD

**Issue by chrd123w** [KimigaiiWuyi/GenshinUID#381]
发生错误 [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\project\\noneBot2\\data\\GenshinUID\\resource\\chars\\.png'，请检查后台输出。这个.png是什么文件

**Comment by chrd123w** [comment]
![Uploading 7F8AC768-F77D-424B-ADA8-59A27089FEEB.png…]()

**Comment by chrd123w** [comment]
![51BA75B9-557B-49CF-AD6F-40907EBD1D9D](https://user-images.githubusercontent.com/30223742/201454025-7b0fdf61-3a4a-442a-b208-4edc1d510b58.png)
控制台输出

**Comment by chrd123w** [comment]
更新后变成\10000073.png了，应该是资源没有更新

**Comment by KimigaiiWuyi** [comment]
`下载全部资源`命令会下到，但是启动的时候应该会自动下载，你机子在海外吗

**Comment by KimigaiiWuyi** [comment]
如果是windows服务器证书问题,导致没办法连上下载服务器的话,可以百度安装证书或者尝试[这个方法](https://github.com/KimigaiiWuyi/GenshinUID/issues/209#issuecomment-1310024758)
