### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by 63248797** [KimigaiiWuyi/GenshinUID#382]
![image](https://user-images.githubusercontent.com/40305048/201457313-26cf9a25-d2e4-4747-bf74-fe6b8097b4bf.png)
提示如图，不知道是什么原因导致的，下载资源的时候一直报错

**Comment by KimigaiiWuyi** [comment]
windows服务器需要安装证书,具体方法可以百度,或者可以尝试[这个方法](https://github.com/KimigaiiWuyi/GenshinUID/issues/209#issuecomment-1310024758)

**Comment by 63248797** [comment]
> windows服务器需要安装证书,具体方法可以百度,或者试一下[这个方法](https://github.com/KimigaiiWuyi/GenshinUID/issues/209#issuecomment-1310024758)

非常感谢，添加cacert.pem以后可以成功下载了，但是这个报错还是没解决，不知道是什么情况
![GZ2}2BDYANOND({A2{8XBXM](https://user-images.githubusercontent.com/40305048/201458965-953aa670-cf94-4417-8910-76dfb57ee053.png)

**Comment by KimigaiiWuyi** [comment]
等下...为什么你要把nonebot装在lib里,应该在个人目录里创建bot 不应该在lib库里装

**Comment by 63248797** [comment]
> 等下...为什么你要把nonebot装在lib里,应该在个人目录里创建bot 不应该在lib库里装

额，那我再重装一次吧，centos系统可以吗？感觉Windows限制太多了

**Comment by KimigaiiWuyi** [comment]
> > 等下...为什么你要把nonebot装在lib里,应该在个人目录里创建bot 不应该在lib库里装
> 
> 额，那我再重装一次吧，centos系统可以吗？感觉Windows限制太多了

尽量用ubuntu...centos问题更多
