### ISSUE TITLE
作者你好，关于添加cookies之后一直提示未找到绑定信息

### ISSUE THREAD

**Issue by VoplsX** [KimigaiiWuyi/GenshinUID#39]
使用添加 cookies之后，显示是添加成功，uid和mys也是正常添加，可以查询。但是不能够进行每月统计和当前状态的查询一直提示是未找到绑定信息，查询词云功能提示为遇到错误。先是用hoshino，绑定cookies之后是可以进行每月统计，但是当前状态还是现实未绑定，后来换了nonebot2，每月统计也查不了了。还请麻烦作者大大解答一下

**Comment by KimigaiiWuyi** [comment]
查询词云功能，因为官方更新基本是废了一大半，后续可能会修；
每月统计和当前状态这两个功能，必须是你绑定的Cookies是你绑定的UID/MYSID，要不然也是错误；

**Comment by KimigaiiWuyi** [comment]
如果确定已经私聊绑定过cookies;然后群聊里绑定了uid，还是无法使用签到/每月统计/当前状态三个功能，请+q444835641

**Comment by KimigaiiWuyi** [comment]
![Screenshot_20211130-004511_米游社](https://user-images.githubusercontent.com/55526518/143908462-ad388f5f-e2df-4d36-aff2-c4feb0926554.png)
实时便筏功能需打开这个开关，望后来者知晓~
