### ISSUE TITLE
小bug？ 查询角色功能 暴击率溢出时计算出来的期望值比暴击值高

### ISSUE THREAD

**Issue by Ninsplay** [KimigaiiWuyi/GenshinUID#391]
rt
还是说我对期望值理解有点问题？我想的就是单纯暴击值乘暴击率的结果，但我看好像也对不上![-1dc8030c16d0480e.jpg](https://user-images.githubusercontent.com/75929887/202245771-67d4784d-b456-49b9-8042-63435d8fa985.jpg)

**Comment by twfx1207** [comment]
期望=(暴击值x暴击率)+(普通值x(1-暴击率))
这里应该没对暴击率超过100%的部分进行处理

eg:
A一段伤害的期望=
(2983*1.031)+(1045*(1-1.031))=3043

**Comment by Ninsplay** [comment]
感谢解答
