### ISSUE TITLE
毕业度bug

### ISSUE THREAD

**Issue by Ninsplay** [KimigaiiWuyi/GenshinUID#397]
rt
![QQ图片20221129215001](https://user-images.githubusercontent.com/75929887/204546602-58e8297d-a282-4cec-b557-d0e98d1491e1.jpg)

**Comment by KimigaiiWuyi** [comment]
噢 妮露的参考伤害是丰壤之核，错误把暴击值当成伤害了，应该是按普通值进行计算毕业度
稍后修复

**Comment by KimigaiiWuyi** [comment]
已修复

**Comment by A-JiuA** [comment]
刻晴的也有问题![61e157126b61b69f.png](https://user-images.githubusercontent.com/34974508/204554451-1884453d-97fe-495b-972f-7e11fd598163.png)

**Comment by Ninsplay** [comment]
我的倒是没问题
![QQ图片20221129222841](https://user-images.githubusercontent.com/75929887/204555881-42cddb2d-f0ca-4dfe-9d1a-e5e46c1e1b69.png)

**Comment by KimigaiiWuyi** [comment]
> 刻晴的也有问题![61e157126b61b69f.png](https://user-images.githubusercontent.com/34974508/204554451-1884453d-97fe-495b-972f-7e11fd598163.png)

更新

**Comment by A-JiuA** [comment]
OK，更新完好了
