### ISSUE TITLE
授权请求

### ISSUE THREAD

**Issue by Roc136** [KimigaiiWuyi/GenshinUID#4]
大佬我可以将您的代码迁移到我自己的仓库吗？我用的是mriai机器人，通过graia-saya管理插件，我现在想将这个插件修改为saya可用的并加到自己的[公开仓库](https://github.com/Roc136/saya_plugins_collection)里（我会在README中附上您的个人主页和本仓库的链接）

**Comment by KimigaiiWuyi** [comment]
> 大佬我可以将您的代码迁移到我自己的仓库吗？我用的是mriai机器人，通过graia-saya管理插件，我现在想将这个插件修改为saya可用的并加到自己的[公开仓库](https://github.com/Roc136/saya_plugins_collection)里（我会在README中附上您的个人主页和本仓库的链接）

没有问题 不过我这个插件后续原神加了新角色就不能用了 得自己添加头像 这点还需要注意

**Comment by Roc136** [comment]
> > 大佬我可以将您的代码迁移到我自己的仓库吗？我用的是mriai机器人，通过graia-saya管理插件，我现在想将这个插件修改为saya可用的并加到自己的[公开仓库](https://github.com/Roc136/saya_plugins_collection)里（我会在README中附上您的个人主页和本仓库的链接）
> 
> 没有问题 不过我这个插件后续原神加了新角色就不能用了 得自己添加头像 这点还需要注意

好的，谢谢
