### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by 836672549** [KimigaiiWuyi/GenshinUID#40]
我在查询深渊时自己可以查询全部，朋友只能查询部分，这种情况怎么解决呢

**Comment by KimigaiiWuyi** [comment]
米游社api限制，因为这个缘故，天空岛数据库和深渊数据网也不能获取到了，这个是没有办法的……

**Comment by 836672549** [comment]
因为我是机器人放在云服务器上，那他是怎么识别这个号是我的还是别人的呢，是因为我是第一个绑定才显示全部吗

**Comment by KimigaiiWuyi** [comment]
> 因为我是机器人放在云服务器上，那他是怎么识别这个号是我的还是别人的呢，是因为我是第一个绑定才显示全部吗

识别这个号到底是谁的，是因为ck的关系，ck里的account_id字段是你的米游社通行证，
现在是随机返回ck，可能正好就是你的ck返回到了，或者说ck库只添加了你的ck；
下个版本会加上优先返回uid所有人ck（已经写好了，但是还有别的功能要写，所以没传）

**Comment by 836672549** [comment]
喔喔懂了
