### ISSUE TITLE
请问这是什么问题？发送指令必须at而且一直Checking for matchers in priority

### ISSUE THREAD

**Issue by bangbanbab** [KimigaiiWuyi/GenshinUID#404]
![image](https://user-images.githubusercontent.com/87685982/207557128-a6d5b94c-6acf-4f4e-9ee6-be6466de3c34.png)

**Comment by KimigaiiWuyi** [comment]
1. `Checking for matchers in priority`是`DEBUG`日志，是正常现象，如果不想看到可以去.env里把`LOG_LEVEL`调成 `INFO`
2. 频道的Bot必须AT，是官方限制，我这边无能为力
3. 频道的BOT插件必须clone `QQGuildBot`分支，而不是`nonebot2-beta1`分支
