### ISSUE TITLE
关于个别uid查询突然崩溃

### ISSUE THREAD

**Issue by VoplsX** [KimigaiiWuyi/GenshinUID#41]
作者你好 很抱歉又来打扰， 在使用过程中 一开始能查询的uid 后来再查，机器人直接反馈输入错误（只有这一个uid是这样），在bot.py输出的是正常得
12-01 01:41:02 [INFO] nonebot | Event will be handled by <Matcher from GenshinUID, type=message, priority=2, temp=False>
12-01 01:41:02 [INFO] nonebot | Matcher <Matcher from GenshinUID, type=message, priority=2, temp=False> running complete，
但是Bot反馈的是 输入错误！ 还请作者指点迷津  :(
(换了设备以及更换BOT账号都是同样的提示

**Comment by VoplsX** [comment]
补充，输入绑定uidxxxxxx之后提示是正常得。。

**Comment by KimigaiiWuyi** [comment]
方便的话可以把uid给我一下吗，我做测试

**Comment by KimigaiiWuyi** [comment]
米游社权限问题
data not public for user
