### ISSUE TITLE
nonebot2-beta1分支中少导了插件

### ISSUE THREAD

**Issue by bakamelon** [KimigaiiWuyi/GenshinUID#411]
## 问题分支：`nonebot2-beta1`
`GenshinUID/__init__.py` 中 `genshinuid_gcg` 和 `genshinuid_xkdata` 没有导入

### 其他问题（小建议）

* 有的地方(比如`genshinuid_check` )的 matcher 没有设置 priority，config 提供的 priority 不能作用到所有 matcher, 希望可以统一 一下
* 有的需要 SUPERUSER 的地方(如 `genshinuid_update`)可以在 matcher 中写 `permisson=SUPERUSER` 来决定是否只能是SUPERUSER用, 不用在 handle 里再用 `if not await SUPERUSER(bot, event)` 进行判断.

**Comment by KimigaiiWuyi** [comment]
已修复一部分，有一部分需要后续同步`__init__`调整
