### ISSUE TITLE
该项目可能不支持微信ntchat

### ISSUE THREAD

**Issue by TomorrowLost** [KimigaiiWuyi/GenshinUID#412]
测试过，nonebot能接收到微信信息，但是没有反应，机器人genshinuid没反应

**Comment by KimigaiiWuyi** [comment]
你clone的是`ntchat`分支么

**Comment by TomorrowLost** [comment]
> 你clone的是`ntchat`分支么

我已经找到原因的，我clone默认的分支。

**Comment by TomorrowLost** [comment]
> 测试过，nonebot能够接收到微信信息，但没有反应，机器人genshinuid没有反应
