### ISSUE TITLE
Ntchat使用过程中问题反馈及建议

### ISSUE THREAD

**Issue by wuchangjun233** [KimigaiiWuyi/GenshinUID#414]
①不能识别超级管理员
![image](https://user-images.githubusercontent.com/34960661/209745521-a16ecaeb-128d-4fcb-a146-d0c821c57cd2.png)

②无法导入、导出抽卡记录
![QQ图片20221228094524](https://user-images.githubusercontent.com/34960661/209745557-1cf2424c-918d-4c9f-82fb-3b5547cc888e.png)

③地图资源查询第二次无法触发
![QQ图片20221228093954](https://user-images.githubusercontent.com/34960661/209743921-94ffb3d4-5e5b-4e4f-a045-5f1ac9cea91c.png)

④查询命令报错
发生错误 list indices must be integers or slices, not str，请检查后台输出。
后台输出定位到genshinuid_enka/__init__.py 第183行 msg_id = req['message_id']
将改行注释后，并将185行 f'{msg_id}.jpg' 改为 f'{uid}.jpg' 无报错。
临时文件夹也能生成图片了 .\data\GenshinUID\resource\temp
![Snipaste_2022-12-28_09-41-15](https://user-images.githubusercontent.com/34960661/209744005-fbdf7721-5c80-4b79-a373-d837001fd668.png)

⑤建议 ： 抽卡记录页面上方默认的QQ头像建议改成其他的（WeChat没有QQ头像啊！）
![Snipaste_2022-12-28_09-44-41](https://user-images.githubusercontent.com/34960661/209744245-7d733a9f-a46c-4ab9-a0ae-70378a5c4cc1.png)
![Snipaste_2022-12-28_09-42-22](https://user-images.githubusercontent.com/34960661/209746098-306238a4-be35-4275-afc0-7c3b96138946.png)

其他的想起来再补充吧꒰ঌ( ⌯' '⌯)໒꒱

**Comment by KimigaiiWuyi** [comment]
其他抽空会修改，
第一条，应该报告给ntchat 适配器，这是上游问题（如果你添加了SUPERUSER正确，但无法识别的话）
第四条，实际上也是上游问题，这里本来应该存放发出去消息的msgid，但是适配器获取不到自己发送消息的msgid，后续会把这一行删掉（意味着`原图`将不可使用）
