### ISSUE TITLE
[gs重启]使用gs重启后无法callapi

### ISSUE THREAD

**Issue by yhzcake** [KimigaiiWuyi/GenshinUID#416]
在使用nonebot-plugin-gocqhttp的时候使用gs重启,可以接受群聊消息,但不能调用任何插件,并且也不会显示重启完成!重启时间:2023-01-05 21:59:47,只有再次手动重启后才会恢复正常
并不能确定确实跟nonebot-plugin-gocqhttp有关,因为我不会手动配置gocqhttp
![image](https://user-images.githubusercontent.com/80627671/210806295-ee30f2c8-d78e-4088-8f6f-f29e667b0db7.png)

**Comment by KimigaiiWuyi** [comment]
从发送`gs重启`到插件无响应的log有吗

**Comment by yhzcake** [comment]
[error.log](https://github.com/KimigaiiWuyi/GenshinUID/files/10366267/error.log)
在这里,我重新启动bot输入指令成功执行后进行gs重启,到重启完毕再次发送指令

**Comment by KimigaiiWuyi** [comment]
v4现在不会重启Nonebot2、只会重启Core
