### ISSUE TITLE
查询词云报错

### ISSUE THREAD

**Issue by li704644993** [KimigaiiWuyi/GenshinUID#42]
查询词云，机器人都是反馈“遇到错误”
让群里别人试也一样。
打断点看了下，运行到getImg.py的119行就没往下运行了，但是进入GetCharacter方法能正常返回数据。麻烦大佬帮忙看一下

**Comment by KimigaiiWuyi** [comment]
词云功能暂时确实用不了，因为现在不返回深渊数据了，我观察一下如果mhy没有加回来的意思，那我后续会更换数据获取方式修复；

**Comment by KimigaiiWuyi** [comment]
`git pull`更新看看能不能用了

**Comment by li704644993** [comment]
getImg里面没有引入cacheDB方法。

**Comment by KimigaiiWuyi** [comment]
> getImg里面没有引入cacheDB方法。

刚另一个issues看到了（低级错误
