### ISSUE TITLE
频道官方机器人nb run后报错

### ISSUE THREAD

**Issue by bangbanbab** [KimigaiiWuyi/GenshinUID#423]
![image](https://user-images.githubusercontent.com/87685982/211714956-95738fb2-56c9-49dc-8abd-36145283beb9.png)
![image](https://user-images.githubusercontent.com/87685982/211714998-56863b85-7339-4344-8f3a-81d708d5bd79.png)

**Comment by KimigaiiWuyi** [comment]
安装最新的 `adapter-qqguild`，MessageMarkDown是新加的

**Comment by KimigaiiWuyi** [comment]
> 安装最新的 `adapter-qqguild`，MessageMarkDown是新加的

[qqguild](https://github.com/nonebot/adapter-qqguild)
版本应该是`0.1.3`
