### ISSUE TITLE
更新最新版本后查询指令只会回复“输入错误”

### ISSUE THREAD

**Issue by Putarku** [KimigaiiWuyi/GenshinUID#43]
其他功能倒是完好
![image](https://user-images.githubusercontent.com/66679443/144708651-7f2735a9-2314-4571-9c2f-0902747de52d.png)
回退到25号的版本后回复正常

**Comment by KimigaiiWuyi** [comment]
hoshino还是nb2

**Comment by Putarku** [comment]
hoshino

**Comment by KimigaiiWuyi** [comment]
我现在没有hoshino环境，能帮忙把`__init__.py`文件里的467行开始的try...except...给去掉，再输入命令 后台看一下报错吗~

**Comment by Putarku** [comment]
没有报错，不止查询不行，查询深渊这些也同样是输入错误

**Comment by Putarku** [comment]
删除了以后查询就不会回复了后台也就显示这样
![image](https://user-images.githubusercontent.com/66679443/144709953-2ab33169-6c8e-4b88-a69d-8444de40dbee.png)

**Comment by KimigaiiWuyi** [comment]
改成这样测试，不要全删了 
<img width="372" alt="Snipaste_2021-12-04_20-53-14" src="https://user-images.githubusercontent.com/55526518/144710115-5a530f0c-720c-47ee-a6f9-e9fe9f3f121a.PNG">

**Comment by Putarku** [comment]
![image](https://user-images.githubusercontent.com/66679443/144710721-c4069514-cb00-4730-966d-3de540220389.png)

**Comment by KimigaiiWuyi** [comment]
`getImg.py`文件夹下 第13行，最后结尾添加`,cacheDB`，重启bot查看是否正常
忘记加这个了（（

**Comment by Putarku** [comment]
ok，没问题了，多谢大佬😂

**Comment by KimigaiiWuyi** [comment]
> ok，没问题了，多谢大佬😂

是我自己傻逼了
