### ISSUE TITLE
将错误信息私聊发送给超级用户，而不向触发者发送具体的错误信息

### ISSUE THREAD

**Issue by bakamelon** [KimigaiiWuyi/GenshinUID#439]
目前出错时的异常信息是直接发送给触发者的，建议出错时将具体错误情况发送给超级用户，对触发者只提供 “出错了，请联系机器人管理员处理” 这样的信息，不告知普通用户具体的错误。

**Comment by KimigaiiWuyi** [comment]
错误太多都发给管理员，不会刷屏吗

**Comment by bakamelon** [comment]
> 错误太多都发给管理员，不会刷屏吗

好像确实有点，但是感觉直接把详细异常发给用户可能不太安全（），或者要不开个文件夹用来输出错误日志
