### ISSUE TITLE
[输入错误！]曾经同时绑定uid和mys的玩家更新后会查询异常

### ISSUE THREAD

**Issue by wudifeixue** [KimigaiiWuyi/GenshinUID#45]
![image](https://user-images.githubusercontent.com/7316929/145082328-eba9d7b0-8efb-4812-87c0-c97a88545c27.png)
查询会给反馈，显示，输入错误！
![image](https://user-images.githubusercontent.com/7316929/145082454-18c37f64-235a-483e-bdb6-42f90de5f761.png)
后台错误信息

解决方案，去在HoshinoBot根目录数据库ID_DATA.db中删除曾经多余绑定的MYUID就可以恢复正常
![image](https://user-images.githubusercontent.com/7316929/145082647-7c5fdec7-64ae-45b6-853a-2778e0fad3a9.png)

**Comment by KimigaiiWuyi** [comment]
添加了自动生成新的空白Cache
