### ISSUE TITLE
当前状态出现异常

### ISSUE THREAD

**Issue by jiyemengmei** [KimigaiiWuyi/GenshinUID#450]
![image](https://user-images.githubusercontent.com/49085794/218315619-015ed48c-f07d-4308-b707-93f04e50cac1.png)
![image](https://user-images.githubusercontent.com/49085794/218315690-32891595-a860-4d92-9b6c-463bc84bb3b1.png)

**Comment by KimigaiiWuyi** [comment]
目前来看应该是CK失效过期，可以重新添加后尝试（`扫码登陆`/`添加xx`均可）
话说为啥不用`mr`

**Comment by jiyemengmei** [comment]
@KimigaiiWuyi 修改了之后还是一样，应该是这个当前状态指令问题
![image](https://user-images.githubusercontent.com/49085794/218318273-5af99730-ad6c-4dd8-9f37-7f6d71a019e7.png)
![image](https://user-images.githubusercontent.com/49085794/218318358-f287871e-85ec-47c4-befe-6abb1d53a099.png)
![image](https://user-images.githubusercontent.com/49085794/218320991-13addb91-9993-454c-9bfa-b51a2e76ddeb.png)

**Comment by KimigaiiWuyi** [comment]
> @KimigaiiWuyi 修改了之后还是一样，应该是这个当前状态指令问题 ![image](https://user-images.githubusercontent.com/49085794/218318273-5af99730-ad6c-4dd8-9f37-7f6d71a019e7.png) ![image](https://user-images.githubusercontent.com/49085794/218318358-f287871e-85ec-47c4-befe-6abb1d53a099.png) ![image](https://user-images.githubusercontent.com/49085794/218320991-13addb91-9993-454c-9bfa-b51a2e76ddeb.png)

看来是风控了，需要过验证码
