### ISSUE TITLE
原神uid和米游社id绑定会无法保存，cookie会刷新

### ISSUE THREAD

**Issue by chenshoyuan** [KimigaiiWuyi/GenshinUID#46]
米游社uid绑定机器人无法记录
原神uid绑定机器人无法记录
cookie会刷新，无法保存记录

**Comment by KimigaiiWuyi** [comment]
什么叫无法保存

**Comment by chenshoyuan** [comment]
就是绑定一次id，后面又要重新绑定


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KimigaiiWuyi/GenshinUID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 下午5:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 原神uid和米游社id绑定会无法保存，cookie会刷新 (Issue #46)





 
什么叫无法保存
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KimigaiiWuyi** [comment]
hoshino版本还是nb2版本？
检查一下主目录下是否生成了ID_DATA.db的数据库文件

**Comment by chenshoyuan** [comment]
hoshino




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月9日(星期四) 下午5:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] 原神uid和米游社id绑定会无法保存，cookie会刷新 (Issue #46)





 
hoshino版本还是nb2版本？
 检查一下主目录下是否生成了ID_DATA.db的数据库文件
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenshoyuan** [comment]
没有id_data文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "归途守候你"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 下午5:52
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [KimigaiiWuyi/GenshinUID] 原神uid和米游社id绑定会无法保存，cookie会刷新 (Issue #46)



hoshino




------------------ 原始邮件 ------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月9日(星期四) 下午5:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] 原神uid和米游社id绑定会无法保存，cookie会刷新 (Issue #46)





 
hoshino版本还是nb2版本？
 检查一下主目录下是否生成了ID_DATA.db的数据库文件
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wudifeixue** [comment]
https://github.com/KimigaiiWuyi/GenshinUID/issues/48#issuecomment-990028788
感觉问题类似

**Comment by KimigaiiWuyi** [comment]
#48
