### ISSUE TITLE
无法签到

### ISSUE THREAD

**Issue by yangchaohe** [KimigaiiWuyi/GenshinUID#460]
这是群聊消息：
![image](https://user-images.githubusercontent.com/58938416/220825896-5906236a-0d9e-48d5-8277-156e398da3c3.png)
这是控制台消息：
![image](https://user-images.githubusercontent.com/58938416/220825966-9e41bb00-25ac-4ec3-90b7-10c48c045ede.png)
不好意思哈，python 小白，请问这是 bug 还是配置文件的原因？

**Comment by KimigaiiWuyi** [comment]
看 #408 #437 #293
