### ISSUE TITLE
建议获取数据成功或失败都记录log信息

### ISSUE THREAD

**Issue by Yuri-YuzuChaN** [KimigaiiWuyi/GenshinUID#461]
主要是信息不对称
![image](https://user-images.githubusercontent.com/65105396/222101569-6a2c68ee-6541-40c4-9c34-ab548cb40104.png)
![image](https://user-images.githubusercontent.com/65105396/222101867-60cdb55e-666a-44a3-8fe3-5d15a5defa74.png)

**Comment by KimigaiiWuyi** [comment]
今晚修复
