### ISSUE TITLE
强制刷新     报错10791

### ISSUE THREAD

**Issue by zhaoZiQu** [KimigaiiWuyi/GenshinUID#469]
![image](https://user-images.githubusercontent.com/65691999/226228343-23018c02-0760-4121-8592-a3ce2f4ea080.png)
![image](https://user-images.githubusercontent.com/65691999/226228656-76dd67ce-6385-465c-8ef7-6ebb9196fe7e.png)
目前只有一个小伙伴出现，其他人正常可以使用
![image](https://user-images.githubusercontent.com/65691999/226228774-038d2ab5-d28c-4b93-ab38-1aabe5eb7e2c.png)
要怎么解决，求助

**Comment by KimigaiiWuyi** [comment]
更新至最新
~~另外报错没截全~~

**Comment by zhaoZiQu** [comment]
好的，
我先试试更新一下

**Comment by zhaoZiQu** [comment]
![image](https://user-images.githubusercontent.com/65691999/226233738-877bf149-d60c-4e69-98a2-0d65c8cd9178.png)
更新  不了

**Comment by zhaoZiQu** [comment]
![image](https://user-images.githubusercontent.com/65691999/226234371-b887a53d-69ab-493d-a4dc-9d0f53b4f185.png)
用git更新的成功了
也能使用了，十分感谢

**Comment by KimigaiiWuyi** [comment]
我个人建议直接使用命令`gs更新`即可，方便（~~也可以使用`gs重启`命令重启应用更新~~）
