### ISSUE TITLE
角色资料无法回复

### ISSUE THREAD

**Issue by chenshoyuan** [KimigaiiWuyi/GenshinUID#47]
qq群聊发送角色【角色名】无法获取角色信息

**Comment by KimigaiiWuyi** [comment]
角色/命座/武器相关api正在维护，暂时无法使用

**Comment by chenshoyuan** [comment]
为什么会这样





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KimigaiiWuyi/GenshinUID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 晚上9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 角色资料无法回复 (Issue #47)





 
Closed #47.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.&nbsp;

**Comment by KimigaiiWuyi** [comment]
> 为什么会这样
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" ***@***.***&gt;; 发送时间:&nbsp;2021年12月9日(星期四) 晚上9:21 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] 角色资料无法回复 (Issue #47) Closed #47. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.&nbsp;

更新完之后已经可以使用

**Comment by chenshoyuan** [comment]
部署完就这样了，有报错的全都弄了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月11日(星期六) 下午4:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] 角色资料无法回复 (Issue #47)





  
为什么会这样
 …
 ------------------ 原始邮件 ------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上9:21 @.&gt;; @.@.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] 角色资料无法回复 (Issue #47) Closed #47. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 
  
更新完之后已经可以使用
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chenshoyuan** [comment]
部署完就这样了，都不知道怎么回事




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月11日(星期六) 下午4:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] 角色资料无法回复 (Issue #47)





  
为什么会这样
 …
 ------------------ 原始邮件 ------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上9:21 @.&gt;; @.@.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] 角色资料无法回复 (Issue #47) Closed #47. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 
  
更新完之后已经可以使用
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KimigaiiWuyi** [comment]
> 部署完就这样了，都不知道怎么回事
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月11日(星期六) 下午4:26 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] 角色资料无法回复 (Issue #47) 为什么会这样 … ------------------ 原始邮件 ------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上9:21 @.&gt;; @.@.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] 角色资料无法回复 (Issue #47) Closed #47. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.  更新完之后已经可以使用 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

没有图看不到

**Comment by chenshoyuan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月11日(星期六) 下午4:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] 角色资料无法回复 (Issue #47)





  
部署完就这样了，都不知道怎么回事
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年12月11日(星期六) 下午4:26 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] 角色资料无法回复 (Issue #47) 为什么会这样 … ------------------ 原始邮件 ------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上9:21 @.&gt;; @.@.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] 角色资料无法回复 (Issue #47) Closed #47. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.  更新完之后已经可以使用 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
没有图看不到
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
