### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by sherlockHlb** [KimigaiiWuyi/GenshinUID#475]
C:\Users\Administrator\Desktop\NBBOOT\FistBot>nb plugin install git+https://github.com/KimigaiiWuyi/GenshinUID.git@nonebot2-beta1#egg=GenshinUID
使用虚拟环境: C:\Users\Administrator\Desktop\NBBOOT\FistBot\.venv\Scripts\python.exe
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting GenshinUID
  Cloning https://github.com/KimigaiiWuyi/GenshinUID.git (to revision nonebot2-beta1) to c:\users\administrator\appdata\local\temp\2\pip-install-n96gnc12\genshinuid_6c176fed0fc24c838b1d0189173f884e
  ERROR: Error [WinError 2] 系统找不到指定的文件。 while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

使用的$ nb plugin install git+https://github.com/KimigaiiWuyi/GenshinUID.git@nonebot2-beta1#egg=GenshinUID

GenshinUID指的是英文单词还是需要替换为游戏UID?

**Comment by KimigaiiWuyi** [comment]
你没有安装git，建议安装完git环境之后  按照[文档](http://docs.gsuid.gbots.work/)来操作
