### ISSUE TITLE
关于直接使用v4版本的问题

### ISSUE THREAD

**Issue by Esmge** [KimigaiiWuyi/GenshinUID#476]
我是今天直接按照教程装的v4版本。
![image](https://user-images.githubusercontent.com/41093896/228256914-ce930379-2c5f-44b8-983c-5cc598efcd32.png)
![image](https://user-images.githubusercontent.com/41093896/228257782-0a90aa98-d313-4769-ab0a-728a39af3a97.png)

core可以运行
![image](https://user-images.githubusercontent.com/41093896/228257041-a0b6051c-e731-4740-854a-2505444dbeb7.png)
gocq加载正常
![image](https://user-images.githubusercontent.com/41093896/228257222-ee1374fb-568b-49ff-a031-f5f6e709056d.png)
![image](https://user-images.githubusercontent.com/41093896/228258203-5725c6dd-f4cf-40a8-9a95-2e4cd5e8bd77.png)
nonebot2成功和gocq通信
然后，我现在需要做什么才能使GenshinUID可以使用呢？我不是很懂，希望大佬解惑

**Comment by KimigaiiWuyi** [comment]
你漏装了一个东西
https://docs.gsuid.gbots.work.minigg.cn/#/NoneBot2
需要在nb2内装`v4-nonebot2`分支插件，详见上面链接安装插件一步

**Comment by Esmge** [comment]
是的。现在已经好了。
