### ISSUE TITLE
cookies

### ISSUE THREAD

**Issue by chenshoyuan** [KimigaiiWuyi/GenshinUID#48]
cookies似乎有时间限制，当发送cookies给机器人群聊里已经绑定完米游社id和原神id，发送签到机器人提示签到失败，请检查Cookies是否失效。

**Comment by KimigaiiWuyi** [comment]
我没太听懂你什么意思，你是做了几个操作？
1、私聊Cookies给机器人
2、群聊绑定mysid/uid
3、群聊查询
4、群聊签到
哪些能成功哪些不能成功？

**Comment by chenshoyuan** [comment]
以上都不能成功




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KimigaiiWuyi/GenshinUID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月9日(星期四) 晚上6:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48)





 
我没太听懂你什么意思，你是做了几个操作？
 1、私聊Cookies给机器人
 2、群聊绑定mysid/uid
 3、群聊查询
 4、群聊签到
 哪些能成功哪些不能成功？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KimigaiiWuyi** [comment]
> 以上都不能成功
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" ***@***.***&gt;; 发送时间:&nbsp;2021年12月9日(星期四) 晚上6:13 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 我没太听懂你什么意思，你是做了几个操作？ 1、私聊Cookies给机器人 2、群聊绑定mysid/uid 3、群聊查询 4、群聊签到 哪些能成功哪些不能成功？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你CK都没成功添加，下面三个操作自然不可能成功啊

**Comment by chenshoyuan** [comment]
关键就是cookie绑定不成功



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月9日(星期四) 晚上6:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48)





  
以上都不能成功
 …
 ------------------ 原始邮件 ------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:13 @.&gt;; @.@.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 我没太听懂你什么意思，你是做了几个操作？ 1、私聊Cookies给机器人 2、群聊绑定mysid/uid 3、群聊查询 4、群聊签到 哪些能成功哪些不能成功？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
你CK都没成功添加，下面三个操作自然不可能成功啊
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KimigaiiWuyi** [comment]
> 关键就是cookie绑定不成功
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 以上都不能成功 … ------------------ 原始邮件 ------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:13 @.&gt;; @.@.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 我没太听懂你什么意思，你是做了几个操作？ 1、私聊Cookies给机器人 2、群聊绑定mysid/uid 3、群聊查询 4、群聊签到 哪些能成功哪些不能成功？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 你CK都没成功添加，下面三个操作自然不可能成功啊 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

这个你只能自己检查CK是否正确获取，我不可能看得到你自己的CK

**Comment by chenshoyuan** [comment]
是正确获取，就是获取了几遍，所有方法都试过了，还是无法绑定




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月9日(星期四) 晚上6:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48)





  
关键就是cookie绑定不成功
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 以上都不能成功 … ------------------ 原始邮件 ------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:13 @.&gt;; @.@.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 我没太听懂你什么意思，你是做了几个操作？ 1、私聊Cookies给机器人 2、群聊绑定mysid/uid 3、群聊查询 4、群聊签到 哪些能成功哪些不能成功？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 你CK都没成功添加，下面三个操作自然不可能成功啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
这个你只能自己检查CK是否正确获取，我不可能看得到你自己的CK
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KimigaiiWuyi** [comment]
> 是正确获取，就是获取了几遍，所有方法都试过了，还是无法绑定
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:17 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 关键就是cookie绑定不成功 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 以上都不能成功 … ------------------ 原始邮件 ------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:13 @.&gt;; @.@.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 我没太听懂你什么意思，你是做了几个操作？ 1、私聊Cookies给机器人 2、群聊绑定mysid/uid 3、群聊查询 4、群聊签到 哪些能成功哪些不能成功？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 你CK都没成功添加，下面三个操作自然不可能成功啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 这个你只能自己检查CK是否正确获取，我不可能看得到你自己的CK &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

校验没通过就是绑定不上啊，总不能校验失败的ck我也给你绑定上去……
依次检查以下：
这个Cookies 对应的米游社账号 有没有登陆过手机端米游社/有没有原神账号；
其次检查这个Cookies有没有account_id = xxxxxx ; Cookie_token = xxxxxx这两条参数

**Comment by chenshoyuan** [comment]
有，就是无法绑定，在群里签到，提示cookies失效



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月9日(星期四) 晚上6:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48)





  
是正确获取，就是获取了几遍，所有方法都试过了，还是无法绑定
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:17 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 关键就是cookie绑定不成功 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 以上都不能成功 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间:&nbsp;2021年12月9日(星期四) 晚上6:13 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 我没太听懂你什么意思，你是做了几个操作？ 1、私聊Cookies给机器人 2、群聊绑定mysid/uid 3、群聊查询 4、群聊签到 哪些能成功哪些不能成功？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 你CK都没成功添加，下面三个操作自然不可能成功啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 这个你只能自己检查CK是否正确获取，我不可能看得到你自己的CK — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
校验没通过就是绑定不上啊，总不能校验失败的ck我也给你绑定上去……
 依次检查以下：
 这个Cookies 对应的米游社账号 有没有登陆过手机端米游社/有没有原神账号；
 其次检查这个Cookies有没有account_id = xxxxxx ; Cookie_token = xxxxxx这两条参数
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KimigaiiWuyi** [comment]
> 有，就是无法绑定，在群里签到，提示cookies失效
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:20 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 是正确获取，就是获取了几遍，所有方法都试过了，还是无法绑定 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:17 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 关键就是cookie绑定不成功 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 以上都不能成功 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间:&nbsp;2021年12月9日(星期四) 晚上6:13 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 我没太听懂你什么意思，你是做了几个操作？ 1、私聊Cookies给机器人 2、群聊绑定mysid/uid 3、群聊查询 4、群聊签到 哪些能成功哪些不能成功？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 你CK都没成功添加，下面三个操作自然不可能成功啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 这个你只能自己检查CK是否正确获取，我不可能看得到你自己的CK — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 校验没通过就是绑定不上啊，总不能校验失败的ck我也给你绑定上去…… 依次检查以下： 这个Cookies 对应的米游社账号 有没有登陆过手机端米游社/有没有原神账号； 其次检查这个Cookies有没有account_id = xxxxxx ; Cookie_token = xxxxxx这两条参数 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你是没绑上，还是绑上了显示失效

**Comment by chenshoyuan** [comment]
绑定上显示失效了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月9日(星期四) 晚上6:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48)





  
有，就是无法绑定，在群里签到，提示cookies失效
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:20 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 是正确获取，就是获取了几遍，所有方法都试过了，还是无法绑定 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:17 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 关键就是cookie绑定不成功 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 以上都不能成功 … ------------------ 原始邮件 ------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:13 @.&gt;; @.@.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 我没太听懂你什么意思，你是做了几个操作？ 1、私聊Cookies给机器人 2、群聊绑定mysid/uid 3、群聊查询 4、群聊签到 哪些能成功哪些不能成功？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 你CK都没成功添加，下面三个操作自然不可能成功啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 这个你只能自己检查CK是否正确获取，我不可能看得到你自己的CK — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 校验没通过就是绑定不上啊，总不能校验失败的ck我也给你绑定上去…… 依次检查以下： 这个Cookies 对应的米游社账号 有没有登陆过手机端米游社/有没有原神账号； 其次检查这个Cookies有没有account_id = xxxxxx ; Cookie_token = xxxxxx这两条参数 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
你是没绑上，还是绑上了显示失效
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KimigaiiWuyi** [comment]
> 绑定上显示失效了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:23 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 有，就是无法绑定，在群里签到，提示cookies失效 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:20 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 是正确获取，就是获取了几遍，所有方法都试过了，还是无法绑定 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:17 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 关键就是cookie绑定不成功 … ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 以上都不能成功 … ------------------ 原始邮件 ------------------ 发件人: "KimigaiiWuyi/GenshinUID" @.&gt;; 发送时间: 2021年12月9日(星期四) 晚上6:13 @.&gt;; @.@.&gt;; 主题: Re: [KimigaiiWuyi/GenshinUID] cookies (Issue #48) 我没太听懂你什么意思，你是做了几个操作？ 1、私聊Cookies给机器人 2、群聊绑定mysid/uid 3、群聊查询 4、群聊签到 哪些能成功哪些不能成功？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 你CK都没成功添加，下面三个操作自然不可能成功啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 这个你只能自己检查CK是否正确获取，我不可能看得到你自己的CK — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 校验没通过就是绑定不上啊，总不能校验失败的ck我也给你绑定上去…… 依次检查以下： 这个Cookies 对应的米游社账号 有没有登陆过手机端米游社/有没有原神账号； 其次检查这个Cookies有没有account_id = xxxxxx ; Cookie_token = xxxxxx这两条参数 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 你是没绑上，还是绑上了显示失效 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你绑定上，为什么根目录会没有Id_data.db

**Comment by KimigaiiWuyi** [comment]
你再检查一下你的/hoshino主目录

**Comment by wudifeixue** [comment]
你这个情况我群友貌似遇见过，这个账号在米游社那边有没有打开过？
如果是从来没打开过米游社的账号，Cookie是会绑定失败的。
还有就是，使用“当前状态“的时候，如果没有在米游社打开过实时便笺，也是会出现错误，必须在米游社打开过一次。
关于查询也应该打开隐私设置。

作者这里的错误处理不太好，bot不会给出正确的反馈，导致用户会感到比较莫名其妙。
