### ISSUE TITLE
无法导入抽卡记录

### ISSUE THREAD

**Issue by LINK-URIBOH** [KimigaiiWuyi/GenshinUID#480]
![image](https://user-images.githubusercontent.com/34745010/229289464-e5d6d047-d7c0-4997-a17e-16103df1b3c8.png)
![image](https://user-images.githubusercontent.com/34745010/229289503-b49e4323-d769-4a52-8c39-6689bd74ee11.png)
按照教程配置了V4版本后，尝试导入抽卡记录时发现无法导入，其他功能可正常使用。发送的json文件符合UIGF标准且在之前的版本成功导入过。不知道是什么原因。

**Comment by KimigaiiWuyi** [comment]
使用`gs全部更新`确认两者均更新成功后，别忘了**到nb插件文件夹更新gsuid**
然后全部重启应该可以使用
