### ISSUE TITLE
疑似存在cq码注入漏洞

### ISSUE THREAD

**Issue by BalconyJH** [KimigaiiWuyi/GenshinUID#489]
![0e3d810108a13f21e1c44f0749e2ce0c](https://user-images.githubusercontent.com/73932916/230363940-8935768f-a6ab-4bd4-9cbe-74382a42fbe2.png)
![image](https://user-images.githubusercontent.com/73932916/230366023-849d1654-1238-47ae-95b5-6100422be20c.png)
经测试大部分cq码均可发出（戳一戳，图片，卡片等）
![{14FD195E-66A6-927D-7622-01F713EF5FEF}](https://user-images.githubusercontent.com/73932916/230366572-cdfbadf7-e8cf-4bc4-bb9f-071bd59b50d7.jpg)

**Comment by KimigaiiWuyi** [comment]
更新后应该解决
