### ISSUE TITLE
Docker安装v4时提示连接失败

### ISSUE THREAD

**Issue by DanLCJ** [KimigaiiWuyi/GenshinUID#491]
我是在docker中安装了虚拟机后再安装的nonebot2，按照https://docs.gsuid.gbots.work.minigg.cn/#/NoneBot2 装的v4，在`nb run`的时候报错提示连接拒绝如图，没有明白哪里有问题……安装之前测试echo是正常的
![image](https://user-images.githubusercontent.com/40844774/230833601-f38bea32-2975-4bb3-9eb6-2d74dfd94496.png)
![image](https://user-images.githubusercontent.com/40844774/230833798-9c9bf772-d56c-4641-962e-e7676ed112b9.png)

**Comment by KimigaiiWuyi** [comment]
可以尝试把core的host改为0.0.0.0

**Comment by DanLCJ** [comment]
> 可以尝试把core的host改为0.0.0.0

已解决，但是是分步修改的，先在GenshinUID里的`config.py`修改，之后下载完core再在core中修改的。非常感谢

顺便提一个小bug吧，下载资源的时候有两个图命名有问题（`{core}/data/GenshinUID/resource/chars` 的10000067/68.png，多了个0），下载完之后会警告资源异常（不影响正常使用）

**Comment by KimigaiiWuyi** [comment]
> > 可以尝试把core的host改为0.0.0.0
> 
> 已解决，但是是分步修改的，先在GenshinUID里的`config.py`修改，之后下载完core再在core中修改的。非常感谢
> 
> 顺便提一个小bug吧，下载资源的时候有两个图命名有问题（`{core}/data/GenshinUID/resource/chars` 的10000067/68.png，多了个0），下载完之后会警告资源异常（不影响正常使用）

其实可以尝试在`.env`文件下加入变量`gsuid_core_host`设置为`0.0.0.0`，而无需修改代码，要不然下次冲突就麻烦了

**Comment by DanLCJ** [comment]
> > > 可以尝试把core的host改为0.0.0.0
> > 
> > 
> > 已解决，但是是分步修改的，先在GenshinUID里的`config.py`修改，之后下载完core再在core中修改的。非常感谢
> > 顺便提一个小bug吧，下载资源的时候有两个图命名有问题（`{core}/data/GenshinUID/resource/chars` 的10000067/68.png，多了个0），下载完之后会警告资源异常（不影响正常使用）
> 
> 其实可以尝试在`.env`文件下加入变量`gsuid_core_host`设置为`0.0.0.0`，而无需修改代码，要不然下次冲突就麻烦了

明白了，现在已经把源码恢复原样之后添加了环境变量，目前一切正常，非常感谢
