### ISSUE TITLE
建议增加命令前缀，并且可配置

### ISSUE THREAD

**Issue by LiShenshun** [KimigaiiWuyi/GenshinUID#492]
由于GenshinUID很多命令会和我用的bot命令重叠，会导致群友一个命令触发两个响应，希望可以增加类似COMMAND_START的设定，让用户可以增加命令前缀，避免多重调用。
虽然这是NB1和2可以默认配置，但是我的NB2也不止装了1个插件，系统可以从插件层面解决。
如果能实现改配置的话，建在"gs帮助"默认不改，但是在帮助图片前会提醒“所有命令前需要加*”这样的思路如何？

**Comment by KimigaiiWuyi** [comment]
可以调整一下，在core层面添加一个`COMMAND_START`

**Comment by KimigaiiWuyi** [comment]
core已更新，用`gs全部更新`更新后，`gsuid_core/gsuid_core/config.json`下会有`command_start`选项，默认为`[]`，可参考的配置
```python
"command_start": ["原神"]
```
修改需要重启core

**Comment by LiShenshun** [comment]
可能运气比较衰，用`gs全部更新`更新卡住了，后来自己用git reset --hard来更新，重启后启动一半卡住，最后是先停nb2，再重启core，再开nb2搞定，`command_start`功能正常。
