### ISSUE TITLE
有计划做群内角色战力pvp的功能吗

### ISSUE THREAD

**Issue by yangzhan-1** [KimigaiiWuyi/GenshinUID#493]

**Comment by KimigaiiWuyi** [comment]
maybe

**Comment by KimigaiiWuyi** [comment]
基本已经搞完了
先`gs开启排名系统`，`gs重启`后即可使用
命令：`排名列表`、`角色排名雷神`等等（注意排名是全球排名而非群内）
有额外需求再开issuse吧
![1](https://github.com/KimigaiiWuyi/GenshinUID/assets/55526518/ddf56bea-afc4-45e3-8bff-d8c073e08784)
![2](https://github.com/KimigaiiWuyi/GenshinUID/assets/55526518/6bf01ac6-6876-4323-8e7e-f4682b192aa6)
