### ISSUE TITLE
导入抽卡记录失败

### ISSUE THREAD

**Issue by fsqhn** [KimigaiiWuyi/GenshinUID#495]
用的ntchat适配器，昨天刚搭的，GenshinUID跟核心都是昨天第一次下的，理论上不会是更新问题。
微信给机器人发json文件后提示在导入，后台看就显示报错。报错截图如下：
![微信图片_20230412151156](https://user-images.githubusercontent.com/13745793/231380900-505ee024-1774-401f-8ce4-4e552cccefeb.png)
![微信图片_20230412150841](https://user-images.githubusercontent.com/13745793/231380910-47b7d0a3-4b79-4f0c-9688-fb738582e56f.png)

因为我抽卡记录21年到现在的，比较长，中间部分解析结果就不截图了。
json文件时原神祈愿导出（Genshin-Wish-Export）这个软件出来的，符合UIGF标准，同样的文件给到qq的云崽那边也能正常导入。

报错结果拿去问chatgpt说是“这段报错代码表示在一个名为`send_import_gacha_info`的函数中调用了另外一个函数`import_gachalogs`，但是在后者的代码中尝试将一段字节数据按照GBK编码解码成字符串时出现了问题。具体来说，字节数据的第269个字节处出现了非法的多字节序列，导致无法正确解码。”

**Comment by KimigaiiWuyi** [comment]
是由于导入的抽卡记录是`gbk`编码的，暂时的解决方法是：转为`UTF-8`编码格式之后再重新导入；另外求一份原始抽卡记录文件，我做一下gbk的适配

**Comment by wuchangjun233** [comment]
题外话:ntchat估计后续也不会维护了
建议换成comwechat

**Comment by fsqhn** [comment]
[UIGF_100747992_202304111305(3)(1).zip](https://github.com/KimigaiiWuyi/GenshinUID/files/11208437/UIGF_100747992_202304111305.3.1.zip)

好的已上传，十分感谢。

**Comment by fsqhn** [comment]
> 题外话:ntchat估计后续也不会维护了 建议换成comwechat

想过用comwechat，但看安装手册那边说nonebot2整comwechat的话需要用onebot12适配器，然后还有什么扩展事件的插件要装，但现在还没写好。就想着先ntchat将就着先，等手册完备了我再另外租个服务器把整套东西扔云端上。

**Comment by wuchangjun233** [comment]
> > 题外话:ntchat估计后续也不会维护了 建议换成comwechat
> 
> 想过用comwechat，但看安装手册那边说nonebot2整comwechat的话需要用onebot12适配器，然后还有什么扩展事件的插件要装，但现在还没写好。就想着先ntchat将就着先，等手册完备了我再另外租个服务器把整套东西扔云端上。

gsuid已经适配完了，可以用了。

**Comment by fsqhn** [comment]
> 是由于导入的抽卡记录是`gbk`编码的，暂时的解决方法是：转为`UTF-8`编码格式之后再重新导入；另外求一份原始抽卡记录文件，我做一下gbk的适配

具体的转为`UTF-8`编码格式教程有么，我用记事本打开然后更改编码格式为`UTF-8`后另存为。结果再次导入还是显示报错。就很迷惑。

**Comment by KimigaiiWuyi** [comment]
请尝试修改`/GenshinUID/genshinuid_gachalog/export_and_import.py`内的第24行
https://github.com/KimigaiiWuyi/GenshinUID/blob/7808c2b06e3d89182dc64ada27d690815e9c88b3/GenshinUID/genshinuid_gachalog/export_and_import.py#L24
删除原先的`'gbk'`, 即修改为
```python
        history_data = json.loads(data_bytes.decode('gbk'))
```
后尝试导入看看是否有报错
