### ISSUE TITLE
YuanShen_User_Info已修复完毕

### ISSUE THREAD

**Issue by jiyemengmei** [KimigaiiWuyi/GenshinUID#5]
RT

**Comment by KimigaiiWuyi** [comment]
已更新新版本，请帮忙测试以下三个功能是否正常：
uidxxxxx
UIDxxxxx
uidxxxxx深渊12

**Comment by KimigaiiWuyi** [comment]
> 已更新新版本，请帮忙测试以下三个功能是否正常：
> uidxxxxx
> UIDxxxxx
> uidxxxxx深渊12

测试好正常之后，可以关闭issues~
