### ISSUE TITLE
米游币自动任务关闭无效

### ISSUE THREAD

**Issue by Esmge** [KimigaiiWuyi/GenshinUID#502]
绑定信息状态如下
![image](https://user-images.githubusercontent.com/41093896/231739531-a0a2f58c-55ac-4c5e-8df7-8329d5caa857.png)
但是仍会执行并推送
![image](https://user-images.githubusercontent.com/41093896/231739619-22fbaacc-3498-4f73-8720-1be929b518ef.png)

**Comment by KimigaiiWuyi** [comment]
已修复
