### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by wangyu1997** [KimigaiiWuyi/GenshinUID#505]
Bug
1. V12 self id获取不到
2. QQ GUILD 原图Reply获取不到
3. 重新扫码无法修改推送target

**Comment by KimigaiiWuyi** [comment]
全部更新一下，应该已修复
~~虽然没有实际测试~~

**Comment by wangyu1997** [comment]
comwechat bot_id获取失败

**Comment by wangyu1997** [comment]
绑定uid不判定bot id直接根据user id绑定到错误记录

**Comment by wangyu1997** [comment]
推送on改成group id依然私聊的问题

**Comment by wangyu1997** [comment]
新bug，发送url时，"/"会被转译，bug代码位于nb端client.py 244行， json encode会转译url
![image](https://user-images.githubusercontent.com/15991233/233823604-c64fb547-2e54-429e-b405-069644f65733.png)

**Comment by wangyu1997** [comment]
问题在与convert message

![image](https://user-images.githubusercontent.com/15991233/233824572-46a9c9a1-7214-4b16-8191-77858b5ea017.png)
 
建议把这个for循环删除 并没什么卵用

**Comment by KimigaiiWuyi** [comment]
> 问题在与convert message
> 
> ![image](https://user-images.githubusercontent.com/15991233/233824572-46a9c9a1-7214-4b16-8191-77858b5ea017.png)
> 
> 建议把这个for循环删除 并没什么卵用

这个是拿来给频道匹配startwith的`/`

**Comment by wangyu1997** [comment]
![image](https://user-images.githubusercontent.com/15991233/234620271-9296b81e-8d19-48b2-bc99-1a332a06c411.png)
wxid是中文的时候raw text会把中文的wxid合并到rawtext中导致触发失败
