### ISSUE TITLE
迪希亚非up池但算成了up角色

### ISSUE THREAD

**Issue by yangzhan-1** [KimigaiiWuyi/GenshinUID#507]
![XKP(2C8X0FHDP1Q24)2 ORY](https://user-images.githubusercontent.com/67181805/232706559-e64ea497-4c69-4f6d-ade9-68fa1c72de87.PNG)

**Comment by KimigaiiWuyi** [comment]
日后补一下狮女的准确up时间

**Comment by KimigaiiWuyi** [comment]
可否导出一份抽卡记录用于DEBUG

**Comment by KimigaiiWuyi** [comment]
~~没有测试，但是~~ 应该已修复
