### ISSUE TITLE
三命雷神，草神满命使用命令雷神换草神圣遗物后不止圣遗物替换了，命座也替换了（我雷神三命查出来满命）

### ISSUE THREAD

**Issue by yangzhan-1** [KimigaiiWuyi/GenshinUID#508]
![(XZ3I3E(DX{}}PD@CI2EG 0](https://user-images.githubusercontent.com/67181805/232708041-bf4575b7-25d9-4fff-8ae5-0f16fbc0ed8f.PNG)

**Comment by KimigaiiWuyi** [comment]
这个目前确实是这样，可以通过`查询三命雷神换草神圣遗物`方式规避，稍微有点反直觉，后期优化一下

**Comment by KimigaiiWuyi** [comment]
已修复
