### ISSUE TITLE
查询深渊人物等级数据显示错误

### ISSUE THREAD

**Issue by wudifeixue** [KimigaiiWuyi/GenshinUID#51]
目前账号已经绑定Cookie，使用的是当前最新版Hoshino插件。
数据错误在我的班尼特在通关深渊的时候记录是69级，结果在使用本插件会得到我目前队伍的最新等级(75)。
同样的错误在查询上期深渊也可以重现。
其他挑战回顾数据例如出战次数，最强一击，元素战技释放数，元素爆发次数等均无错误。

附图：
![image](https://user-images.githubusercontent.com/7316929/145496747-f33d0718-5064-45b2-acfb-7ccb8beea469.png)
![image](https://user-images.githubusercontent.com/7316929/145496837-b02e9b0d-bfb8-476c-8db0-8ec3b6c9dd5e.png)

**Comment by KimigaiiWuyi** [comment]
这个是自动调用的当前的人物，正常返回信息其实没有命座和好感相关的

**Comment by wudifeixue** [comment]
诶，哪怕是用米油社的cookie也得不到数据么？我看貌似已经在 #36 的时候有提过现在优先用cookie查了

**Comment by KimigaiiWuyi** [comment]
> 诶，哪怕是用米油社的cookie也得不到数据么？我看貌似已经在 #36 的时候有提过现在优先用cookie查了

用自己的ck也得不到数据，用自己的ck只能多一个 三间的出战列表，得不到好感/命座，等级是能得到的

**Comment by wudifeixue** [comment]
原来如此，看来这个问题是可以靠Cookie查询纠正的，就是回报率有些差
