### ISSUE TITLE
能否添加单独插件响应头

### ISSUE THREAD

**Issue by YouYouLip** [KimigaiiWuyi/GenshinUID#513]
如题，因为该插件的绑定uid的指令和小派蒙冲突，（想小派蒙和早柚一起用）所以添加一个单独响应早柚插件的命令头
我觉得在某种意义上也算是一个有用的（？

**Comment by KimigaiiWuyi** [comment]
如果你使用的是`v4`分支，即`gsuid_core`，可以在gsuid_core的配置文件`gsuid_core/config.json`中修改`command_start`以指定所有通过`gsuid_core`插件的命令头

**Comment by YouYouLip** [comment]
> 如果你使用的是`v4`分支，即`gsuid_core`，可以在gsuid_core的配置文件`gsuid_core/config.json`中修改`command_start`以指定所有通过`gsuid_core`插件的命令头
感谢 问题解决了

**Comment by YouYouLip** [comment]
> 如果你使用的是`v4`分支，即`gsuid_core`，可以在gsuid_core的配置文件`gsuid_core/config.json`中修改`command_start`以指定所有通过`gsuid_core`插件的命令头

问题解决了 感谢
