### ISSUE TITLE
更新v4以后群友发送的消息里有正则符号bot就会回复正在进行[正则测试]

### ISSUE THREAD

**Issue by 2085673514** [KimigaiiWuyi/GenshinUID#520]
大概就像这样：

群友 18:19:34
1+1

bot 18:19:35
正在进行[正则测试]

bot 18:19:37
[正则测试]校验成功！

**Comment by KimigaiiWuyi** [comment]
用`gs全部更新`更新到最新应该没有问题，你可能昨晚在我两次更新中间 更新了一下（）
