### ISSUE TITLE
gs更新报错，报错原因not enough memory for initialization

### ISSUE THREAD

**Issue by RSRH-Rs** [KimigaiiWuyi/GenshinUID#525]
![3%KGHSV`}YF@VN~L7((`45V](https://user-images.githubusercontent.com/54684882/234470184-29992424-260b-4799-8b34-cedee999e1dd.png)

用gs更新的时候更新不了，强行强制更新也是报一样的错。内存是足够的

**Comment by RSRH-Rs** [comment]
问过群友，目测是因为2G的内存装了个win10的系统，换个系统应该就好了。😊

**Comment by KimigaiiWuyi** [comment]
2G也不应该报这个啊，我1G都不会报
你clone的时候有添加`--depth=1`和`--single-branch`吗

**Comment by RSRH-Rs** [comment]
> 2G也不应该报这个啊，我1G都不会报 你clone的时候有添加`--depth=1`和`--single-branch`吗

emm，没用clone，就是用的自带的更新，git clone的话是可以clone的

**Comment by RSRH-Rs** [comment]
重启了一下用的强制更新，更新上了
