### ISSUE TITLE
部分插件未加载

### ISSUE THREAD

**Issue by jugongchang** [KimigaiiWuyi/GenshinUID#527]
刚刚更新以后mr和gs帮助无反应，core启动时没有这些关键词触发器加载的提示，有一条报错“[ERROR] gsuid_core.server | No module named 'urllib3'”不知是否有关

**Comment by KimigaiiWuyi** [comment]
手动进入`gsuid_core`目录，执行`poetry run pip install urllib3`

**Comment by jugongchang** [comment]
解决了，谢谢无疑佬
