### ISSUE TITLE
原图功能无法使用

### ISSUE THREAD

**Issue by RSRH-Rs** [KimigaiiWuyi/GenshinUID#528]
开了随机图之后查看面板回复原图，后台显示触发了但是没有报错也不发消息。
![image](https://user-images.githubusercontent.com/54684882/234693656-4f51c083-729e-48b6-9d69-0b06046fee5a.png)
![image](https://user-images.githubusercontent.com/54684882/234693714-624a287c-37ab-4e26-93cf-f445325d4d35.png)

**Comment by KimigaiiWuyi** [comment]
你应该回复 自己发的`查询xx`这句话

**Comment by RSRH-Rs** [comment]
> 你应该回复 自己发的`查询xx`这句话

好的，谢谢wuyi佬
