### ISSUE TITLE
linux服务器core启动uvicorn.server报错，code99

### ISSUE THREAD

**Issue by RSRH-Rs** [KimigaiiWuyi/GenshinUID#529]
![image](https://user-images.githubusercontent.com/54684882/235011395-467d8cf0-9ea0-4b65-bd1b-b35319ae29df.png)
其他全部成功加载了但是到uvicorn这一步就报错了，linux服务器ubuntu20.04

**Comment by KimigaiiWuyi** [comment]
如果有用虚拟机或者等其他类似服务，需要把`config.json`里的host改成`0.0.0.0`

**Comment by RSRH-Rs** [comment]
> 如果有用虚拟机或者等其他类似服务，需要把`config.json`里的host改成`0.0.0.0`

好的，已解决，谢谢wuyi佬
