### ISSUE TITLE
希望增加限制每个人查询次数的功能。

### ISSUE THREAD

**Issue by li704644993** [KimigaiiWuyi/GenshinUID#53]
最好能根据权限设置不同人可查询uid次数，比如机器人管理员无限制，群主100次，管理员50次之类的。不然有些人进群只为查询，从不冒泡。
不好实现的话，就所有人限制10次也行。
感谢大佬。

**Comment by KimigaiiWuyi** [comment]
你限制10次也没有解决他们进群只为查询的目的啊……一天能查个五次已经算多了

**Comment by lgc2333** [comment]
可以用配置文件
我有时间写



在 2021-12-13 18:01:56，"li704644993" ***@***.***> 写道：

最好能根据权限设置不同人可查询uid次数，比如机器人管理员无限制，群主100次，管理员50次之类的。不然有些人进群只为查询，从不冒泡。
不好实现的话，就所有人限制10次也行。
感谢大佬。

**Comment by KimigaiiWuyi** [comment]
> 可以用配置文件 我有时间写 在 2021-12-13 18:01:56，"li704644993" ***@***.***> 写道： 最好能根据权限设置不同人可查询uid次数，比如机器人管理员无限制，群主100次，管理员50次之类的。不然有些人进群只为查询，从不冒泡。 不好实现的话，就所有人限制10次也行。 感谢大佬。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

问题是没有意义啊……
而且他应该用的hoshino，你现在用的nb2吧

**Comment by lgc2333** [comment]
> > 可以用配置文件 我有时间写 在 2021-12-13 18:01:56，"li704644993" _**@**_.***> 写道： 最好能根据权限设置不同人可查询uid次数，比如机器人管理员无限制，群主100次，管理员50次之类的。不然有些人进群只为查询，从不冒泡。 不好实现的话，就所有人限制10次也行。 感谢大佬。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 问题是没有意义啊…… 而且他应该用的hoshino，你现在用的nb2吧

az

**Comment by KimigaiiWuyi** [comment]
> 我这里主要是好多人进群一天查10几20次，感觉在外面接了私活一样。也不聊天，就只查询。

为何不直接t了，反正不聊天，t起来也没有什么心理负担吧

**Comment by KimigaiiWuyi** [comment]
> > > 可以用配置文件 我有时间写 在 2021-12-13 18:01:56，"li704644993" _**@**_.***> 写道： 最好能根据权限设置不同人可查询uid次数，比如机器人管理员无限制，群主100次，管理员50次之类的。不然有些人进群只为查询，从不冒泡。 不好实现的话，就所有人限制10次也行。 感谢大佬。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 问题是没有意义啊…… 而且他应该用的hoshino，你现在用的nb2吧
> 
> az 如果我没记错，hoshino也有配置文件吧

主要我是觉得 默认这么设置的话，正常的群用起来会很难受

**Comment by li704644993** [comment]
> 

好的，那我close了～感谢解惑
