### ISSUE TITLE
帮我看看

### ISSUE THREAD

**Issue by Xiao-yux** [KimigaiiWuyi/GenshinUID#530]
![image](https://user-images.githubusercontent.com/79674967/235049945-9ac45173-227b-4471-b36a-329071ccc8ef.png)
加了原神插件后，这个塔罗牌插件发不出消息了

**Comment by KimigaiiWuyi** [comment]
你应该看看塔罗牌插件是否成功加载，gsuid不会阻断任何其他插件的信息
