### ISSUE TITLE
gscore启动报错

### ISSUE THREAD

**Issue by fsqhn** [KimigaiiWuyi/GenshinUID#531]
报错代码如下，是不是我搞了啥操作导致出问题了  
File "D:\nonebot\gsuid_core\gsuid_core\core.py", line 126, in <module>
    main()
  File "D:\nonebot\gsuid_core\gsuid_core\core.py", line 98, in main
    site.mount_app(app)
  File "C:\Users\CDYH02\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-HscqR8Pf-py3.10\lib\site-packages\fastapi_amis_admin\admin\admin.py", line 1447, in mount_app
    self.register_router()
  File "C:\Users\CDYH02\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-HscqR8Pf-py3.10\lib\site-packages\fastapi_amis_admin\admin\admin.py", line 1342, in register_router
    self._register_admin_router_all()
  File "C:\Users\CDYH02\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-HscqR8Pf-py3.10\lib\site-packages\fastapi_amis_admin\admin\admin.py", line 1334, in _register_admin_router_all
    admin.register_router()
  File "C:\Users\CDYH02\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-HscqR8Pf-py3.10\lib\site-packages\fastapi_amis_admin\admin\admin.py", line 1082, in register_router
    self.register_crud()
  File "C:\Users\CDYH02\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-HscqR8Pf-py3.10\lib\site-packages\fastapi_amis_admin\crud\base.py", line 81, in register_crud
    self.schema_list = schema_list or self._create_schema_list()
  File "C:\Users\CDYH02\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-HscqR8Pf-py3.10\lib\site-packages\fastapi_amis_admin\crud\_sqlmodel.py", line 269, in _create_schema_list
    [self.parser.get_modelfield(sqlfield, clone=True) for sqlfield in self._select_entities.values()],
  File "C:\Users\CDYH02\AppData\Local\Programs\Python\Python310\lib\functools.py", line 981, in __get__
    val = self.func(instance)
  File "C:\Users\CDYH02\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-HscqR8Pf-py3.10\lib\site-packages\fastapi_amis_admin\crud\_sqlmodel.py", line 118, in _select_entities
    return {self.parser.get_alias(insfield): insfield for insfield in self.fields}
  File "C:\Users\CDYH02\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-HscqR8Pf-py3.10\lib\site-packages\fastapi_amis_admin\crud\_sqlmodel.py", line 118, in <dictcomp>
    return {self.parser.get_alias(insfield): insfield for insfield in self.fields}
  File "C:\Users\CDYH02\AppData\Local\pypoetry\Cache\virtualenvs\gsuid-core-HscqR8Pf-py3.10\lib\site-packages\fastapi_amis_admin\crud\parser.py", line 96, in get_alias
    if field.table.name == self.default_model.__tablename__
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by KimigaiiWuyi** [comment]
同时更新`gsuid_core`和插件，确保两边都是最新的
建议更新使用`gs全部更新`命令

**Comment by fsqhn** [comment]
> 同时更新`gsuid_core`和插件，确保两边都是最新的 建议更新使用`gs全部更新`命令

现在是感觉连不上gsuid_core。04-28 12:41:41 [SUCCESS] nonebot | OneBot V12 wxid_aebwufp5g0ne22 | [message.private]: Message 4681475490548303523 from wxid_c3bb9wcwnpft21 'gs全部更新'
04-28 12:41:41 [INFO] GenshinUID | Bot_ID: NoneBot2连接至[gsuid-core]: ws://localhost:8765/ws/NoneBot2...
04-28 12:41:41 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
04-28 12:41:41 [INFO] GenshinUID | Bot_ID: NoneBot2连接至[gsuid-core]: ws://localhost:8765/ws/NoneBot2...
04-28 12:41:45 [ERROR] GenshinUID | Core服务器连接失败...请稍后使用[启动core]命令启动...
04-28 12:41:45 [ERROR] GenshinUID | Core服务器连接失败...请稍后使用[启动core]命令启动...
04-28 12:41:45 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
04-28 12:41:54 [SUCCESS] nonebot | OneBot V12 wxid_aebwufp5g0ne22 | [message.private]: Message 3199599339805725585 from wxid_c3bb9wcwnpft21 'gs全部更新'
04-28 12:41:54 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
04-28 12:41:54 [INFO] GenshinUID | Bot_ID: NoneBot2连接至[gsuid-core]: ws://localhost:8765/ws/NoneBot2...
04-28 12:41:59 [ERROR] GenshinUID | Core服务器连接失败...请稍后使用[启动core]命令启动...
04-28 12:41:59 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
然后就恶性循环了，要怎么搞？删了重装？

**Comment by KimigaiiWuyi** [comment]
> > 同时更新`gsuid_core`和插件，确保两边都是最新的 建议更新使用`gs全部更新`命令
> 
> 现在是感觉连不上gsuid_core。04-28 12:41:41 [SUCCESS] nonebot | OneBot V12 wxid_aebwufp5g0ne22 | [message.private]: Message 4681475490548303523 from wxid_c3bb9wcwnpft21 'gs全部更新' 04-28 12:41:41 [INFO] GenshinUID | Bot_ID: NoneBot2连接至[gsuid-core]: ws://localhost:8765/ws/NoneBot2... 04-28 12:41:41 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID) 04-28 12:41:41 [INFO] GenshinUID | Bot_ID: NoneBot2连接至[gsuid-core]: ws://localhost:8765/ws/NoneBot2... 04-28 12:41:45 [ERROR] GenshinUID | Core服务器连接失败...请稍后使用[启动core]命令启动... 04-28 12:41:45 [ERROR] GenshinUID | Core服务器连接失败...请稍后使用[启动core]命令启动... 04-28 12:41:45 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete 04-28 12:41:54 [SUCCESS] nonebot | OneBot V12 wxid_aebwufp5g0ne22 | [message.private]: Message 3199599339805725585 from wxid_c3bb9wcwnpft21 'gs全部更新' 04-28 12:41:54 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID) 04-28 12:41:54 [INFO] GenshinUID | Bot_ID: NoneBot2连接至[gsuid-core]: ws://localhost:8765/ws/NoneBot2... 04-28 12:41:59 [ERROR] GenshinUID | Core服务器连接失败...请稍后使用[启动core]命令启动... 04-28 12:41:59 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete 然后就恶性循环了，要怎么搞？删了重装？

手动git pull更新啊，没事删了重装干啥

**Comment by fsqhn** [comment]
> 手动git pull更新啊，没事删了重装干啥

在gsuid_core执行git pull，显示Already up to date.  但问题依旧

**Comment by KimigaiiWuyi** [comment]
其内部plugins/GenshinUID也是最新的吗，截个图看看

**Comment by fsqhn** [comment]
在D:\nonebot\gsuid_core\gsuid_core\plugins\GenshinUID 下执行git pull后能正常启动core了。但是好像只对深渊指令有反应，gs帮助和签到和gs全部更新都没反应。
04-28 13:12:56 [SUCCESS] nonebot | OneBot V12 wxid_aebwufp5g0ne22 | [message.private]: Message 7345587259259516485 from wxid_c3bb9wcwnpft21 'gs全部更新'
04-28 13:12:56 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
04-28 13:12:56 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot_v12
04-28 13:12:56 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
04-28 13:12:56 [INFO] gsuid_core.handler | [Raw] raw_text=gs全部更新, image=None, at=None, image_list=None, at_list=[], is_tome=True, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot_v12, bot_self_id=wxid_aebwufp5g0ne22, msg_id=7345587259259516485, user_type=direct, group_id=None, user_id=wxid_c3bb9wcwnpft21, user_pm=1, content=[Message(type='text', data='gs全部更新')],
04-28 13:12:59 [SUCCESS] nonebot | OneBot V12 wxid_aebwufp5g0ne22 | [message.private]: Message 7348273048439438656 from wxid_c3bb9wcwnpft21 'gs帮助'
04-28 13:12:59 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
04-28 13:12:59 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot_v12
04-28 13:12:59 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
04-28 13:12:59 [INFO] gsuid_core.handler | [Raw] raw_text=gs帮助, image=None, at=None, image_list=None, at_list=[], is_tome=True, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot_v12, bot_self_id=wxid_aebwufp5g0ne22, msg_id=7348273048439438656, user_type=direct, group_id=None, user_id=wxid_c3bb9wcwnpft21, user_pm=1, content=[Message(type='text', data='gs帮 助')],
04-28 13:13:02 [SUCCESS] nonebot | OneBot V12 wxid_aebwufp5g0ne22 | [message.private]: Message 5542846137032616359 from wxid_c3bb9wcwnpft21 '刻晴攻略'
04-28 13:13:02 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
04-28 13:13:02 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot_v12
04-28 13:13:02 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
04-28 13:13:02 [INFO] gsuid_core.handler | [Raw] raw_text=刻晴攻略, image=None, at=None, image_list=None, at_list=[], is_tome=True, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot_v12, bot_self_id=wxid_aebwufp5g0ne22, msg_id=5542846137032616359, user_type=direct, group_id=None, user_id=wxid_c3bb9wcwnpft21, user_pm=1, content=[Message(type='text', data='刻 晴攻略')],
04-28 13:13:06 [SUCCESS] nonebot | OneBot V12 wxid_aebwufp5g0ne22 | [message.private]: Message 2572019866442329022 from wxid_c3bb9wcwnpft21 '签到'
04-28 13:13:06 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
04-28 13:13:06 [INFO] GenshinUID | 【发送】[gsuid-core]: onebot_v12
04-28 13:13:06 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
04-28 13:13:06 [INFO] gsuid_core.handler | [Raw] raw_text=签到, image=None, at=None, image_list=None, at_list=[], is_tome=True, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot_v12, bot_self_id=wxid_aebwufp5g0ne22, msg_id=2572019866442329022, user_type=direct, group_id=None, user_id=wxid_c3bb9wcwnpft21, user_pm=1, content=[Message(type='text', data='签到')],

**Comment by KimigaiiWuyi** [comment]
全部更新后请重启bot看看

**Comment by fsqhn** [comment]
更新后重启了还是这样，试了下，公告，查询角色，查委托啥的都能用，
但是签到，帮助，xx攻略，哪里有xx之类的功能就没反应。
启动core的代码里夹杂了两条如下报错
04-28 13:25:02 [ERROR] gsuid_core.server | No module named 'urllib3'
04-28 13:25:02 [WARNING] gsuid_core.server | 插件GenshinUID加载失败

**Comment by KimigaiiWuyi** [comment]
> 更新后重启了还是这样，试了下，公告，查询角色，查委托啥的都能用， 但是签到，帮助，xx攻略，哪里有xx之类的功能就没反应。 启动core的代码里夹杂了两条如下报错 04-28 13:25:02 [ERROR] gsuid_core.server | No module named 'urllib3' 04-28 13:25:02 [WARNING] gsuid_core.server | 插件GenshinUID加载失败

噢，cd到gsuid_core文件夹内输入`poetry run pip install urllib3`

**Comment by fsqhn** [comment]
感谢，可以了。试了下正常了。十分感谢！
