### ISSUE TITLE
哪里有甜甜花 断连

### ISSUE THREAD

**Issue by zrwkkd** [KimigaiiWuyi/GenshinUID#532]
onebotv12 python3.11.3 comwechat-client v0.0.7
测了几次，当问到哪里有甜甜花的时候就会断开连接，过了会回重新连接，然后会显示networkerror卡着,需要ctrl+c
05-01 21:46:49 [INFO] gsuid_core.handler | [Trigger] 消息 「哪里有甜甜花」 触发 「prefix」 类型触发器, 关键词: 「哪里有 」
05-01 21:46:49 [INFO] gsuid_core.handler | [Command] command=哪里有, text=甜甜花
05-01 21:46:49 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
05-01 21:46:49 [INFO] GenshinUID | [查找资源点]正在执行...当前地图为提瓦特
05-01 21:46:49 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
05-01 21:46:49 [INFO] GenshinUID | 本地已有提瓦特_甜甜花的资源点,直接发送...
05-01 21:46:49 [INFO] gsuid_core.bot | [发送消息to] onebot_v12 - group - 344031@chatroom
05-01 21:46:50 [INFO] GenshinUID | 【接收】[gsuid-core]: onebot_v12 - group - 344031@chatroom
05-01 21:47:01 [WARNING] nonebot | OneBot V12 | WebSocket for Bot wxid_jn356 closed by peer
05-01 21:47:01 [INFO] logging | connection closed
05-01 21:47:17 [INFO] logging | ('127.0.0.1', 52351) - "WebSocket /onebot/v12/ws/" [accepted]
05-01 21:47:17 [INFO] logging | connection open
05-01 21:47:21 [ERROR] GenshinUID | NetWorkError(message='WebSocket call api upload_file timeout')
05-01 21:47:51 [INFO] nonebot | OneBot V12 | Bot wxid_jn356 connected

跟python版本有关？问到有关石珀本地未缓存的，渲染成功并发送了

05-01 22:11:42 [INFO] gsuid_core.handler | [Trigger] 消息 「哪里有石珀」 触发 「prefix」 类型触发器, 关键词: 「哪里有」
05-01 22:11:42 [INFO] gsuid_core.handler | [Command] command=哪里有, text=石珀
05-01 22:11:42 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
05-01 22:11:42 [INFO] GenshinUID | [查找资源点]正在执行...当前地图为提瓦特
05-01 22:11:42 [INFO] GenshinUID | 【接收】[gsuid-core]: NoneBot2 - None - None
05-01 22:11:42 [INFO] GenshinUID | 本地未缓存,正在渲染...
05-01 22:11:47 [INFO] gsuid_core.bot | [发送消息to] onebot_v12 - direct - ui
05-01 22:11:47 [INFO] GenshinUID | 【接收】[gsuid-core]: onebot_v12 - direct - ui

**Comment by KimigaiiWuyi** [comment]
comwechat那边设置了超过2MB的图不能发送好像，直接就断了，具体查看comwechat那边

**Comment by zrwkkd** [comment]
> comwechat那边设置了超过2MB的图不能发送好像，直接就断了，具体查看comwechat那边

好的 感谢
