### ISSUE TITLE
部分功能无法使用

### ISSUE THREAD

**Issue by yxkisane** [KimigaiiWuyi/GenshinUID#533]
扫码登陆，gs重启之类的功能没有反应
![1](https://user-images.githubusercontent.com/93441183/235520677-1350aeb5-a838-4677-998b-6a8a1a83f44d.png)
![2](https://user-images.githubusercontent.com/93441183/235520682-0a877de3-c9da-475a-b1a3-abd62417a61b.png)

**Comment by KimigaiiWuyi** [comment]
看看core端的log

**Comment by dzdsjserver** [comment]
> 

![Uploading IMG_20230502_125305.jpg…]()

**Comment by youguangyixing** [comment]
> 看看core端的log

![IMG_20230502_125305](https://user-images.githubusercontent.com/13484017/235582939-fb6c24b8-27de-4dd7-9d6f-e7623fadfcae.jpg)

**Comment by KimigaiiWuyi** [comment]
没有设定nb端的su（超级管理员用户），请查看nb的文档 nb2.baka.icu
在.env里设置`SUPERUSERS`

**Comment by youguangyixing** [comment]
> 没有设定nb端的su（超级管理员用户），请查看nb的文档 nb2.baka.icu 在.env里设置`SUPERUSERS`

gs重启之类的可以用了，但是扫码登录，添加cookie都没反应

**Comment by KimigaiiWuyi** [comment]
> > 没有设定nb端的su（超级管理员用户），请查看nb的文档 nb2.baka.icu 在.env里设置`SUPERUSERS`
> 
> gs重启之类的可以用了，但是扫码登录，添加cookie都没反应

重新更新一下两边 包括gsuid_core和里面的插件GenshinUID，进入文件夹内输入命令`git pull`，重启后观察是否正常

**Comment by yxkisane** [comment]
> > > 没有设定nb端的su（超级管理员用户），请查看nb的文档 nb2.baka.icu 在.env里设置`SUPERUSERS`
> > 
> > 
> > gs重启之类的可以用了，但是扫码登录，添加cookie都没反应
> 
> 重新更新一下两边 包括gsuid_core和里面的插件GenshinUID，进入文件夹内输入命令`git pull`，重启后观察是否正常

全部显示Already up-to-date.

**Comment by yxkisane** [comment]
> > > 没有设定nb端的su（超级管理员用户），请查看nb的文档 nb2.baka.icu 在.env里设置`SUPERUSERS`
> > 
> > 
> > gs重启之类的可以用了，但是扫码登录，添加cookie都没反应
> 
> 重新更新一下两边 包括gsuid_core和里面的插件GenshinUID，进入文件夹内输入命令`git pull`，重启后观察是否正常

他现在有反应，但是不多直接卡住了，
![6WJH9EVIV8FCVQC P)6_KE0](https://user-images.githubusercontent.com/93441183/235633428-7dbc95b3-beeb-4452-b14e-a1c6d0d755bc.png)

**Comment by yxkisane** [comment]
> > > > 没有设定nb端的su（超级管理员用户），请查看nb的文档 nb2.baka.icu 在.env里设置`SUPERUSERS`
> > > 
> > > 
> > > gs重启之类的可以用了，但是扫码登录，添加cookie都没反应
> > 
> > 
> > 重新更新一下两边 包括gsuid_core和里面的插件GenshinUID，进入文件夹内输入命令`git pull`，重启后观察是否正常
> 
> 他现在有反应，但是不多直接卡住了， ![6WJH9EVIV8FCVQC P)6_KE0](https://user-images.githubusercontent.com/93441183/235633428-7dbc95b3-beeb-4452-b14e-a1c6d0d755bc.png)
![H`M4DD46SE9@L~ 9`JKF JV](https://user-images.githubusercontent.com/93441183/235639733-7628bc54-3cd3-446d-b365-8973d1ba214c.png)

**Comment by yxkisane** [comment]
> > > > > 没有设定nb端的su（超级管理员用户），请查看nb的文档 nb2.baka.icu 在.env里设置`SUPERUSERS`
> > > > 
> > > > 
> > > > gs重启之类的可以用了，但是扫码登录，添加cookie都没反应
> > > 
> > > 
> > > 重新更新一下两边 包括gsuid_core和里面的插件GenshinUID，进入文件夹内输入命令`git pull`，重启后观察是否正常
> > 
> > 
> > 他现在有反应，但是不多直接卡住了， ![6WJH9EVIV8FCVQC P)6_KE0](https://user-images.githubusercontent.com/93441183/235633428-7dbc95b3-beeb-4452-b14e-a1c6d0d755bc.png)
> > ![HM4DD46SE9@L~ 9JKF JV](https://user-images.githubusercontent.com/93441183/235639733-7628bc54-3cd3-446d-b365-8973d1ba214c.png)

![JGC2_W@PNP$IYJ0D1NW4QJ5](https://user-images.githubusercontent.com/93441183/235640520-9eea4ac0-b3e2-4d4c-bd3f-46aa6e617baa.png)

**Comment by KimigaiiWuyi** [comment]
开了梯子之类的网络原因

**Comment by yxkisane** [comment]
> 开了梯子之类的网络原因

我什么都没开，那应该是服务器的问题，我去找服务商要求更换机器

**Comment by KimigaiiWuyi** [comment]
> > 开了梯子之类的网络原因
> 
> 我什么都没开，那应该是服务器的问题，我去找服务商要求更换机器

哪家机子啊，也可以修改代码关闭ssl校验 应该就正常了

**Comment by yxkisane** [comment]
> > > 开了梯子之类的网络原因
> > 
> > 
> > 我什么都没开，那应该是服务器的问题，我去找服务商要求更换机器
> 
> 哪家机子啊，也可以修改代码关闭ssl校验 应该就正常了

n7yun的

**Comment by yxkisane** [comment]
> > > 开了梯子之类的网络原因
> > 
> > 
> > 我什么都没开，那应该是服务器的问题，我去找服务商要求更换机器
> 
> 哪家机子啊，也可以修改代码关闭ssl校验 应该就正常了

问一下大佬怎么关闭ssl校验

**Comment by KimigaiiWuyi** [comment]
> > > > 开了梯子之类的网络原因
> > > 
> > > 
> > > 我什么都没开，那应该是服务器的问题，我去找服务商要求更换机器
> > 
> > 
> > 哪家机子啊，也可以修改代码关闭ssl校验 应该就正常了
> 
> 问一下大佬怎么关闭ssl校验

更新一下core那边，然后最新版提供了一个开关，打开core后进入网页控制台，进入修改设定，关闭ssl校验的按钮，然后**确认提交**，重启core，检查是否生效

**Comment by yxkisane** [comment]
> > > > > 开了梯子之类的网络原因
> > > > 
> > > > 
> > > > 我什么都没开，那应该是服务器的问题，我去找服务商要求更换机器
> > > 
> > > 
> > > 哪家机子啊，也可以修改代码关闭ssl校验 应该就正常了
> > 
> > 
> > 问一下大佬怎么关闭ssl校验
> 
> 更新一下core那边，然后最新版提供了一个开关，打开core后进入网页控制台，进入修改设定，关闭ssl校验的按钮，然后**确认提交**，重启core，检查是否生效

解决了，谢谢无疑佬
