### ISSUE TITLE
05-03 09:08:23 [ERROR] GenshinUID | Core服务器连接失败...请稍后使用[启动core]命令启动...

### ISSUE THREAD

**Issue by zhaoZiQu** [KimigaiiWuyi/GenshinUID#534]
![image](https://user-images.githubusercontent.com/65691999/235816362-ddb19735-3df8-4808-ad98-3ca485b8b6cd.png)
![image](https://user-images.githubusercontent.com/65691999/235816424-c990f3ff-ad20-41ff-83b5-6572a91c83e5.png)
![image](https://user-images.githubusercontent.com/65691999/235816482-53398585-446c-4787-b428-0ae0cd0c8a61.png)
命令触发不了

**Comment by zhaoZiQu** [comment]
![image](https://user-images.githubusercontent.com/65691999/235817115-dd3f2968-f75a-48b1-ae7a-c8a83c6db41d.png)
![image](https://user-images.githubusercontent.com/65691999/235817166-8e19ec94-d593-41c2-bf35-2ed09f870e75.png)
![image](https://user-images.githubusercontent.com/65691999/235817184-3b9aa0bb-0ea6-4dd9-b46c-dda9ca09af2c.png)

使用gs安装后后台报错

**Comment by zhaoZiQu** [comment]
![image](https://user-images.githubusercontent.com/65691999/235821751-60b01314-076a-4e09-bf04-8ffabb76594a.png)
手动安装是这个报错

**Comment by zhaoZiQu** [comment]
win11系统上手动安装可以成功了，服务器上失败还是那个报错

**Comment by zhaoZiQu** [comment]
@KimigaiiWuyi 大佬救救

**Comment by KimigaiiWuyi** [comment]
建议手动安装，手动启动core

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/65691999/235821751-60b01314-076a-4e09-bf04-8ffabb76594a.png) 手动安装是这个报错

这个报错是因为poetry版本过低，更新一下poetry

**Comment by zhaoZiQu** [comment]
多谢，解决了
