### ISSUE TITLE
Hoshino连接器导入抽卡记录异常

### ISSUE THREAD

**Issue by soapspree** [KimigaiiWuyi/GenshinUID#535]
环境是常规的go-cqhttp + HoshinoBot，发现私聊Bot导入抽卡记录时没有反应，Bot不回复消息也没有看到log有报错，看了下可能是Hoshino连接器这个位置的问题：
https://github.com/KimigaiiWuyi/GenshinUID/blob/2a4af236b512d798cad41a9c6271c46e129a264b/GenshinUID/__init__.py#L118-L119
私聊发送文件时我log到的事件报文里面没有`message_type`这个字段，这里一定会return导致完全没有响应，翻了下go-cqhttp的事件文档，接收离线文件这个事件也没有包含这个字段，麻烦大佬检查下是不是存在问题？

**Comment by KimigaiiWuyi** [comment]
可以提供一下私聊发送文件时，ev长啥样吗

**Comment by soapspree** [comment]
> 可以提供一下私聊发送文件时，ev长啥样吗

草原来有的，复制引用的时候没留意给覆盖掉了

    <Event, {'post_type': 'notice', 'notice_type': 'offline_file', 'time': 1683288585, 'self_id': 打码, 'file': {'name': '打码.json', 'size': 317957, 'url': '打码'}, 'user_id': 打码}>

**Comment by KimigaiiWuyi** [comment]
可以尝试更新一下看是否解决，~~或者诞生了新的bug~~

**Comment by soapspree** [comment]
[2023-05-05 17:58:44,171 nonebot] ERROR: 'message_type'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/nonebot/notice_request.py", line 83, in handle_notice_or_request
        await _bus.emit(ev_name, session)
      File "/usr/local/lib/python3.10/dist-packages/aiocqhttp/bus.py", line 60, in emit
        results += await run_async_funcs(self._subscribers[event], *args,
      File "/usr/local/lib/python3.10/dist-packages/aiocqhttp/utils.py", line 40, in run_async_funcs
        results += await asyncio.gather(*coros)
      File "/HoshinoBot/hoshino/service.py", line 396, in wrapper
        return await func(session)
      File "/HoshinoBot/hoshino/modules/GenshinUID/GenshinUID/__init__.py", line 132, in import_gacha_log_info
        if priv.check_priv(ev, priv.SUPERUSER):
      File "/HoshinoBot/hoshino/priv.py", line 81, in check_priv
        if ev['message_type'] == 'group':
    KeyError: 'message_type'

还是寄了，132行调用check_priv函数也要获取这个`message_type`，不过好消息是把这段也去掉之后就没问题了，可以正常导入，但是不太清楚缺失了这个超管权限会有什么影响

**Comment by KimigaiiWuyi** [comment]
> ```
> [2023-05-05 17:58:44,171 nonebot] ERROR: 'message_type'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/nonebot/notice_request.py", line 83, in handle_notice_or_request
>     await _bus.emit(ev_name, session)
>   File "/usr/local/lib/python3.10/dist-packages/aiocqhttp/bus.py", line 60, in emit
>     results += await run_async_funcs(self._subscribers[event], *args,
>   File "/usr/local/lib/python3.10/dist-packages/aiocqhttp/utils.py", line 40, in run_async_funcs
>     results += await asyncio.gather(*coros)
>   File "/HoshinoBot/hoshino/service.py", line 396, in wrapper
>     return await func(session)
>   File "/HoshinoBot/hoshino/modules/GenshinUID/GenshinUID/__init__.py", line 132, in import_gacha_log_info
>     if priv.check_priv(ev, priv.SUPERUSER):
>   File "/HoshinoBot/hoshino/priv.py", line 81, in check_priv
>     if ev['message_type'] == 'group':
> KeyError: 'message_type'
> ```
> 
> 还是寄了，132行调用check_priv函数也要获取这个`message_type`，不过好消息是把这段也去掉之后就没问题了，可以正常导入，但是不太清楚缺失了这个超管权限会有什么影响

暂时没有插件会用到文件这边的权限，不过未来也许会有影响

**Comment by KimigaiiWuyi** [comment]
更新后应该正常，这样应该影响小一点

**Comment by soapspree** [comment]
> 更新后应该正常，这样应该影响小一点

试了下没问题了，感谢
