### ISSUE TITLE
docker方式运行的hoshinobot，怎么安装core啊？

### ISSUE THREAD

**Issue by WindStill** [KimigaiiWuyi/GenshinUID#538]
`gs一键安装` 报错，找不到 git 命令， `ERROR: Cmd('git') not found due FileNotFoundError: [Errno 2] No such file or directory: 'git'`

**Comment by KimigaiiWuyi** [comment]
需要在启动环境中有可用的git，文档应该有提，git的具体安装方法可百度或者问newbing

**Comment by WindStill** [comment]
> 需要在启动环境中有可用的git，文档应该有提，git的具体安装方法可百度或者问newbing

普通环境下好安装，只是docker中安装完git再重启就没了😂。

我记得有个issue中提到 ，core也是个单独运行的服务，他自己把core打包成了docker镜像。想问下，官方有提供core的docker镜像吗？

**Comment by KimigaiiWuyi** [comment]
> > 需要在启动环境中有可用的git，文档应该有提，git的具体安装方法可百度或者问newbing
> 
> 普通环境下好安装，只是docker中安装完git再重启就没了😂。
> 
> 我记得有个issue中提到 ，core也是个单独运行的服务，他自己把core打包成了docker镜像。想问下，官方有提供core的docker镜像吗？

没有提供，可以自己学习打包

**Comment by WindStill** [comment]
> > > 需要在启动环境中有可用的git，文档应该有提，git的具体安装方法可百度或者问newbing
> > 
> > 
> > 普通环境下好安装，只是docker中安装完git再重启就没了😂。
> > 我记得有个issue中提到 ，core也是个单独运行的服务，他自己把core打包成了docker镜像。想问下，官方有提供core的docker镜像吗？
> 
> 没有提供，可以自己学习打包

好的。多谢
