### ISSUE TITLE
查询指令返回的图像错误

### ISSUE THREAD

**Issue by Putarku** [KimigaiiWuyi/GenshinUID#54]
![image](https://user-images.githubusercontent.com/66679443/145983374-7b4e9fc3-68f8-4513-ada1-977f503c410f.png)

一斗池子更新后就变成这样了

**Comment by KimigaiiWuyi** [comment]
> 
并发间隔问题，详见[#486](https://github.com/Arondight/Adachi-BOT/issues/486)

**Comment by KimigaiiWuyi** [comment]
目前来看应该无望恢复……

**Comment by 741807012** [comment]
建议出个版本，自己Cookie查自己的，不能查别人的

**Comment by KimigaiiWuyi** [comment]
> 建议出个版本，自己Cookie查自己的，不能查别人的

现在默认就是查自己调用自己CK啊，你的意思是自己的CK不允许用来给别人查询这个功能是吗

**Comment by 741807012** [comment]
> > 建议出个版本，自己Cookie查自己的，不能查别人的
> 
> 现在默认就是查自己调用自己CK啊，你的意思是自己的CK不允许用来给别人查询这个功能是吗

绑定mys后查询错误这个修复了吗

**Comment by KimigaiiWuyi** [comment]
> > > 建议出个版本，自己Cookie查自己的，不能查别人的
> > 
> > 
> > 现在默认就是查自己调用自己CK啊，你的意思是自己的CK不允许用来给别人查询这个功能是吗
> 
> 绑定mys后查询错误这个修复了吗

你可以试试，我一直没有复现，怀疑是之前校验命令出现错误一起出现的bug

**Comment by 741807012** [comment]
> > > > 建议出个版本，自己Cookie查自己的，不能查别人的
> > > 
> > > 
> > > 现在默认就是查自己调用自己CK啊，你的意思是自己的CK不允许用来给别人查询这个功能是吗
> > 
> > 
> > 绑定mys后查询错误这个修复了吗
> 
> 你可以试试，我一直没有复现，怀疑是之前校验命令出现错误一起出现的bug

我建议还是出一个版本绑定Cookie才可以查的吧

**Comment by KimigaiiWuyi** [comment]
> > > > > 建议出个版本，自己Cookie查自己的，不能查别人的
> > > > 
> > > > 
> > > > 现在默认就是查自己调用自己CK啊，你的意思是自己的CK不允许用来给别人查询这个功能是吗
> > > 
> > > 
> > > 绑定mys后查询错误这个修复了吗
> > 
> > 
> > 你可以试试，我一直没有复现，怀疑是之前校验命令出现错误一起出现的bug
> 
> 我建议还是出一个版本绑定Cookie才可以查的吧

其实在NewCookiesTable这个表里预留了Extra字段可以马上做Ck的权限问题，开放`open`，关闭`closed`，和私有`private`，但是现在api变动让我得修改一下UI才行 ；会和新的`原神wiki`（包含类别查询/武器特定级别属性/角色特定级别基础属性），`活动列表`，`御神签`，`用户权限管理`功能一同上线

**Comment by 741807012** [comment]
[抽卡图片素材.zip](https://github.com/KimigaiiWuyi/GenshinUID/files/7739044/default.zip)
发点视频素材给你看看，如果能用上就好了

**Comment by KimigaiiWuyi** [comment]
已修改为 分开的8角色UI和全角色UI

**Comment by KimigaiiWuyi** [comment]
> [抽卡图片素材.zip](https://github.com/KimigaiiWuyi/GenshinUID/files/7739044/default.zip) 发点视频素材给你看看，如果能用上就好了

感谢！属性图标好像能用上，不过感觉也不太好加，先留着备用把
