### ISSUE TITLE
[v4]今天在网吧使用全新nonebot项目产生问题合集

### ISSUE THREAD

**Issue by yhzcake** [KimigaiiWuyi/GenshinUID#540]
几个问题
1：在auto_install.py中使用了git这个库，可能有部分人未安装git导致缺少git的环境变量，解决办法为在import前添加os.environ["GIT_PYTHON_REFRESH"]="quiet"
2：即使写了安装和启动core但实际上只在指令中使用了
3：在bot链接的时候写了gsclient.connet但是core不在也没用
所以初始化自动下载core压根就没写，现在只能手动下载启动core

我的评价是在bot.py里加个subprocess.Popen("poetry run python core.py",cwd="D:\\nonebot\\gsuid_core\\gsuid_core")

**Comment by KimigaiiWuyi** [comment]
有`启动core`命令，不过通常不建议使用，最好还是手动启动
文档有提过必须确保git存在
