### ISSUE TITLE
能不能设置+特定前缀才会触发？

### ISSUE THREAD

**Issue by grinxxoo** [KimigaiiWuyi/GenshinUID#543]
群友正常吹牛皮偶尔会触发各种命令，能不能+前缀才触发啊 比如#+命令

**Comment by KimigaiiWuyi** [comment]
可以设置core的command_start，也可以设置nb的command_start

**Comment by grinxxoo** [comment]
> 可以设置core的command_start，也可以设置nb的command_start

nonebot的COMMAND_START="/"我设置了依然能触发如"查询"等命令 我试试core的command_start
