### ISSUE TITLE
求助一个信息 core无法使用

### ISSUE THREAD

**Issue by tianyu121** [KimigaiiWuyi/GenshinUID#548]
无法使用core，能帮我看一下是什么原因造成的吗

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]

正常启动core，会提示以上信息，导致core无法启动

**Comment by KimigaiiWuyi** [comment]
poetry 版本应该在1.4.0以上

**Comment by tianyu121** [comment]
好的我看看

**Comment by tianyu121** [comment]
刚刚试了一下，目前poetry版本是1.5.0 还是报错
05-24 15:54:14 [INFO] nonebot_plugin_gocqhttp | [285497741] 检查更新完成. 当前已运行最新版本.
05-24 15:54:14 [INFO] nonebot_plugin_gocqhttp | [285497741] 开始诊断网络情况
05-24 15:54:15 [INFO] nonebot_plugin_gocqhttp | [285497741] 收到服务器地址更新通知, 将在下一次重连时应用.
05-24 15:54:17 [INFO] nonebot_plugin_gocqhttp | [285497741] 网络诊断完成. 未发现问题
05-24 15:54:33 [INFO] nonebot_plugin_gocqhttp | [285497741] 收到好友 天域与音(799855103) 的消息: 启动core (20099492)
05-24 15:54:33 [SUCCESS] nonebot | OneBot V11 285497741 | [message.private.friend]: Message 20099492 from 799855103 '启动core'
05-24 15:54:33 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
05-24 15:54:33 [INFO] nonebot_plugin_gocqhttp | [285497741] 发送好友 799855103(799855103)  的消息: [{"type":  ... (-1525748279)
05-24 15:54:33 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)


  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]


root@tianyu-UT3000F:~# poetry --version
Poetry (version 1.5.0)

**Comment by tianyu121** [comment]
重启完后，出现
05-24 16:11:02 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
Warning: Found deprecated key 'default' or 'secondary' in pyproject.toml configuration for source mirrors. Please provide the key 'priority' instead. Accepted values are: 'default', 'primary', 'secondary', 'supplemental', 'explicit'.
Traceback (most recent call last):
  File "/root/gsuid_core/gsuid_core/core.py", line 6, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'

**Comment by KimigaiiWuyi** [comment]
> 重启完后，出现 05-24 16:11:02 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete Warning: Found deprecated key 'default' or 'secondary' in pyproject.toml configuration for source mirrors. Please provide the key 'priority' instead. Accepted values are: 'default', 'primary', 'secondary', 'supplemental', 'explicit'. Traceback (most recent call last): File "/root/gsuid_core/gsuid_core/core.py", line 6, in import uvicorn ModuleNotFoundError: No module named 'uvicorn'

没有安装依赖，目测没有poetry install或者没有用poetry run python core.py启动core

**Comment by tianyu121** [comment]
感谢大佬，给了我一个启发，我因为第一次不知道装在那，有些地方装了core，结果我刚刚仔细看，发现调用的是我之前装的，在那个目录装完依赖，目前应该属于正常了
05-24 16:23:37 [INFO] gsuid_core.server | NoneBot2已连接！
05-24 16:23:37 [INFO] websockets.legacy.server | connection open
05-24 16:23:37 [SUCCESS] GenshinUID | 与[gsuid-core]成功连接! Bot_ID: NoneBot2
05-24 16:23:37 [INFO] plugins.core_command.core_restart | 检查遗留信息...
05-24 16:23:37 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_update.__init__ | 检查遗留信息...
05-24 16:23:37 [INFO] plugins.core_command.core_restart.__init__ | 检查遗留信息...
05-24 16:23:37 [INFO] gsuid_core.plugins.core_command.core_restart | 检查遗留信息...
05-24 16:23:37 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_update | 检查遗留信息...
