### ISSUE TITLE
nb2 分支中钩子为 on_startswith 的指令无法正确匹配 nb2 env 中设置的命令前缀

### ISSUE THREAD

**Issue by ZhouYingSASA** [KimigaiiWuyi/GenshinUID#55]
假如 nb2 中没有设置匹配所有命令，on_startswith 钩子还是能匹配所有消息，相反 on_command 钩子就必须先匹配上 nb 的前缀之后再匹配全命令。

hoshino 中的 on_prefix 和 on_fullcommand 就完全不管 nb1 的命令前缀，任何消息都能匹配。

**Comment by KimigaiiWuyi** [comment]
nb2的设置应该有说要加command start，所以我这边说明就没写

**Comment by ZhouYingSASA** [comment]
是的，我遇到的情况是 on_startswith 不管是否匹配 COMMAND_START 内的命令前缀

**Comment by ZhouYingSASA** [comment]
这个不知道是 nb2 的设计问题还是 bug，如果就是这么设计的可能需要在这个插件内进行适配。。

**Comment by KimigaiiWuyi** [comment]
> 这个不知道是 nb2 的设计问题还是 bug，如果就是这么设计的可能需要在这个插件内进行适配。。

应该就是这么设计的，commandstart就只对on_command 生效，实际上你设置command start为空字符串 也可以欺骗自己（

**Comment by ZhouYingSASA** [comment]
设置前缀主要就是为了防止误触发命令so。。感觉nb2这样不太合理，我去那边扯扯皮🤣
