### ISSUE TITLE
启动core时报错

### ISSUE THREAD

**Issue by yangzhan-1** [KimigaiiWuyi/GenshinUID#550]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/68652f4f-a2e7-42dd-b5c7-371ea795c15c)

**Comment by KimigaiiWuyi** [comment]
看文档中的FAQ（常见问题）一节

**Comment by yangzhan-1** [comment]
还是报错
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/22e5526c-ba46-4b92-adf3-7a4b3b2b7d16)

**Comment by KimigaiiWuyi** [comment]
msvc-runtime呢

**Comment by yangzhan-1** [comment]
这些命令我都是在gitbash终端里面的，你说的这个是c的东西吗

**Comment by yangzhan-1** [comment]
msvc-runtime这个是要自己手动安装吗

**Comment by yangzhan-1** [comment]
确实是msvc-runtime的问题
