### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by yangzhan-1** [KimigaiiWuyi/GenshinUID#557]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/c4fb9062-22ca-4bbd-8b0b-dddbeafba58e)

**Comment by KimigaiiWuyi** [comment]
更新你的poetry至1.5以上
`pip install poetry -U -i https://pypi.org/simple`

**Comment by yangzhan-1** [comment]
运行了升级指令版本一直还是1.4
![Uploading image.png…]()

**Comment by yangzhan-1** [comment]
运行了升级指令版本一直还是1.4
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/76dcff63-12c3-424b-a79a-ac1aab5cf9ac)

**Comment by yangzhan-1** [comment]
这显示是升级到了1.5但实际使用版本却一直在1.4
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/fa43510d-c444-4795-8062-64b49c5490f1)

**Comment by KimigaiiWuyi** [comment]
说明你这个poetry不是pip装的，想想你当时怎么装的
