### ISSUE TITLE
core启动报错[source.0] Additional properties are not allowed ('priority' was unexpected)

### ISSUE THREAD

**Issue by Guoyh1212** [KimigaiiWuyi/GenshinUID#558]
前天core还能正常启动，安装了星铁和原神插件后登录网页端进行过一次更新。而后昨天机器人被夹，重启机器人后就没办法启动核心了，每次启动核心就报错。

报错Log：
06-08 10:30:10 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete
06-08 10:33:36 [INFO] nonebot_plugin_gocqhttp | [2142567304] 收到群 万达国际交流会(831268895) 内 12点不睡是傻逼(264201041) 的消息: 启动core (-754682521)
06-08 10:33:36 [SUCCESS] nonebot | OneBot V11 2142567304 | [message.group.normal]: Message -754682521 from 264201041@[群:831268895] '启动core'
06-08 10:33:36 [INFO] nonebot | Event will be handled by Matcher(type='message', module=GenshinUID)
06-08 10:33:37 [INFO] nonebot_plugin_gocqhttp | [2142567304] 发送群 万达国际交流会(831268895) 的消息: [{"type":  ... (1136355574)
06-08 10:33:37 [INFO] nonebot | Matcher(type='message', module=GenshinUID) running complete

The Poetry configuration is invalid:
  - [source.0] Additional properties are not allowed ('priority' was unexpected)

**Comment by KimigaiiWuyi** [comment]
看 #557
