### ISSUE TITLE
充值功能api报错

### ISSUE THREAD

**Issue by yangzhan-1** [KimigaiiWuyi/GenshinUID#560]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/67c4026f-6b0e-48c6-a684-22c6f776da10)

**Comment by KimigaiiWuyi** [comment]
端午检查修复

**Comment by KimigaiiWuyi** [comment]
更新core即可修复，需要注意的是，米游社已经取消wx支付，所以只能支持zfb

**Comment by AmamiHaruka** [comment]
充值相关的使用文档我似乎没有看到欸

**Comment by KimigaiiWuyi** [comment]
> 充值相关的使用文档我似乎没有看到欸

这需要啥文档，直接发命令不就可以用了

**Comment by AmamiHaruka** [comment]
> > 充值相关的使用文档我似乎没有看到欸
> 
> 这需要啥文档，直接发命令不就可以用了

命令列表里面没看到，翻看了代码才知道，还有这个功能。

**Comment by KimigaiiWuyi** [comment]
> > > 充值相关的使用文档我似乎没有看到欸
> > 
> > 
> > 这需要啥文档，直接发命令不就可以用了
> 
> 命令列表里面没看到，翻看了代码才知道，还有这个功能。

部分敏感功能不会直接出现在`gs帮助`内

**Comment by AmamiHaruka** [comment]
> > > > 充值相关的使用文档我似乎没有看到欸
> > > 
> > > 
> > > 这需要啥文档，直接发命令不就可以用了
> > 
> > 
> > 命令列表里面没看到，翻看了代码才知道，还有这个功能。
> 
> 部分敏感功能不会直接出现在`gs帮助`内

了解。
