### ISSUE TITLE
资源始终还是不会去下载

### ISSUE THREAD

**Issue by yangzhan-1** [KimigaiiWuyi/GenshinUID#561]
给的资源包内容有缺失
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/67181805/ac5b8c20-e88a-43d3-9440-6a71a83f0f6b)

**Comment by KimigaiiWuyi** [comment]
resource3.7
https://www.123pan.com/s/St4DVv-L3ejH.html  提取码:wuyi

**Comment by KimigaiiWuyi** [comment]
已修复
