### ISSUE TITLE
每日自动米游币没有全部完成

### ISSUE THREAD

**Issue by mhy9989** [KimigaiiWuyi/GenshinUID#562]
每天自动米游币，总是只完成浏览3个帖子，点赞只完成2个，签到和分享不会完成。然而使用“开始获取米游币”进行手动获取会继续完成没有完成的项目，这是有什么bug吗？

**Comment by KimigaiiWuyi** [comment]
应该只是第一次任务有部分失败，第二次只是继续下去了而已，因为两者调用的函数一致，我后续检查一下
