### ISSUE TITLE
留影叙佳期自动完成

### ISSUE THREAD

**Issue by ShaoNian-end** [KimigaiiWuyi/GenshinUID#563]
留影叙佳期自动完成
留影叙佳期自动完成
留影叙佳期自动完成
留影叙佳期自动完成
留影叙佳期自动完成
留影叙佳期自动完成

**Comment by KimigaiiWuyi** [comment]
更新core & gsuid即可享受（未经测试）

**Comment by ShaoNian-end** [comment]
- [ ] 谢谢wuyi鸽鸽
