### ISSUE TITLE
查询命令：当前状态 卡死导致core工作阻塞

### ISSUE THREAD

**Issue by AmamiHaruka** [KimigaiiWuyi/GenshinUID#564]
使用[当前状态]查询体力情况时，监控core运行日志输出，有时可以正确返回，但有时会请求卡死，然后导致core阻塞，无法处理后续命令响应。

**Comment by KimigaiiWuyi** [comment]
log等级调整为`DEBUG`后截图卡死后台看看

**Comment by KimigaiiWuyi** [comment]
位于core文件夹内`config.json`的`log_level`，把`INFO`改为`DEBUG`

**Comment by AmamiHaruka** [comment]
我的core似乎没有正常启动，在这次重启后，我才用的是手动启动core和 hoshino genshinGUI插件方式。现在对于什么命令都没有响应了，我先尝试解决

**Comment by KimigaiiWuyi** [comment]
> 我的core似乎没有正常启动，在这次重启后，我才用的是手动启动core和 hoshino genshinGUI插件方式。现在对于什么命令都没有响应了，我先尝试解决

如果可以在core看到消息，但是不响应命令，可以
1. 检查core启动时是否有报错（插件是否加载成功）
2. 发送`重置core配置`后重启查看是否相应

**Comment by AmamiHaruka** [comment]
看不到消息，应该是hoshino没能正确连接到core，后面重启动bot解决了，下面是当前状态的 debug图
![debug](https://github.com/KimigaiiWuyi/GenshinUID/assets/10334215/0049be8f-37a3-4d4c-9219-e8d5709a0d04)
值得注意的是我自己本身的查询每次都很顺利，这个账户每次都会导致卡死，有一个明显的区别是这位ck绑定的米友社账户并没有对应的星穹铁道zhang'huzhanghu

**Comment by KimigaiiWuyi** [comment]
> 看不到消息，应该是hoshino没能正确连接到core，后面重启动bot解决了，下面是当前状态的 debug图 ![debug](https://user-images.githubusercontent.com/10334215/249333717-0049be8f-37a3-4d4c-9219-e8d5709a0d04.png) 值得注意的是我自己本身的查询每次都很顺利，这个账户每次都会导致卡死，有一个明显的区别是这位ck绑定的米友社账户并没有对应的星穹铁道zhang'huzhanghu

到这就卡死了？敲个回车看看

**Comment by AmamiHaruka** [comment]
确信，到这里就没有输出了。

**Comment by KimigaiiWuyi** [comment]
收到，今晚检查修复，应该是core的自动生成报错图片的问题

**Comment by KimigaiiWuyi** [comment]
ok, 问题定位的比我想的快
**更新core**之后重试，检查是否正常

**Comment by AmamiHaruka** [comment]
已经更新了嘛。另外每次生成报错图片的时候（比如米游社出现验证码）都会在服务器自动打开那个png，现在我服务器开了好多png

**Comment by KimigaiiWuyi** [comment]
> 已经更新了嘛。另外每次生成报错图片的时候（比如米游社出现验证码）都会在服务器自动打开那个png，现在我服务器开了好多png

现在应该不会了，更新core即可（不是更新gsuid）
