### ISSUE TITLE
问题：[绑定cookies失败][仅回复某几个特定关键字]

### ISSUE THREAD

**Issue by Morecafes** [KimigaiiWuyi/GenshinUID#568]
**首先感谢您在百忙之中能抽空看一下这个问题，在提问前我查阅了bug列表也发现了类似的问题，但是此类问题的解决方式并不是很有效，所以才在次情况下开启了这个问题，以下是我问题的详细情况：**
1、在查阅wiki 的时候我发现需要先绑定米游社的cookies，但是当我在使用无痕浏览并使用获取cookie的方式发送给机器人后，机器人返送cookie绑定失败信息，如下图所示：
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/74084015/ea5ef56e-ba23-4db9-8663-5763397ba639)
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/74084015/c2a88fd8-5fd3-4b2c-8304-58166625b599)
其中包括了"cookie_token"和”ltoken“及”ltuid“，但是任然显示验证未通过。
2、在与机器人私聊的时候，现在仅能检测关键字
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/74084015/1f731fc3-6c55-4f6a-a164-93815679bdc9)
-----------------------------------
启动时截图：
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/74084015/5044eefe-4c33-4f8b-8fa1-a30e72d9d2e9)

**Comment by KimigaiiWuyi** [comment]
可以绑定uid之后，直接发送`扫码登陆`，使用米游社扫码即可完成绑定ck

有关ck的内容，现在可能需要stoken才能完成验证

**Comment by Morecafes** [comment]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/74084015/0930f454-f361-4867-b6f0-73090359b4f6)
嗯，十分不好意思，就是现在输入绑定UID没有触发关键词回复，现在就只有输入绑定信息后机器人才会触发关键词回复消息
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/74084015/6636a90a-628b-4c0f-852a-cc3777c090a2)
这个是输入绑定UID指令后的。在nonebot的.dev文件设置的触发关键词回复也是“”和“/”
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/74084015/bfc2cbd4-c360-4ea6-8df2-12f8898a9965)

**Comment by KimigaiiWuyi** [comment]
> ![image](https://user-images.githubusercontent.com/74084015/253269760-0930f454-f361-4867-b6f0-73090359b4f6.png) 嗯，十分不好意思，就是现在输入绑定UID没有触发关键词回复，现在就只有输入绑定信息后机器人才会触发关键词回复消息 ![image](https://user-images.githubusercontent.com/74084015/253269983-6636a90a-628b-4c0f-852a-cc3777c090a2.png) 这个是输入绑定UID指令后的。在nonebot的.dev文件设置的触发关键词回复也是“”和“/” ![image](https://user-images.githubusercontent.com/74084015/253270055-bfc2cbd4-c360-4ea6-8df2-12f8898a9965.png)

不要加空格，直接`绑定uid123456789`

**Comment by Morecafes** [comment]
好的，问题解决了，谢谢您了，我这儿把问题关闭了。ヾ(≧▽≦*)o
