### ISSUE TITLE
"角色" 命令无法查询最新角色(荒泷一斗)

### ISSUE THREAD

**Issue by ZhouYingSASA** [KimigaiiWuyi/GenshinUID#57]
应该不是 avatar_json 更新不及时的原因，也不是数据源缺失，目前没有找到原因。
![QQ截图20211216024304](https://user-images.githubusercontent.com/43701548/146246418-42c2f6cd-9c53-43cd-88b3-c42419c1daca.png)

**Comment by ZhouYingSASA** [comment]
补充：日志一切照常。另外其实不是没有找到原因，是我去睡觉了🥱

**Comment by KimigaiiWuyi** [comment]
![Snipaste_2021-12-16_09-19-13](https://user-images.githubusercontent.com/55526518/146290241-684ee6f0-3ef5-4f48-8808-5b462c906f15.png)
![Screenshot_20211216-091828_QQ](https://user-images.githubusercontent.com/55526518/146290282-c0ac8f37-3ed0-4910-817e-c5bd9bd0123e.png)
看上去没有什么问题（我想能获取到命座的话 应该数据源至少是没有问题的

**Comment by ZhouYingSASA** [comment]
很奇怪  我之后打几个点看看。

**Comment by ZhouYingSASA** [comment]
倾向是 QQ 吞消息。。。
![IMG_20211216_143039](https://user-images.githubusercontent.com/43701548/146320035-45aca9ac-80a9-44e9-bf43-7678d0d18f8d.jpg)
![SJCAT}C}SZA~HH3E4%K0P4B](https://user-images.githubusercontent.com/43701548/146320037-f8ec12e4-b5e9-46bc-9938-9e1ebc62aa23.png)
