### ISSUE TITLE
早柚核心无法启动

### ISSUE THREAD

**Issue by BainingYou** [KimigaiiWuyi/GenshinUID#572]
移动至gsuid_core/gsuid_core文件夹内
输入命令poetry run python core.py后显示ModuleNotFoundError: No module named 'uvicorn'
![OVH4VZJ8GPNZTC~VDL}ML45](https://github.com/KimigaiiWuyi/GenshinUID/assets/124949970/aa4fea34-1295-4ad6-beb0-5b32bfe2d0d0)

**Comment by KimigaiiWuyi** [comment]
需要先执行`poetry install`安装依赖

**Comment by BainingYou** [comment]
![30TE6 HQ7BZXV2}}HV7PA}W](https://github.com/KimigaiiWuyi/GenshinUID/assets/124949970/5376d585-d24f-4725-9bab-26dae8817e52)
已经安装过poetry了，这样子要怎么办呀
