### ISSUE TITLE
获取绑定信息报错

### ISSUE THREAD

**Issue by Luer2778** [KimigaiiWuyi/GenshinUID#574]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/113490872/d21554ab-8761-4edd-b35a-2a6b731175e1)

**Comment by KimigaiiWuyi** [comment]
更新core后尝试看看是否已修复

**Comment by Luer2778** [comment]
> 更新core后尝试看看是否已修复

![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/113490872/b2af9926-cc40-4d1f-b604-2224d2c9945a)
大佬，出了另一个错

**Comment by Luer2778** [comment]
已解决，感谢大佬
