### ISSUE TITLE
扫码登录报错

### ISSUE THREAD

**Issue by Luer2778** [KimigaiiWuyi/GenshinUID#582]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/113490872/8d4f9d40-e060-4557-88ae-405978ccccef)
使用nonebot2

**Comment by KimigaiiWuyi** [comment]
需要先绑定uid 然后再扫码登录看看

**Comment by Luer2778** [comment]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/113490872/383df767-17fa-4467-bba8-77c078dddaf0)
大佬，还是这样

**Comment by KimigaiiWuyi** [comment]
更新一下gsuid_core之后再尝试

**Comment by Luer2778** [comment]
感谢大佬，ok了
