### ISSUE TITLE
gs开启体力后网页控制台推送管理中无相关数据

### ISSUE THREAD

**Issue by luochenyao** [KimigaiiWuyi/GenshinUID#583]
[2023-09-15.log](https://github.com/KimigaiiWuyi/GenshinUID/files/12615238/2023-09-15.log)
core和插件版本是最新的，poetry版本1.6.1，Windows2022数据中心版，ck和uid绑定正常，mr功能可用，发送gs开启体力时机器人回复正常，但是设置阈值时失败，数据库推送管理中始终是空的，uid和ck管理中数据正常
![IMG_2687(20230915-105519)](https://github.com/KimigaiiWuyi/GenshinUID/assets/109839686/cc680b4c-af20-4730-b9db-bac9e5844027)

**Comment by luochenyao** [comment]
![QQ图片20230915214754](https://github.com/KimigaiiWuyi/GenshinUID/assets/109839686/d1501993-2b82-4691-aa81-270ce7a9c63c)
有一个这样的报错，推送管理列表里还是空的

**Comment by KimigaiiWuyi** [comment]
同时更新core和gsuid，应该已修复

**Comment by luochenyao** [comment]
> 同时更新core和gsuid，应该已修复

好的～好使了，但是还有其他问题qwq，推送完体力之后，即使体力已推送标记为on，也会无限重复推送，清完体力之后不推送，但是体力已推送标记没有被修改成off还是on，没有开启催命模式。

**Comment by KimigaiiWuyi** [comment]
> > 同时更新core和gsuid，应该已修复
> 
> 好的～好使了，但是还有其他问题qwq，推送完体力之后，即使体力已推送标记为on，也会无限重复推送，清完体力之后不推送，但是体力已推送标记没有被修改成off还是on，没有开启催命模式。

更新后检查是否已修复（NTQQ没邮件提醒没看到

**Comment by luochenyao** [comment]
好的，好使了，辛苦无疑佬~
