### ISSUE TITLE
无法访问下载地址

### ISSUE THREAD

**Issue by ABKQPO** [KimigaiiWuyi/GenshinUID#589]
http://file.microgg.cn/KimigaiiWuyi/resource
http://jp-iij-1.lcf.icu:10200/
两个网址无法访问

**Comment by KimigaiiWuyi** [comment]
更新gsuid并重启bot，目前两个最新的下载地址应该是

http://hk-1.5gbps-2.lcf.icu:10200/
https://kr-arm.qxqx.me/GenshinUID/

会自动选择最快的地址进行下载

https://github.com/KimigaiiWuyi/GenshinUID/blob/e780c8725bb613f03469c1e014c7ce3a14a79ed6/GenshinUID/utils/resource/download_from_miniggicu.py#L60-L71
