### ISSUE TITLE
关于QQ频道Bot的适配

### ISSUE THREAD

**Issue by KimigaiiWuyi** [KimigaiiWuyi/GenshinUID#59]
实际上基于官方PythonSDK的频道Bot已经基本移植完成（原本移植到GolangSDK的计划废除）；
但是频道个人Bot目前限制太多：
需要申请；
发送图片必须发送已备案的URL，而不能直接发送本地图片或者其他在线图床的URL；
公域Bot非备案无法发送Ark；
每日主动消息限制每个频道20条（之前是2条）；

故而暂时不开源，如有希望体验（测试）的，可主动联系我，需要满足上述条件。

**Comment by a970703218** [comment]
这是指官方的QQbot？

**Comment by KimigaiiWuyi** [comment]
> 这是指官方的QQbot？

对，需要自己申请；然后才能用，QQGuildBot分支我已上传，还有就是尽量不要在已关闭的issuse里回复；有疑问可以新开
