### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by liuqianpan2008** [KimigaiiWuyi/GenshinUID#6]
[![hThxiT.png](https://z3.ax1x.com/2021/09/08/hThxiT.png)](https://imgtu.com/i/hThxiT)

**Comment by KimigaiiWuyi** [comment]
噢 ，多加了一个函数，你可以打开__init__.py在第六行，把draw_pic,这几个字直接删除即可，或者等我晚上回去更新

**Comment by KimigaiiWuyi** [comment]
已修复
