### ISSUE TITLE
由于米游社API变动，导致部署在VPS上的本项目部分功能失效

### ISSUE THREAD

**Issue by 741807012** [KimigaiiWuyi/GenshinUID#60]
cookie_token=xxxxxxx; account_id=xxxxxxx这个字段不行了
ltoken=xxxxxx; ltuid=xxxxx看看这个字段查询能用吗

**Comment by KimigaiiWuyi** [comment]
mysapi变动，详见[我回复的](https://github.com/Arondight/Adachi-BOT/issues/520)

**Comment by wudifeixue** [comment]
正在测试修复，目前错误状态如下
![S01YKWA1E0G56ND1(2@%M(U](https://user-images.githubusercontent.com/7316929/147320369-5313beb7-fc28-4994-9756-c8be73afeba0.png)
中

**Comment by KimigaiiWuyi** [comment]
已修复，但是目前如果是Vps部署的，包含阿里云，腾讯云均无法访问米游社新api，自家建的可以。

**Comment by 741807012** [comment]
> 已修复，但是目前如果是Vps部署的，包含阿里云，腾讯云均无法访问米游社新api，自家建的可以。

我刚好是自建的，家里的软路由

**Comment by KimigaiiWuyi** [comment]
> > 已修复，但是目前如果是Vps部署的，包含阿里云，腾讯云均无法访问米游社新api，自家建的可以。
> 
> 我刚好是自建的，家里的软路由

自建是正常的对吧
米游社这一手搞得有点难受

**Comment by 741807012** [comment]
> > > 已修复，但是目前如果是Vps部署的，包含阿里云，腾讯云均无法访问米游社新api，自家建的可以。
> > 
> > 
> > 我刚好是自建的，家里的软路由
> 
> 自建是正常的对吧 米游社这一手搞得有点难受

很正常一直到现在都没问题2021/12/24 22:30

**Comment by Ctumille** [comment]
> 已修复，但是目前如果是Vps部署的，包含阿里云，腾讯云均无法访问米游社新api，自家建的可以。

问，用的阿里云和hoshinobot，是不是没救了等您下次更新（

**Comment by KimigaiiWuyi** [comment]
> > 已修复，但是目前如果是Vps部署的，包含阿里云，腾讯云均无法访问米游社新api，自家建的可以。
> 
> 问，用的阿里云和hoshinobot，是不是没救了等您下次更新（

也只能先等了，目前几家uid查询类的，都暂时没有恢复的方法，我现在人在外地没法尝试，回去尝试修一修
自家部署是完全正常的，只是vps部署的挂了而已

**Comment by wudifeixue** [comment]
> > 已修复，但是目前如果是Vps部署的，包含阿里云，腾讯云均无法访问米游社新api，自家建的可以。
> 
> 问，用的阿里云和hoshinobot，是不是没救了等您下次更新（

你给阿里云挂个梯子是可以救一下的（）

**Comment by loveyoutan90** [comment]
我腾讯云还是不行有点恼火哎

**Comment by KimigaiiWuyi** [comment]
> 

现在确实还不行，之前只是短暂的可以了半小时；
基本上我觉得以后希望也渺茫

**Comment by KimigaiiWuyi** [comment]
> 我腾讯云还是不行有点恼火哎

现在确实还不行，之前只是短暂的可以了半小时；
基本上我觉得以后希望也渺茫

**Comment by loveyoutan90** [comment]
暂时只有等大佬修复，感谢大佬的插件分享，给群添加了许多乐趣，辛苦啦。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月28日(星期二) 晚上10:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] 由于米游社API变动，导致部署在VPS上的本项目部分功能失效 (Issue #60)





   
现在确实还不行，之前只是短暂的可以了半小时；
 基本上我觉得以后希望也渺茫
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by loveyoutan90** [comment]
主要问题是腾讯云和阿里云的不能访问新api嘛？如吧hoshinobot换成nonebot2行不行呢

**Comment by KimigaiiWuyi** [comment]
> 主要问题是腾讯云和阿里云的不能访问新api嘛？如吧hoshinobot换成nonebot2行不行呢

没有区别的，还想用的话估计只能挂在自家网络环境下，比如软路由；树莓派；NAS之类的设备下

**Comment by loveyoutan90** [comment]
哦好的，谢谢解答




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月29日(星期三) 上午9:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] 由于米游社API变动，导致部署在VPS上的本项目部分功能失效 (Issue #60)





  
主要问题是腾讯云和阿里云的不能访问新api嘛？如吧hoshinobot换成nonebot2行不行呢
  
没有区别的，还想用的话估计只能挂在自家网络环境下，比如软路由；树莓派；NAS之类的设备下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KimigaiiWuyi** [comment]
刚接到反馈，老api（也就是不加-record的原本的api），已经恢复，并且可以在VPS上使用

**Comment by KimigaiiWuyi** [comment]
[522](https://github.com/Arondight/Adachi-BOT/issues/522)

**Comment by loveyoutan90** [comment]
nice，辛苦了，辛苦了

**Comment by wudifeixue** [comment]
离大谱，要滚回么？还是要改成两个api哪个不行换另外一个？

**Comment by KimigaiiWuyi** [comment]
> 离大谱，要滚回么？还是要改成两个api哪个不行换另外一个？

我先把消息放出来，让他们自己改一下；
我晚上回去做个校验，两个api都放上去；还有就是其实我没有测 `当前状态`等一些其他的，老Api能不能用，回去一起测

**Comment by loveyoutan90** [comment]
我改了一下把-record去掉了，但是任然添加不了cookies

**Comment by KimigaiiWuyi** [comment]
> 我改了一下把-record去掉了，但是任然添加不了cookies

我晚上回去详细的测一下；

**Comment by loveyoutan90** [comment]
今晚上突然又好了

**Comment by loveyoutan90** [comment]
很奇怪绑定cookies还是绑定不了，但是以前的cookies能用，所有功能均正常

**Comment by wudifeixue** [comment]
> 很奇怪绑定cookies还是绑定不了，但是以前的cookies能用，所有功能均正常

绑定不了cookie有时候也是用户没有从来没有用账号打开过米游社，没有打开便笺，没有设定好隐私设置，这些都可能造成问题的。
