### ISSUE TITLE
当前状态派遣应显示角色名(或派遣地点)而不应为随机的 UUID

### ISSUE THREAD

**Issue by Ghost-chu** [KimigaiiWuyi/GenshinUID#607]
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/30802565/fda4fb07-17ac-4df3-b0f6-bb7fb992fa8f)

![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/30802565/9f551e81-78a6-41d0-b3a3-b49c17eecce5)

**Comment by KimigaiiWuyi** [comment]
和米游社改版有关 好像不太好修
而且好像没什么人用这个命令 可以用`mr`或`每日`
并且可以关闭core的自动文转图，`当前状态`发送应该是纯文字
