### ISSUE TITLE
查询命令的世界探索-枫丹部分超出其应该显示的范围，盖过了华丽宝箱的区域

### ISSUE THREAD

**Issue by Ghost-chu** [KimigaiiWuyi/GenshinUID#608]
是否可能根据条目数量，纵向拓展该行的卡片高度？
![image](https://github.com/KimigaiiWuyi/GenshinUID/assets/30802565/838b664e-db24-4c6a-b33c-9a2d681922f9)

**Comment by Ghost-chu** [comment]
千年珍珠那个我记得是Boss？这个不应该被放入世界探索吧？

**Comment by KimigaiiWuyi** [comment]
这个属于是米游社api被刺，上周 该功能的新ui 已经加入了的todo的计划中

**Comment by KimigaiiWuyi** [comment]
新版`查询`UI已更新
缝了`wcd`和`角色列表` 
<details><summary>预览效果</summary><p>
<a><img src="https://github.com/KimigaiiWuyi/GenshinUID/assets/55526518/f816540d-e809-4bc0-b090-e170532398d1"></a>
</p></details>
