### ISSUE TITLE
下载错误SSL

### ISSUE THREAD

**Issue by addre98** [KimigaiiWuyi/GenshinUID#618]
安装GenshinUID后，下载资源错误

> PS D:\Servers\Bot\core\gsuid_core> ..\Scripts\activate
> (core) PS D:\Servers\Bot\core\gsuid_core> poetry run core
> 02-18 19:40:59 [INFO] gsuid_core.server | [GsCore] 开始加载插件...
> 02-18 19:41:00 [SUCCESS] gsuid_core.server | 插件core_command导入成功!
> 02-18 19:41:00 [SUCCESS] gsuid_core.server | 插件GenshinUID导入成功!
> 02-18 19:41:00 [SUCCESS] gsuid_core.server | 插件gs_test导入成功!
> 02-18 19:41:01 [INFO] logging | Started server process [23568]
> 02-18 19:41:01 [INFO] logging | Waiting for application startup.
> 02-18 19:41:01 [INFO] gsuid_core.webconsole.__init__ | 尝试挂载WebConsole
> 02-18 19:41:01 [WARNING] gsuid_core.webconsole.__init__ | WebConsole挂载于本地, 如想外网访问请修改config.json中host为0.0.0.0!
> 02-18 19:41:01 [SUCCESS] gsuid_core.webconsole.__init__ | WebConsole挂载成功:http://localhost:8765/genshinuid
> 02-18 19:41:01 [INFO] gsuid_core.aps | 定时任务启动...
> 02-18 19:41:01 [INFO] logging | Application startup complete.
> 02-18 19:41:01 [INFO] logging | Uvicorn running on http://localhost:8765 (Press CTRL+C to quit)
> 02-18 19:41:01 [INFO] logging | ('127.0.0.1', 56780) - "WebSocket /ws/NoneBot2" [accepted]
> 02-18 19:41:01 [INFO] gsuid_core.server | NoneBot2已连接！
> 02-18 19:41:01 [INFO] gsuid_core.core | 启动GsCore...
> 02-18 19:41:01 [INFO] logging | connection open
> 02-18 19:41:01 [INFO] gsuid_core.plugins.core_command.core_restart | 检查遗留信息...
> 02-18 19:41:01 [INFO] plugins.core_command.core_restart | 检查遗留信息...
> 02-18 19:41:02 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_resource | [资源文件下载] 正在检查与下载缺失的资源文件， 可能需要较长时间，请稍等
> 02-18 19:41:02 [INFO] gsuid_core.utils.download_resource.download_core | [GsCore资源下载]测速中...
> 02-18 19:41:02 [INFO] gsuid_core.utils.download_resource.download_core | [HKFRP] http://hk-1.5gbps-2.lcf.icu:10200 超时...
> 02-18 19:41:02 [INFO] gsuid_core.utils.download_resource.download_core | [JPFRP] http://jp-2.lcf.icu:13643 超时...
> 02-18 19:41:02 [INFO] gsuid_core.utils.download_resource.download_core | [Seoul] https://kr-s.qxxx.tech 超时...
> 02-18 19:41:02 [INFO] gsuid_core.utils.download_resource.download_core | [Chuncheon] https://kr.qxxx.tech 超时...
> 02-18 19:41:02 [INFO] logging | ('::1', 56794) - "WebSocket /ws/NoneBot2" [accepted]
> 02-18 19:41:02 [INFO] gsuid_core.server | NoneBot2已连接！
> 02-18 19:41:02 [INFO] gsuid_core.core | 启动GsCore...
> 02-18 19:41:02 [INFO] logging | connection open
> 02-18 19:41:02 [INFO] gsuid_core.plugins.core_command.core_restart | 检查遗留信息...
> 02-18 19:41:02 [INFO] plugins.core_command.core_restart | 检查遗留信息...
> 02-18 19:41:02 [INFO] gsuid_core.utils.download_resource.download_core | [Tokyo] https://jp.qxqx.me 超时...
> 02-18 19:41:02 [INFO] gsuid_core.utils.download_resource.download_core | 最快资源站:
> 2024-02-18 19:41:02.897 | ERROR    | plugins.GenshinUID.GenshinUID.genshinuid_start.main:all_start:30 - /GenshinUID/resource/char_namecard/
> Traceback (most recent call last):
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1030, in _bootstrap
>     self._bootstrap_inner()
>     │    └ <function Thread._bootstrap_inner at 0x000001B90DCA4540>
>     └ <Thread(Thread-5 (<lambda>), started daemon 18104)>
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
>     self.run()
>     │    └ <function Thread.run at 0x000001B90DCA4220>
>     └ <Thread(Thread-5 (<lambda>), started daemon 18104)>
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
>     self._target(*self._args, **self._kwargs)
>     │    │        │    │        │    └ {}
>     │    │        │    │        └ <Thread(Thread-5 (<lambda>), started daemon 18104)>
>     │    │        │    └ ()
>     │    │        └ <Thread(Thread-5 (<lambda>), started daemon 18104)>
>     │    └ <function <lambda> at 0x000001B9192A3060>
>     └ <Thread(Thread-5 (<lambda>), started daemon 18104)>
> 
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_start\main.py", line 33, in <lambda>
>     threading.Thread(target=lambda: asyncio.run(all_start()), daemon=True).start()
>     │         │                     │       │   └ <function all_start at 0x000001B9192A2FC0>
>     │         │                     │       └ <function run at 0x000001B90F7F3600>
>     │         │                     └ <module 'asyncio' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\__init__.py'>
>     │         └ <class 'threading.Thread'>
>     └ <module 'threading' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py'>
> 
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
>     return runner.run(main)
>            │      │   └ <coroutine object all_start at 0x000001B9192DC2B0>
>            │      └ <function Runner.run at 0x000001B90F895620>
>            └ <asyncio.runners.Runner object at 0x000001B9192815E0>
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            │    │     │                  └ <Task cancelling name='Task-1' coro=<all_start() running at D:\Servers\Bot\core\gsuid_core\gsuid_core\plugins\GenshinUID\Gens...
>            │    │     └ <function BaseEventLoop.run_until_complete at 0x000001B90F8931A0>
>            │    └ <ProactorEventLoop running=True closed=False debug=False>
>            └ <asyncio.runners.Runner object at 0x000001B9192815E0>
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 671, in run_until_complete
>     self.run_forever()
>     │    └ <function ProactorEventLoop.run_forever at 0x000001B90F953380>
>     └ <ProactorEventLoop running=True closed=False debug=False>
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
>     super().run_forever()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 638, in run_forever
>     self._run_once()
>     │    └ <function BaseEventLoop._run_once at 0x000001B90F894F40>
>     └ <ProactorEventLoop running=True closed=False debug=False>
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1971, in _run_once
>     handle._run()
>     │      └ <function Handle._run at 0x000001B90F7DAC00>
>     └ <Handle Task.task_wakeup(<_GatheringFu...ar_namecard/>>)>
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
>     self._context.run(self._callback, *self._args)
>     │    │            │    │           │    └ <member '_args' of 'Handle' objects>
>     │    │            │    │           └ <Handle Task.task_wakeup(<_GatheringFu...ar_namecard/>>)>
>     │    │            │    └ <member '_callback' of 'Handle' objects>
>     │    │            └ <Handle Task.task_wakeup(<_GatheringFu...ar_namecard/>>)>
>     │    └ <member '_context' of 'Handle' objects>
>     └ <Handle Task.task_wakeup(<_GatheringFu...ar_namecard/>>)>
> 
> > File "D:\Servers\Bot\core\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_start\main.py", line 22, in all_start
>     await startup()
>           └ <function startup at 0x000001B9192A0220>
> 
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_resource\__init__.py", line 22, in startup
>     logger.info(f'[资源文件下载] {await download_all_resource()}')
>     │      │                      └ <function download_all_resource at 0x000001B919287420>
>     │      └ <function Logger.info at 0x000001B910F7F7E0>
>     └ <loguru.logger handlers=[(id=1, level=20, sink=<stdout>), (id=2, level=40, sink=<stderr>), (id=3, level=20, sink='D:\Servers\...
> 
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\utils\resource\download_all_resource.py", line 7, in download_all_resource
>     ret = await asyncio.gather(download_all_file_from_miniggicu())
>                 │       │      └ <function download_all_file_from_miniggicu at 0x000001B919287600>
>                 │       └ <function gather at 0x000001B90F887B00>
>                 └ <module 'asyncio' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\__init__.py'>
> 
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\utils\resource\download_from_miniggicu.py", line 19, in download_all_file_from_miniggicu
>     await download_all_file(
>           └ <function download_all_file at 0x000001B919287E20>
> 
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\utils\download_resource\download_core.py", line 116, in download_all_file
>     base_data = await _get_url(url, sess)
>                       │        │    └ <aiohttp.client.ClientSession object at 0x000001B91BA13C20>
>                       │        └ '/GenshinUID/resource/char_namecard/'
>                       └ <function _get_url at 0x000001B919287D80>
> 
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\utils\download_resource\download_core.py", line 81, in _get_url
>     req = await sess.get(url=url)
>                 │    │       └ '/GenshinUID/resource/char_namecard/'
>                 │    └ <function ClientSession.get at 0x000001B911766660>
>                 └ <aiohttp.client.ClientSession object at 0x000001B91BA13C20>
> 
>   File "D:\Servers\Bot\core\Lib\site-packages\aiohttp\client.py", line 545, in _request
>     req = self._request_class(
>           │    └ <class 'aiohttp.client_reqrep.ClientRequest'>
>           └ <aiohttp.client.ClientSession object at 0x000001B91BA13C20>
>   File "D:\Servers\Bot\core\Lib\site-packages\aiohttp\client_reqrep.py", line 326, in __init__
>     self.update_host(url)
>     │    │           └ URL('/GenshinUID/resource/char_namecard/')
>     │    └ <function ClientRequest.update_host at 0x000001B9116DF560>
>     └ <aiohttp.client_reqrep.ClientRequest object at 0x000001B91BAAD220>
>   File "D:\Servers\Bot\core\Lib\site-packages\aiohttp\client_reqrep.py", line 400, in update_host
>     raise InvalidURL(url)
>           │          └ URL('/GenshinUID/resource/char_namecard/')
>           └ <class 'aiohttp.client_exceptions.InvalidURL'>
> 
> aiohttp.client_exceptions.InvalidURL: /GenshinUID/resource/char_namecard/
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_start\main.py", line 22, in all_start
>     await startup()
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_resource\__init__.py", line 22, in startup
>     logger.info(f'[资源文件下载] {await download_all_resource()}')
>                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\utils\resource\download_all_resource.py", line 7, in download_all_resource
>     ret = await asyncio.gather(download_all_file_from_miniggicu())
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\utils\resource\download_from_miniggicu.py", line 19, in download_all_file_from_miniggicu
>     await download_all_file(
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\utils\download_resource\download_core.py", line 116, in download_all_file
>     base_data = await _get_url(url, sess)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Servers\Bot\core\gsuid_core\gsuid_core\utils\download_resource\download_core.py", line 81, in _get_url
>     req = await sess.get(url=url)
>           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "D:\Servers\Bot\core\Lib\site-packages\aiohttp\client.py", line 545, in _request
>     req = self._request_class(
>           ^^^^^^^^^^^^^^^^^^^^
>   File "D:\Servers\Bot\core\Lib\site-packages\aiohttp\client_reqrep.py", line 326, in __init__
>     self.update_host(url)
>   File "D:\Servers\Bot\core\Lib\site-packages\aiohttp\client_reqrep.py", line 400, in update_host
>     raise InvalidURL(url)

**Comment by KimigaiiWuyi** [comment]
看起来是几个资源站都超时了,我这边看 https://kr-s.qxxx.tech/  是正常的,你可以检查一下网络之类的

**Comment by addre98** [comment]
> 看起来是几个资源站都超时了,我这边看 https://kr-s.qxxx.tech/ 是正常的,你可以检查一下网络之类的

是在云服务器，但是浏览器访问正常。应该检查哪些方面？
或者
有办法手动下载资源吗？已经将 #399 中给的resource放进了正确的位置。

**Comment by KimigaiiWuyi** [comment]
> > 看起来是几个资源站都超时了,我这边看 https://kr-s.qxxx.tech/ 是正常的,你可以检查一下网络之类的
> 
> 是在云服务器，但是浏览器访问正常。应该检查哪些方面？ 或者 有办法手动下载资源吗？已经将 #399 中给的resource放进了正确的位置。

现在应该已经正常了

**Comment by YingLing3** [comment]
问题同上，浏览器访问正常，但是启动全部超时
