### ISSUE TITLE
部分数据错误

### ISSUE THREAD

**Issue by ghost** [KimigaiiWuyi/GenshinUID#622]
【查询收集】：传送点总数应为431，普通宝箱2980，精致2219，珍贵682
【查询探索】：水神瞳现总数应为216，顺带提一手，给的图最下面的沉玉谷不知道是bug还是刻意这样的（无数据）
【uidxxxx】：有块地方猜测应该是沉玉谷.南陵，写成了纳塔

**Comment by KimigaiiWuyi** [comment]
数据之后更新一下
关于2和3现在可以先用`wcd`和`角色列表`替代，过段时间会合并成`查询`

**Comment by iedhgherljhfloj** [comment]
收到

**Comment by ghost** [comment]
> 数据之后更新一下 关于2和3现在可以先用和替代，过段时间会合并成`wcd``角色列表``查询`

收到

**Comment by KimigaiiWuyi** [comment]
新版`查询`UI已更新
缝了`wcd`和`角色列表` 
<details><summary>预览效果</summary><p>
<a><img src="https://github.com/KimigaiiWuyi/GenshinUID/assets/55526518/f816540d-e809-4bc0-b090-e170532398d1"></a>
</p></details>

**Comment by ghost** [comment]
> 新版UI已更新 缝了和`查询``wcd``角色列表`
> 
> 预览效果
> ![](https://private-user-images.githubusercontent.com/55526518/313482666-f816540d-e809-4bc0-b090-e170532398d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODkwMDIsIm5iZiI6MTcxMDY4ODcwMiwicGF0aCI6Ii81NTUyNjUxOC8zMTM0ODI2NjYtZjgxNjU0MGQtZTgwOS00YmMwLWIwOTAtZTE3MDUzMjM5OGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MTY0Y2Q1ODJiYTM4MmU1ZThlM2MwMzZlNGZiNDQ2YjcyN2M5MTY2YWE1MmYyNWY5NTBmNTdlMTlkMWFhNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Nm-Z2IgqztCXv1ZMjB4Tz69Cl9d78xfJxW1mr4P3Qg)

OK

**Comment by ghost** [comment]
> 新版`查询`UI已更新 缝了`wcd`和`角色列表`
> 
> 预览效果
> ![](https://private-user-images.githubusercontent.com/55526518/313482666-f816540d-e809-4bc0-b090-e170532398d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTAxODEsIm5iZiI6MTcxMDY4OTg4MSwicGF0aCI6Ii81NTUyNjUxOC8zMTM0ODI2NjYtZjgxNjU0MGQtZTgwOS00YmMwLWIwOTAtZTE3MDUzMjM5OGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MzgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NGRmOWY0ZGRiODdmMzJhYzE4MjhlNTZjZDNlYmNiOTc0OGM5YzUxNmM4NTZkMTBkOTllMzY2NmE2M2UwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-M6lTU66C1jfvgh0JN2N-jnrGb-nonXXPSceT4WjEV8)

佬晚上好，更新后武器「有乐御簾切」和「沙中伟贤的对答」命名好像有问题（多了个后缀）导致无法读取，删除后缀后正常

**Comment by KimigaiiWuyi** [comment]
> > 新版`查询`UI已更新 缝了`wcd`和`角色列表`
> > 预览效果
> > ![](https://private-user-images.githubusercontent.com/55526518/313482666-f816540d-e809-4bc0-b090-e170532398d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTAxODEsIm5iZiI6MTcxMDY4OTg4MSwicGF0aCI6Ii81NTUyNjUxOC8zMTM0ODI2NjYtZjgxNjU0MGQtZTgwOS00YmMwLWIwOTAtZTE3MDUzMjM5OGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MzgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NGRmOWY0ZGRiODdmMzJhYzE4MjhlNTZjZDNlYmNiOTc0OGM5YzUxNmM4NTZkMTBkOTllMzY2NmE2M2UwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-M6lTU66C1jfvgh0JN2N-jnrGb-nonXXPSceT4WjEV8)
> 
> 佬晚上好，更新后武器「有乐御簾切」和「沙中伟贤的对答」命名好像有问题（多了个后缀）导致无法读取，删除后缀后正常

哪一个功能的，有报错log吗

**Comment by ghost** [comment]
> > > 新版`查询`UI已更新 缝了`wcd`和`角色列表`
> > > 预览效果
> > > ![](https://private-user-images.githubusercontent.com/55526518/313482666-f816540d-e809-4bc0-b090-e170532398d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTAxODEsIm5iZiI6MTcxMDY4OTg4MSwicGF0aCI6Ii81NTUyNjUxOC8zMTM0ODI2NjYtZjgxNjU0MGQtZTgwOS00YmMwLWIwOTAtZTE3MDUzMjM5OGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MzgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NGRmOWY0ZGRiODdmMzJhYzE4MjhlNTZjZDNlYmNiOTc0OGM5YzUxNmM4NTZkMTBkOTllMzY2NmE2M2UwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-M6lTU66C1jfvgh0JN2N-jnrGb-nonXXPSceT4WjEV8)
> > 
> > 
> > 佬晚上好，更新后武器「有乐御簾切」和「沙中伟贤的对答」命名好像有问题（多了个后缀）导致无法读取，删除后缀后正常
> 
> 哪一个功能的，有报错log吗

就是查询uid，应该是你角色带了该武器就不行了

**Comment by ghost** [comment]
> > > 新版`查询`UI已更新 缝了`wcd`和`角色列表`
> > > 预览效果
> > > ![](https://private-user-images.githubusercontent.com/55526518/313482666-f816540d-e809-4bc0-b090-e170532398d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTAxODEsIm5iZiI6MTcxMDY4OTg4MSwicGF0aCI6Ii81NTUyNjUxOC8zMTM0ODI2NjYtZjgxNjU0MGQtZTgwOS00YmMwLWIwOTAtZTE3MDUzMjM5OGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MzgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NGRmOWY0ZGRiODdmMzJhYzE4MjhlNTZjZDNlYmNiOTc0OGM5YzUxNmM4NTZkMTBkOTllMzY2NmE2M2UwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-M6lTU66C1jfvgh0JN2N-jnrGb-nonXXPSceT4WjEV8)
> > 
> > 
> > 佬晚上好，更新后武器「有乐御簾切」和「沙中伟贤的对答」命名好像有问题（多了个后缀）导致无法读取，删除后缀后正常
> 
> 哪一个功能的，有报错log吗

    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Desktop\\gsuid_core\\data\\GenshinUID\\resource\\weapon\\沙中伟贤的对答.png'

**Comment by KimigaiiWuyi** [comment]
> > > > 新版`查询`UI已更新 缝了`wcd`和`角色列表`
> > > > 预览效果
> > > > ![](https://private-user-images.githubusercontent.com/55526518/313482666-f816540d-e809-4bc0-b090-e170532398d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTAxODEsIm5iZiI6MTcxMDY4OTg4MSwicGF0aCI6Ii81NTUyNjUxOC8zMTM0ODI2NjYtZjgxNjU0MGQtZTgwOS00YmMwLWIwOTAtZTE3MDUzMjM5OGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MzgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NGRmOWY0ZGRiODdmMzJhYzE4MjhlNTZjZDNlYmNiOTc0OGM5YzUxNmM4NTZkMTBkOTllMzY2NmE2M2UwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-M6lTU66C1jfvgh0JN2N-jnrGb-nonXXPSceT4WjEV8)
> > > 
> > > 
> > > 佬晚上好，更新后武器「有乐御簾切」和「沙中伟贤的对答」命名好像有问题（多了个后缀）导致无法读取，删除后缀后正常
> > 
> > 
> > 哪一个功能的，有报错log吗
> 
> ```
> fp = builtins.open(filename, "rb")
> ```
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Administrator\Desktop\gsuid_core\data\GenshinUID\resource\weapon\沙中伟贤的对答.png'

尝试使用`下载全部资源`之后，无需重启，再次尝试
如果不行，再等五分钟左右（可能是资源库还没同步），再次重复上述步骤

**Comment by ghost** [comment]
> > > > > 新版`查询`UI已更新 缝了`wcd`和`角色列表`
> > > > > 预览效果
> > > > > ![](https://private-user-images.githubusercontent.com/55526518/313482666-f816540d-e809-4bc0-b090-e170532398d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTAxODEsIm5iZiI6MTcxMDY4OTg4MSwicGF0aCI6Ii81NTUyNjUxOC8zMTM0ODI2NjYtZjgxNjU0MGQtZTgwOS00YmMwLWIwOTAtZTE3MDUzMjM5OGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MzgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NGRmOWY0ZGRiODdmMzJhYzE4MjhlNTZjZDNlYmNiOTc0OGM5YzUxNmM4NTZkMTBkOTllMzY2NmE2M2UwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-M6lTU66C1jfvgh0JN2N-jnrGb-nonXXPSceT4WjEV8)
> > > > 
> > > > 
> > > > 佬晚上好，更新后武器「有乐御簾切」和「沙中伟贤的对答」命名好像有问题（多了个后缀）导致无法读取，删除后缀后正常
> > > 
> > > 
> > > 哪一个功能的，有报错log吗
> > 
> > 
> > ```
> > fp = builtins.open(filename, "rb")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Administrator\Desktop\gsuid_core\data\GenshinUID\resource\weapon\沙中伟贤的对答.png'
> 
> 尝试使用`下载全部资源`之后，无需重启，再次尝试 如果不行，再等五分钟左右（可能是资源库还没同步），再次重复上述步骤

我删了后缀后正常了，只是应该算个失误，跟你提一下

**Comment by KimigaiiWuyi** [comment]
> > > > > > 新版`查询`UI已更新 缝了`wcd`和`角色列表`
> > > > > > 预览效果
> > > > > > ![](https://private-user-images.githubusercontent.com/55526518/313482666-f816540d-e809-4bc0-b090-e170532398d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2OTAxODEsIm5iZiI6MTcxMDY4OTg4MSwicGF0aCI6Ii81NTUyNjUxOC8zMTM0ODI2NjYtZjgxNjU0MGQtZTgwOS00YmMwLWIwOTAtZTE3MDUzMjM5OGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE1MzgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NGRmOWY0ZGRiODdmMzJhYzE4MjhlNTZjZDNlYmNiOTc0OGM5YzUxNmM4NTZkMTBkOTllMzY2NmE2M2UwMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-M6lTU66C1jfvgh0JN2N-jnrGb-nonXXPSceT4WjEV8)
> > > > > 
> > > > > 
> > > > > 佬晚上好，更新后武器「有乐御簾切」和「沙中伟贤的对答」命名好像有问题（多了个后缀）导致无法读取，删除后缀后正常
> > > > 
> > > > 
> > > > 哪一个功能的，有报错log吗
> > > 
> > > 
> > > ```
> > > fp = builtins.open(filename, "rb")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Administrator\Desktop\gsuid_core\data\GenshinUID\resource\weapon\沙中伟贤的对答.png'
> > 
> > 
> > 尝试使用`下载全部资源`之后，无需重启，再次尝试 如果不行，再等五分钟左右（可能是资源库还没同步），再次重复上述步骤
> 
> 我删了后缀后正常了，只是应该算个失误，跟你提一下

可能是之前资源更新时的失误， 感谢提出
