### ISSUE TITLE
强制刷新报错

### ISSUE THREAD

**Issue by YingLing3** [KimigaiiWuyi/GenshinUID#624]
03-05 16:05:56 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_enka | [强制刷新]uid: 225249141
Task exception was never retrieved
future: <Task finished name='Task-1378' coro=<send_card_info() done, defined at C:\Users\MINI\Desktop\bot\gsuid_core\gsuid_core\sv.py:34> exception=TypeError("'NoneType' object is not iterable")>
Traceback (most recent call last):
  File "C:\Users\MINI\Desktop\bot\gsuid_core\gsuid_core\sv.py", line 37, in wrapper
    result = await func(bot, event)
  File "C:\Users\MINI\Desktop\bot\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_enka\__init__.py", line 334, in send_card_info
    im = await enka_to_card(uid)
  File "C:\Users\MINI\Desktop\bot\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_enka\to_card.py", line 32, in enka_to_card
    char_data_list = await enka_to_dict(uid, enka_data)
  File "C:\Users\MINI\Desktop\bot\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_enka\to_data.py", line 139, in enka_to_dict
    for char in enka_data['avatarInfoList']:
TypeError: 'NoneType' object is not iterable

**Comment by KimigaiiWuyi** [comment]
> 03-05 16:05:56 [INFO] plugins.GenshinUID.GenshinUID.genshinuid_enka | [强制刷新]uid: 225249141 Task exception was never retrieved future: <Task finished name='Task-1378' coro=<send_card_info() done, defined at C:\Users\MINI\Desktop\bot\gsuid_core\gsuid_core\sv.py:34> exception=TypeError("'NoneType' object is not iterable")> Traceback (most recent call last): File "C:\Users\MINI\Desktop\bot\gsuid_core\gsuid_core\sv.py", line 37, in wrapper result = await func(bot, event) File "C:\Users\MINI\Desktop\bot\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_enka__init__.py", line 334, in send_card_info im = await enka_to_card(uid) File "C:\Users\MINI\Desktop\bot\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_enka\to_card.py", line 32, in enka_to_card char_data_list = await enka_to_dict(uid, enka_data) File "C:\Users\MINI\Desktop\bot\gsuid_core\gsuid_core\plugins\GenshinUID\GenshinUID\genshinuid_enka\to_data.py", line 139, in enka_to_dict for char in enka_data['avatarInfoList']: TypeError: 'NoneType' object is not iterable

应该是游戏内展柜开了隐藏,没有展示出来
这块API内容有变动, genshinuid还没处理这里的地方,今晚更新一下错误提示
