### ISSUE TITLE
哪里有XX，任务XX，报错

### ISSUE THREAD

**Issue by dwsxx1** [KimigaiiWuyi/GenshinUID#633]
网站证书过期了，按照文档里教的方法，但找不到小锁在哪
![6ACB809F09E0A47F7BB9F50B38C9CDA8](https://github.com/user-attachments/assets/9996120b-f7b6-40a4-b5dd-a70e476cacbf)

**Comment by dwsxx1** [comment]
前几天还能用这些功能，显示的是7月30号过期的

**Comment by KimigaiiWuyi** [comment]
应该已经恢复

**Comment by dwsxx1** [comment]
感谢大佬
