### ISSUE TITLE
扫码登录过期

### ISSUE THREAD

**Issue by mengluo04** [KimigaiiWuyi/GenshinUID#636]
疑似被风控，昨天在其他机器人扫码登录也是秒过期
![image](https://github.com/user-attachments/assets/e3f7b10f-41a1-4ad5-a711-d69f912dd36b)

**Comment by KimigaiiWuyi** [comment]
应该已修复,
尝试`core全部更新`之后`gs重启`后重试

**Comment by mengluo04** [comment]
> 应该已修复, 尝试`core全部更新`之后`gs重启`后重试

可以了，感谢
