### ISSUE TITLE
【功能建议】体力推送时加上游戏标识

### ISSUE THREAD

**Issue by mengluo04** [KimigaiiWuyi/GenshinUID#637]
现在的信息不能一眼分辨出是哪个游戏的体力推送
![image](https://github.com/user-attachments/assets/c1c6742a-c689-42d4-a49f-e0bd7613aed1)
派遣可领取显示即将可收取
![159da517604b43ac92d20847558d0d5a](https://github.com/user-attachments/assets/af6773ba-a1ce-48eb-90c5-c682a66f49db)
如果能在推送消息里加上`当前体力`就更直观了

**Comment by KimigaiiWuyi** [comment]
可以检查一下优化效果是否符合预期

**Comment by mengluo04** [comment]
> 可以检查一下优化效果是否符合预期

委托已完成是否可以修改为：你的派遣已可收取或者类似的，现在是 你有派遣信息即将可收取，感觉有歧义。
另外，体力阈值推送之后，是否需要在体力满的时候再次推送。
还有便签数据，文字版显示对的，但是图片上周本和参变仪显示数据未知。魔神任务感觉意义不大，不知道能否获取到晶蝶诱捕器的数据
![image](https://github.com/user-attachments/assets/497a9c75-1e6c-4df0-bc36-610efc9f939b)

**Comment by KimigaiiWuyi** [comment]
> > 可以检查一下优化效果是否符合预期
> 
> 委托已完成是否可以修改为：你的派遣已可收取或者类似的，现在是 你有派遣信息即将可收取，感觉有歧义。 另外，体力阈值推送之后，是否需要在体力满的时候再次推送。 还有便签数据，文字版显示对的，但是图片上周本和参变仪显示数据未知。魔神任务感觉意义不大，不知道能否获取到晶蝶诱捕器的数据 ![image](https://private-user-images.githubusercontent.com/32565940/356842416-497a9c75-1e6c-4df0-bc36-610efc9f939b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTI5NjYsIm5iZiI6MTcyMzM1MjY2NiwicGF0aCI6Ii8zMjU2NTk0MC8zNTY4NDI0MTYtNDk3YTljNzUtMWU2Yy00ZGYwLWJjMzYtNjEwZWZjOWY5MzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA1MDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NTY1OWNjNGExZGM1ODNmZmE1OWQ1MzQ1YTAzNjAxMzZjMDQzYzhhYjUyNDYyNjYwN2Q3MjJmMDhlODE2Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LMM9uUsW7WePeFvjnsAjGhWsaiTeYEvES3_aPZsKTdM)

可以在网页控制台配置使用小组件源或者战绩源，战绩源是全的但是有概率触发验证码，小组件源不全但是不会触发验证码

**Comment by KimigaiiWuyi** [comment]
没有晶蝶的数据
如果需要再次推送，可以打开催命模式，即达到阈值之后，每次间隔半小时都会再次提醒

**Comment by mengluo04** [comment]
> > > 可以检查一下优化效果是否符合预期
> > 
> > 
> > 委托已完成是否可以修改为：你的派遣已可收取或者类似的，现在是 你有派遣信息即将可收取，感觉有歧义。 另外，体力阈值推送之后，是否需要在体力满的时候再次推送。 还有便签数据，文字版显示对的，但是图片上周本和参变仪显示数据未知。魔神任务感觉意义不大，不知道能否获取到晶蝶诱捕器的数据 ![image](https://private-user-images.githubusercontent.com/32565940/356842416-497a9c75-1e6c-4df0-bc36-610efc9f939b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTI5NjYsIm5iZiI6MTcyMzM1MjY2NiwicGF0aCI6Ii8zMjU2NTk0MC8zNTY4NDI0MTYtNDk3YTljNzUtMWU2Yy00ZGYwLWJjMzYtNjEwZWZjOWY5MzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA1MDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NTY1OWNjNGExZGM1ODNmZmE1OWQ1MzQ1YTAzNjAxMzZjMDQzYzhhYjUyNDYyNjYwN2Q3MjJmMDhlODE2Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LMM9uUsW7WePeFvjnsAjGhWsaiTeYEvES3_aPZsKTdM)
> 
> 可以在网页控制台配置使用小组件源或者战绩源，战绩源是全的但是有概率触发验证码，小组件源不全但是不会触发验证码

![image](https://github.com/user-attachments/assets/e0603e10-3043-4dcb-99ee-b52a3dcfbee0)
这个吗，是使用的组件的，过码的配了地址和打开了签到和查询的开关，能正常过码的

**Comment by mengluo04** [comment]
> 没有晶蝶的数据 如果需要再次推送，可以打开催命模式，即达到阈值之后，每次间隔半小时都会再次提醒

好的，原来催命模式是干这个的

**Comment by KimigaiiWuyi** [comment]
> > > > 可以检查一下优化效果是否符合预期
> > > 
> > > 
> > > 委托已完成是否可以修改为：你的派遣已可收取或者类似的，现在是 你有派遣信息即将可收取，感觉有歧义。 另外，体力阈值推送之后，是否需要在体力满的时候再次推送。 还有便签数据，文字版显示对的，但是图片上周本和参变仪显示数据未知。魔神任务感觉意义不大，不知道能否获取到晶蝶诱捕器的数据 ![image](https://private-user-images.githubusercontent.com/32565940/356842416-497a9c75-1e6c-4df0-bc36-610efc9f939b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTI5NjYsIm5iZiI6MTcyMzM1MjY2NiwicGF0aCI6Ii8zMjU2NTk0MC8zNTY4NDI0MTYtNDk3YTljNzUtMWU2Yy00ZGYwLWJjMzYtNjEwZWZjOWY5MzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA1MDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NTY1OWNjNGExZGM1ODNmZmE1OWQ1MzQ1YTAzNjAxMzZjMDQzYzhhYjUyNDYyNjYwN2Q3MjJmMDhlODE2Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LMM9uUsW7WePeFvjnsAjGhWsaiTeYEvES3_aPZsKTdM)
> > 
> > 
> > 可以在网页控制台配置使用小组件源或者战绩源，战绩源是全的但是有概率触发验证码，小组件源不全但是不会触发验证码
> 
> ![image](https://private-user-images.githubusercontent.com/32565940/356852147-e0603e10-3043-4dcb-99ee-b52a3dcfbee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTMzMzcsIm5iZiI6MTcyMzM1MzAzNywicGF0aCI6Ii8zMjU2NTk0MC8zNTY4NTIxNDctZTA2MDNlMTAtMzA0My00ZGNiLTk5ZWUtYjUyYTNkY2ZiZWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA1MTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTdhODUzMzlkOWE5MmMwZDdjZTFhMjQ2ODUwMGJlY2I4MjBmYjQ1YWIwZTg3ZjEzZmI5ZWUxZDAyZGQ0ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GKqj5quBJoiQU5yOir0WNOU7jHkgaLIIehPjVCN3424) 这个吗，是使用的组件的，过码的配了地址和打开了签到和查询的开关，能正常过码的

那你可以直接关闭，使用战绩源即可

**Comment by mengluo04** [comment]
> > > > > 可以检查一下优化效果是否符合预期
> > > > 
> > > > 
> > > > 委托已完成是否可以修改为：你的派遣已可收取或者类似的，现在是 你有派遣信息即将可收取，感觉有歧义。 另外，体力阈值推送之后，是否需要在体力满的时候再次推送。 还有便签数据，文字版显示对的，但是图片上周本和参变仪显示数据未知。魔神任务感觉意义不大，不知道能否获取到晶蝶诱捕器的数据 ![image](https://private-user-images.githubusercontent.com/32565940/356842416-497a9c75-1e6c-4df0-bc36-610efc9f939b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTI5NjYsIm5iZiI6MTcyMzM1MjY2NiwicGF0aCI6Ii8zMjU2NTk0MC8zNTY4NDI0MTYtNDk3YTljNzUtMWU2Yy00ZGYwLWJjMzYtNjEwZWZjOWY5MzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA1MDQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NTY1OWNjNGExZGM1ODNmZmE1OWQ1MzQ1YTAzNjAxMzZjMDQzYzhhYjUyNDYyNjYwN2Q3MjJmMDhlODE2Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LMM9uUsW7WePeFvjnsAjGhWsaiTeYEvES3_aPZsKTdM)
> > > 
> > > 
> > > 可以在网页控制台配置使用小组件源或者战绩源，战绩源是全的但是有概率触发验证码，小组件源不全但是不会触发验证码
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/32565940/356852147-e0603e10-3043-4dcb-99ee-b52a3dcfbee0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTMzMzcsIm5iZiI6MTcyMzM1MzAzNywicGF0aCI6Ii8zMjU2NTk0MC8zNTY4NTIxNDctZTA2MDNlMTAtMzA0My00ZGNiLTk5ZWUtYjUyYTNkY2ZiZWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA1MTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwYTdhODUzMzlkOWE5MmMwZDdjZTFhMjQ2ODUwMGJlY2I4MjBmYjQ1YWIwZTg3ZjEzZmI5ZWUxZDAyZGQ0ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GKqj5quBJoiQU5yOir0WNOU7jHkgaLIIehPjVCN3424) 这个吗，是使用的组件的，过码的配了地址和打开了签到和查询的开关，能正常过码的
> 
> 那你可以直接关闭，使用战绩源即可

测试通过，感谢

**Comment by KimigaiiWuyi** [comment]
> > 可以检查一下优化效果是否符合预期
> 
> 委托已完成是否可以修改为：你的派遣已可收取或者类似的，现在是 你有派遣信息即将可收取，感觉有歧义。 另外，体力阈值推送之后，是否需要在体力满的时候再次推送。 还有便签数据，文字版显示对的，但是图片上周本和参变仪显示数据未知。魔神任务感觉意义不大，不知道能否获取到晶蝶诱捕器的数据 ![image](https://private-user-images.githubusercontent.com/32565940/356842416-497a9c75-1e6c-4df0-bc36-610efc9f939b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTYxMDUsIm5iZiI6MTcyMzM1NTgwNSwicGF0aCI6Ii8zMjU2NTk0MC8zNTY4NDI0MTYtNDk3YTljNzUtMWU2Yy00ZGYwLWJjMzYtNjEwZWZjOWY5MzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA1NTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YTAzNTNhMzRhOGM3NjhkOTEwYzFmYWZlMGM5M2U0MzRhMzkzYzIyZmFkODk3MjhkMGIxMDNhNDBmNzNlNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jlj7OQhih9z7KJ9oA5w25VKmdFv3dCPW_inPCn6JMY)

现在的提示应该是 `你有派遣奖励即将可领取！` 应该没有歧义了吧

**Comment by mengluo04** [comment]
> > > 可以检查一下优化效果是否符合预期
> > 
> > 
> > 委托已完成是否可以修改为：你的派遣已可收取或者类似的，现在是 你有派遣信息即将可收取，感觉有歧义。 另外，体力阈值推送之后，是否需要在体力满的时候再次推送。 还有便签数据，文字版显示对的，但是图片上周本和参变仪显示数据未知。魔神任务感觉意义不大，不知道能否获取到晶蝶诱捕器的数据 ![image](https://private-user-images.githubusercontent.com/32565940/356842416-497a9c75-1e6c-4df0-bc36-610efc9f939b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTYxMDUsIm5iZiI6MTcyMzM1NTgwNSwicGF0aCI6Ii8zMjU2NTk0MC8zNTY4NDI0MTYtNDk3YTljNzUtMWU2Yy00ZGYwLWJjMzYtNjEwZWZjOWY5MzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA1NTY0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YTAzNTNhMzRhOGM3NjhkOTEwYzFmYWZlMGM5M2U0MzRhMzkzYzIyZmFkODk3MjhkMGIxMDNhNDBmNzNlNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jlj7OQhih9z7KJ9oA5w25VKmdFv3dCPW_inPCn6JMY)
> 
> 现在的提示应该是 `你有派遣奖励即将可领取！` 应该没有歧义了吧

应该差不多吧，想不到更好的，说 已完成 也不太对
