### ISSUE TITLE
【bug】gspush的model中少了sr_uid字段导致sr的push报错

### ISSUE THREAD

**Issue by mengluo04** [KimigaiiWuyi/GenshinUID#640]
get_gameid_name方法里面写了
![image](https://github.com/user-attachments/assets/5053adcd-3951-4777-9688-d5bf1fa40415)
但是GsPush的midel中没有定义
![image](https://github.com/user-attachments/assets/adaf19d0-c35f-499f-82f3-5d34c5c7bb71)
sr推送
GsPush.select_data_by_uid(user.sr_uid, 'sr')
报错
AttributeError: sr_uid

**Comment by KimigaiiWuyi** [comment]
理论上SR应该自己单开一个推送表的

**Comment by mengluo04** [comment]
> 理论上SR应该自己单开一个推送表的

有道理（）

**Comment by Jerry-FaGe** [comment]
[gsuid_core/utils/database/dal.py](https://github.com/Genshin-bots/gsuid_core/blob/master/gsuid_core/utils/database/dal.py)

```python
async def update_push_data(
        self, uid: str, bot_id: str, data: dict
    ) -> bool:
        retcode = -1
        if await GsPush.data_exist(uid=uid):
            retcode = await GsPush.update_data_by_uid(
                # uid, self.bot_id, 'sr' if self.is_sr else None, **data
                uid, self.bot_id, None, **data
            )
        else:
            retcode = await GsPush.full_insert_data(
                uid=uid, bot_id=bot_id, **data
            )
        status = True if retcode == 0 else False
        return status
```

**Comment by mengluo04** [comment]
> [gsuid_core/utils/database/dal.py](https://github.com/Genshin-bots/gsuid_core/blob/master/gsuid_core/utils/database/dal.py)
> 
> ```python
> async def update_push_data(
>         self, uid: str, bot_id: str, data: dict
>     ) -> bool:
>         retcode = -1
>         if await GsPush.data_exist(uid=uid):
>             retcode = await GsPush.update_data_by_uid(
>                 # uid, self.bot_id, 'sr' if self.is_sr else None, **data
>                 uid, self.bot_id, None, **data
>             )
>         else:
>             retcode = await GsPush.full_insert_data(
>                 uid=uid, bot_id=bot_id, **data
>             )
>         status = True if retcode == 0 else False
>         return status
> ```

尝试过问题不在这里，在上一步就报错了。我应该把问题tidaocore那边，调用的是core的方法

**Comment by mengluo04** [comment]
> 理论上SR应该自己单开一个推送表的

感觉这东西应该和core解耦，开关和阈值什么的在插件里面配置

**Comment by KimigaiiWuyi** [comment]
> > 理论上SR应该自己单开一个推送表的
> 
> 感觉这东西应该和core解耦，开关和阈值什么的在插件里面配置

是的 SR那边可以通过继承模型的方式去处理, 我这周和sr的作者处理一下

**Comment by mengluo04** [comment]
> > > 理论上SR应该自己单开一个推送表的
> > 
> > 
> > 感觉这东西应该和core解耦，开关和阈值什么的在插件里面配置
> 
> 是的 SR那边可以通过继承模型的方式去处理, 我这周和sr的作者处理一下

膜拜大佬🫡🫡🫡🫡🫡

**Comment by Jerry-FaGe** [comment]
> > [gsuid_core/utils/database/dal.py](https://github.com/Genshin-bots/gsuid_core/blob/master/gsuid_core/utils/database/dal.py)
> > ```python
> > async def update_push_data(
> >         self, uid: str, bot_id: str, data: dict
> >     ) -> bool:
> >         retcode = -1
> >         if await GsPush.data_exist(uid=uid):
> >             retcode = await GsPush.update_data_by_uid(
> >                 # uid, self.bot_id, 'sr' if self.is_sr else None, **data
> >                 uid, self.bot_id, None, **data
> >             )
> >         else:
> >             retcode = await GsPush.full_insert_data(
> >                 uid=uid, bot_id=bot_id, **data
> >             )
> >         status = True if retcode == 0 else False
> >         return status
> > ```
> 
> 尝试过问题不在这里，在上一步就报错了。我应该把问题tidaocore那边，调用的是core的方法

我是要告诉你既然没有 `sr` 标识就不要管那个字段，把 sr 当 gs 用，这是我用了半年多的临时解决方案，sr 还没换库的时候我就在研究这东西了

[StarRailUID/starrailuid_stamina/notice.py](https://github.com/baiqwerdvd/StarRailUID/blob/master/StarRailUID/starrailuid_stamina/notice.py)
```python
async def get_notice_list() -> Dict[str, Dict[str, Dict]]:
    msg_dict: Dict[str, Dict[str, Dict]] = {}
    for _ in gss.active_bot:
        user_list = await GsUser.get_all_push_user_list()
        for user in user_list:
            if user.sr_uid is not None:
                raw_data = await mys_api.get_daily_data(user.sr_uid)
                if isinstance(raw_data, int):
                    logger.error(f'[sr推送提醒]获取{user.sr_uid}的数据失败!')
                    continue
                # push_data = await GsPush.select_data_by_uid(user.sr_uid, 'sr')
                push_data = await GsPush.select_data_by_uid(user.sr_uid, None)
                msg_dict = await all_check(
                    user.bot_id,
                    raw_data,
                    push_data.__dict__,
                    msg_dict,
                    user.user_id,
                    user.sr_uid,
                )
    return msg_dict
```
![image](https://github.com/user-attachments/assets/e3faa49e-d91d-4291-b212-90cb1a74e355)
