### ISSUE TITLE
【bug】米游社游戏签到推送没有正确将cq码转为at消息

### ISSUE THREAD

**Issue by mengluo04** [KimigaiiWuyi/GenshinUID#642]
![image](https://github.com/user-attachments/assets/bcd9714c-71ad-4cd5-b5eb-3ded7f393c6e)

**Comment by KimigaiiWuyi** [comment]
请`core全部更新`之后检查是否正常

**Comment by mengluo04** [comment]
> 请`core全部更新`之后检查是否正常

已正常，没有at消息了，只有文本
