### ISSUE TITLE
【bug】初次使用米游社代替enka会报错文件不存在

### ISSUE THREAD

**Issue by mengluo04** [KimigaiiWuyi/GenshinUID#645]
![image](https://github.com/user-attachments/assets/27d303b4-d807-47fb-a978-b2c09bda4b23)
对比了一下enka的代码，发现少了这个` path.mkdir(parents=True, exist_ok=True)`，路径不存在时没有自动创建，write失败了

**Comment by KimigaiiWuyi** [comment]
应该已修复
