### ISSUE TITLE
【功能建议】便签图片增加洞天宝钱和委托完成 情况展示

### ISSUE THREAD

**Issue by mengluo04** [KimigaiiWuyi/GenshinUID#648]
看了下战绩里面的便签接口是可以获取到这两个数据的，体力桌面组件也可以获取到洞天宝钱和委托信息
![b2f3d26af333064a05394319841210e](https://github.com/user-attachments/assets/adb350ee-a9d6-4fbc-b93b-10ef5e684e43)

**Comment by KimigaiiWuyi** [comment]
洞天宝钱和委托完成情况`mr`功能不是有信息么
![image](https://github.com/user-attachments/assets/929c5afc-b586-4928-b276-836b2471b6d9)

**Comment by mengluo04** [comment]
> 洞天宝钱和委托完成情况`mr`功能不是有信息么 ![image](https://private-user-images.githubusercontent.com/55526518/359409419-929c5afc-b586-4928-b276-836b2471b6d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDQ3MjIsIm5iZiI6MTcyNDE0NDQyMiwicGF0aCI6Ii81NTUyNjUxOC8zNTk0MDk0MTktOTI5YzVhZmMtYjU4Ni00OTI4LWIyNzYtODM2YjI0NzFiNmQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA5MDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5MDI3MWQ0NjQwMjdhMDg3ZDg4M2U5ZmI3YTI2ZTc2NDQzMTlmZTc0OGRlYTc1MmM1NWQzZWE1NTVlYWE0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JUOhC9782BbQmdZUWPpF6wODv4fKwORg2Ed4aTC0Aq0)

眼睛瞎了，没注意到😰
