### ISSUE TITLE
查询指令出错

### ISSUE THREAD

**Issue by lgc2333** [KimigaiiWuyi/GenshinUID#65]
```
12-25 16:23:21 [SUCCESS] nonebot | CQHTTP 3436954762 | [message.group.normal]: Message -912602555 from 3076823485@[群:1158894874] "查询"
12-25 16:23:21 [INFO] nonebot | Event will be handled by <Matcher from GenshinUID, type=message, priority=6, temp=False>
12-25 16:23:22 [SUCCESS] nonebot | CQHTTP 3436954762 | [message_sent]: {'time': 1640420602, 'self_id': 3436954762, 'post_type': 'message_sent', 'user_id': 3436954762, 'sub_type': 'normal', 'raw_message': '输入错误！', 'group_id': 1158894874, 'font': 0, 'message': [{'data': {'text': '输入错误！'}, 'type': 'text'}], 'message_id': 1476288486, 'message_type': 'group', 'anonymous': None, 'message_seq': 20484, 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': 'Shigure~', 'role': 'admin', 'sex': 'unknown', 'title': '', 'user_id': 3436954762}}
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2\nonebot2/plugins\GenshinUID\__init__.py", line 526, in _
    bg = await draw_pic(uid[0], nickname, image, uid[1])
  File "C:\Users\Administrator\Desktop\stu-files\bot\go-cq\nonebot2\nonebot2/plugins\GenshinUID\getImg.py", line 858, in draw_pic
    for i in mys_data['data']['list']:
TypeError: string indices must be integers
```
为啥都不print一下 不好定位错误

**Comment by lgc2333** [comment]
是cookies问题吗

**Comment by KimigaiiWuyi** [comment]
> 是cookies问题吗

你挂在vps上了，现在vps上全挂了

**Comment by KimigaiiWuyi** [comment]
[这里](https://github.com/Arondight/Adachi-BOT/issues/520)

**Comment by lgc2333** [comment]
> 

草

**Comment by lgc2333** [comment]
> > 是cookies问题吗
> 
> 你挂在vps上了，现在vps上全挂了

草

**Comment by lgc2333** [comment]
测试了 挂了vpn就没屏蔽

**Comment by KimigaiiWuyi** [comment]
> 测试了 挂了vpn就没屏蔽

挂公共代理池之类的可以绕过吗，想看看有没有通解

**Comment by lgc2333** [comment]
> 测试了 挂了vpn就没屏蔽

![image](https://user-images.githubusercontent.com/59048777/147381174-82900285-e973-45b5-a7fb-91af22192846.png)
![image](https://user-images.githubusercontent.com/59048777/147381193-7e4b30c6-b931-4f50-a198-0552dc29c099.png)

**Comment by lgc2333** [comment]
> 测试了 挂了vpn就没屏蔽

嘶刚刚一不小心IP暴露了
![image](https://user-images.githubusercontent.com/59048777/147381234-caa46bde-17bf-4c78-bd4e-927105053110.png)
![image](https://user-images.githubusercontent.com/59048777/147381247-dc04e12f-dcd5-4d6b-9485-be50abea05b6.png)

**Comment by lgc2333** [comment]
![image](https://user-images.githubusercontent.com/59048777/147381267-fd58afaf-137f-4e1d-85b7-7696ac0446a7.png)

**Comment by lgc2333** [comment]
浏览器可以访问 在项目上用环境变量设置代理就不行了

**Comment by lgc2333** [comment]
> > 测试了 挂了vpn就没屏蔽
> 
> 挂公共代理池之类的可以绕过吗，想看看有没有通解

可以用代理试试 写在配置文件里
我没有时间写qwq

**Comment by Putarku** [comment]
> > 是饼干问题吗
> 
> 你挂在vps上，现在vps上全挂了

貌似现在vps的又好了，可以测试下试试，我自己腾讯云的今天下午突然没问题了

**Comment by KimigaiiWuyi** [comment]
统一在这里讨论吧 #60
