### ISSUE TITLE
【功能建议】增加前瞻兑换码查询功能

### ISSUE THREAD

**Issue by mengluo04** [KimigaiiWuyi/GenshinUID#650]

**Comment by KimigaiiWuyi** [comment]
nb2有gscode插件了，当时作者也在我群里，所以不是很想做重复的功能
不过现在作者神隐了，倒是可以搬过来了

**Comment by mengluo04** [comment]
> nb2有gscode插件了，当时作者也在我群里，所以不是很想做重复的功能 不过现在作者神隐了，倒是可以搬过来了

那个插件我用过，甚至想把zzz的也加进去

**Comment by KimigaiiWuyi** [comment]
#654
