### ISSUE TITLE
gs查询角色问题

### ISSUE THREAD

**Issue by dwsxx1** [KimigaiiWuyi/GenshinUID#658]
已确定插件依赖core版本都为最新
输入查询角色显示如下
![B10228A961CBDE1B3FA56515AF456DD4](https://github.com/user-attachments/assets/7fc75fbc-b648-4015-bb3c-90e2712e1efc)

**Comment by KimigaiiWuyi** [comment]
这是在查哪个角色
还是说所有角色/所有用户都会这样

**Comment by dwsxx1** [comment]
妮露，问题gs强制刷新的指令也会出这个报错，但bot会发出刷新成功的回复，查询就没有回复了

**Comment by dwsxx1** [comment]
所有角色所有用户都一样

**Comment by dwsxx1** [comment]
绝区零的角色查询一切正常

**Comment by KimigaiiWuyi** [comment]
我这边似乎无法复现你说的问题, 如果更新新版本之后还有问题, 可以尝试开启gscore的`DEBUG`模式, 再截图日志查看

**Comment by dwsxx1** [comment]
怎么开启这个模式，今天重新下载了插件，现在是gs强制刷新命令无报错但bot回复错误500可能是网络波动，然后查询角色依旧还是上面的报错

**Comment by KimigaiiWuyi** [comment]
> 怎么开启这个模式，今天重新下载了插件，现在是gs强制刷新命令无报错但bot回复错误500可能是网络波动，然后查询角色依旧还是上面的报错

![image](https://github.com/user-attachments/assets/9ad79c63-bd22-487c-909c-5465cc8672a0)

`gs强制刷新`是由于今天游戏更新了, ENKA服务尚未切换, 你可以使用米游社更新面板代替ENKA服务

**Comment by dwsxx1** [comment]
无法更新依赖
![Uploading BFABC2B8B6FE8137F673C071E5D77A7A.png…]()

**Comment by dwsxx1** [comment]
无法更新依赖
![BFABC2B8B6FE8137F673C071E5D77A7A](https://github.com/user-attachments/assets/50d6fde0-1bc2-4551-b48c-f2951f3cd4ff)
![B9BC37A66CFA1E5826FEBABD064EBFA6](https://github.com/user-attachments/assets/419521ba-5b2d-4b2d-b419-2bd9061b8351)

**Comment by KimigaiiWuyi** [comment]
这个报错无需关心

**Comment by KimigaiiWuyi** [comment]
这次应该不会出现网络访问的问题了
使用`core全部更新` 同时更新两者之后 `gs重启` 稍等资源下载后 再使用`gs强制刷新`和`gs查询妮露`应该就ok了
