### ISSUE TITLE
无数据使用圣遗物仓库报错

### ISSUE THREAD

**Issue by CM-Edelweiss** [KimigaiiWuyi/GenshinUID#663]
没有面板数据的uid直接使用[圣遗物仓库]会报错

**Comment by CM-Edelweiss** [comment]
![Screenshot_20241223_095702](https://github.com/user-attachments/assets/4179ed92-fa1c-44b3-9ee5-74a590daf037)

**Comment by KimigaiiWuyi** [comment]
更新后应该已修复
