### ISSUE TITLE
请问要怎么在nonebot2上使用呢？

### ISSUE THREAD

**Issue by bcbs-352** [KimigaiiWuyi/GenshinUID#67]
九月份是装在hoshino/moudules/这边的，部署完能正常运行，前段时间更新了一下，结果发现不能用了。现在安装了nonebot2，直接放在src/Plugins文件夹里运行不了吧
新手不太了解。。。

**Comment by KimigaiiWuyi** [comment]
切换到nb2分支有教程 还有就是去nb2那看部署教程
hoshino现在1也是能用的，只不过因为vps问题，部署在vps上的不能用了，可以看看其他issues
