### ISSUE TITLE
当天添加Cookie问题

### ISSUE THREAD

**Issue by 741807012** [KimigaiiWuyi/GenshinUID#68]
某人今天没添加Cookie查询过后,然后添加Cookie再查询不能调用自己的Cookie

**Comment by KimigaiiWuyi** [comment]
因为有缓存的存在，当天查询过后就锁定了都用这个ck查询；后续看看能不能添加的时候顺便直接刷新缓存好了，优先级较低

**Comment by KimigaiiWuyi** [comment]
已修复~
