### ISSUE TITLE
大佬，关于频道bot

### ISSUE THREAD

**Issue by a970703218** [KimigaiiWuyi/GenshinUID#69]
申请是需要什么资格吗？感觉没入口似的。

**Comment by KimigaiiWuyi** [comment]
https://bot.q.qq.com/wiki/develop/api/
左上角可以看到机器人平台
需要自行注册；请自行阅读好相关细则

**Comment by a970703218** [comment]
> https://bot.q.qq.com/wiki/develop/api/ 右上角可以看到机器人平台 需要自行注册；请自行阅读好相关细则

好的 感谢大佬！
不知道我注册好了能否参与genshin插件的频道版测试？

**Comment by KimigaiiWuyi** [comment]
> > https://bot.q.qq.com/wiki/develop/api/ 右上角可以看到机器人平台 需要自行注册；请自行阅读好相关细则
> 
> 好的 感谢大佬！ 不知道我注册好了能否参与genshin插件的频道版测试？

我昨天就传了新分支，可以自己试用；有Bug和建议提Issuse就好

**Comment by a970703218** [comment]
> > > https://bot.q.qq.com/wiki/develop/api/ 右上角可以看到机器人平台 需要自行注册；请自行阅读好相关细则
> > 
> > 
> > 好的 感谢大佬！ 不知道我注册好了能否参与genshin插件的频道版测试？
> 
> 我昨天就传了新分支，可以自己试用；有Bug和建议提Issuse就好

谢谢大佬，非常感谢！
