### ISSUE TITLE
希望加一个uid绑定QQ的功能

### ISSUE THREAD

**Issue by likingsdee** [KimigaiiWuyi/GenshinUID#7]
由于我所在的群成份比较杂，所以群名片基本都是不带uid的，每次进行查询都要先上游戏找一下uid，我希望查询过一次自己uid信息之后，会自动绑定qq和uid，这样下次查询就不用去找自己的uid了

**Comment by KimigaiiWuyi** [comment]
已更新，具体使用方法查阅更新记录~
如果测试没有问题后，麻烦关闭issues
