### ISSUE TITLE
Cookie校验失败

### ISSUE THREAD

**Issue by King-Nameless** [KimigaiiWuyi/GenshinUID#70]
Cookie一直校验失败，绑定mys通行证提示成功，但使用查询之类的功能就提示输入错误，游戏uid没试，其他的就发现不需要绑定的功能，例如活动列表，角色、武器材料之类的可以使用

**Comment by KimigaiiWuyi** [comment]
使用了老api还是新api？

**Comment by loveyoutan90** [comment]
我经过这次更新后发现，添加不了20个以上cookies，添加第21个的时候会导致已添加的随机一个cookies失效

**Comment by King-Nameless** [comment]
> 使用了老api还是新api？

不清楚，出问题的当天装的插件，不过今天睡不着，看到更新了就给插件重装了下，只绑定mys通行证的话，查询命令提示输入错误，继续把uid也绑了才能用，cookie添加也没问题了，功能正常使用
推送和签到功能很棒，就个人感觉来说，只有查询显示的图感觉不太好看，5星和4星的角色背景颜色太淡了点，不如游戏中那样好看

**Comment by KimigaiiWuyi** [comment]
> 我经过这次更新后发现，添加不了20个以上cookies，添加第21个的时候会导致已添加的随机一个cookies失效

按道理来说 不应该会有这种问题，有经过多次尝试确定复现吗？
失效的CK是不是确实是因为过期才导致失效了？

**Comment by King-Nameless** [comment]
> > 我经过这次更新后发现，添加不了20个以上cookies，添加第21个的时候会导致已添加的随机一个cookies失效
> 
> 按道理来说 不应该会有这种问题，有经过多次尝试确定复现吗？ 失效的CK是不是确实是因为过期才导致失效了？

应该没有吧，cookie是我今天早上刚弄的最新的，我傍晚mys后查询了2、3次，然后就把uid绑了，之后就能用了，不确定重试会不会还出错

**Comment by loveyoutan90** [comment]
不是因为过期，因为我绑定了自己cookies结果第二天就无法使用了，我校验了一下，提示该条cookies以失效就直接删除了，然后我再次绑定我的cookies，就正常了可以签到，然后群里有个小伙伴绑定cookies，他绑定成功了，过来一会我查看状态的时候提示cookies未绑定，我校验全部cookies又提示我那一条cookies失效，然后我再次绑定，再次校验cookies，结果显示另一条cookies以失效，目前只有20条cookies

**Comment by loveyoutan90** [comment]
我这个添加cookies也有问题，返回添加失败，但是校验cookies的时候却有

**Comment by KimigaiiWuyi** [comment]
> 不是因为过期，因为我绑定了自己cookies结果第二天就无法使用了，我校验了一下，提示该条cookies以失效就直接删除了，然后我再次绑定我的cookies，就正常了可以签到，然后群里有个小伙伴绑定cookies，他绑定成功了，过来一会我查看状态的时候提示cookies未绑定，我校验全部cookies又提示我那一条cookies失效，然后我再次绑定，再次校验cookies，结果显示另一条cookies以失效，目前只有20条cookies

我尝试添加到20条以上CK未能复现；（之前其实加了几百条也没事）；
不过之前确实是有刚获取的ck几分钟就失效的情况，我怀疑应该就是ck快速失效
正常来说不修改密码的时候ck失效大约在3个月左右，之前有刚获取到几分钟就失效的例子，我也不知道是为什么，过几天再获取ck就正常了；
添加Ck说失败，校验却有，这个可能的原因蛮多，我需要再排查一下；
如果使用的是hoshino版本的话，我可能确实没办法一一去复现了（因为我现在用的nb2（逃

**Comment by loveyoutan90** [comment]
就是nb2的话就目前这个插件安装我没找到方法




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月1日(星期六) 晚上7:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] Cookie校验失败 (Issue #70)





  
不是因为过期，因为我绑定了自己cookies结果第二天就无法使用了，我校验了一下，提示该条cookies以失效就直接删除了，然后我再次绑定我的cookies，就正常了可以签到，然后群里有个小伙伴绑定cookies，他绑定成功了，过来一会我查看状态的时候提示cookies未绑定，我校验全部cookies又提示我那一条cookies失效，然后我再次绑定，再次校验cookies，结果显示另一条cookies以失效，目前只有20条cookies
  
我尝试添加到20条以上CK未能复现；（之前其实加了几百条也没事）；
 不过之前确实是有刚获取的ck几分钟就失效的情况，我怀疑应该就是ck快速失效
 正常来说不修改密码的时候ck失效大约在3个月左右，之前有刚获取到几分钟就失效的例子，我也不知道是为什么，过几天再获取ck就正常了；
 添加Ck说失败，校验却有，这个可能的原因蛮多，我需要再排查一下；
 如果使用的是hoshino版本的话，我可能确实没办法一一去复现了（因为我现在用的nb2（逃
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
