### ISSUE TITLE
群友不清体力，一直推送

### ISSUE THREAD

**Issue by 3273576540** [KimigaiiWuyi/GenshinUID#71]
群友一直不清体力一直推送，超级用户能关别人的体力推送嘛

**Comment by KimigaiiWuyi** [comment]
这个我倒是没想到……目前可以直接修改数据库实现；
不过考虑到大多数人确实不会去动数据库，下次更新加进去吧
希望是一个怎么样的方式呢？`@xxx 关闭推送`这样吗？

**Comment by 3273576540** [comment]
可以，这样挺好

**Comment by KimigaiiWuyi** [comment]
> 可以，这样挺好

更新后尝试一下，命令为 `关闭推送 @xxx`
开启/关闭 还有 推送/自动签到 都能用，命令前置，at后置才能触发；
有bug及时反馈。

**Comment by Mateoust** [comment]
可以增加推送次数的限制来解决吗？例如一天之内推送2次。

**Comment by KimigaiiWuyi** [comment]
> 可以增加推送次数的限制来解决吗？例如一天之内推送2次。

推送两次 万一错过了怎么办

**Comment by 3273576540** [comment]
貌似还是没反应  关闭推送@xxx
hoshinobot

**Comment by KimigaiiWuyi** [comment]
> 貌似还是没反应 关闭推送@xxx hoshinobot

后台报什么错

**Comment by 3273576540** [comment]
貌似是关的自己的，cmd是关键词触发嘛。
如果我没绑ck发指令就显示未绑，如果我绑了我的ck，发指令则只显示成功
实则群友的没取消，取消的是我的。

**Comment by KimigaiiWuyi** [comment]
> 貌似是关的自己的，cmd是关键词触发嘛。 如果我没绑ck发指令就显示未绑，如果我绑了我的ck，发指令则只显示成功 实则群友的没取消，取消的是我的。

尝试更新一下新代码再试一下；
我现在没有在用hoshino，不知道hoshino那边的管理员命令写的对不对（

**Comment by 3273576540** [comment]
好，谢大佬

**Comment by KimigaiiWuyi** [comment]
> 好，谢大佬

记得给反馈 以便更好地定位问题
