### ISSUE TITLE
深渊无法查询

### ISSUE THREAD

**Issue by King-Nameless** [KimigaiiWuyi/GenshinUID#73]
其他功能都正常，包括查询功能，但是查询深渊发出后提示输入错误，用uid或者mys查深渊也是提示输入错误

**Comment by KimigaiiWuyi** [comment]
> 其他功能都正常，包括查询功能，但是查询深渊发出后提示输入错误，用uid或者mys查深渊也是提示输入错误

用的hoshino版本还是nonebot2版本

**Comment by King-Nameless** [comment]
> > 其他功能都正常，包括查询功能，但是查询深渊发出后提示输入错误，用uid或者mys查深渊也是提示输入错误
> 
> 用的hoshino版本还是nonebot2版本

用的hoshino版本

**Comment by King-Nameless** [comment]
另外刚刚使用时发现没有推送派遣完成的功能，这个不能添加吗，我觉得机器人最好用的就是签到和推送这2个功能了
![E51E3141774C97EC5ACF5EA3DC872437](https://user-images.githubusercontent.com/83447487/147845815-3f568fac-2697-4f8c-ae0e-632168aada1d.jpg)

**Comment by KimigaiiWuyi** [comment]
> 其他功能都正常，包括查询功能，但是查询深渊发出后提示输入错误，用uid或者mys查深渊也是提示输入错误

你确定你这次深渊有打吗（或者刚打完没多久，米游社有延迟），如果没数据源是生成不出图片的；
你可以试试查询上期深渊看看能不能生成

**Comment by KimigaiiWuyi** [comment]
> 另外刚刚使用时发现没有推送派遣完成的功能，这个不能添加吗，我觉得机器人最好用的就是签到和推送这2个功能了 ![E51E3141774C97EC5ACF5EA3DC872437](https://user-images.githubusercontent.com/83447487/147845815-3f568fac-2697-4f8c-ae0e-632168aada1d.jpg)

派遣完成可以添加，虽然个人感觉必要性不大，一般都是一天收一次菜；所以优先级较低

**Comment by King-Nameless** [comment]
> > 另外刚刚使用时发现没有推送派遣完成的功能，这个不能添加吗，我觉得机器人最好用的就是签到和推送这2个功能了 ![E51E3141774C97EC5ACF5EA3DC872437](https://user-images.githubusercontent.com/83447487/147845815-3f568fac-2697-4f8c-ae0e-632168aada1d.jpg)
> 
> 派遣完成可以添加，虽然个人感觉必要性不大，一般都是一天收一次菜；所以优先级较低

emmm，我深渊没打，刚刚群里打的人查出来了，我不管是查自己的，还是查打的人的，都提示错误_(:зゝ∠)_ 
因为我没刻晴，没有5个减派遣时间的，有一个派遣会多出来5小时左右，我可以把4个再去派遣一次4小时的任务，有推送的话比较方便

**Comment by KimigaiiWuyi** [comment]
> > > 另外刚刚使用时发现没有推送派遣完成的功能，这个不能添加吗，我觉得机器人最好用的就是签到和推送这2个功能了 ![E51E3141774C97EC5ACF5EA3DC872437](https://user-images.githubusercontent.com/83447487/147845815-3f568fac-2697-4f8c-ae0e-632168aada1d.jpg)
> > 
> > 
> > 派遣完成可以添加，虽然个人感觉必要性不大，一般都是一天收一次菜；所以优先级较低
> 
> emmm，我深渊没打，刚刚群里打的人查出来了_(:зゝ∠)_ 因为我没刻晴，没有5个减派遣时间的，有一个派遣会多出来5小时左右，我可以把4个再去派遣一次4小时的任务，有推送的话比较方便

打的人能查出来就ok啦，没打的查不出来是正常的
