### ISSUE TITLE
nonebot2

### ISSUE THREAD

**Issue by loveyoutan90** [KimigaiiWuyi/GenshinUID#74]
我查找了很多文档，暂时不清楚如何将GenshinUID插件加载到nonebot2，我通过nb2的文档加载插件目录的方法将该插件放到plugins下，但是无法加载。有适配nb2的方法嘛

**Comment by KimigaiiWuyi** [comment]
切换本项目到nb2分支，那里有安装方法。
nb2文档里也有添加插件方法，视你安装nb2时所选插件目录而定

**Comment by loveyoutan90** [comment]
好的，谢谢，麻烦大佬了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月3日(星期一) 中午11:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [KimigaiiWuyi/GenshinUID] nonebot2 (Issue #74)





 
切换本项目到nb2分支，那里有安装方法。
 nb2文档里也有添加插件方法，视你安装nb2时所选插件目录而定
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by loveyoutan90** [comment]
我今天删掉了nb1换了nb2，加载好插件，但是命令无响应，然后nb2也报错，nonebot | running matcher <matcher from src.plugins.GeninUID,type=message,priority=2,temp=False> failed 。问了官方群里面的人也解决不了，他们还认为我在骗他们，最开始命令完全没有反应，后来添加.env配置后就开始报错了，问了一下午没解决，只有问问大佬您了，打扰了

**Comment by KimigaiiWuyi** [comment]
> 我今天删掉了nb1换了nb2，加载好插件，但是命令无响应，然后nb2也报错，nonebot | running matcher <matcher from src.plugins.GeninUID,type=message,priority=2,temp=False> failed 。问了官方群里面的人也解决不了，他们还认为我在骗他们，最开始命令完全没有反应，后来添加.env配置后就开始报错了，问了一下午没解决，只有问问大佬您了，打扰了

插件确认加载无报错吗？
看一看启动log和.env还有bot.py的配置？

**Comment by loveyoutan90** [comment]
成功加载后没有任何报错，但是命令不响应，然后配置了一下.env，查询命令有响应了，但是nb2单方面报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KimigaiiWuyi/GenshinUID"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 晚上7:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] nonebot2 (Issue #74)





  
我今天删掉了nb1换了nb2，加载好插件，但是命令无响应，然后nb2也报错，nonebot | running matcher <matcher from src.plugins.GeninUID,type=message,priority=2,temp=False&gt; failed 。问了官方群里面的人也解决不了，他们还认为我在骗他们，最开始命令完全没有反应，后来添加.env配置后就开始报错了，问了一下午没解决，只有问问大佬您了，打扰了
  
插件确认加载无报错吗？
 看一看启动log和.env还有bot.py的配置？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KimigaiiWuyi** [comment]
> 成功加载后没有任何报错，但是命令不响应，然后配置了一下.env，查询命令有响应了，但是nb2单方面报错
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "KimigaiiWuyi/GenshinUID" ***@***.***&gt;; 发送时间:&nbsp;2022年1月3日(星期一) 晚上7:45 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [KimigaiiWuyi/GenshinUID] nonebot2 (Issue #74) 我今天删掉了nb1换了nb2，加载好插件，但是命令无响应，然后nb2也报错，nonebot | running matcher <matcher from src.plugins.GeninUID,type=message,priority=2,temp=False&gt; failed 。问了官方群里面的人也解决不了，他们还认为我在骗他们，最开始命令完全没有反应，后来添加.env配置后就开始报错了，问了一下午没解决，只有问问大佬您了，打扰了 插件确认加载无报错吗？ 看一看启动log和.env还有bot.py的配置？ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我主要想看看你怎么配置的，你插件是nonebot2目录下的吗

**Comment by lgc2333** [comment]
> 我今天删掉了nb1换了nb2，加载好插件，但是命令无响应，然后nb2也报错，nonebot | running matcher <matcher from src.plugins.GeninUID,type=message,priority=2,temp=False> failed 。问了官方群里面的人也解决不了，他们还认为我在骗他们，最开始命令完全没有反应，后来添加.env配置后就开始报错了，问了一下午没解决，只有问问大佬您了，打扰了

报错信息呢
Traceback...

**Comment by KimigaiiWuyi** [comment]
超过时限
