### ISSUE TITLE
多渊下宫了

### ISSUE THREAD

**Issue by 741807012** [KimigaiiWuyi/GenshinUID#75]
现在机器人是不是更新中了，查询不正常了

**Comment by KimigaiiWuyi** [comment]
预计今晚修复

**Comment by KimigaiiWuyi** [comment]
已修复，连带更新的`语音`指令（需要FFmpeg环境）也可以测试一下，如果没有问题可以关闭issuse

**Comment by King-Nameless** [comment]
> 已修复，连带更新的`语音`指令（需要FFmpeg环境）也可以测试一下，如果没有问题可以关闭issuse

不行啊，用的HoshinoBot，查询还是错误

**Comment by KimigaiiWuyi** [comment]
> > 已修复，连带更新的`语音`指令（需要FFmpeg环境）也可以测试一下，如果没有问题可以关闭issuse
> 
> 不行啊，用的HoshinoBot，查询还是错误

报的什么错误，或者直接加我Q吧444835641
