### ISSUE TITLE
活动列表报错

### ISSUE THREAD

**Issue by ZhouYingSASA** [KimigaiiWuyi/GenshinUID#76]
cqhttp报错
```
> [2022-01-05 20:16:23] [WARNING]: 转换CQ码 ({"type": "image", "data": {"file": "file://src/plugins/GenshinUID/mys/event.jpg"}}) 到MiraiGo Element时出现错误: file not found 将忽略本段CQ码.
> [2022-01-05 20:16:23] [WARNING]: 好友消息发送失败: 消息为空.
```

看起来获取到了相对 nonebot2 (`~/GenshinBot/`)的路径。我机器上的正确路径应该是 `~/GenshinBot/src/plugins/GenshinUID/mys/event.jpg` 。我是用 screen 跑的，不知道是否有影响。
PS: 目前我在期末繁忙期，暂时没有时间提 PR。

**Comment by lgc2333** [comment]
已发pr，等待merge

**Comment by ZhouYingSASA** [comment]
不过现在的活动列表有没有发现一个问题。。这个日期有点喜感

**Comment by ZhouYingSASA** [comment]
我看了一下api的内容是正常的，还请大佬修复一下

**Comment by KimigaiiWuyi** [comment]
> 我看了一下api的内容是正常的，还请大佬修复一下

因为这个日期是算的；
我之后会修一下，看能不能用正则获取到真实日期
