### ISSUE TITLE
当我输入“查询”命令时，输出“输入错误！”

### ISSUE THREAD

**Issue by joshefi** [KimigaiiWuyi/GenshinUID#8]
当我输入一系列查询命令时，机器人输出“输入错误！”

**Comment by KimigaiiWuyi** [comment]
是否成功添加上cookies？

**Comment by joshefi** [comment]
![S}4TL37RJ)UAGP(`(}PY`1](https://user-images.githubusercontent.com/73376500/135831004-192859f9-abf5-461e-a397-58d0ba58b59b.png)
您好！我是添加成功了，但无法得知cookies获取方式及结果是否正确

**Comment by KimigaiiWuyi** [comment]
uid方式查询是否能成功？

**Comment by joshefi** [comment]
![Q0H%5ZJMR{XG0LQ6NIWD4$E](https://user-images.githubusercontent.com/73376500/135840215-fdb2cefb-0a1f-4dd1-94eb-212644619de9.png)
如果您说的此方式，结果是并未成功。

**Comment by joshefi** [comment]
我应如何查找报错信息并向您汇报

**Comment by KimigaiiWuyi** [comment]
> 我应如何查找报错信息并向您汇报

我的意思是直接去掉绑定，直接查uid，比如输入uid191xxxx这种方式

**Comment by KimigaiiWuyi** [comment]
大概率应该是cookies输入错误，建议删除ID_DATA.db这个数据库，然后获取到正确cookies之后，重新添加cookies（获取方法可参考readme）

**Comment by joshefi** [comment]
是的，问题是cookies输入，我重新获取后使用成功

**Comment by joshefi** [comment]
感谢
