### ISSUE TITLE
大佬，关于频道bot

### ISSUE THREAD

**Issue by a970703218** [KimigaiiWuyi/GenshinUID#88]
如何添加Cookies呢？
还有输入help提示no permission to use this ark template。

**Comment by KimigaiiWuyi** [comment]
Cookies添加：命令`整理cookies`，扫描同目录下`cookies_simp.json`文件，读取`[data]`数据中的全部Cookies；
help：ark权限如果是公域机器人需要申请；私域的话自动开通

**Comment by a970703218** [comment]
> Cookies添加：命令`整理cookies`，扫描同目录下`cookies_simp.json`文件，读取`[data]`数据中的全部Cookies； help：ark权限如果是公域机器人需要申请；私域的话自动开通

好的  谢谢大佬

**Comment by MiniGrayGay** [comment]
如需添加原神Bot【奶香的一刀】到自己有权限管理的频道


可以加入【原神-奶香的一刀】，频道在频道内点击机器人头像，点击右上角三个点，然后点击【添加到我的其他频道】

如果添加失败或其他情况，可以私聊Q：1042815109处理
