### ISSUE TITLE
大佬，请问下cookies_simp.json文件下的ck数据格式

### ISSUE THREAD

**Issue by a970703218** [KimigaiiWuyi/GenshinUID#89]
大佬，请问是直接在
{"data":［］}中添加整段cookies还是？

**Comment by MiniGrayGay** [comment]
填入整段ck就行，建议填多点

**Comment by MiniGrayGay** [comment]
如需添加原神Bot【奶香的一刀】到自己有权限管理的频道


可以加入【原神-奶香的一刀】，频道在频道内点击机器人头像，点击右上角三个点，然后点击【添加到我的其他频道】

如果添加失败或其他情况，可以私聊Q：1042815109处理

**Comment by a970703218** [comment]
> 填入整段ck就行，建议填多点

大佬 我填的整段cookies，然后提示ck添加错误

**Comment by MiniGrayGay** [comment]
附图或者Q：1042815109

**Comment by a970703218** [comment]
> ![image](https://user-images.githubusercontent.com/64829926/148790418-fb780c67-d356-4c7a-9cf9-8d9fde3c981a.png)
> 
> 你可以参考下这个格式，每个ck用双引号，中间逗号间隔，一定要有`cookie_token`，最好有`ltoken`、`ltuid`、`cookie_token`、`account_id`

![Screenshot_20220110_233305_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148792776-2ddaba1f-80f9-486e-915e-6f4bbdb9c2dc.jpg)
大佬，这是我取出来的cookies，不知道为何就是无法添加成功

**Comment by a970703218** [comment]
> > ![image](https://user-images.githubusercontent.com/64829926/148790418-fb780c67-d356-4c7a-9cf9-8d9fde3c981a.png)
> > 你可以参考下这个格式，每个ck用双引号，中间逗号间隔，一定要有`cookie_token`，最好有`ltoken`、`ltuid`、`cookie_token`、`account_id`
> 
> ![Screenshot_20220110_233305_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148792776-2ddaba1f-80f9-486e-915e-6f4bbdb9c2dc.jpg) 大佬，这是我取出来的cookies，不知道为何就是无法添加成功

hoshino版本是可以添加成功的。

**Comment by KimigaiiWuyi** [comment]
> 

json的缩进弄好……

**Comment by a970703218** [comment]
> > 
> 
> json的缩进弄好……

啊......弄好了....大概？！
![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)

**Comment by KimigaiiWuyi** [comment]
> > > 
> > 
> > 
> > json的缩进弄好……
> 
> 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)

你ck咋全露出来了，我发现你这ck就不对啊；
要有`cookie_token`字段和`account_id`字段啊

**Comment by a970703218** [comment]
> > > > 
> > > 
> > > 
> > > json的缩进弄好……
> > 
> > 
> > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> 
> 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊

露出来没事，到时候重置一下就好，我再抓一次试试

**Comment by a970703218** [comment]
> > > > 
> > > 
> > > 
> > > json的缩进弄好……
> > 
> > 
> > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> 
> 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`

![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg)
大佬，这样的就可以了吗？

**Comment by KimigaiiWuyi** [comment]
> > > > > 
> > > > 
> > > > 
> > > > json的缩进弄好……
> > > 
> > > 
> > > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> > 
> > 
> > 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`
> 
> ![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg) 大佬，这样的就可以了吗？

你试一下就知道可不可以了，别忘了文件名

**Comment by a970703218** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > json的缩进弄好……
> > > > 
> > > > 
> > > > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> > > 
> > > 
> > > 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`
> > 
> > 
> > ![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg) 大佬，这样的就可以了吗？
> 
> 你试一下就知道可不可以了，别忘了文件名

![-35c41faf2e346856](https://user-images.githubusercontent.com/48351858/148867942-450849a4-2953-4882-8353-b054b981314c.jpg)
啊.....还是不行，文件名也对的呀

**Comment by a970703218** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > json的缩进弄好……
> > > > 
> > > > 
> > > > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> > > 
> > > 
> > > 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`
> > 
> > 
> > ![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg) 大佬，这样的就可以了吗？
> 
> 你试一下就知道可不可以了，别忘了文件名

啊....大佬，我还是不行，是我的cookies格式有问题吗？文件名也没错啊。
![Screenshot_20220111_102454_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870400-963c7924-6993-4e9e-952d-c52e35f30edb.jpg)

**Comment by KimigaiiWuyi** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > json的缩进弄好……
> > > > > 
> > > > > 
> > > > > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> > > > 
> > > > 
> > > > 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`
> > > 
> > > 
> > > ![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg) 大佬，这样的就可以了吗？
> > 
> > 
> > 你试一下就知道可不可以了，别忘了文件名
> 
> 啊....大佬，我还是不行，是我的cookies格式有问题吗？文件名也没错啊。 ![Screenshot_20220111_102454_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870400-963c7924-6993-4e9e-952d-c52e35f30edb.jpg)

看上去倒是没有什么问题？可能是过期了
控制台报什么错

**Comment by a970703218** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > json的缩进弄好……
> > > > > > 
> > > > > > 
> > > > > > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> > > > > 
> > > > > 
> > > > > 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`
> > > > 
> > > > 
> > > > ![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg) 大佬，这样的就可以了吗？
> > > 
> > > 
> > > 你试一下就知道可不可以了，别忘了文件名
> > 
> > 
> > 啊....大佬，我还是不行，是我的cookies格式有问题吗？文件名也没错啊。 ![Screenshot_20220111_102454_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870400-963c7924-6993-4e9e-952d-c52e35f30edb.jpg)
> 
> 看上去倒是没有什么问题？可能是过期了 控制台报什么错

![Screenshot_20220111_102840_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870731-75558c1b-5146-45b4-94c5-33baa52d6a9d.jpg)
这个

**Comment by KimigaiiWuyi** [comment]
> > > > > > > > > 
> > > > > > > > 
> > > > > > > > 
> > > > > > > > json的缩进弄好……
> > > > > > > 
> > > > > > > 
> > > > > > > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> > > > > > 
> > > > > > 
> > > > > > 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`
> > > > > 
> > > > > 
> > > > > ![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg) 大佬，这样的就可以了吗？
> > > > 
> > > > 
> > > > 你试一下就知道可不可以了，别忘了文件名
> > > 
> > > 
> > > 啊....大佬，我还是不行，是我的cookies格式有问题吗？文件名也没错啊。 ![Screenshot_20220111_102454_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870400-963c7924-6993-4e9e-952d-c52e35f30edb.jpg)
> > 
> > 
> > 看上去倒是没有什么问题？可能是过期了 控制台报什么错
> 
> ![Screenshot_20220111_102840_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870731-75558c1b-5146-45b4-94c5-33baa52d6a9d.jpg) 这个

File not found，那就是文件没有在对应地方

**Comment by a970703218** [comment]
> > > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > json的缩进弄好……
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> > > > > > > 
> > > > > > > 
> > > > > > > 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`
> > > > > > 
> > > > > > 
> > > > > > ![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg) 大佬，这样的就可以了吗？
> > > > > 
> > > > > 
> > > > > 你试一下就知道可不可以了，别忘了文件名
> > > > 
> > > > 
> > > > 啊....大佬，我还是不行，是我的cookies格式有问题吗？文件名也没错啊。 ![Screenshot_20220111_102454_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870400-963c7924-6993-4e9e-952d-c52e35f30edb.jpg)
> > > 
> > > 
> > > 看上去倒是没有什么问题？可能是过期了 控制台报什么错
> > 
> > 
> > ![Screenshot_20220111_102840_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870731-75558c1b-5146-45b4-94c5-33baa52d6a9d.jpg) 这个
> 
> File not found，那就是文件没有在对应地方

阿哲，不是放在根目录吗？

**Comment by KimigaiiWuyi** [comment]
> > > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > json的缩进弄好……
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> > > > > > > 
> > > > > > > 
> > > > > > > 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`
> > > > > > 
> > > > > > 
> > > > > > ![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg) 大佬，这样的就可以了吗？
> > > > > 
> > > > > 
> > > > > 你试一下就知道可不可以了，别忘了文件名
> > > > 
> > > > 
> > > > 啊....大佬，我还是不行，是我的cookies格式有问题吗？文件名也没错啊。 ![Screenshot_20220111_102454_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870400-963c7924-6993-4e9e-952d-c52e35f30edb.jpg)
> > > 
> > > 
> > > 看上去倒是没有什么问题？可能是过期了 控制台报什么错
> > 
> > 
> > ![Screenshot_20220111_102840_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870731-75558c1b-5146-45b4-94c5-33baa52d6a9d.jpg) 这个
> 
> File not found，那就是文件没有在对应地方

这是WIN8？测一下相对位置在哪，可能不是在和`bot.py`同目录，还是说你之前没有放在和`bot.py`同目录

**Comment by a970703218** [comment]
> > > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > json的缩进弄好……
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`
> > > > > > > 
> > > > > > > 
> > > > > > > ![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg) 大佬，这样的就可以了吗？
> > > > > > 
> > > > > > 
> > > > > > 你试一下就知道可不可以了，别忘了文件名
> > > > > 
> > > > > 
> > > > > 啊....大佬，我还是不行，是我的cookies格式有问题吗？文件名也没错啊。 ![Screenshot_20220111_102454_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870400-963c7924-6993-4e9e-952d-c52e35f30edb.jpg)
> > > > 
> > > > 
> > > > 看上去倒是没有什么问题？可能是过期了 控制台报什么错
> > > 
> > > 
> > > ![Screenshot_20220111_102840_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870731-75558c1b-5146-45b4-94c5-33baa52d6a9d.jpg) 这个
> > 
> > 
> > File not found，那就是文件没有在对应地方
> 
> 这是WIN8？测一下相对位置在哪，可能不是在和`bot.py`同目录，还是说你之前没有放在和`bot.py`同目录

我一直放在根目录的呀
![Screenshot_20220111_103235_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148871071-fe3e66f2-547d-4a19-b28c-2ccd0057b34b.jpg)

**Comment by KimigaiiWuyi** [comment]
> > > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > json的缩进弄好……
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg) 大佬，这样的就可以了吗？
> > > > > > > 
> > > > > > > 
> > > > > > > 你试一下就知道可不可以了，别忘了文件名
> > > > > > 
> > > > > > 
> > > > > > 啊....大佬，我还是不行，是我的cookies格式有问题吗？文件名也没错啊。 ![Screenshot_20220111_102454_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870400-963c7924-6993-4e9e-952d-c52e35f30edb.jpg)
> > > > > 
> > > > > 
> > > > > 看上去倒是没有什么问题？可能是过期了 控制台报什么错
> > > > 
> > > > 
> > > > ![Screenshot_20220111_102840_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870731-75558c1b-5146-45b4-94c5-33baa52d6a9d.jpg) 这个
> > > 
> > > 
> > > File not found，那就是文件没有在对应地方
> > 
> > 
> > 这是WIN8？测一下相对位置在哪，可能不是在和`bot.py`同目录，还是说你之前没有放在和`bot.py`同目录
> 
> 我一直放在根目录的呀 ![Screenshot_20220111_103235_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148871071-fe3e66f2-547d-4a19-b28c-2ccd0057b34b.jpg)

win8的话可能相对路径不在那里，你得自己测一下

**Comment by a970703218** [comment]
> > > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > json的缩进弄好……
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 啊......弄好了....大概？！ ![Screenshot_20220111_094355_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148866781-39454029-a991-46cf-84f9-2c97334d8764.jpg)
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 你ck咋全露出来了，我发现你这ck就不对啊； 要有`cookie_token`字段和`account_id`字段啊 而且文件命名也不是`cookies——simp.json`，而应该是`cookies_simp.json`
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ![Screenshot_20220111_095112_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148867422-baa50d37-ab93-44e8-8fce-8cd1c5c0a3d1.jpg) 大佬，这样的就可以了吗？
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 你试一下就知道可不可以了，别忘了文件名
> > > > > > > 
> > > > > > > 
> > > > > > > 啊....大佬，我还是不行，是我的cookies格式有问题吗？文件名也没错啊。 ![Screenshot_20220111_102454_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870400-963c7924-6993-4e9e-952d-c52e35f30edb.jpg)
> > > > > > 
> > > > > > 
> > > > > > 看上去倒是没有什么问题？可能是过期了 控制台报什么错
> > > > > 
> > > > > 
> > > > > ![Screenshot_20220111_102840_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148870731-75558c1b-5146-45b4-94c5-33baa52d6a9d.jpg) 这个
> > > > 
> > > > 
> > > > File not found，那就是文件没有在对应地方
> > > 
> > > 
> > > 这是WIN8？测一下相对位置在哪，可能不是在和`bot.py`同目录，还是说你之前没有放在和`bot.py`同目录
> > 
> > 
> > 我一直放在根目录的呀 ![Screenshot_20220111_103235_com microsoft rdc android](https://user-images.githubusercontent.com/48351858/148871071-fe3e66f2-547d-4a19-b28c-2ccd0057b34b.jpg)
> 
> win8的话可能相对路径不在那里，你得自己测一下

好吧，谢谢大佬，辛苦了，我自己再摸索下！
