### ISSUE TITLE
每晚自动米游社签到经常会在中途中断

### ISSUE THREAD

**Issue by Putarku** [KimigaiiWuyi/GenshinUID#91]
![image](https://user-images.githubusercontent.com/66679443/149552319-43084e31-6fb3-4226-991d-3dc43a7f9ce5.png)
但是用全部重签命令就可以完整签到所有人

**Comment by Putarku** [comment]
实际账号没有被风控，hoshino后台那边提示查看cq

**Comment by KimigaiiWuyi** [comment]
这……发消息太频繁了？也不对，有sleep(7)……好迷；
其实一直有人给我报说人多了自动签到会有几个人签不上，一直搞不懂什么原因

**Comment by wudifeixue** [comment]
这个问题最近随着bot用户增加我也出现了一模一样的情况，我思考的原因是，由于每一条签到都会at一下用户，短期内at了太多次用户，并不符合真实用户行为，导致at这个功能被风控，所以我这几天和群友讨论，也思考两个解决方案，就是都是要改设计了：
1. 先全部后台签到完成，然后批量一次反馈完成信息给用户
2. 只at提醒签到失败的人，签到成功的给一个总结表发一次信息

然后也可以考虑，如果漏签了，自动/手动从当前失败的地方继续，而不是假设100个用户，使用了“全部重签”，必须从头开始再一点点开始重复签到，浪费了大量时间和资源，增加了账号风控风险。

**Comment by KimigaiiWuyi** [comment]
> 这个问题最近随着bot用户增加我也出现了一模一样的情况，我思考的原因是，由于每一条签到都会at一下用户，短期内at了太多次用户，并不符合真实用户行为，导致at这个功能被风控，所以我这几天和群友讨论，也思考两个解决方案，就是都是要改设计了：
> 
> 1. 先全部后台签到完成，然后批量一次反馈完成信息给用户
> 2. 只at提醒签到失败的人，签到成功的给一个总结表发一次信息
> 
> 然后也可以考虑，如果漏签了，自动/手动从当前失败的地方继续，而不是假设100个用户，使用了“全部重签”，必须从头开始再一点点开始重复签到，浪费了大量时间和资源，增加了账号风控风险。

我目前仍然无法确定到底是由于cqhttp发不出去；还是由于米游社api访问失败所以签到失败；
我先当成是由于qq风控的影响吧，那我就会考虑做成一个群一次性推送一次+如果是私聊开启那单独推送；
如果是由于米游社api访问失败，我觉得可以再增加sleep时间

**Comment by wudifeixue** [comment]
米游社访问失败会回馈出来签到失败，这个不会中断程序继续签到，但是cqhttp发不出去，一定会中断程序的正确运行，这个我出现了好多次，我开始还不确定在测试，今天一看居然issue里情况一样，大概率就是风控了

**Comment by wudifeixue** [comment]
你要是想保留以前的at提醒我觉得也没问题，就是这个人数超过10就开始逐渐有问题了，人再多就开始越来越容易签到漏了一半卡死了

**Comment by KimigaiiWuyi** [comment]
> 你要是想保留以前的at提醒我觉得也没问题，就是这个人数超过10就开始逐渐有问题了，人再多就开始越来越容易签到漏了一半卡死了

成 我晚上修改一下发送方式

**Comment by KimigaiiWuyi** [comment]
测试了三天，已经push上去了，大概已修复
