### ISSUE TITLE
Cookie添加

### ISSUE THREAD

**Issue by RemKeeper** [KimigaiiWuyi/GenshinUID#93]
![image](https://user-images.githubusercontent.com/78486275/149614476-1909f01e-673e-4c7d-a9db-3ccfe06713a3.png)
不知道是不是我自己使用的问题~，我是超级管理员，只有我发送添加Cookie才会提示成功，其他群成员会提示失败~
是不是我哪里权限配置错了（；´д｀）ゞ

**Comment by KimigaiiWuyi** [comment]
看上去是成功了？只是成功和失败的信息都被发出去了？
你让他`绑定uid`之后使用`当前状态`或者`签到`看看是否能正确识别
是hoshino版本还是nb2？

**Comment by RemKeeper** [comment]
hoshino版本，nb2找不到教程，不会部署::>_<::

**Comment by KimigaiiWuyi** [comment]
> hoshino版本，nb2找不到教程，不会部署::>_<::

所以是添加成功了吗，`签到`命令有正确识别吗

**Comment by Putarku** [comment]
这个我现在也是这个情况，实际上cookies已经成功添加了，只是会发两个消息

**Comment by RemKeeper** [comment]
签到命令没有回复，但是自动签到会签

**Comment by wudifeixue** [comment]
这个我最近也有收到用户反馈，是否在群里先绑定uid了呢？我也不知道为什么，但是绑定uid，米游社绑定成功账号打开一次，再有就是看看隐私设置，都操作一遍往往就好了。。
