### ISSUE TITLE
在nonebot2 v2.0.0-beta.1安装出现问题

### ISSUE THREAD

**Issue by Aues6uen11Z** [KimigaiiWuyi/GenshinUID#95]
新版nonebot2中把cqhttp改成了onebot v11，在加载GenshinUID插件时会报错，求大佬更新

**Comment by KimigaiiWuyi** [comment]
暂时先用a16吧，新版的文档还没出完好像

**Comment by MingxuanGame** [comment]
```shell
pip install nonebot2==2.0.0a16
```

**Comment by Aues6uen11Z** [comment]
我试了a16版本，还是报错了。。。
nonebot2和go-cqhttp已经可以正常用了，发qq有回复。GenshinUID已经按照说明放在src/plugins下，安装了依赖库，bot.py中添加了nonebot.load_plugins("src/plugins")，运行时这样报错：

01-16 12:27:44 [ERROR] nonebot | Failed to import "GenshinUID"
Traceback (most recent call last):
  File "bot.py", line 8, in <module>
    nonebot.load_plugins("src/plugins")
  File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/__init__.py", line 1005, in load_plugins
    result = context.run(_load_plugin, manager, plugin_name)
> File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/__init__.py", line 953, in _load_plugin
    module = manager.load_plugin(plugin_name)
  File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin
    return importlib.import_module(f"{self.namespace}.{name}")
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "src/plugins/GenshinUID/__init__.py", line 32, in <module>
    draw_event = require("nonebot_plugin_apscheduler").scheduler

查了半天也没解决，麻烦大佬看看(ಥ_ಥ)

**Comment by KimigaiiWuyi** [comment]
> 我试了a16版本，还是报错了。。。 nonebot2和go-cqhttp已经可以正常用了，发qq有回复。GenshinUID已经按照说明放在src/plugins下，安装了依赖库，bot.py中添加了nonebot.load_plugins("src/plugins")，运行时这样报错：
> 
> 01-16 12:27:44 [ERROR] nonebot | Failed to import "GenshinUID" Traceback (most recent call last): File "bot.py", line 8, in nonebot.load_plugins("src/plugins") File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/**init**.py", line 1005, in load_plugins result = context.run(_load_plugin, manager, plugin_name)
> 
> > File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/**init**.py", line 953, in _load_plugin
> > module = manager.load_plugin(plugin_name)
> > File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin
> > return importlib.import_module(f"{self.namespace}.{name}")
> > File "/usr/lib/python3.7/importlib/**init**.py", line 127, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1006, in _gcd_import
> > File "", line 983, in _find_and_load
> > File "", line 967, in _find_and_load_unlocked
> > File "", line 677, in _load_unlocked
> > File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
> > super().exec_module(module)
> > File "", line 728, in exec_module
> > File "", line 219, in _call_with_frames_removed
> > File "src/plugins/GenshinUID/**init**.py", line 32, in 
> > draw_event = require("nonebot_plugin_apscheduler").scheduler
> 
> 查了半天也没解决，麻烦大佬看看(ಥ_ಥ)

还需要装依赖`nonebot_plugin_apscheduler`

**Comment by Aues6uen11Z** [comment]
> 

这个包已经安了，也是新版的

**Comment by Aues6uen11Z** [comment]
> > 我试了a16版本，还是报错了。。。 nonebot2和go-cqhttp已经可以正常用了，发qq有回复。GenshinUID已经按照说明放在src/plugins下，安装了依赖库，bot.py中添加了nonebot.load_plugins("src/plugins")，运行时这样报错：
> > 01-16 12:27:44 [ERROR] nonebot | Failed to import "GenshinUID" Traceback (most recent call last): File "bot.py", line 8, in nonebot.load_plugins("src/plugins") File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/**init**.py", line 1005, in load_plugins result = context.run(_load_plugin, manager, plugin_name)
> > > File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/**init**.py", line 953, in _load_plugin
> > > module = manager.load_plugin(plugin_name)
> > > File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin
> > > return importlib.import_module(f"{self.namespace}.{name}")
> > > File "/usr/lib/python3.7/importlib/**init**.py", line 127, in import_module
> > > return _bootstrap._gcd_import(name[level:], package, level)
> > > File "", line 1006, in _gcd_import
> > > File "", line 983, in _find_and_load
> > > File "", line 967, in _find_and_load_unlocked
> > > File "", line 677, in _load_unlocked
> > > File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
> > > super().exec_module(module)
> > > File "", line 728, in exec_module
> > > File "", line 219, in _call_with_frames_removed
> > > File "src/plugins/GenshinUID/**init**.py", line 32, in
> > > draw_event = require("nonebot_plugin_apscheduler").scheduler
> > 
> > 
> > 查了半天也没解决，麻烦大佬看看(ಥ_ಥ)
> 
> 还需要装依赖`nonebot_plugin_apscheduler`

这个包已经安了，而且版本也是新的

**Comment by KimigaiiWuyi** [comment]
> > > 我试了a16版本，还是报错了。。。 nonebot2和go-cqhttp已经可以正常用了，发qq有回复。GenshinUID已经按照说明放在src/plugins下，安装了依赖库，bot.py中添加了nonebot.load_plugins("src/plugins")，运行时这样报错：
> > > 01-16 12:27:44 [ERROR] nonebot | Failed to import "GenshinUID" Traceback (most recent call last): File "bot.py", line 8, in nonebot.load_plugins("src/plugins") File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/**init**.py", line 1005, in load_plugins result = context.run(_load_plugin, manager, plugin_name)
> > > > File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/**init**.py", line 953, in _load_plugin
> > > > module = manager.load_plugin(plugin_name)
> > > > File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/manager.py", line 161, in load_plugin
> > > > return importlib.import_module(f"{self.namespace}.{name}")
> > > > File "/usr/lib/python3.7/importlib/**init**.py", line 127, in import_module
> > > > return _bootstrap._gcd_import(name[level:], package, level)
> > > > File "", line 1006, in _gcd_import
> > > > File "", line 983, in _find_and_load
> > > > File "", line 967, in _find_and_load_unlocked
> > > > File "", line 677, in _load_unlocked
> > > > File "/usr/local/lib/python3.7/dist-packages/nonebot/plugin/manager.py", line 267, in exec_module
> > > > super().exec_module(module)
> > > > File "", line 728, in exec_module
> > > > File "", line 219, in _call_with_frames_removed
> > > > File "src/plugins/GenshinUID/**init**.py", line 32, in
> > > > draw_event = require("nonebot_plugin_apscheduler").scheduler
> > > 
> > > 
> > > 查了半天也没解决，麻烦大佬看看(ಥ_ಥ)
> > 
> > 
> > 还需要装依赖`nonebot_plugin_apscheduler`
> 
> 这个包已经安了，而且版本也是新的

pip3 list 看一看

**Comment by Aues6uen11Z** [comment]
![image](https://user-images.githubusercontent.com/79563000/149660453-e5207f61-3971-462b-978a-22361366ba57.png)

**Comment by Aues6uen11Z** [comment]
![QQ图片20220116204637](https://user-images.githubusercontent.com/79563000/149660481-62034824-5f8c-4fdb-9f4f-e7a9a6e44f2b.png)

**Comment by Aues6uen11Z** [comment]
> ![QQ图片20220116204637](https://user-images.githubusercontent.com/79563000/149660481-62034824-5f8c-4fdb-9f4f-e7a9a6e44f2b.png)

不知道能不能看见，方便加qq聊吗？我已经发送好友请求了

**Comment by Aues6uen11Z** [comment]
问题解决了，因为我是在手机通过aidlux搭建的linux环境，tzloca包l下unix.py需要删除这段代码：
    # Are we under Termux on Android?
    if os.path.exists('/system/bin/getprop'):
        import subprocess
        androidtz = subprocess.check_output(['getprop', 'persist.sys.timezone']).strip().decode()
        return pytz.timezone(androidtz)
这个错会导致nonebot_plugin_apscheduler引用失败
