### ISSUE TITLE
【建议】树脂提醒可以设置一天内提醒次数，提醒太多次了

### ISSUE THREAD

**Issue by RemKeeper** [KimigaiiWuyi/GenshinUID#96]
![V`KONYB`S(6~MC{{RK3{C6S](https://user-images.githubusercontent.com/78486275/149820251-2945188e-6429-46ef-a6cc-69690da27af7.png)
![6R4G76031@$KFRH91E~LGTN](https://user-images.githubusercontent.com/78486275/149820271-c6508678-33dc-4b1f-aaa6-281fc50e0b2e.png)
隔一段时间提醒一次，群友已经烦了

**Comment by KimigaiiWuyi** [comment]
提醒次数太少会不会导致错过提醒；
我后续可以改成超过140提醒2次，之后不降回60以下再升到140 而是维持140以上的话就不再提醒了；
另外还有一点，这个推送不是可以私聊开启吗？
私聊bot开启推送就是私聊开启，在群里确实有点扰民

**Comment by KimigaiiWuyi** [comment]
好像现在更烦了，加入了洞天宝钱/派遣提醒/树脂提醒……

**Comment by RemKeeper** [comment]
啊这，群成员都不开那个了，都说太烦了
