### ISSUE TITLE
【功能请求】给洞天宝钱添加预计储存上限时间

### ISSUE THREAD

**Issue by wudifeixue** [KimigaiiWuyi/GenshinUID#97]
现在的：
当前状态

@wudifeixue 
*数据刷新可能存在一定延迟，请以当前游戏实际数据为准
==============
原粹树脂：35/160 (00:00:02/16:32:02)
每日委托：4/4 奖励已领取
周本减半：3/3
洞天宝钱：30/2400
探索派遣：
总数/完成/上限：5/0/5
安柏 剩余时间12:04:19
重云 剩余时间13:53:07
九条裟罗 剩余时间13:53:07
班尼特 剩余时间13:53:07
菲谢尔 剩余时间13:53:07

添加功能给洞天宝钱
把恢复满剩余时间加上
举例：
洞天宝钱：30/2400 (01:25:00/78:35:00)

**Comment by KimigaiiWuyi** [comment]
这个洞天宝钱的恢复速度是怎么计算的

**Comment by KimigaiiWuyi** [comment]
好像api就有返回，我傻逼了

**Comment by KimigaiiWuyi** [comment]
已修复
