### ISSUE TITLE
nonebot2部署后无法添加cookie

### ISSUE THREAD

**Issue by persudo** [KimigaiiWuyi/GenshinUID#98]
![image](https://user-images.githubusercontent.com/27010143/150907656-f4abc197-e9d0-4cb6-b45b-4d70483b8527.png)
nonebot2版本是a16，已经安装了requirements.txt中的依赖。
Windows和Linux环境下启动机器人都无法添加cookie，不管是自己复制的还是用
`var cookie=document.cookie;var Str_Num = cookie.indexOf('_MHYUUID=');cookie ='添加 '+cookie.substring(Str_Num);var ask=confirm('Cookie:'+cookie+'\n\n按确认，然后粘贴发送给机器人');if(ask==true){copy(cookie);msg=cookie}else{msg='Cancel'}`
这个命令复制的，都不能正常添加。
求大佬解答

**Comment by KimigaiiWuyi** [comment]
检查一下cookies内是否含有`account_id = xxxxxx ; Cookie_token = xxxxxx`这两条参数

**Comment by persudo** [comment]
![image](https://user-images.githubusercontent.com/27010143/150910676-24d925e2-1ea9-4b20-8074-172684408be7.png)
有

**Comment by persudo** [comment]
Cookie_token第一个字母改成大写也无法添加

**Comment by KimigaiiWuyi** [comment]
> Cookie_token第一个字母改成大写也无法添加，换了一个米游社账号之后也一样。

这个账号有玩过原神账号并登录手机米游社吗
不行的话可以加我Q444835641 我检查一下

**Comment by persudo** [comment]
都有，还是无法解决，其它机器人插件正常。

**Comment by persudo** [comment]
> > Cookie_token第一个字母改成大写也无法添加，换了一个米游社账号之后也一样。
> 
> 这个账号有玩过原神账号并登录手机米游社吗
> 不行的话可以加我Q444835641 我检查一下

已经加了，麻烦大佬了
